Add Blister Pill Packs
Helixis/Paradise pull request #1009
Opened 2021-06-17 02:50 UTC by Spircen

## What Does This PR Do
Añade los paquetes pequeños de píldoras, este tipo de contenedor solamente permite el sacar las pastillas no volver a insertarlas se puede encontrar dentro de botiquines y permite la rápida administración de píldoras si atacas a una persona con el objeto y hay píldoras aun dentro. 

A su vez corrige unos detalles de las descripciones de los First Aid Kits debido a que nuestra branch no tiene HAs en los medikits.

## Why It's Good For The Game
Añade mejor portabilidad al juego y mas oportunidades para laborar.

## Images of changes

## Changelog
:cl:
add: Blister Pill Pack
/:cl:

2021-06-25 17:37 UTC, Danaleja2005 commented
Esto es como un hypospray pero en forma de pastillas?, digo eso es lo que me hace entender la descripción :thinking:

2021-07-10 15:57 UTC, DanaDririon requested changes
Están geniales, aunque me gustaría que las pastillas se sacaran aprentando el blister pack en vez de que sea un storage
Comentarios adicionales:

2021-07-10 15:57 UTC, DanaDririon commented on code/game/objects/items/weapons/storage/firstaid.dm
>  	new /obj/item/reagent_containers/food/pill/salicylic(src)
En los fire kits hay un Blister Pack y aparte una píldora, se ve raro

2021-07-10 15:57 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +	slot_flags = SLOT_BELT
Los blister pack aparecen en los kits, pero no se pueden meter dentro porque son muy grandes (size)

2021-07-10 15:57 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +	return FALSE
¿Para qué este texto si no se puede meter nada dentro?

2021-07-10 15:57 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +				applying_meds = FALSE
Este if es irrelevante

2021-07-10 15:57 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +	desc = "A blister pack of hydrocodone pills. DONT CONSUME MORE THAN ONE."
Creaste este blister pack, pero no se puede obtener sin admin

2021-07-10 16:39 UTC, PotatoTheDeveloper commented
la idea es bonita pero como dice dana, si solo son un storage son solo botellas de píldoras respriteadas, que te den una píldora al hacerles click sería mas rápido e interesante

2021-07-11 21:32 UTC, Danaleja2005 commented
pienso igual que Patata

2022-07-23 01:02 UTC, closed without merging