Port Giga Puddi (VG)
Helixis/Paradise pull request #1025
Opened 2021-06-30 18:19 UTC by Spircen

## What Does This PR Do
Portea los Giga Puddis de VG y agrega un nuevo tipo de reagent llamado Pure Hate el cual hace lo contrario a Pure Love.

## Why It's Good For The Game
Comida divertida y bonita.

## Images of changes
![image](https://user-images.githubusercontent.com/46639834/124011411-9a826480-d9a5-11eb-9885-5fc1939e3ca6.png)
![FalseRichKookaburra-size_restricted](https://user-images.githubusercontent.com/46639834/124011577-c7cf1280-d9a5-11eb-9675-8cf6184f4113.gif)

## Changelog
:cl:
add: Giga Puddi
/:cl:

2021-06-30 18:20 UTC, PotatoTheDeveloper commented
c:

2021-07-15 18:17 UTC, DanaDririon requested changes
Recetas y comidas funcionando

2021-07-15 18:17 UTC, DanaDririon commented on code/hispania/modules/food_and_drinks/food/foods/misc.dm
> +	bitesize = 1
Me demoro mucho en terminarme un puddi
```suggestion
	bitesize = 50
```

2021-07-15 18:17 UTC, DanaDririon commented on code/hispania/modules/reagents/chemistry/reagents/misc.dm
> +	taste_description = "<font color='pink'><b>love</b></font>"
Quetachendo
```suggestion
	taste_description = "<font color='pink'><b>love</b></font>"
```

2021-07-15 18:17 UTC, DanaDririon commented on code/hispania/modules/reagents/chemistry/reagents/misc.dm
> +	L.can_change_intents = FALSE //Now you have no choice but to do harm
Se queda sin poder cambiar intents para siempre? 🤔 Con el datum/reagent/love tal vez te creo, pero no estoy seguro si es bueno dejar a alguien en harm hasta que le cambien la variable

2022-03-07 17:36 UTC, Spircen commented on code/hispania/modules/reagents/chemistry/reagents/misc.dm
> +	L.can_change_intents = FALSE //Now you have no choice but to do harm
Es solamente por el tiempo en el cual tengas el reagent en tu organismo si tienes muchísimo pues tardara mas. Funciona igual que los abrazos o el amor que son reagents que obtienes de abrazar peluches.

2022-03-07 17:43 UTC, Spircen commented on code/hispania/modules/reagents/chemistry/reagents/misc.dm
> +	taste_description = "<font color='pink'><b>love</b></font>"
Esto estaba en el codigo del reagent del amor por eso dice love pero realmente no se como consigues que este texto sea visible asi que solo pondre odio.

2022-07-23 01:01 UTC, merged