Knucles ahora se craftea diferente (no mergees de una que debo hacer algo)
Helixis/Paradise pull request #1039
Opened 2021-07-16 16:37 UTC by Magmabros

El 4 es mi numero de la suerte, esta si es la vencida

## What Does This PR Do
Añade las Knucles, para peliar como un hombre y  demostrar tu robustes a puño limpio, un nuevo craft para hacer armas improvisadas, y permite roliar peleas callejeras mas realistas.

## Why It's Good For The Game
Complace las sugerencias de discord y les hace creer que esto es una democria.

## Images of changes
![imagen](https://user-images.githubusercontent.com/59675671/125980362-f84b2c6e-fd63-4610-b473-099c1286675c.png)

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: Tweaked a few things
fix: Fixed a few things
wip: Added a few works in progress
soundadd: Added a new sound thingy
sounddel: Removed an old sound thingy
imageadd: Added some icons and images
imagedel: Deleted some icons and images
spellcheck: Fixed a few typos
experiment: Added an experimental thingy
/:cl:

2021-07-16 16:40 UTC, Magmabros commented
no me quiere subir un archivo en cuanto lo logre si

2021-07-16 16:43 UTC, Magmabros reviewed
no puedo ver el code

2021-07-16 17:04 UTC, Magmabros reviewed
porfin descubri actualizar cambios

2021-07-16 17:11 UTC, Magmabros reviewed
creo que ya esta todo
revisa ai porfa

2021-07-16 17:14 UTC, Magmabros reviewed
confirmo ya se puede mergear

2021-07-16 18:17 UTC, PotatoTheDeveloper commented on code/hispania/modules/crafting/recipes.dm
> +				/obj/item/stack/tape_roll = 1)
no tiene sentido que requiere tape_roll cuando lo haces con soldador

2021-07-16 18:48 UTC, Magmabros commented on code/hispania/modules/crafting/recipes.dm
> +				/obj/item/stack/tape_roll = 1)
deja lo cambio por cable ya que con algo tendras que amarrar el metal para poder soldarlo

2021-07-16 18:51 UTC, Magmabros reviewed
ya elimine la cinta, vamos a finjir que todos somos soldadores expertos y puede sujetarlo con las manos

2021-07-16 18:52 UTC, Magmabros reviewed
creo que ahora si ta listo

2021-07-16 22:59 UTC, SagaStars commented on code/hispania/modules/crafting/recipes.dm
> +	reqs = list(/obj/item/stack/sheet/metal = 5)
Okay, para culminar el PR cambia este material por plasteel por asuntos de balance, 12 de daño no es algo que deberías poder hacer con metal tan fácilmente. (Es mas fuerte que una toolbox)

2021-07-16 23:00 UTC, SagaStars requested changes
You know what to do

2021-07-17 16:56 UTC, Magmabros reviewed
listo para merge again,  (yeah que este ban no significa que dejare de codiar ahora puedo hacer prs solito)

si alguien tiene otro proyecto simple o sugerencia escribanme al dm

2021-07-17 16:56 UTC, Magmabros commented on code/hispania/modules/crafting/recipes.dm
> +	reqs = list(/obj/item/stack/sheet/metal = 5)
listo

2021-12-23 15:39 UTC, AsrielFBI commented
No veo que el autor siga interesado en seguir este PR. Lo cerraré, puedes volver a rehacer el PR cuando veas que te vuelve el interés en coddear.

2021-12-23 15:39 UTC, closed without merging