Paracetamol
Helixis/Paradise pull request #1080
Opened 2021-10-22 01:32 UTC by maxtreland

## What Does This PR Do
Añade una nueva pildora a las vendings de med llamada paracetamol que contiene oculine y mannitol en ella

## Why It's Good For The Game
Es bueno porque añade una nueva forma rapida y sencilla de aliviar el dolor de cabeza

## Images of changes

## Changelog
:cl:
add: paracetamol
/:cl:

2021-10-22 01:38 UTC, UmeBelle commented
Yo digo que si, debería mergergears-HALP MAINT

2021-10-22 02:53 UTC, SagaStars requested changes, later dismissed
Boop. Acomoda esto y estamos.

2021-10-22 02:53 UTC, SagaStars commented on code/modules/reagents/reagent_containers/pill.dm
>  	list_reagents = list("capulettium_plus" = 50)
```suggestion
	list_reagents = list("capulettium_plus" = 50)
	
```

2021-10-22 02:53 UTC, SagaStars commented on code/hispania/modules/reagents/reagent_containers/pill.dm
> +	list_reagents = list("oculine" = 20,"mannitol" =20)
```suggestion
	list_reagents = list("oculine" = 20,"mannitol" =20)
	
```

2021-10-26 11:08 UTC, maxtreland commented on code/modules/reagents/reagent_containers/pill.dm
>  	list_reagents = list("capulettium_plus" = 50)
ok, pero como jijiji

2021-10-27 19:16 UTC, merged