Nuevo Z level!
Helixis/Paradise pull request #1093
Opened 2021-11-03 02:48 UTC by Tilk1

Un nuevo Z level para hispania, una mision divertida y con variada dificultad. El objetivo es accionar las 4 palancas de cada bioma para luego acceder a la sala del tesoro

![image](https://user-images.githubusercontent.com/24284918/140003524-ed3283b3-16ef-4ca4-96de-9585c0acc531.png)

:cl:
add: Nuevo Z level para la gateway
/:cl:

2021-11-08 22:00 UTC, Tilk1 commented
Bueno oficialmente esta en version 1.0   listo para ser testeado / revisado por alguien mas y recibir feedback

2021-11-09 04:49 UTC, SagaStars commented
Cuando me vea en una oportunidad lo probare.

2021-11-10 14:35 UTC, SagaStars requested changes, later dismissed
El mapa me parece genial es bastante variado y se ve hasta cierto punto desafiante pero tengo ciertos puntos para mejorarlo:

Esta sala necesita mas distancia entre ellas, si alguien tiene mesons va a poder ver el otro lado y se perdera la inmersion. Tambien sugiero el quitar las ventanas para que sea mas sorprendente la revelacion del tesoro.
![image](https://user-images.githubusercontent.com/55407528/141129718-568bd9ea-6832-4d99-8cb2-76c38ae15f02.png)

Esta sala tambien, es mejor que esten separadas.
![image](https://user-images.githubusercontent.com/55407528/141130505-9c6a91da-f677-4a33-9337-f75481fb2814.png)

Recomiendo que en la basta mayoria de paredes le des una profundidad de 7 tiles para tapar puntos de espacio que se verian para gente que tenga cosas como xrays o mensons

![image](https://user-images.githubusercontent.com/55407528/141130966-36c4c81e-2e9a-4de9-80d5-73065aff0872.png)

CIERRA LOS RIOS QUE LUEGO SE NOS ESCAPAN AL ESPACIO AAAAAA
![image](https://user-images.githubusercontent.com/55407528/141131262-b03211b6-50a8-4891-9ac5-79aaf41d8b6c.png)
Por ultimo, hay un par de errores de ortografia en los documentos esparcidos por el mapa, te recomiendo una revisada rapida. **Pasa el .wav a .ogg tambien.**


Arreglado todo esto y las sugerencias de codigo, tu pr pasaria la prueba y quedaria moradito.

2021-11-10 14:35 UTC, SagaStars commented on data/mode.txt
> +extended
Regresalo como antes para quitar el file.
```suggestion
secret
```

2021-11-10 14:35 UTC, SagaStars commented on code/game/objects/structures/misc.dm
> +	var/estado = 0 //0 izquierda, 1 derecha
Cambia los 0 por FALSE y 1 por TRUE, por el bien de mi ojitos. Esto va para todo el .dm

2021-11-13 02:54 UTC, Tilk1 commented
Se atendio a todas las sugerencias con excepcion de lo de no hacer visible la sala del tesoro.  Pense q podia ser mas motivante poder ver el interior de la sala pero no poder acceder a ella hasta tener todas las palancas activadas

2021-11-13 03:00 UTC, Tilk1 commented
> El mapa me parece genial es bastante variado y se ve hasta cierto punto desafiante pero tengo ciertos puntos para mejorarlo:
> 
> Esta sala necesita mas distancia entre ellas, si alguien tiene mesons va a poder ver el otro lado y se perdera la inmersion. Tambien sugiero el quitar las ventanas para que sea mas sorprendente la revelacion del tesoro. ![image](https://user-images.githubusercontent.com/55407528/141129718-568bd9ea-6832-4d99-8cb2-76c38ae15f02.png)
> 
> Esta sala tambien, es mejor que esten separadas. ![image](https://user-images.githubusercontent.com/55407528/141130505-9c6a91da-f677-4a33-9337-f75481fb2814.png)
> 
> Recomiendo que en la basta mayoria de paredes le des una profundidad de 7 tiles para tapar puntos de espacio que se verian para gente que tenga cosas como xrays o mensons
> 
> ![image](https://user-images.githubusercontent.com/55407528/141130966-36c4c81e-2e9a-4de9-80d5-73065aff0872.png)
> 
> CIERRA LOS RIOS QUE LUEGO SE NOS ESCAPAN AL ESPACIO AAAAAA ![image](https://user-images.githubusercontent.com/55407528/141131262-b03211b6-50a8-4891-9ac5-79aaf41d8b6c.png) Por ultimo, hay un par de errores de ortografia en los documentos esparcidos por el mapa, te recomiendo una revisada rapida. **Pasa el .wav a .ogg tambien.**
> 
> Arreglado todo esto y las sugerencias de codigo, tu pr pasaria la prueba y quedaria moradito.

![image](https://user-images.githubusercontent.com/24284918/141603359-42d9dc94-b000-412e-97df-c02d65aecef7.png)
![image](https://user-images.githubusercontent.com/24284918/141603380-4b74ebb5-4863-40b6-820c-2f1f544974b1.png)

![image](https://user-images.githubusercontent.com/24284918/141603373-9e46b504-33fa-48ae-a663-c6128f5d3240.png)

2021-11-14 17:23 UTC, SagaStars approved these changes
Todo correcto, incluyendo la nueva zona que agregastes a la izquierda.

2021-11-14 17:23 UTC, merged