[FIXES] Saca Dababy de la votación de mapas, Arregla error de drone invisible
Helixis/Paradise pull request #1098
Opened 2021-11-09 03:56 UTC by Danaleja2005

## What Does This PR Do
Saco Dababy de la votación como una opción a elegir cuando esta sale al final de la ronda, ademas de arreglar el error del drone sin sprite, que yo mismo provoque jijiji

## Why It's Good For The Game

Dababy es un error, que nunca debio ocurrir.

## Images of changes
![Screenshot_19](https://user-images.githubusercontent.com/43283605/140859187-dcde7b3c-c5c4-4be6-a550-47b52805a6e4.png)
![Screenshot_18](https://user-images.githubusercontent.com/43283605/140859203-6bcc3aa5-5337-462a-b55e-69a6081f3d3b.png)

## Changelog
:cl:
fix: arregla sprite invisible de drone
fix: Dababy ya no es una opción elegible en la votación de mapas
/:cl:

2021-11-09 04:48 UTC, SagaStars requested changes
Separa los PRs para que pueda aceptar uno y rechazar el otro. 🐟

2021-11-09 13:03 UTC, Danaleja2005 commented
> Separa los PRs para que pueda aceptar uno y rechazar el otro. fish

deja lo aguevonado Saga, no hay nada que rechazar, Dababy es un mapa que ni debería existir, no es divertido ni para la crew ni para los antags, este mapa le falta absolutamente todo, departamentos totalmente incomplantes, IAA, NTrep, Magistrate y otros mas ni siquiera tienen oficina, las celdas de Seguridad estan literalmente en la misma sala donde Sec tiene su equipo y vend, el unico job que se salva del desastre que es dababy es el de minero porque el outpost sigue igual que siempre, probablemente la unicas personas que votan este mapa es gente que entra a shittear o de roles que no hacen nada ni en la estaciones grandes (clown, mimo, etc), y no, no soy solo yo quejandome de este mapa, varias personas lo han hecho, pero tu terquedad por no borrar este mapa es increible, la única razón para dejar este mapa asqueroso es porque es un meme.

2021-11-09 17:25 UTC, PotatoTheDeveloper commented
> > Separa los PRs para que pueda aceptar uno y rechazar el otro. fish
> 
> deja lo aguevonado Saga, no hay nada que rechazar, Dababy es un mapa que ni debería existir, no es divertido ni para la crew ni para los antags, este mapa le falta absolutamente todo, departamentos totalmente incompletos, IAA, NTrep, Magistrate y otros mas ni siquiera tienen oficina, las celdas de Seguridad estan literalmente en la misma sala donde Sec tiene su equipo y vend, el unico job que se salva del desastre que es dababy es el de minero porque el outpost sigue igual que siempre, probablemente la unicas personas que votan este mapa es gente que entra a shittear o de roles que no hacen nada ni en la estaciones grandes (clown, mimo, etc), y no, no soy solo yo quejandome de este mapa, varias personas lo han hecho, pero tu terquedad por no borrar este mapa es increible, la única razón para dejar este mapa asqueroso es porque es un meme.

Shut the fuck up, dababy se queda

2021-11-09 17:25 UTC, PotatoTheDeveloper commented
Y separa los prs

2021-11-10 14:06 UTC, SagaStars approved these changes

2021-11-10 14:07 UTC, merged