Retro hispania
Helixis/Paradise pull request #1104
Opened 2021-11-11 06:21 UTC by Tilk1

Nuevo mapa a la rotacion. Versión retro de hispania, mas pequeña y con distintas  disposiciones de los departamentos (basadas en como era el mapa en 2015)  ademas se agregaron consolas vintage y otros sprites .

:cl:
add: retro hispania a la rotacion
add: sprites retro
/:cl:

2021-11-14 18:15 UTC, Tilk1 commented
Agrego WIP porque aun falta arreglar algunos sprites

2021-11-15 03:36 UTC, Tilk1 commented
Esta todo listo para ser testeado y eventualmente agregado a la rotación.

Por mi cuenta testie bastante el mapa y los sprites nuevos,  solo se aplican dichos sprites cuando el mapa elegido es retro_hispania.   En caso de elegir el mapa comun hispania entonces los sprites son los mismos de siempre.  Esto permite tener set de tiles distintos por mapa.


**Importante:  Actualmente esta reemplazando al cyberaid  para ser testeado mas facilmente (Sin DB). Una vez que sea aprobado hay q acordarse de cambiarlo y dejar los nombres y rutas correctas.**

2021-11-15 17:26 UTC, SagaStars requested changes
Tienes problemas con el CI por resolver.

- 1: Necesitas transformar el mapa al formato de TGM, esto es por que creastes el mapa en DM, ocupa este convertidor para transformarlo, creo que necesitabas python instalado, en caso de que no te sirva me avisas. Este proceso no lo vas a tener que repetir cuando guardes en sdmm.
![image](https://user-images.githubusercontent.com/55407528/141825526-ff3ed10c-75a6-4803-a678-fca371f20816.png)
- 2: El CI muestra bastantes runtimes en las pipes, como ves dice algo sobre pipes duplicadas, ve a las coordenadas que te muestra y solucionalos removiendo los duplicados (Para ver la lista completa tienes que ir a la parte baja del PR y ir a Unit Tests + SQL Validation (/datum/map/cyberiad))
![image](https://user-images.githubusercontent.com/55407528/141825799-25f8c4a3-fe9d-4b83-b50d-bbfc16c303a9.png)

Resuelto los conflictos para que revise minuciosamente el mapa, suerte.

2021-11-15 19:42 UTC, Tilk1 commented
Pipes solucionados solo falta quitar los tags

2021-11-15 23:45 UTC, Tilk1 commented
Tags quitados,  no esta pasando el travis por algo con los space pods

2021-12-14 14:11 UTC, merged