Nuevo Evento random.  Feed me!
Helixis/Paradise pull request #1153
Opened 2021-12-18 23:51 UTC by Tilk1

Es hora de poner a prueba las habilidades culinarias de la estacion y los miembros de servicio.

Feed me es un evento random en el que centcomm envia un catador  para  comer platillos.  El deambulara por el bar y si ve alguna comida correra a comerla. El objetivo es darle de comer toda la comida posible pero  sera mucho mas facil si sigues los gustos del invitado.

Por ejemplo el payaso va sumar x10  su saciedad al comer alimentos que sean con bananas.

![image](https://user-images.githubusercontent.com/24284918/146658564-e870154d-de61-431e-9dd6-1dbcbaa12d9a.png)

2021-12-18 23:54 UTC, AsrielFBI commented
2,800 additions, 5,631 deletions ¿Hiciste el map merge?

2021-12-18 23:56 UTC, AsrielFBI requested changes
Quisiera saber que has tenido que modificar en el mapa escrito dentro del PR.

2021-12-18 23:58 UTC, Tilk1 commented
debug qitados

2021-12-19 00:31 UTC, Tilk1 commented
Queda pendiente agregar mas comensales con sus respectivos platillos y sprites

2021-12-19 00:43 UTC, AsrielFBI commented
> Queda pendiente agregar mas comensales con sus respectivos platillos y sprites

Si aún no terminaste tú pr, pon en el título [WIC] y cuando lo termines algo como [TERMINADO].
No somos magos y no sabemos cuándo consideras que tú pr fue terminados.

Gracias.

2021-12-19 03:03 UTC, Tilk1 commented
Agregados el carnivoro y el mexicano. Todo parece funcionar

2021-12-19 03:16 UTC, AsrielFBI requested changes
Si aún no terminaste tú pr, pon en el título [WIP] y cuando lo termines algo como [TERMINADO].
No somos magos y no sabemos cuándo consideras que tú pr fue terminados.
De lo contrario asumiremos que este es el producto final y será juzgado como tal.

En un futuro es posible que podamos pedir más información sobre el PR. Gracias.

2021-12-19 03:18 UTC, AsrielFBI commented
Para cuando avances más en el PR. Me gustaría fotos acerca de como aparecen los personajes en la estación y un poco el cómo funcionan.

Estaría bien también un pequeño changelog con good lo que has incluido en tú evento. Me parece muy poca información la que das para algo que promete tanto.

2021-12-19 13:15 UTC, AsrielFBI requested changes
En lo general se ve bien,... 
Pero para el evento has puesto que pueda ocurrir sin que hayan chefs. ¿Cómo vamos a realizar el evento si no hay chefs en la estación? Opino que este evento solo debe de saltar cuando hayan chefs, sinó solo será un evento que sirve para griffear una partida de horas de trabajo.
La idea sería darle al chef la emoción de tener la responsabilidad de salvar la estación. Si no hay chef, el ingeniero no se podrá poner a cocinar porque ni siquiera sabe.

2021-12-19 15:33 UTC, Helixis commented
No importa porque cualquier persona puede hacer cocina si no hay chef

2021-12-19 22:55 UTC, AsrielFBI commented
> 



> No importa porque cualquier persona puede hacer cocina si no hay chef

Insisto, cada evento está enfocado para un tipo de rol concreto. Si no hay ingenieros; ¿Qué necesidad hay de que caigan meteoros? 
Sí que la gente normal pueden reparar las brechas ¿pero porque deberían estar "forzados" a hacer algo que no querían en un inicio hacer solo para seguir la ronda?
Esta historia se repite con cada evento del tipo "moderado", no hay ninguno que se lance con el tipo "any", todos tienen pesos por roles. 


Solo trato de hacer que el evento sea balanceado respectivamente con la gente que juega ya que cómo dije, si no he entrado de chef me parece feo verme obligado a tener que cocinar por muy permitido que tenga la cocina. Si el evento no concluyera con literalmente una explosión enorme no le daría mucha importancia y hasta consideraría que podría ser un evento de tipo "leve". 

Pero dadas las circumstancias y el daño que puede producir en base a no tener un chef considero que debería de tener cómo requisito roles de servicio como mínimo. Ningún otro evento moderado se pone con el "any" todos piensan igual a la hora de que es innecesario **forzar** roles completamente distintos a los que tú querías cumplir al entrar a jugar.


Tampoco veo que esté matando a nadie por poner que tenga peso sobre rondas donde haya gente con tal rol. A menos que claro el objetivo del PR sea solo crear una valid-bomba para casi cada partida en la que no haya gente con ganas de rolear cocina, que en tal caso solo podría comentar que no tiene sentido meter un evento así.
![imagen](https://user-images.githubusercontent.com/56162938/146693800-9947629f-8f9e-4ccd-a822-81916549107a.png)

2021-12-20 03:16 UTC, Tilk1 commented
Pense que cualquiera tiene acceso al jardin publico para hacer alimentos entonces no tenia mucho sentido restringirlo al cheff.  Pero acepto la sugerencia y ahora es para rol  de servicio.

2021-12-20 13:51 UTC, AsrielFBI commented
Ok, ya probé el PR. Va bien, aunque antes de mergearlo te propondría de si quieres hacer que si el catador termina satisfecho darle alguna recompensa a la estación.
Es un evento que requiere activamente de ir haciendo cosas, estaría bien alguna pequeña recompensa si te parece bien.

De lo contrario ya estaría listo para ser mergeado (pero estaría bien que tuviera lo que he dicho).

2021-12-20 14:08 UTC, AsrielFBI approved these changes

2021-12-21 22:03 UTC, merged