Modificación de Uniformes de Cap, Nueva maquina Wall drobe y trenchcoat para Capitán
Helixis/Paradise pull request #147
Opened 2019-09-19 22:36 UTC by Danaleja2005

Este PR modifica el sprite de los uniformes de capitán y sombreros, y añade una maquina la cual no trae mucho ya que solo es un vending de pared, tambien añade un trenchcoat para Capitán que actua como el trenchcoat del HoS, pero con un poco mas de protección

los Wall drobes se pueden conseguir en dos lugares solamente, una se encuentra en la oficina del cap y otra en la oficina del RD ( el cual solo tiene dos batas que añadí hace tiempo)

Cambios en uniformes 
![image](https://user-images.githubusercontent.com/43283605/65284368-55aa7800-db07-11e9-8773-130be253a2d1.png) 
![image](https://user-images.githubusercontent.com/43283605/65284449-82f72600-db07-11e9-9ad1-9106250ca7c0.png)

![image](https://user-images.githubusercontent.com/43283605/65284548-de291880-db07-11e9-8637-56b1b10b88f6.png)
![image](https://user-images.githubusercontent.com/43283605/65284575-f731c980-db07-11e9-861f-9c9de5612390.png)

( Muestro solamente esta dos partes de los uniformes ya que los cambios de ambos uniformes son en los colores y uno que otro detalle)

![image](https://user-images.githubusercontent.com/43283605/65284628-20525a00-db08-11e9-9765-5a363385a633.png)
![image](https://user-images.githubusercontent.com/43283605/65284640-2f390c80-db08-11e9-8f76-81ab78295ff0.png)

(no muestro el otro sombrero, ya que es lo mismo que este pero con el color del uniforme azul, al igual que los uniformes, los cambios son pocos)

![image](https://user-images.githubusercontent.com/43283605/65284736-7921f280-db08-11e9-980b-2eb3bb2ce9e6.png)
![image](https://user-images.githubusercontent.com/43283605/65284780-a373b000-db08-11e9-87bf-bd3a585c70fc.png)
![image](https://user-images.githubusercontent.com/43283605/65284805-b4bcbc80-db08-11e9-9e5e-9a2f154f23cc.png)

Este trenchcoat ofrece una buena protección contra daños melee, laser y projectiles, protege brazos, pecho, y piernas

Wall drobe

![Walldrobe](https://user-images.githubusercontent.com/43283605/65285156-9dca9a00-db09-11e9-8a01-ca70752cd588.gif) (on)

![Walldrobe](https://user-images.githubusercontent.com/43283605/65285422-64465e80-db0a-11e9-82d5-5a413780fb8e.gif) (vending)

![Walldrobe](https://user-images.githubusercontent.com/43283605/65285456-804a0000-db0a-11e9-9d95-c3016bf6e862.gif) (deny)

![Walldrobe1](https://user-images.githubusercontent.com/43283605/65285577-e33b9700-db0a-11e9-9ec7-316dc5d72a92.png) (off)

![Walldrobe1](https://user-images.githubusercontent.com/43283605/65285742-5f35df00-db0b-11e9-9aab-c0a221375b86.png)  (broken)

(ingnoren los gifs donde sale cuadros blancos, se me olvidaron quitar unos frames en el aseprite hehe)

:cl: 
imageadd: Añade sprite para Wall Vendrobe
imageadd: Añade sprites para Captain's trenchcoat
tweak: Modifica el code del closet del capitan, eliminando uniformes formales y sombreros light y dark, moviendolos a Wall drobe
tweak: El labcoat dark, ahora se puede conseguir en el Wall drobe en la oficina del RD
tweak: Añade Wall drobe a la oficina del RD y Capitán
/:cl:

2019-09-26 12:33 UTC, Evankhell561 commented
code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
ahi te faltaron los guantes de latex y los zapatos del RD

2019-09-26 13:24 UTC, Evankhell561 requested changes

2019-09-26 13:24 UTC, Evankhell561 commented on code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
>  	new /obj/item/clothing/gloves/color/latex(src)
Te faltó quitar los zapatos y los guantes del RD y meterlos en tu maquina.

2019-09-27 11:59 UTC, Evankhell561 requested changes

2019-09-27 11:59 UTC, Evankhell561 commented on code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
> -	new /obj/item/clothing/suit/armor/reactive/teleport(src)
Yo le dejaria la armadura del RD en su locker, éste es un item protegido y no es simplemente un cambio de ropa.

2019-09-27 13:52 UTC, Danaleja2005 commented on code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
> -	new /obj/item/clothing/suit/armor/reactive/teleport(src)
pues el dispensador, es seguro tambien te digo, aunque no estoy seguro si se puede emmagear o no

2019-09-28 21:15 UTC, Evankhell561 requested changes

2019-09-28 21:15 UTC, Evankhell561 commented on code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
> -	new /obj/item/clothing/suit/armor/reactive/teleport(src)
Cuando ryzor te dijo que sacar esta armadura de acá estaba bien estaba más dormido que despierto. Vuelve a poner la armadura del RD acá.

2019-09-29 21:38 UTC, iRyzor commented
Luego de mil arreglos quedó algo medianamente bien.

2019-09-29 21:38 UTC, merged