Miniature energy gun para el Magistrado .
Helixis/Paradise pull request #169
Opened 2019-09-29 21:39 UTC by SagaStars

Oh yeah mr krabs. Este PR ubicara un miniature energy gun personalizado para el magistrado para que tenga una pequeña proteccion extra por tener una ID con accesos a **Equipamiento de Sec** lo cual lo haria mas grande como objetivo, la miniature energy gun estara ubicada en su locker. 

_Imagen del sprite_
![Peter_Griffin](https://user-images.githubusercontent.com/55407528/65839865-75982380-e2df-11e9-9488-c43fdb25bb14.png)

_este es un verdadero momento evan buffeando un solo dep._

2019-09-29 21:40 UTC, SagaStars commented
OHSI ME TOCO EL PR 1**69**

2019-09-29 23:08 UTC, Evankhell561 requested changes

2019-09-29 23:08 UTC, Evankhell561 commented on code/HISPANIA/game/hispania_items.dm
> +/obj/item/gun/energy/gun/minimagistrate
¿Ésta es una copia de la del hop, verdad? Solo tenias que hacer /obj/item/gun/energy/gun/mini/magistrate y añadir las variables name, desc, icon_state, e icon. Y con eso ya tienes tu pistola de magistrado. No necesitas copiar todo el codigo de la pistola del hop.

2019-10-21 14:13 UTC, Evankhell561 requested changes

2019-10-21 14:13 UTC, Evankhell561 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/gun/energy/gun/mini/magistrate(src)
Puedes meter esto en el closet del magistrado desde un nuevo dm en hispania, tal como lo hiciste con el closet del hos.

2019-11-17 20:35 UTC, iRyzor reviewed
1- Arregla el changelog.
2- Los sprites de armas tienen un sitio específico donde ponerlos.
3- Las armas tienen una carpeta específica donde ponerlos, no lo metas dentro de hispania_items.
4- El nombre del icon_state es un poco... genérico, sugiero que le pongas un nombre acorde al objeto.
5- Lo que dijo Evankhell.

2019-11-17 20:35 UTC, iRyzor commented on code/HISPANIA/game/hispania_items.dm
> +	desc = "A small, pistol-sized energy gun with a built-in flashlight. It has fancy colors!."
Esa coma va ahí? :thinking:

2019-11-18 01:48 UTC, SagaStars commented
WHooPSIEEE DOOOOPSUS

![](https://cdn.discordapp.com/attachments/387645048386486273/645796715722571805/7130000c6a1bd6d935835712fe68482f.png)

![](https://cdn.discordapp.com/attachments/387645048386486273/645796931477569537/5ca4d22788e5f0b06820f043fbfe98d9.png)

2019-11-18 01:48 UTC, closed without merging