Nueva botella en la Vending del Bartender (Denme mi puto color)
Helixis/Paradise pull request #203
Opened 2019-10-07 23:35 UTC by asdflyy

Illo, hice un licor nuevo. Ta en la maquina esa to chula del bartender
![mezkal](https://user-images.githubusercontent.com/43289462/66356587-5a04cc80-e920-11e9-9498-1541a67cb374.png)

Servida en vaso ta así:

![mezcaloide](https://user-images.githubusercontent.com/43289462/66356599-6557f800-e920-11e9-887d-fd6e84d222ae.png)

y poh eso, luego le hago un par de cockteles yo que se tio voy muy fumado ayuda

2019-11-07 20:05 UTC, iRyzor reviewed
No me gusta como se ve el sprite de la botella ingame por la falta de sombras y detalles que tiene y la bebida en vaso parece leche, para mejorar eso podrías quitarle opacidad al líquido.
Y debes seguir el formato de los prs que están por algo, añade un changelog y aclara qué es tu pr en el título.

2019-11-07 20:05 UTC, iRyzor commented on code/HISPANIA/modules/reagents/chemistry/reagents/alcohol.dm
> +	color = "15140f" // rgb: 102, 67, 0
Dudo que ese sea el color del mezcal, de paso ponle # delante como el resto de bebidas. (Podrías hacerlo también en el bloque de código del fernet que está arriba? gracias). Y el comentario que le sigue pasa a no tener sentido porque no es su rgb, procura cambiarlo también.

2019-11-07 20:05 UTC, iRyzor commented on code/HISPANIA/modules/reagents/chemistry/reagents/alcohol.dm
> +	description = "it's mezcal, like tequila, but hipster"
punto y mayus.

2020-01-23 16:21 UTC, Evankhell561 requested changes
arregla el changelog y testeo esto.

2020-02-12 17:04 UTC, merged