Medbay Oxigen Assistant [
Helixis/Paradise pull request #223
Opened 2019-10-18 07:27 UTC by SagaStars

## What Does This PR Do

## Why It's Good For The Game

## Images of changes

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
wip: added a few works in progress
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
experiment: added an experimental thingy
/:cl:

2019-10-21 13:41 UTC, Evankhell561 requested changes

2019-10-21 13:41 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/obj/item/stock_parts/cell/high/bcell = null
Cuando hablamos en discord, no me di cuneta de esto. 
ponerle var/obj/item/stock_parts/cell/high/bcell = null puede darte problemas cuando quieras cambiarle la bateria y con algunas cosillas más. 
cambialo por 
var/obj/item/stock_parts/cell/bcell = null

2019-10-21 13:46 UTC, Evankhell561 commented
Tengo, algunas preguntas, ¿Donde consigues este aparato? ¿donde consigues el medicamento?
recomendaria que la maquina solo pueda pedirse por cargo/ciencias y que no esté desde el inicio. 
¿se podrán producir los quimicos que estás usando?
no me gustaria que un quimico pueda hacer esto, a menos que el quimico solo funcione en esta maquina y no funcione normalmente (o si funciona que funcione en el cryotubo)

2019-10-21 13:50 UTC, Evankhell561 requested changes

2019-10-21 13:50 UTC, Evankhell561 commented on code/HISPANIA/game/machinery/moa_drip.dm
> +/obj/machinery/iv_drip/attackby(obj/item/I, mob/user, params)
esto deberia ser /obj/machinery/iv_drip/moa/attackby(obj/item/I, mob/user, params)
en vez de /obj/machinery/iv_drip/attackby(obj/item/I, mob/user, params). Al hacerlo como lo estás haciendo tú, afectas al iv_drip original. Otra cosa, si esto tiene una bateria, deberias poder cambiarsela, por lo que deberia al menos tener algo programado en el attackby para abrir la maquina, para cerrarla, para quitarle la bateria y para insertar una nueva.

2019-10-21 13:56 UTC, Evankhell561 requested changes

2019-10-21 13:56 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +/obj/item/reagent_containers/iv_bag/attack_self(mob/user)
/obj/item/reagent_containers/iv_bag/moa/attack_self(mob/user)

2019-10-21 14:07 UTC, Evankhell561 requested changes

2019-10-21 14:07 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/hitcost = 25
Con un hit cost de 25 kW y una bateria de 10000kW esto tardará unos 400 ticks en gastarse, lo que se traduce a 800 segundos, lo es unos 13 minutos y eso representa todo el tiempo que vayas a usar esta cosa y más. Subirlo un poco da la oportunidad a que se le acabe la bateria y que conseguir una mejor sea importante. Yo lo subiria a 110 para que dure como 3 minutos con una beteria como la que le estás colocando inicialmente. o ponerle 66 para que dure como 5 minutos (aunque me parece mucho pero eso ya es decision tuya).

2019-10-21 21:10 UTC, SagaStars commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/obj/item/stock_parts/cell/high/bcell = null
Understandable

2019-10-21 21:22 UTC, SagaStars commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/hitcost = 25
Pues si reconsiderandolo es demasiado tiempo para una version con un cell basica, lo pondre en 64.

2019-10-21 21:27 UTC, SagaStars commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +/obj/item/reagent_containers/iv_bag/attack_self(mob/user)
Si, justo me fije de esto luego hacer el commit. Pronto lo arreglo.

2019-10-21 21:27 UTC, SagaStars commented on code/HISPANIA/game/machinery/moa_drip.dm
> +/obj/machinery/iv_drip/attackby(obj/item/I, mob/user, params)
Si, justo me fije de esto luego hacer el commit. Pronto lo arreglo.

2019-10-21 21:42 UTC, SagaStars commented
> Tengo, algunas preguntas, ¿Donde consigues este aparato? ¿donde consigues el medicamento?
> recomendaria que la maquina solo pueda pedirse por cargo/ciencias y que no esté desde el inicio.
> ¿se podrán producir los quimicos que estás usando?
> no me gustaria que un quimico pueda hacer esto, a menos que el quimico solo funcione en esta maquina y no funcione normalmente (o si funciona que funcione en el cryotubo)

- Solo vendria una maquina en medbay por defecto y el medicamento no podria ser creado.
- Tengo la idea de que pueda ser pedida por cargo a un precio relativamente alto (como el de un hardsuit) y sobre ciencias, seria a niveles altos. 
- No.
- Misma idea tengo, por ahora estoy viendo soluciones a este problema como que necesites tal temperatura y la maquina te suba y tal.

2019-10-21 22:15 UTC, Evankhell561 requested changes

2019-10-21 22:15 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/obj/item/stock_parts/cell/high = null
travis te tiró error porque lo que yo dije fue que cambiaras 
var/obj/item/stock_parts/cell/high/bcell  por var/obj/item/stock_parts/cell/bcell. 
En cambio tu lo que hiciste fue cambiarlo por var/obj/item/stock_parts/cell/high.

2019-10-21 22:23 UTC, SagaStars commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/obj/item/stock_parts/cell/high = null
![IMG_0275](https://user-images.githubusercontent.com/55407528/67247584-dd014900-f42f-11e9-8352-4499a7d8b454.jpeg)

2019-10-21 22:29 UTC, Evankhell561 commented
Pues te diria que mejor la metieras en cargo, hacerla en ciencias genera mucho problema. Hacer un pedido es más sencillo.

2019-10-21 22:39 UTC, SagaStars commented
Lo tendre en consideracion *wink*

2019-10-31 20:39 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/obj/item/stock_parts/cell/bcell = null
no es obligatorio pero puedes quitar todo lo que diga "bcell", y reemplazarlo por "cell"? Funcionará igual y no cambiará nada pero odio el "bcell". Acá un ejemplo: 
var/obj/item/stock_parts/cell/bcell = null
var/obj/item/stock_parts/cell/cell= null

2019-11-11 05:28 UTC, closed without merging

2019-11-11 05:28 UTC, SagaStars commented
acabo de hacer un whoopsie.