ME AÑADO EN EL JUEGO Y LO DESTRUYO (y ademas añado el slime crossbreeding)
Helixis/Paradise pull request #225
Opened 2019-10-18 17:03 UTC by josesitomartinez

## What Does This PR Do
Intento añadir el slime crossbreeding de TG.

## Why It's Good For The Game
Mas cosas que hacer.
## Images of changes
Mas tarde
## Changelog
:cl:
add: Todo
del: Nada
:cl:

2019-10-21 00:56 UTC, Evankhell561 commented
Pues se ve bien la forma en la que lo vas llevando. Poco a poco. Supongo que porque los ports que yo hago suelo porter todo a la vez y luego solucionar los errores me hizo ver esto como una tarea extremadamente complicada pero creo que esto llegará a buen puerto.

2019-10-21 08:45 UTC, josesitomartinez commented
Muchas gracias, voy poco a poco para poder ir testeando cada core y ver cuales funcionan y cuales no.
Igualmente, algunos no estan implementados por no entender como funcionan algunas cosas de TG en Paradise (como hacer que se le puedan inyectar cosas a un core) pero creo que este PR se podria terminar pronto (sin contar los cores que que necesitan el sistema de traits)

2019-10-23 23:40 UTC, josesitomartinez commented
![image](https://user-images.githubusercontent.com/43261137/67441956-effd5000-f5cc-11e9-93a7-62a3334f3a88.png)
![image](https://user-images.githubusercontent.com/43261137/67441960-f7bcf480-f5cc-11e9-8967-9664783307ad.png)

2019-10-24 01:23 UTC, Evankhell561 commented
Vaya trabajo, mi mierdi pc ya hubiera explotado. Tu pr actual considera éste pr también?
https://github.com/tgstation/tgstation/pull/40928/files

2019-10-24 01:27 UTC, josesitomartinez commented
Si, ya todo lo que pude hacer esta listo en chilling. Ahora mismo estoy tratrando de arreglar los que no funcionan

2019-10-24 11:38 UTC, Evankhell561 requested changes

2019-10-24 11:38 UTC, Evankhell561 commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/_misc.dm
> +	chargerate = 2250 //1.5 times the normal rate.
No sé como funcione el self_charge en tg pero ha de funcionar muy diferente a hispania. Si éste valor llegara al live, bien podrias quitar el generador de energia y darles varias de éstas a inge. Nuesto core cargado tiene solo 500 de chargerate, así que para un 1.5 veces eso, tienes que cambiar de chargerate = 2250 a chargerate = 750

2019-10-24 18:45 UTC, josesitomartinez commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/_misc.dm
> +	chargerate = 2250 //1.5 times the normal rate.
arreglado

2019-10-24 18:46 UTC, SagaStars commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/_misc.dm
> +	chargerate = 2250 //1.5 times the normal rate.
texto

2019-11-03 21:54 UTC, closed without merging