Nuevo Mob Lavaland: Plazmite
Helixis/Paradise pull request #241
Opened 2019-10-31 20:20 UTC by Spircen

## What Does This PR Do
-Agrega un nuevo mob a Lavaland los Plazmite, son avispas enormes que inyectan una toxina única cada que atacan.
-Agrega una nueva carne para poder ser cocinada en lava, las Plazmite Legs.
-Plazmite suelta 1 hueso y 1 Plazmite leg al ser guibeado.
-Agrega Tendrils de Plazmite a la rotación de Tendrils que pueden hacer spawn.
-Agrega un nuevo químico, Plazmite Venom.
-Aumenta el numero de mobs que pueden hacer spawn alrededor de un tendril de 3 a 4. 

## Why It's Good For The Game

-Adjunta un nuevo peligro a lavaland agregando un mob mas rápido capaz de seguir y envenenar.
-Da a los spawn points de lavaland la posibilidad de conseguir charcoal cocinando las patas de Plazmites.
-Agrega diversidad a la iluminación de lavaland debido a que los plazmite brillan. 
-Aumenta el peligro de cazar tendrils debido a que antes con solo 3 mobs alrededor de los tendrils se creaban puntos ciegos donde la gente podía entrar sin necesidad de pelear para conseguir un tendril.

## Images of changes

<img src="https://i.imgur.com/HwE4gEE.png" alt="tree" style="max-width:100%;">
<img src="https://i.imgur.com/jsXC1ze.png" alt="tree" style="max-width:100%;">

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
wip: added a few works in progress
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
experiment: added an experimental thingy
/:cl:

2019-10-31 20:30 UTC, Evankhell561 commented
Varias cosas
1. Me encanta el mosco nuevo.
2. El cambio de aumentar el numero de mobs que aparecen no me parece adecuado meterlo también en este pr. Si el aumento fuera solo para el mosco nuevo, me pareceria bien pero como lo aplicas a todos los mobs es como llegar y decir "si quieren mi mosco nuevo, aprueben mi cambio al juego". Yo mismo sufro de eso a veces, muchas veces.
3. se supone que tienes que modificar el changelog donde se reflejen los cambios. Aunque hacerlo luego de  ponerlos en la sección de: "What Does This PR Do" pueda parecer redundante, la diferencia es que en esa sección puedes explayarte más sobre como funciona cada cosa mientras en el changelog va es el cambio a secas.

2019-10-31 20:34 UTC, Evankhell561 requested changes

2019-10-31 20:34 UTC, Evankhell561 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +/obj/item/reagent_containers/food/snacks/plazmiteleg
Esto debe ir a la carpeta de hispania.

2019-10-31 20:34 UTC, Evankhell561 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +/obj/item/reagent_containers/food/snacks/plazmiteleg/burn()
Esto también debe ir en una carpeta en hispania.

2019-10-31 20:34 UTC, Evankhell561 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +/obj/item/reagent_containers/food/snacks/plazmite_fingers
y esto.

2019-10-31 20:34 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/plazmite.dm
> +/mob/living/simple_animal/hostile/asteroid/poison/plazmite
igual acá, mueve todo este dm a hispania.

2019-10-31 20:34 UTC, Evankhell561 commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +/datum/reagent/plazmite_venom
hispania again.

2019-10-31 20:35 UTC, Evankhell561 commented
Los sprites del mosco también deberian ir en hispania

2019-10-31 20:39 UTC, SagaStars requested changes
120 de vida es muy poco, de dos disparos de KA te lo cargas y considerando que hay dual wielding moriria de un solo disparo. Yo preferiblemente lo pondria en 125 o 130 para que solo pueda morir rapidamente con una upgrade de daño, evita el rusheo tho.

2019-10-31 20:43 UTC, Spircen commented on code/modules/food_and_drinks/food/foods/meat.dm
> +/obj/item/reagent_containers/food/snacks/plazmiteleg
¿Pero por que debo mover los artículos que componen al mob a hispania si su existencia depende de una linea de code que no puedo re ubicar a otro punto?

2019-10-31 20:46 UTC, Evankhell561 requested changes
los sprites del mosco también deben ir en una carpeta de hispania hispania.

2019-10-31 20:50 UTC, Evankhell561 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +/obj/item/reagent_containers/food/snacks/plazmiteleg
A ver, con "mueve esto a hispania" me refiero a esa linea y a todas las otras lineas de codigo que la acompañan, todo el codigo de "/obj/item/reagent_containers/food/snacks/plazmiteleg". Si eso es lo que preguntas. La razon y la lógica que usamos es la siguiente: si estás agregando una linea de codigo que no depende del dm en qué esté entonces debe ir a hispania. Acá por ejemplo debes mover tu codigo nuevo de "code/modules/food_and_drinks/food/foods/meat.dm" a "code/hispania/modules/food_and_drinks/food/foods/meat.dm"

2019-10-31 20:59 UTC, Evankhell561 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +/obj/item/reagent_containers/food/snacks/plazmiteleg
acá un ejemplo sacado de https://github.com/Helixis/Paradise/pull/177/files.
![image](https://user-images.githubusercontent.com/49106866/67985672-c01eff80-fbff-11e9-94ff-6c00ddafdb1c.png)

2019-10-31 21:00 UTC, Evankhell561 commented on code/modules/food_and_drinks/food/foods/meat.dm
> +/obj/item/reagent_containers/food/snacks/plazmiteleg
Acá un ejemplo sacado de https://github.com/Helixis/Paradise/pull/177/files. 
![image](https://user-images.githubusercontent.com/49106866/67985786-feb4ba00-fbff-11e9-8bb3-d30c00fa099d.png)

2019-10-31 21:19 UTC, Evankhell561 requested changes

2019-10-31 21:19 UTC, Evankhell561 commented on code/game/objects/structures/lavaland/necropolis_tendril.dm
> +/obj/structure/spawner/lavaland/plazmite
Esto también para hispania.

2019-10-31 21:23 UTC, Evankhell561 requested changes

2019-10-31 21:23 UTC, Evankhell561 commented on code/game/objects/structures/lavaland/necropolis_tendril.dm
> +	max_mobs = 4
Este es el cambio que creo deberias hacer en otro pr. En especial, luego de que muevas  los cambios a este dm a hispania, tu nuevo pr no creará conflictos con el actual. Si a ryzor le gusta este cambio margueará tu nuevo pr casi de inmediato, Si no le gusta no lo hará. Pero si le gusta este cambio y está metido junto con el pr del mosco vas a tener que esperar que testee tu mosco para que se apruebe (si es que le gusta tu mosco)

2019-10-31 21:39 UTC, Evankhell561 requested changes

2019-10-31 21:39 UTC, Evankhell561 commented on code/modules/reagents/chemistry/reagents/toxins.dm
> +/datum/reagent/plazmite_venom/on_mob_life(mob/living/M)
Ésto también.

2020-02-02 23:47 UTC, Spircen commented
Ya arme la version final en otro lado xd mejor cerrar esta.

2020-02-02 23:47 UTC, closed without merging