Medbay Oxigen Assistant
Helixis/Paradise pull request #245
Opened 2019-11-11 05:44 UTC by SagaStars

- Añade el M.O.A (Medbay Oxigen Assistant) curara un 16 de daño de sofocación tambien estabilizando el ritmo cardiaco y dependera de una powercell. Usando un quimico especial que no puede ser obtenible de ninguna manera ( Tarda como 5 minutos en descargarse con una bateria inicial ).
- El M.O.A ya aparecera por defecto en medbay, con una bateria claro.

## Why It's Good For The Game
   La principal razon del objeto es que servira como una alternativa a dejar a un tripulante sin pulmon 15 minutos en cryo mientras que operar a un mono humanizado para sacar un pulmon y transplantarselo, dejando al jugador poder hablar por la radio, responder pdas, ect. 

   En resumen un estabilizador que gaste energia en vez de quimicos de manera efectiva. Que hara el trabajo de medbay un poco mas comodo a la hora de dejar en espera a pacientes o tratar a distintos a la vez.

![](https://cdn.discordapp.com/attachments/643316781980712960/643316803438903306/unknown.png)

![](https://cdn.discordapp.com/attachments/643316781980712960/643316972725075978/unknown.png)

## Changelog
🆑 
add: nuevo equipamiento para medbay (moa)
add: el quimico que usa el moa
🆑

2019-11-11 13:36 UTC, SagaStars commented
No tengo ni la menor idea de por que el 2º commit no esta haciendo nada.

2019-11-11 13:41 UTC, SagaStars commented
> No tengo ni la menor idea de por que el 2º commit no esta haciendo nada.

Bruh, sobrescribio los cambios.

2019-11-11 15:50 UTC, Evankhell561 commented
¿Tiene algo negativo el ir por ahi con uno de esos?
¿Si no es así, esto me permitiria ir por ahi corriendo sin pulmones?

2019-11-11 15:58 UTC, Evankhell561 requested changes

2019-11-11 15:58 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +		if(bcell.charge < (hitcost+chrgdeductamt)) // If after the deduction the baton doesn't have enough charge for a stun hit it turns off.
> If after the deduction the baton doesn't have enough charge for a stun hit it turns off.

¿El Baton, cual baton?

2019-11-11 16:02 UTC, Evankhell561 requested changes

2019-11-11 16:02 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	..()
si lo unico que harás deficinedo el attack_self de éste objeto es:
`..()`
entonces no necesitas esa ninguna de estas lineas de código.

2019-11-11 16:06 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	..()
Tengo entendido que  `..()` es para llamar a los comportamientos viejos, osea que estás haciendo una deficinion nueva solo para que tu objeto se comporte como se iba a comportar si no hacias una definición nueva de attack_self().

2019-11-11 16:18 UTC, Evankhell561 commented
te recomiendo actualizar tu master, copiar el mapa de tu master, actualizar ésta branch con tu master
y luego pegar manualmente el mapa de tu master en ésta branch. Luego, puedes modificar el mapa de nuevo.

2019-11-12 00:45 UTC, SagaStars commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +		if(bcell.charge < (hitcost+chrgdeductamt)) // If after the deduction the baton doesn't have enough charge for a stun hit it turns off.
cHHUcHAAAAAAAAAAAAAA

2019-11-12 00:45 UTC, SagaStars commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	..()
H U H

2019-11-12 00:47 UTC, SagaStars commented
> ¿Tiene algo negativo el ir por ahi con uno de esos?
> ¿Si no es así, esto me permitiria ir por ahi corriendo sin pulmones?

Pues... Es demasiado grande como para guardarlo en una duffelbag, eso cuenta?

2019-11-17 23:48 UTC, Evankhell561 requested changes

2019-11-17 23:48 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/obj/item/stock_parts/cell/bcell = null
¿No queria molestarte porque tenias varios conflictos pero puedes reemplazar todas las "bcell" por "cell" en todo tu codigo? En paradise ya no queda ninguna referencia a los "bcell". Esto no tendrá ningun efecto real pero ayuda a tener un codigo más entendible y más fácil de manejar. En esta linea por ejemplo pasas de  var/obj/item/stock_parts/cell/bcell = null a 
var/obj/item/stock_parts/cell/cell = null

2019-11-17 23:51 UTC, SagaStars commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/obj/item/stock_parts/cell/bcell = null
Tambien con los bcell = null?

2019-11-17 23:52 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +	var/obj/item/stock_parts/cell/bcell = null
Cada vez que veas que tu codigo dice "bcell", lo borras y pones "cell" en su lugar.

2019-11-17 23:55 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagent_containers/moa.dm
> +			bcell = null
ejemplo, de: ```
		if(bcell)
			bcell.loc = get_turf(src.loc)
			bcell = null
```
a:
```
		if(cell)
			cell.loc = get_turf(src.loc)
			cell = null
```

2019-11-18 01:47 UTC, SagaStars commented
wHOpSIE DOOPSIEEEE

![](https://cdn.discordapp.com/attachments/387645048386486273/645796715722571805/7130000c6a1bd6d935835712fe68482f.png)

![](https://cdn.discordapp.com/attachments/387645048386486273/645796931477569537/5ca4d22788e5f0b06820f043fbfe98d9.png)

2019-11-18 01:47 UTC, closed without merging