Medbay Oxigen Assistant: 358/2 days (funky mode edition)
Helixis/Paradise pull request #246
Opened 2019-11-18 18:59 UTC by SagaStars

- Añade el M.O.A (Medbay Oxigen Assistant) curara un 16 de daño de sofocación tambien estabilizando el ritmo cardiaco y dependera de una powercell. Usando un quimico especial que no puede ser obtenible de ninguna manera ( Tarda como 5 minutos en descargarse con una bateria inicial ).
- El M.O.A ya aparecera por defecto en medbay, con una bateria claro.

## Why It's Good For The Game
La principal razon del objeto es que servira como una alternativa a dejar a un tripulante sin pulmon 15 minutos en cryo mientras que operar a un mono humanizado para sacar un pulmon y transplantarselo, dejando al jugador poder hablar por la radio, responder pdas, ect.

En resumen un estabilizador que gaste energia en vez de quimicos de manera efectiva. Que hara el trabajo de medbay un poco mas comodo a la hora de dejar en espera a pacientes o tratar a distintos a la vez.

![image](https://user-images.githubusercontent.com/55407528/69081144-c1c83000-0a13-11ea-9e4d-369e79578515.png)
![image](https://user-images.githubusercontent.com/55407528/69081168-cdb3f200-0a13-11ea-9a56-a1a97f997a03.png)

## Changelog
:cl: 
add: nuevo equipamiento para medbay (moa)
add: el quimico que usa el moa
:cl:

2019-11-18 19:07 UTC, SagaStars commented
Y si evan, le puse lo de las ``cell`` 
![image](https://user-images.githubusercontent.com/55407528/69081787-2041de00-0a15-11ea-968b-c9ac26678e50.png)

2019-11-21 22:36 UTC, Evankhell561 requested changes

2019-11-21 22:36 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/chemistry/reagents/medicine.dm
> +	name = "Oxygen"
No había ya un químico llamado oxygen?

2019-11-21 22:36 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/chemistry/reagents/medicine.dm
> +		update_flags |= M.adjustOxyLoss(-16, FALSE)
todos los otros químicos que usan `update_flags |= algo llevan `al final `return ..() | update_flags`. No sé para qué es pero seguro es importante. 

![image](https://user-images.githubusercontent.com/49106866/69382576-ca2b9f80-0c8d-11ea-950f-576ab14139c5.png)

2019-11-21 22:44 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagents_containers/moa.dm
> +	var/mode = IV_INJECT
No vi que llegaste a usar esta variable nunca, ¿para qué o dónde la usas?

2019-11-21 22:45 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagents_containers/moa.dm
> +#define IV_INJECT 1
Veo que has definido esto para usarlos en la variable "mode" pero no vi que la hayas usado para otra cosa que no sea definirla. Si no vas a usar "mode" en ningun lado estas dos definiciones no son necesarias.

2019-11-21 22:50 UTC, Evankhell561 requested changes

2019-11-21 22:50 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/chemistry/reagents/medicine.dm
> +	taste_description = "a safe refuge"
Tiene el mismo `taste_description ` que la cryoxadona. No creo que dos bebidas debieran compartir la misma `taste_description `

2019-11-21 22:54 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagents_containers/moa.dm
> +		end_processing()
Me gusta como terminas el proceso y lo inicas solo cuando es necesario, me robaré este código a futuro :3

2019-11-21 22:54 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagents_containers/moa.dm
> +/obj/item/reagent_containers/moa/pickup(mob/user)
me robo esto de actualizar iconos también~

2019-11-22 18:25 UTC, SagaStars commented on code/HISPANIA/modules/reagents/reagents_containers/moa.dm
> +	var/mode = IV_INJECT
Fuck

2019-11-22 18:26 UTC, SagaStars commented on code/HISPANIA/modules/reagents/chemistry/reagents/medicine.dm
> +		update_flags |= M.adjustOxyLoss(-16, FALSE)
hmm... ya lo pongo

2019-11-22 18:26 UTC, SagaStars commented on code/HISPANIA/modules/reagents/chemistry/reagents/medicine.dm
> +	taste_description = "a safe refuge"
vaya caprichos evan

2019-11-22 18:26 UTC, SagaStars commented on code/HISPANIA/modules/reagents/chemistry/reagents/medicine.dm
> +	taste_description = "a safe refuge"
ya lo pongo po

2019-11-22 18:27 UTC, SagaStars commented on code/HISPANIA/modules/reagents/reagents_containers/moa.dm
> +		end_processing()
**epico**

2019-11-22 18:44 UTC, SagaStars commented on code/HISPANIA/modules/reagents/chemistry/reagents/medicine.dm
> +	name = "Oxygen"
meme nombre time

2020-02-15 02:43 UTC, Evankhell561 requested changes

2020-02-15 02:43 UTC, Evankhell561 commented on code/HISPANIA/modules/reagents/reagents_containers/moa.dm
> +	var/hitcost = 64
pon esto en 85.

2020-02-16 20:14 UTC, closed without merging