NUEVO Arte Marcial para el HoS: Seckaraty [WIP]
Helixis/Paradise pull request #247
Opened 2019-11-19 18:42 UTC by DanaDririon

## What Does This PR Do
Agrega un arte marcial para el HoS. Este es un WIP. Se irán agregando las descripciones de los combos a medida que se balanceen y eso.

## Why It's Good For The Game
Al HoS le faltaba un arte marcial para cazar antags y abusar de los prisioneros. 

## Changelog
:cl: DanaDririon
add: Arte Marcial Seckaraty
/:cl:

2019-11-19 18:57 UTC, Evankhell561 commented
¿Agrega también una version reducida de todo esto para sec? Lo iba a hacer yo pero no tengo tanto tiempo como antes u.u

2019-11-19 19:02 UTC, DanaDririon commented
> ¿Agregas también una version reducida de todo esto para sec? Lo iba a hacer yo pero no tengo tanto tiempo como antes u.u
> PD: para el piloto no, el piloto es KK porque ya mola demasiado.

No, sólo para el HoS

2019-11-21 23:14 UTC, Evankhell561 commented
"-Backpack Drop: Disarm Disarm Grab. Le quita todas las mochilas al objetivo y las pone en las manos del usuario."
¿Todas las mochilas? osea que si peleo con alguien y le hago eso de repente tendré su mochila en la mano? No me parece mal pero me parece que hacer eso es raro e incomodo cuando lo que se quiere es pelear con alguien. ¿por qué no robarle al objetivo lo que tenga en la mano? Esto es más natural y más util en una pelea creo yo.

2019-11-21 23:18 UTC, Evankhell561 commented
De igual forma, no sé. Me gustaria que todos los de sec tengan algun conocimiento básico de combate para que no solo sean robustos por rol quizá solo un combo o una sola habilidad de este estilo de combate para los securatas. También fomenta la idea de que el hos recibió un entrenamiento similar que ellos pero el suyo está completo~
supongo que lo haré yo en el futuro si esto se aprueba.

2019-11-21 23:47 UTC, DanaDririon commented
Hice el arte marcial más como crowd control, cuando el HoS anda patrullando y en alerta roja no están cooperando, o cuando algún prisionero o civil está molestado. Si no, hubiera hecho un Krav Maga 2 o un CQC: La secuela. En una emergencia van a seguir usando tasers y letales. Pienso que lo que hice es algo diferente y creativo, y no golpes que hagan más daño y eso.

2019-11-21 23:51 UTC, Evankhell561 commented
> Hice el arte marcial más como crowd control, cuando el HoS anda patrullando y en alerta roja no están cooperando, o cuando algún prisionero o civil está molestado. Si no, hubiera hecho un Krav Maga 2 o un CQC: La secuela. En una emergencia van a seguir usando tasers y letales. Pienso que lo que hice es algo diferente y creativo, y no golpes que hagan más daño y eso.

Entiendo, es un enfoque diferente al que yo creía.

2019-11-22 00:34 UTC, DanaDririon commented
> Entiendo, es un enfoque diferente al que yo creía.

Recuerda que a melee siguen ganando los stunbaton, las telescopic, el glare del vampiro, el screech del ling, el congelado del Shadow, los talismanes del culto, el Stun de los Xenos, etc...
Jaja

2019-11-24 23:30 UTC, Evankhell561 requested changes

2019-11-24 23:30 UTC, Evankhell561 commented on code/HISPANIA/modules/martial_arts/seckaraty.dm
> +		return 1
Noto que tienes muchos return 1 y return 0. Vas a infartar a Ryzor, te recomiendo cambiar los return 1 por return TRUE y los return 0 por return FALSE.

2019-11-25 16:39 UTC, DanaDririon commented on code/HISPANIA/modules/martial_arts/seckaraty.dm
> +		return 1
No importa si es que aceptan el de Saga y no el mío 😔

2019-11-25 16:40 UTC, Evankhell561 commented on code/HISPANIA/modules/martial_arts/seckaraty.dm
> +		return 1
No aceptarán el de saga ni el tuyo con todos esos return 0 y return 1.

2019-11-25 16:42 UTC, Evankhell561 commented on code/HISPANIA/modules/martial_arts/seckaraty.dm
> +		return 1
además, el de saga está como más inspirado a la agresividad. No he analizado mucho el tuyo pero parece algo más defensivo. Si el hos no lo quiere tal vez el blueshield sí. Osea es un tipo entrenado especialmente por NT en cuerpo y mente para proteger a tipos importantes, tener algo como esto seria genial por si no lo quieren para el hos.

2019-11-25 16:45 UTC, DanaDririon commented on code/HISPANIA/modules/martial_arts/seckaraty.dm
> +		return 1
:0
Para el Blueshield
Me has dado ánimos jeje
Hoy arreglo lo que me falta

2020-01-05 19:44 UTC, DanaDririon commented
El de Saga está mejor, más flashy y dinámico
Voy a ver si hago un arte marcial para el Blueshield, y si reuso alguno de estos

2020-01-05 19:44 UTC, closed without merging