En russia los airlocks se pegan a las hojas.
Helixis/Paradise pull request #262
Opened 2019-12-18 04:32 UTC by SagaStars

Mero capricho mio, la `overlay` de cuando pones un papel u foto en un airlock se me hacia muy pequeño y muy imperceptible, así que ahora es 2 pixeles mas grande. _sep eso es todo._

![Screenshot_1](https://user-images.githubusercontent.com/55407528/71055889-a8f38d00-212d-11ea-817e-d093c6f2f234.png)

### Changelog
:cl:
imageadd: tweaks a la `airlock_overlay` cuando pones una foto o papel en un airlock
:cl:

2019-12-19 12:13 UTC, Evankhell561 requested changes
me gusta pero yo hubiera cambiado el codigo del overay para que redireccione a alguna carpeta a hispania donde estaria guardado este overay modificado.

2020-01-25 14:54 UTC, SagaStars commented
> me gusta pero yo hubiera cambiado el codigo del overay para que redireccione a alguna carpeta a hispania donde estaria guardado este overay modificado.

Done

2020-01-31 18:54 UTC, SagaStars commented
Travis culero, compila bien y todo

2020-01-31 18:59 UTC, SagaStars commented
>Travis culero, compila bien y todo

Olviden lo que dije, compila una mierda.
![image](https://user-images.githubusercontent.com/55407528/73566470-50a4f000-443a-11ea-9d50-6d415223185c.png)

2020-03-04 02:13 UTC, closed without merging