health analyzers quitados de medikits
Helixis/Paradise pull request #272
Opened 2019-12-25 21:50 UTC by Nicaragua1

Idea de Evan, extraida de TG

https://github.com/tgstation/tgstation/pull/46917

:cl:
balance: Los health analyzer ahora son mas raros
/:cl:

2019-12-26 22:16 UTC, Evankhell561 requested changes

2019-12-26 22:16 UTC, Evankhell561 commented on code/modules/research/designs/medical_designs.dm
> +/datum/design/healthanalyzer
Deberias hacer este cambio en hispania y no en paradise. Mete este diseño en code/hispania/modules/research/designs/medical_designs.dm

2020-01-20 18:32 UTC, iRyzor commented
Aja, por qué?

2020-01-22 03:44 UTC, Nicaragua1 commented on code/modules/research/designs/medical_designs.dm
> +/datum/design/healthanalyzer
El nuevo  medical_designs.dm  en esa ruta que pasaste agrego todo el otro code tambien o solo las lineas del healthanalyzer?

Es decir creo un dm  que sea un espejo del que ya existe agregando el nuevo healthanalyzer? o creo un nuevo dm solo con las lineas del health anaylzer?

2020-01-22 11:38 UTC, Evankhell561 commented on code/modules/research/designs/medical_designs.dm
> +/datum/design/healthanalyzer
creas el code/hispania/modules/research/designs/medical_designs.dm. y ahi solo debe tener las linas de codigo del diseño del health analyzer. Cabe mencionar que debes eliminar el diseño del health analizer de aca code/modules/research/designs/medical_designs.dm

2020-02-02 17:26 UTC, Nicaragua1 commented on code/modules/research/designs/medical_designs.dm
> +/datum/design/healthanalyzer
Hecho

2020-02-02 17:27 UTC, Nicaragua1 commented
Listo para ser aprobado

2020-02-02 17:28 UTC, Nicaragua1 commented
Actualizado
Movido a carpeta hispania diseño

Listo para ser aprobado

2020-02-02 18:25 UTC, Evankhell561 commented
Testeaste esto?

2020-02-02 19:55 UTC, Nicaragua1 commented
> Testeaste esto?

si

2020-02-02 19:57 UTC, Evankhell561 commented
> > Testeaste esto?
> 
> si

Tonces porqué falta el paradise.dme?

2020-02-02 21:05 UTC, Evankhell561 requested changes

2020-02-02 21:05 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/medical_designs.dm
> +/datum/design/healthanalyzer
Este archivo, no lo veo incluido en el dme.

2020-02-04 23:31 UTC, Nicaragua1 commented
Ya esta para mergear

2020-02-05 10:53 UTC, Evankhell561 commented
No le pusiste el check al nuevo archivo, si margeo esto, el health analizer no estara en el protolathe

2020-02-05 11:06 UTC, Evankhell561 commented
La proxima vez  no solo compiles, testea. ve al protolathe y asegurate de que puedas imprimirlo.

2020-02-12 19:28 UTC, Evankhell561 requested changes

2020-02-12 19:28 UTC, Evankhell561 commented on code/game/objects/items/weapons/storage/firstaid.dm
> -		new /obj/item/healthanalyzer( src )
Comenta en vez de borrar. Ayuda con los conflictos.

2020-02-14 02:21 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/medical_designs.dm
> +/datum/design/healthanalyzer
Sigues sin ponerle el check a este dm cuando compilas con el dream maker. Solo eso falta.

2020-02-14 02:41 UTC, Evankhell561 requested changes

2020-02-14 02:41 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/medical_designs.dm
> +	build_type =  PROTOLATHE
Sin ideas mias o tienes dos espacios aca?

2020-02-14 02:42 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/medical_designs.dm
> +/datum/design/healthanalyzer
Sigue sin tener el check este dm al compilar

2020-02-14 03:34 UTC, Nicaragua1 commented on code/HISPANIA/modules/research/designs/medical_designs.dm
> +	build_type =  PROTOLATHE
ideas tuyas

2020-02-14 22:35 UTC, Evankhell561 requested changes

2020-02-14 22:35 UTC, Evankhell561 commented on code/game/objects/items/weapons/storage/firstaid.dm
> -		new /obj/item/healthanalyzer( src )
falto comentar este precisamente. es el unico que borraste.

2020-02-14 22:35 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/medical_designs.dm
> +	build_type =  PROTOLATHE
hay dos putos espacios ahi, quita uno.

2020-02-15 05:04 UTC, Nicaragua1 commented on code/game/objects/items/weapons/storage/firstaid.dm
> -		new /obj/item/healthanalyzer( src )
agregado

2020-02-15 05:04 UTC, Nicaragua1 commented on code/HISPANIA/modules/research/designs/medical_designs.dm
> +	build_type =  PROTOLATHE
fixed

2020-02-15 12:14 UTC, merged