OH VAYA UN PR SOBRE ARMAS!
Helixis/Paradise pull request #275
Opened 2020-01-01 03:24 UTC by SagaStars

- Nuevas sprites para las armas de la armeria y unos toquesitos al lasercannon
- Un monton de sprites inhand
- La **lasergun** ahora hace = `22.5` de daño
- El **ion rifle** y el **lasercannon** ahora tienen la habilidad del lwap para poder apuntar(`Toggle scope`), ahora pueden ver 3 tiles mas adelante y ver 3 tiles menos atras.
## Why It's Good For The Game
 Creo que es muy obvio lo positivo de ver las armas `in-game` en las manos de tu pj o de otro pj, ahora pueden temer por tu vida sin tener que examinar a alguien antes para saber si tiene un .357, el cambio de sprites de armas fue para que destaquemos un poco mas diferentes a los otros codes. 

El cambio del daño en la **laser gun** es para darle un poco mas de sentido el por que elegir entre **energy gun** o **laser gun**, **energy gun** para humanos, **lasergun** para arañas, vines, ect

La extension en la habilidad de `toggle scope` es por consistencia, el ion rifle ya de por si tiene mira y el lasercannon se basa en que hace mas daño por mas lejos que este el enemigo por lo cual es logico que tenga una mirilla.
## Images of changes
![asdasdasdasdasdadasdasd](https://user-images.githubusercontent.com/55407528/71637809-eecb4d80-2c23-11ea-9930-6f1b4506d5bf.png)

## Changelog
:cl:
add: `toggle scope` de 3 tiles para la **ion rifle** y el **lasercannon**
tweak: Ahora el **lasergun** hace `2.5` daño.
fix: El **rocketlauncher** ahora tiene su sprite `in-hand` arreglada (El nombre del `item_state` antes era incorrecto)
imageadd: Sprites `in-hand` de muchas armas, ya podrán ver que arma tienen sin tener que examinar.
/:cl:

2020-01-01 11:13 UTC, Evankhell561 commented
¿Y si mueves todos esos sprites a hispania? con que en paradise modifiquen un solo sprite de esos y se perderan los tuyos. si quieres borra los viejos de paradise para ahorrar espacio, no idea.

2020-01-01 11:50 UTC, Evankhell561 requested changes

2020-01-01 11:50 UTC, Evankhell561 commented on code/modules/projectiles/projectile/beams.dm
> +	damage = 22.5
me encantan todos tus cambios, solo no entiendo el por qué de éste. También, podrías mover esto a hispania.

2020-01-01 11:51 UTC, Evankhell561 requested changes

2020-01-01 11:51 UTC, Evankhell561 commented on code/modules/projectiles/ammunition/energy.dm
> +	select_name = "kill"
fuera de lo que ya dije de que no entiendo este cambio, podrias mover esto a hispania.

2020-01-01 19:34 UTC, SagaStars commented
> ¿Y si mueves todos esos sprites a hispania? con que en paradise modifiquen un solo sprite de esos y se perderan los tuyos. si quieres borra los viejos de paradise para ahorrar espacio, no idea.

Evan no sabes cuanto te odio 
![640287274743103543](https://user-images.githubusercontent.com/55407528/71645272-2a115f00-2cac-11ea-8d3e-55306d70eb26.gif)

2020-01-01 19:35 UTC, SagaStars commented on code/modules/projectiles/ammunition/energy.dm
> +	select_name = "kill"
lo mismo que ya dije.

2020-01-01 19:35 UTC, SagaStars commented on code/modules/projectiles/projectile/beams.dm
> +	damage = 22.5
Esto es necesario para que el **lasergun** haga ``22.5 de daño``, y ya lo muevo en breve

2020-01-02 03:25 UTC, Evankhell561 commented
Aja, pero por qué quieres que haga 22.5 de daño?

2020-01-04 16:41 UTC, SagaStars commented
> Aja, pero por qué quieres que haga 22.5 de daño?

Este cambio solo aplica a la **lasergun**, es para darle un poco mas de amor por que siempre termina siendo el ultimo niño al que eligen cuando van a jugar pelota. Siempre quedaba como una **energy gun** con otra sprite sin disabler por lo cual con esto se le da un poco mas de imagen y da un aspecto mas táctico a la armería (Ya que esta seria mas efectiva contra xenos ,vines ,blob , terrors).

2020-01-31 21:47 UTC, Evankhell561 commented
el changelog
![image](https://user-images.githubusercontent.com/49106866/73576850-cf595780-4451-11ea-95ea-ac0220c6dcbf.png)

2020-01-31 22:11 UTC, SagaStars commented
> el changelog
> ![image](https://user-images.githubusercontent.com/49106866/73576850-cf595780-4451-11ea-95ea-ac0220c6dcbf.png)

CHING CHOOONG LISTooOoOoo

2020-02-02 15:00 UTC, Evankhell561 requested changes

2020-02-02 15:00 UTC, Evankhell561 commented on code/modules/projectiles/ammunition/energy.dm
> +/obj/item/ammo_casing/energy/lasergun2
Pasa esto a hispania y terminaste.

2020-02-02 15:09 UTC, Evankhell561 requested changes

2020-02-02 15:09 UTC, Evankhell561 commented on code/modules/projectiles/projectile/beams.dm
> +/obj/item/projectile/beam/laser2
Pasa esto a hispania.

2020-02-02 16:33 UTC, merged