Anillos y guantes de boxeo al loadout.
Helixis/Paradise pull request #284
Opened 2020-01-11 16:08 UTC by Silverexperience

## What Does This PR Do
Añade guantes de boxeo y anillos al loadout de guantes.

## Why It's Good For The Game
Mas variedad para escojer objetos al personaje.

## Images of changes
![imagen](https://user-images.githubusercontent.com/58746682/72207023-d6b1c480-3494-11ea-8f8b-f97b408485c2.png)

## Changelog
:cl:
add: Añade mas objetos al loadout de guantes.
/:cl:

2020-01-11 16:11 UTC, DanaDririon commented
Anillos :ok_hand: 
Guantes de boxeo :thinking: 
Por cierto en el changelog, después del primer :cl: pone tu nombre

2020-01-11 16:15 UTC, Silverexperience commented
> Por cierto en el changelog, después del primer cl pone tu nombre
¿A que te refieres?

2020-01-11 16:27 UTC, DanaDririon commented
> > Por cierto en el changelog, después del primer cl pone tu nombre
> 
> ¿A que te refieres?

:cl: Silverexperience
add: ...
/:cl:

2020-01-11 16:30 UTC, Silverexperience commented
> 
> 
> > > Por cierto en el changelog, después del primer cl pone tu nombre
> > 
> > 
> > ¿A que te refieres?
> 
> cl Silverexperience
> add: ...
> /cl

Yo no lo veo asi ni al editar sale.
![imagen](https://user-images.githubusercontent.com/58746682/72207272-feeef280-3497-11ea-8876-50a1cb890711.png)

2020-01-12 15:37 UTC, SagaStars commented
> > > > Por cierto en el changelog, después del primer cl pone tu nombre
> > > 
> > > 
> > > ¿A que te refieres?
> > 
> > 
> > cl Silverexperience
> > add: ...
> > /cl
> 
> Yo no lo veo asi ni al editar sale.
> ![imagen](https://user-images.githubusercontent.com/58746682/72207272-feeef280-3497-11ea-8876-50a1cb890711.png)

No es necesario eso de poner tu nombre al lado del :cl: , el bot del changelog agarra el nombre del usuario de github del PR si no escriben nada al lado.

2020-01-22 00:18 UTC, Evankhell561 commented
¿Los guantes de box tienen algna propiedad especial?

Uhm, también, hay un pr similar a este en paradise. esperaré a ver que resuelven ellos para testear esto así que se quedará acá un tiempo.

2020-01-22 00:22 UTC, Silverexperience commented
> 
> 
> ¿Los guantes de box tienen algna propiedad especial?
> 


Los guantes de boxeo permiten golpear a alguien sin hacerle daño bruto

2020-01-23 16:26 UTC, Evankhell561 commented
En pardise hay un pr parecido a este, esperare a ver que deciden allá antes de marguear esto y que luego tengan conflictos. 
https://github.com/ParadiseSS13/Paradise/pull/12873

2020-01-23 16:30 UTC, Evankhell561 requested changes

2020-01-23 16:30 UTC, Evankhell561 commented on code/modules/client/preference/loadout/loadout_gloves.dm
> +/datum/gear/gloves/boxinggreen
Creo que podrias mover todos estos nuevos agregados a una carpeta en hispania.

2020-01-26 14:53 UTC, Silverexperience commented on code/modules/client/preference/loadout/loadout_gloves.dm
> +/datum/gear/gloves/boxinggreen
Movidos

2020-01-26 15:49 UTC, Evankhell561 approved these changes

2020-04-28 23:00 UTC, Spircen commented
Todo en orden aquí, buen aporte.

2020-04-28 23:00 UTC, merged

2020-04-29 00:54 UTC, Evankhell561 commented
Esto estaba en wait por algo, luego hay que revisar que tanto de esto es codigo duplicado y qué no lo es.

2020-04-29 01:12 UTC, Spircen commented
Dude lleva en wait dos meses, igualmente todo esta bien pero ya vi un error super basico que no note y es que faltan los include al juego.