w0w cinta policia y de ingenieria epica
Helixis/Paradise pull request #288
Opened 2020-01-17 03:35 UTC by SagaStars

_porteado de baystation_

Este PR añade 2 nuevos objetos (**police tape** y **engineering tape**) el cual estará en las vendings de seguridad y ingeniería (SecTech y YouTool) el cual sirve para hacer seudo-barricadas las cuales no dejan pasar al jugador a menos que este suba la cinta con `help_intent` y deje accesible al paso a los jugadores por 2 segundos, tambien puede romper la cinta con `harm_intent` o disparandole con un arma. Esto también aplica para las puertas (Hay un pequeño inconveniente con esto y es que solo puedes poner cinta en un airlock en `harm_intent`)
![image](https://user-images.githubusercontent.com/55407528/72582099-05c29e80-38b8-11ea-819f-c6507cd72664.png)

![image](https://user-images.githubusercontent.com/55407528/72582033-ca27d480-38b7-11ea-88bf-df6845f0344e.png)

Also, puedes crear unas `area_markings` en el suelo con tan solo tocarle al suelo con la cinta.
![image](https://user-images.githubusercontent.com/55407528/72582018-c1370300-38b7-11ea-9e44-4508592c7086.png)

![MEH](https://user-images.githubusercontent.com/55407528/72581669-85e80480-38b6-11ea-9cab-3d8bd2564e54.png)
![Screenshot_3](https://user-images.githubusercontent.com/55407528/72581675-88e2f500-38b6-11ea-9149-bbd8f754ad34.png)

Da mas inmersión y evita que gente caminando sin ver a donde van terminen metiéndose en una brecha como anormales, blah blah blah

**VIENE CON SONIDOS INCLUIDOS B)** (((reciclados)))
## Changelog
:cl:
add: Cinta policial y una cinta para ingenieria presentes en las vendings de sus departamentos
:cl:

2020-01-20 18:21 UTC, Nicaragua1 commented
Me gusta mucho la idea solo que no me convence el sprite. Resalta demasiado a la vista el ancho y el tono del rojo

2020-01-20 18:23 UTC, Evankhell561 commented
> Me gusta mucho la idea solo que no me convence el sprite. Resalta demasiado a la vista el ancho y el tono del rojo

Ahora que lo dices.., la roja se ve rara. si fuera igual a la amarilla fuera genial.

2020-01-20 19:49 UTC, SagaStars commented
> > Me gusta mucho la idea solo que no me convence el sprite. Resalta demasiado a la vista el ancho y el tono del rojo
> 
> Ahora que lo dices.., la roja se ve rara. si fuera igual a la amarilla fuera genial.

Hmmm... Ahora que lo dices tienes razón. Cambiare el color de el de ingenieria a naranja y a sec a amarillo

2020-01-20 20:04 UTC, Evankhell561 commented
> Hmmm... Ahora que lo dices tienes razón. Cambiare el color de el de ingenieria a naranja y a sec a amarillo

creo que me expresé mal. a mi lo que me incomoda es lo rectangular que se ve... no sé por qué 
![image](https://user-images.githubusercontent.com/49106866/72754520-6abf1280-3b9e-11ea-8925-3d2f9e798889.png)

así lo veo bien pero con los colores que ya tiene. pero hey, no me hagas mucho caso.

2020-01-25 03:15 UTC, SagaStars commented
> > Hmmm... Ahora que lo dices tienes razón. Cambiare el color de el de ingenieria a naranja y a sec a amarillo
> 
> creo que me expresé mal. a mi lo que me incomoda es lo rectangular que se ve... no sé por qué
> ![image](https://user-images.githubusercontent.com/49106866/72754520-6abf1280-3b9e-11ea-8925-3d2f9e798889.png)
> 
> así lo veo bien pero con los colores que ya tiene. pero hey, no me hagas mucho caso.

Esto ya dependerá del oficial, como puedes ver se puede poner en todas las direcciones, por lo cual se le quita esa impresión tan rectangular.
![image](https://user-images.githubusercontent.com/55407528/73115634-31b8d200-3eff-11ea-8552-55570a676da3.png)

2020-01-25 22:41 UTC, Evankhell561 commented
entonces que le hiciste a los colores al final? a mi me gustaba el rojo-naranja del sec y el amarillo de inge.

2020-01-25 23:56 UTC, SagaStars commented
> entonces que le hiciste a los colores al final? a mi me gustaba el rojo-naranja del sec y el amarillo de inge.

Pues cambie a sec a amarillo y a ingenieria a naranja. A mi tambien me gustaba el rojo pero luego de darme cuenta de que le quedaba mal con las marcas del suelo amarilla... La cambie a amarilla y pues de hecho ahora me gusta mas con el amarillo, tiene un toque mas de "Escena del crimen". Ya reflejare los cambios en la desc del PR.

2020-01-29 06:30 UTC, Evankhell561 requested changes
funciona bien y me gusta pero segun estuve testeando esta cosa no tiene limite de uso, y la funcion stop puede poner una cinta tan grande como se quiera. Ambas funciones deberian tener un uso limitado.

2020-02-02 12:16 UTC, Evankhell561 requested changes

2020-02-02 12:16 UTC, Evankhell561 commented on code/__DEFINES/layers.dm
> -#define NOT_HIGH_OBJ_LAYER 3.5
que hacen los cambios a estas definiciones?

2020-02-02 15:26 UTC, SagaStars commented on code/__DEFINES/layers.dm
> -#define NOT_HIGH_OBJ_LAYER 3.5
Es el orden en el que se van a mostrar las layers, solo he agregado 3 mas `#define BELOW_MOB_LAYER 3.9
#define LYING_MOB_LAYER 3.91
#define ABOVE_HUMAN_LAYER 4`
De esta manera la tape esta encima del locker, y ect

2020-02-02 15:31 UTC, Evankhell561 commented on code/__DEFINES/layers.dm
> -#define NOT_HIGH_OBJ_LAYER 3.5
esta muy bien que hayas agregado tres pero por que modificar los demas y alterar el orden?

2020-02-02 16:05 UTC, SagaStars commented on code/__DEFINES/layers.dm
> -#define NOT_HIGH_OBJ_LAYER 3.5
Puta que me he equivocado, solo agrege dos el `#define ABOVE_DOOR_LAYER 3.3` y `#define ABOVE_HUMAN_LAYER 4`.
No he cambiado el orden de nada, simplemente he subido los valores para poder poner el  `#define ABOVE_DOOR_LAYER 3.3` en medio y el `#define LYING_MOB_LAYER 3.91` para que no llegase a **4** y alterase de verdad el orden

2020-02-03 01:58 UTC, merged