Globos
Helixis/Paradise pull request #301
Opened 2020-01-22 15:07 UTC by Silverexperience

## What Does This PR Do
Añade Globos porteados de TG, menos uno, con sus recetas de construccion.

## Why It's Good For The Game
Globos decorativos con los que decorar y tener una escusa mas para matar al perro del HoP.

## Images of changes
![PR_1](https://user-images.githubusercontent.com/58746682/72905650-2912a100-3d31-11ea-8c97-f3cbc4f5d5bd.png)
![PR_2](https://user-images.githubusercontent.com/58746682/72905726-447dac00-3d31-11ea-8084-7c085f261727.png)

## Changelog
:cl:
add: Añade Globos y sus recetas de construccion
/:cl:

2020-01-22 15:24 UTC, DanaDririon commented
Buen PR :ok_hand: 
Aunque arreglaría unos typos
-Cambiar el nombre del dm: Ballons.dm > ballons.dm , para llevar concordancia con el resto del code
-Poner una línea de código vacía entre los tipos de globos

2020-01-22 16:27 UTC, Silverexperience commented
Ahora ya deberia estar listo

2020-01-22 18:30 UTC, Silverexperience commented
Ahora si que si deberia

2020-01-22 18:41 UTC, DanaDririon commented
Aún me estresa que tenga la mayúscula **B**allons.dm 
xd

2020-01-22 18:42 UTC, Silverexperience commented
> 
> 
> Aún me estresa que tenga la mayúscula **B**allons.dm
> xd

Esta cambiado pero lo sigue poniendo asi, abajo se ve en el codigo que no tiene mayuscula

2020-01-22 18:44 UTC, DanaDririon commented
> > Aún me estresa que tenga la mayúscula **B**allons.dm
> > xd
> 
> Esta cambiado pero lo sigue poniendo asi, abajo se ve en el codigo que no tiene mayuscula

Ah ya :eyes:
Merge entonces :fire:

2020-01-22 18:45 UTC, Silverexperience commented
> 
> 
> > > Aún me estresa que tenga la mayúscula **B**allons.dm
> > > xd
> > 
> > 
> > Esta cambiado pero lo sigue poniendo asi, abajo se ve en el codigo que no tiene mayuscula
> 
> Ah ya eyes
> Merge entonces fire

Espera un commit mas

2020-01-22 19:01 UTC, Silverexperience commented
Listo

2020-01-23 14:27 UTC, Evankhell561 requested changes
Este pr está bien pero me parece que añade demasiadas opciones de crafteo para una sola cosa. Intenta reducirlas de alguna forma.

2020-01-24 15:03 UTC, Nicaragua1 commented
Se me ocurre que pueda ser craftear baloon y luego con Alt cambiarle el sprite por unica ves. Como el revolver del detective. O con un crayon tendria sentido igual que como se hacen las figuras de carton

2020-02-01 01:35 UTC, Silverexperience commented
> 
> 
> Este pr está bien pero me parece que añade demasiadas opciones de crafteo para una sola cosa. Intenta reducirlas de alguna forma.

Listo, ahora puedes cambiar el colo con los crayones del color especifico.

2020-02-01 01:47 UTC, Evankhell561 requested changes

2020-02-01 01:47 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/toys/Balloons.dm
> +/obj/item/toy/balloon_H
quita la H mayuscula de la ruta, nada de mayusculas en la ruta de los objetos.

2020-02-01 18:01 UTC, Silverexperience commented on code/HISPANIA/game/objects/items/toys/Balloons.dm
> +/obj/item/toy/balloon_H
Quitados

2020-02-02 10:44 UTC, Evankhell561 commented
Cuantos recipes quedaron al final?

2020-02-02 12:20 UTC, Evankhell561 commented
Cuantas opciones de crafteo quedan?
el payaso tiene una caja de crayones o un crayon multicolor?

2020-02-02 14:20 UTC, Silverexperience commented
> 
> 
> Cuantos recipes quedaron al final?

5,el del mimo,payaso,corgi y macdonalds

2020-02-02 14:21 UTC, Silverexperience commented
> el payaso tiene una caja de crayones o un crayon multicolor?

El crayon multicolor se le da  al payaso

2020-02-03 01:21 UTC, Evankhell561 commented
Testeaste los de los crayones de mimo y payasin?

2020-02-03 01:43 UTC, Silverexperience commented
> 
> 
> Testeaste los de los crayones de mimo y payasin?


![](https://cdn.discordapp.com/attachments/387645048386486273/673704463596388363/unknown.png)

![](https://cdn.discordapp.com/attachments/387645048386486273/673704476116516885/unknown.png)

![](https://cdn.discordapp.com/attachments/387645048386486273/673704524715786250/unknown.png)
Funciona y testeado
Aunque cambies el color solo detecta el crayon ,o color

2020-02-05 17:38 UTC, merged