Mas canciones
Helixis/Paradise pull request #304
Opened 2020-01-22 23:47 UTC by Silverexperience

## What Does This PR Do
Añade canciones al Hispaniabox.
Añade:Star Wars Cantina, Never gona give you up, Rappin for Jesus,Golden wind song,Meganolovania,Fly me to the moon, The house of the rising sun y tripaloski.

## Why It's Good For The Game
Mas variedad de musica que escuchar cuando te aburres en el bar y quieres montar fiesta con globos.

## Changelog
:cl:Silverexperience
add: Mas canciones al Hispaniabox
/:cl:

2020-01-22 23:53 UTC, DanaDririon commented
Ah, arreglaste el Gurú Griff

2020-01-31 08:33 UTC, EnzoSeptum commented
Re bien meter canciones de los jojos y tripaloski, la música slav está super guapa

2020-02-12 21:46 UTC, Silverexperience commented
> 
> 
> Re bien meter canciones de los jojos y tripaloski, la música slav está super guapa

¡O dios! ¡El legendario Reido comento mi PR!

2020-02-15 16:37 UTC, Evankhell561 requested changes
agrega solo una cancion extra. las demas puedes reemplazarlas. te recomendria dejar las mas populares.

2020-02-15 16:37 UTC, Evankhell561 commented
hay algunas aca que tambien estan en el lobby, cuidado con ellas.

2020-02-15 20:12 UTC, Silverexperience commented
> 
> 
> agrega solo una cancion extra. las demas puedes reemplazarlas. te recomendria dejar las mas populares.

Ya quita alguna de la antiguas para remplazarlas aun asi añade 4 megabytes el archivo

2020-02-17 04:35 UTC, merged