Gym and kitchen
Helixis/Paradise pull request #342
Opened 2020-02-06 03:38 UTC by ABAtilus

## What Does This PR Do

Este Pr incluye una modificacion en la zona de entretenimiento. Cambiando un mini teatro por un gimnasio compacto. Tambien incluye una modificacion de la cocina, agregando un cereal mixer, un objeto normalmente admin spawned, y sacando un tacho de disposals.
## Why It's Good For The Game

Creo que el gimnasio tiene mas potencial para otorgar rol, ya que el mini teatro es inutilizado en la gran mayoria de partidas.
Ume me pidio que agregara el cereal mixer a la cocina para mas variedad de comidas.
## Images of changes

**Gimnasio:**
Antes:
![imagen](https://user-images.githubusercontent.com/60436899/73903783-b64d0e00-4878-11ea-9491-2787db27b0ab.png)
Despues:
![imagen](https://user-images.githubusercontent.com/60436899/73903790-b947fe80-4878-11ea-86da-b36953323eda.png)
**Cocina**
Antes:
![imagen](https://user-images.githubusercontent.com/60436899/73903803-c369fd00-4878-11ea-8d84-087e10b676b3.png)
Despues:
![imagen](https://user-images.githubusercontent.com/60436899/73903806-c7961a80-4878-11ea-866d-ad5e26978477.png)

## Changelog
:cl:
add: Gimnasio en la zona de entretenimiento
add: Cereal mixer en la cocina, arriba de una mesa
del: Tacho de disposals en la cocina
:cl:

2020-02-06 11:00 UTC, Evankhell561 requested changes

2020-02-06 11:00 UTC, Evankhell561 commented on _maps/arena_template.dmm.backup
> +"a" = (/turf/unsimulated/wall,/area/space)
borra este archivo.

2020-02-06 11:00 UTC, Evankhell561 commented on _maps/map_backups/MinaGate.dmm.backup
> +"aa" = (/turf/simulated/mineral/random,/area/space)
y este tambien.

2020-02-11 04:24 UTC, Evankhell561 commented
tengo sentimientos encontrados, por un lado este pr podria marguearse ahora, por otro, las maquinas de ejercicio de la parte de abajo te haecne parecer que chocas con la ventana. y el saco de box de abajo queda raro tambien al poderte meter abajo de el, parece que cuelga de la nada... :thonkl: no sé que hacer con esto.

2020-02-11 14:04 UTC, ABAtilus commented
> tengo sentimientos encontrados, por un lado este pr podria marguearse ahora, por otro, las maquinas de ejercicio de la parte de abajo te haecne parecer que chocas con la ventana. y el saco de box de abajo queda raro tambien al poderte meter abajo de el, parece que cuelga de la nada... :thonkl: no sé que hacer con esto.

Hm, bueno eso es lo más que pude hacer sin ocupar mucho espacio. Quería mantenerlo del tamaño del mini teatro para no alterar mucho el mapa. Pero solo se me ocurrió ponerlo de esa forma.

2020-02-11 14:14 UTC, merged