Nuevo Virus: Coronavirus (WIP)
Helixis/Paradise pull request #343
Opened 2020-02-06 03:59 UTC by Spircen

## What Does This PR Do

Agrega un nuevo virus en desarrollo llamado coronavirus, la única forma de ser contagiado por este horrible virus es mediante sopa de un murciélago en especifico. Por el momento si bien el prototipo es funcional necesito discutir los valores de la enfermedad con la comunidad y a su vez determinar un lugar de spawn para dicho 

## Why It's Good For The Game

Agrega la diversidad de formas de amenaza que no solo sean pega y mata. Por el momento quiero determinar que forma de curarla consideran seria algo justo e interesante con la comunidad.

## Images of changes

![image](https://user-images.githubusercontent.com/46639834/73904683-5f3c3e80-4862-11ea-8db7-ac9120ef4c4b.png)
![ezgif-1-8b4896116d7d](https://user-images.githubusercontent.com/46639834/73904722-8e52b000-4862-11ea-920b-2f5b5f8664a9.gif)

## Changelog
:cl:
add: coronavirus
add: toxicbat
add: bat meat
add: bianfu reagent
add: sprites de toxic bat y bat meat
/:cl:

2020-02-07 23:40 UTC, Evankhell561 requested changes

2020-02-07 23:40 UTC, Evankhell561 commented on paradise.dme
> +#include "code\HISPANIA\game\objects\items\toys\Balloons.dm"
no me envies este cambio.

2020-02-08 21:51 UTC, Spircen commented on paradise.dme
> +#include "code\HISPANIA\game\objects\items\toys\Balloons.dm"
Voy a actualizar todos mis PR que tienen este cambio. Si no lo enviaba anteriormente, github hacia que fallara la cosa que hace para validar los cambios.

2020-03-16 01:37 UTC, Spircen commented
1.

2020-03-16 01:37 UTC, closed without merging