Chad Peste negra (WIP)
Helixis/Paradise pull request #346
Opened 2020-02-07 00:43 UTC by Silverexperience

## What Does This PR Do
Con esto del coronavirus no podia faltar una peste negra.
Añade una peste negra espacial con sintomas algo nuevos y mezclados de los diferentes tipos de peste.

WIP:Añadir una forma de contagiarse la enfermedad que no sea con admins.

## Why It's Good For The Game
Mas trabajo para esos vagos de los virologos y darle uso al disfraz de peste en sentido decorativo.
## Images of changes
![EO_jwuhW4AE4BsI](https://user-images.githubusercontent.com/58746682/73990972-0b595480-494b-11ea-9ba7-b287975ff292.png)

## Changelog
:cl:
add: Añade peste negra.
fix: Quita la mayuscula de globos
/:cl:

2020-02-14 17:31 UTC, Silverexperience commented
Listo el WIP

2020-03-09 02:13 UTC, Evankhell561 requested changes

2020-03-09 02:13 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/fleas.dm
> +	name = "Bunch of space fleas"
mayusculas

2020-03-09 07:07 UTC, Silverexperience commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/fleas.dm
> +	name = "Bunch of space fleas"
¿Le añado mayúsculas?

2020-03-09 07:08 UTC, Silverexperience commented
@Evankhell561 El mob tiene densidad.
                            Llegue a ver al los space fleas spawnear.

2020-03-09 11:09 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/fleas.dm
> +	name = "Bunch of space fleas"
Esto no me parece un nombre propio para tener mayúsculas... Los otros mobs lo tienen

2020-03-09 14:09 UTC, Silverexperience commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/fleas.dm
> +	name = "Bunch of space fleas"
Mayusculas quitadas.

2020-03-09 20:50 UTC, merged