Almacén de Instrumentaría Medbay (WIP)
Helixis/Paradise pull request #350
Opened 2020-02-09 03:53 UTC by Spircen

## What Does This PR Do

Agregara un mueble capaz de ser crafteable con metal para poder almacenar botiquines y muchisima mas instrumentaría medica, por el momento el PR esta en pasos de bebe solamente con el mueble existente que guarda botiquinies, cajas de parches, pildoras e IV´'s ademas de que al ser desarmado da metal. Planeo aun el hablar respecto a que instrumentaria deberia ser capaz de almacenar, cuanto serian sus limites y si debería tener algún tipo de bloqueo de accesos.

## Why It's Good For The Game

Agrega la posibilidad de tener un mejor orden de la instrumentaría medica y sus utensilios que suelen ocupar la mayoría de el recibidor de medbay esta atascada de instrumentaría medica que esta tirada en las mesas y en caso de brechas son mortales. 

## Images of changes

En cuanto pueda avanzar mas puedo subir las imagenes por el momento ocupa sprites reutilizados de otras maquinarias.
## Changelog
:cl:
add: medcase
/:cl:

2020-02-09 03:55 UTC, SagaStars commented
Queremos imagenes de los cambios spircen 
![image](https://user-images.githubusercontent.com/55407528/74095944-8008cc00-4ace-11ea-8d21-7ed41280e652.png)

2020-02-10 04:22 UTC, Evankhell561 commented
hay otro pr de mapeo, quiza entren en conflicto... ambos estan en wip por ahora. ya veremos.

2020-02-10 04:23 UTC, Evankhell561 requested changes

2020-02-10 04:23 UTC, Evankhell561 commented on code/HISPANIA/modules/medfur/med_fur_items.dm
> +	icon = 'icons/obj/library.dmi'
mete el icono a hispania.

2020-02-10 20:01 UTC, Spircen commented on code/HISPANIA/modules/medfur/med_fur_items.dm
> +	icon = 'icons/obj/library.dmi'
Dije que estoy reutilizando sprites. Ese icono solo hace referencia para poder tener un sprite por el momento. Eventualmente creare un sprite distinto.

2020-03-16 01:37 UTC, closed without merging