Esquilemos al zorro
Helixis/Paradise pull request #379
Opened 2020-02-15 17:14 UTC by Silverexperience

## What Does This PR Do
Le quita la sangre,los huesos y los organos respirativos a los diona, les devuelve su lentitud y la inmunidad al espacio pero aun reciben mas daño por quemaduras y el nuevo critico solo impide que es regeneren con la luz pero no los mata.

## Why It's Good For The Game
A nadie le gustan las diona rapidas y este las devuelve a como gustaban

## Changelog
:cl:
add: Antiguas caracteristicas de Diona
del: Nuevas caracteristicas de Diona
/:cl:

2020-02-15 18:18 UTC, Evankhell561 requested changes

2020-02-15 18:18 UTC, Evankhell561 commented on code/modules/surgery/organs/subtypes/diona.dm
> +	alcohol_intensity = 0.5
devuelve esto justo a la linea de donde la sacaste.

2020-02-15 18:34 UTC, Silverexperience commented on code/modules/surgery/organs/subtypes/diona.dm
> +	alcohol_intensity = 0.5
> 
> 
> devuelve esto justo a la linea de donde la sacaste.

Devuelto, creo.

2020-02-15 18:38 UTC, Evankhell561 requested changes

2020-02-15 18:38 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +
quita esta linea inecesaria.

2020-02-15 18:38 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	brute_mod = 0.40
ponlo a 0.75

2020-02-15 18:38 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/friendly/diona.dm
> -	minbodytemp = 0
que hace la variable minbodytemp = 0?

2020-02-15 18:53 UTC, Silverexperience commented on code/modules/mob/living/simple_animal/friendly/diona.dm
> -	minbodytemp = 0
La temperatura minima que puede alcanzar el cuerpo de manera estable

2020-02-15 18:54 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +
Quitado

2020-02-15 18:54 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	brute_mod = 0.40
Puesto

2020-02-15 19:02 UTC, Evankhell561 requested changes

2020-02-15 19:02 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	speed_mod = 5
si todo lo que vas a hacer es darle resistencia al daño fisico y que no sienta dolor no es necesario este nerf a la velocidad. si quieres nerfear esta caracteristica puedes subirla a 2.

2020-02-15 19:04 UTC, Evankhell561 commented
tambien arregla el changelog
balance: las dionas resisten más daño bruto
balance: las dionas no sienten dolor.

2020-02-15 19:07 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	speed_mod = 5
Le subo el daño de los puñetazos tambien

2020-02-15 19:13 UTC, Evankhell561 commented
bien, entonces el concepto de diona mecanicamente es : un tanke de daño fisico que te puede reventar la cara a puñetazos.

2020-02-15 19:14 UTC, Silverexperience commented
> 
> 
> bien, entonces el concepto de diona mecanicamente es : un tanke de daño fisico que te puede reventar la cara a puñetazos.

Si, basicamente eso.

2020-02-15 19:16 UTC, Evankhell561 commented
me sigue pareciendo que cindo de velocidad es demasiado lento incluso para esto. y que subirlo a 4 no está mal.

2020-02-15 19:17 UTC, Silverexperience commented
> 
> 
> me sigue pareciendo que cindo de velocidad es demasiado lento incluso para esto. y que subirlo a 4 no está mal.

Bien, lo subo a 4.

2020-02-15 21:09 UTC, Evankhell561 commented
yo le añadiria tambien resitencia a los disambler. o a los daños a la stamia. tambien le subiria un poco la vida. tal vez a 120 y le aumentaria el daño que recibien del fuego para compensar.

2020-02-15 21:11 UTC, Evankhell561 commented
También, se me ocurre podrian regenerar brazos y piernas.  como los slimes.

2020-02-15 21:13 UTC, Evankhell561 commented
incluso le añadiria que reciban más daño de cosas filosas.

2020-02-15 21:19 UTC, Silverexperience commented
> 
> 
> También, se me ocurre podrian regenerar brazos y piernas. como los slimes.

¿Y a que costo seria la regeneracion?, si no estaria bastante roto.

2020-02-15 21:20 UTC, Evankhell561 commented
> ¿Y a que costo seria la regeneracion?, si no estaria bastante roto.

cierto, olvide de que ya se curaban las heridas en la luz. olvidalo.

2020-02-15 21:20 UTC, Silverexperience commented
> 
> 
> > ¿Y a que costo seria la regeneracion?, si no estaria bastante roto.
> 
> cierto, olvide de que ya se curaban las heridas en la luz. olvidalo.

Lo demas podria intentar añadirlo

2020-02-15 21:22 UTC, Evankhell561 commented
> Lo demas podria intentar añadirlo

bien, tampoco digo que le des inmunidad al daño de stamia o a los disambler. solo que sea dificil tumbarlos de esa forma. debido a que ya son lentos de por sí.

2020-02-15 22:03 UTC, Evankhell561 requested changes

2020-02-15 22:03 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		brute_mod = W.force / 10
entre 5.

2020-02-15 22:05 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		brute_mod = W.force / 10
Eso quizas seria demasiado porque para objetos con 32 de daño afilados quedaria con 6,4 de debilidad al daño bruto

2020-02-15 22:08 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		brute_mod = W.force / 10
tienes 20 de vida extra man.

2020-02-15 22:10 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		brute_mod = W.force / 10
Bueno, lo dejare entre 5

2020-02-17 15:27 UTC, Evankhell561 requested changes

2020-02-17 15:27 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	punchdamagehigh = 14
esto no parece estar funcionado. no pega duro.

2020-02-17 15:27 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	stamina_mod = 0.65
pon esto a 0.75

2020-02-17 15:27 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	burn_mod = 1.3
segun el discord, le estamos dando mucho powa. subele esto a 1.4.

2020-02-17 15:27 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		brute_mod = W.force / 5
las armas filosas tambien hacen daño filoso por lo que si le reduces el 25% y luego le aumentas el 25% es como si no le aumentaras nada. pon force / 2.

2020-02-17 17:32 UTC, Evankhell561 requested changes

2020-02-17 17:32 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		brute_mod = W.force / 2
solo para asegurarnos, al final de este proc pon: ..()

2020-02-17 17:38 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	stamina_mod = 0.65
listo

2020-02-17 17:38 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	burn_mod = 1.3
Listo.

2020-02-17 17:39 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		brute_mod = W.force / 5
Listo

2020-02-17 17:39 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +		brute_mod = W.force / 2
Listo

2020-02-17 18:09 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	punchdamagehigh = 14
Ahora si pega mas duro o eso comprobe

2020-02-17 18:11 UTC, Evankhell561 requested changes

2020-02-17 18:11 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	punchdamagehigh = 19
no creo que solo aumentar el valor lo solucione... y esos valores si funcionan son demasiado altos. prueba poner 10 y 15 y testea.

2020-02-17 18:13 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	punchdamagehigh = 19
Tengo imagenes de lo testeado en la descripcion del PR aunque si hace bastante daño.

2020-02-17 18:21 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	punchdamagehigh = 19
caules son estos valores para un humano?

2020-02-17 18:26 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/species/diona.dm
> +	punchdamagehigh = 19
De 0 a 9

2020-02-17 21:12 UTC, merged