La mascota no divertida del basurero
Helixis/Paradise pull request #380
Opened 2020-02-15 22:56 UTC by Silverexperience

## What Does This PR Do
Añade una nueva mascota al basurero.
Añade a un pug llamado Vulcano

## Why It's Good For The Game
Ahora habra un mob renegado de la sociedad que protejera toda la basura del lugar mientras la gente se burla de el, ¡Oh sociedada!

## Images of changes
![imagen](https://user-images.githubusercontent.com/58746682/74596365-8fe45b00-504e-11ea-9139-9439442a8c41.png)

## Changelog
:cl:
add: Añade una mascota al basurero
/:cl:

2020-02-15 22:57 UTC, DanaDririon commented
Lptm
Te doy puntos porque lo pusiste en disposals

2020-02-16 03:17 UTC, Evankhell561 requested changes

2020-02-16 03:17 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +/mob/living/simple_animal/pet/dog/pug/unfunny
Hispania, bro.

2020-02-16 12:59 UTC, Silverexperience commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +/mob/living/simple_animal/pet/dog/pug/unfunny
Movido a Hispania

2020-02-16 16:27 UTC, Silverexperience commented
Ignoremos esto, no sucedio.

2020-02-16 16:34 UTC, closed without merging