Van 2 abejas y se cae la del medio.
Helixis/Paradise pull request #384
Opened 2020-02-16 01:51 UTC by N0thy

(Agradecimiento a @Silverexperience por el mapmergue)
## What Does This PR Do
Añade el sub-job de Beekeeper, un apiary en botánica y una taquilla para el Beekeeper 

## Why It's Good For The Game
Bueno, hay jugadores que les interesa más concentrarse en cuidar a las abejas que de las plantas en sí, así que pensé que sería buena idea añadirlo como sub-job con sus cosas.

## Images of changes
(Gracias @/Sauronato por la SS)
![image](https://user-images.githubusercontent.com/53350410/74590727-3f9ad800-5011-11ea-8d8e-9790c93e9808.png)
![image](https://user-images.githubusercontent.com/53350410/74590549-b20ab880-500f-11ea-85d5-9d0eb851f3ef.png)
![image](https://user-images.githubusercontent.com/53350410/74590558-d1a1e100-500f-11ea-8d31-df6156f323f5.png)

## Changelog 
:cl: Nothing
add: sub-rol beekeeper
add: traje de apicultor al empezar siendo beekeeper
add: locker para beekeeper
imageadd: sprite para locker para beekeeper
del: pump que había debajo del locker
/:cl:

2020-02-16 12:09 UTC, Evankhell561 requested changes

2020-02-16 12:09 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/hydroponics.dm
> +	new	/obj/item/honey_frame(src)
y estos espacios enormes?

2020-02-16 12:12 UTC, Evankhell561 requested changes

2020-02-16 12:12 UTC, Evankhell561 commented on code/game/jobs/job/support.dm
> +	spawn_positions = 2
por qué aumentas el numero de bartenders en la estacion?

2020-02-16 12:12 UTC, Evankhell561 commented on code/game/jobs/job/support.dm
> +	spawn_positions = 1
por qué reduces el numero de chef en la estacion?

2020-02-16 12:12 UTC, Evankhell561 commented on code/game/jobs/job/support.dm
> +/datum/outfit/job/hydro/pre_equip(mob/living/carbon/human/H, visualsOnly = FALSE)
esto para hispania

2020-02-16 12:14 UTC, Evankhell561 commented
pasa tambien una SS de ti hablando por la radio, quiero asegurarme de que aparezca del color correcto cuando habla y cuando tiene prendido las configuraciones de las telecomunicaciones

2020-02-16 13:18 UTC, N0thy commented on code/game/jobs/job/support.dm
> +	spawn_positions = 2
Bueno, fallo mío es que resulta que justamente quise aumentar el número de Chefs porque mi Repo no estaba actualizado entonces al hacer el PR cambiaba el número de Chefs a 1, cuando estaba a 2, así que cometí el fallo no leí que es lo que modifiqué exactamente y ahora mismo tenemos 2 bartenders )¿?
Ahora lo soluciono.

2020-02-16 14:29 UTC, Evankhell561 requested changes

2020-02-16 14:29 UTC, Evankhell561 commented on code/HISPANIA/game/jobs/job/support.dm
> +
comenta aca que esto es la indumentario del beekeeper.

2020-02-16 14:37 UTC, Evankhell561 commented on code/game/jobs/job/support.dm
> -
regresa estas dos lineas

2020-02-16 20:23 UTC, Evankhell561 requested changes

2020-02-16 20:23 UTC, Evankhell561 commented on code/game/jobs/job/support.dm
> +/datum/outfit/job/hydro/pre_equip(mob/living/carbon/human/H, visualsOnly = FALSE)
si ya enviaste esto a hispania deberias eliminarlo de aca.

2020-02-16 20:25 UTC, Evankhell561 requested changes

2020-02-16 20:25 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/hydroponics.dm
> +/obj/structure/closet/secure_closet/beekeeper
este dm no tiene el check puesto.

2020-02-17 15:48 UTC, Evankhell561 requested changes

2020-02-17 15:48 UTC, Evankhell561 commented on code/game/jobs/job/support.dm
> -
regresa esta linea que has eliminado

2020-02-17 16:40 UTC, merged