¡¡Nueva mecánica para las armas de largo alcance!! || Los disparos de escopetas a pointblank te empujan || El stun del taser ya no es instantáneo
Helixis/Paradise pull request #405
Opened 2020-02-18 23:11 UTC by SagaStars

------
### --- Port de TG https://github.com/tgstation/tgstation/pull/47677, Una nueva mecánica para las armas de largo alcance que funciona de la siguiente manera!. ---
- Con el arma en tu mano a una distancia de pointblank, clickeas sobre el objetivo en concreto en `grab_intent` en el cual lo dejaras en un estado en el cual si se mueve, se dispara tu arma de manera automatica **(steady)**, es importante decir que el objetivo aun podra interactuar con objetos, tirarte objetos, moverse en su inventario, hablar, comunicarse por la radio y pda. OJO! tu si podras moverte y hasta disparar tu arma sin remover el estado! pero ten en cuenta de que tienes un maximo de 2 tiles en las cuales puedes desplazarte sin cancelar el **steady**.
- Entre mas tiempo este el objetivo en el estado de **steady** tu punteria cambiara de estado, los cuales traen modificadores de daño!
**-- Estado I** = En este estado inicial, el arma no tendra modificador.
**-- Estado II** = Luego de 3 segundos, tendra un modificador de `2x` de daño.
**-- Estado III** = Luego de 10 segundos, tendra un modificador de` 2.5x` de daño.
- FLINCH, Si el usuario que este apuntando al objetivo es herido/empujado, habra una probabilidad de que se accione el arma sola.
-- Flinch Normal = 88%
-- Flinch Siendo herido en el brazo que este tu arma || Si estas en el Estado III = 100%
_**Toda la informacion que estoy dando tendra su feedback in-game con texto a la par de sonidos.**_
------
### --- Port de TG _again_ https://github.com/tgstation/tgstation/pull/47443. Las escopetas accionadas a objetivos en pointblank empujan. Ta padre si o no?
------
### --- Los electrodes ya no stunean instantáneamente, asies la municion usada por tasers. Ahora tienen un delay de 1.5 segundos antes de efectuar su stun en el objetivo.
------
### BONUUUS
- Cuando apuntas a alguien en harm_intent con un arma suena el iconico *click* ya saben como los cliches esos que cuando suben un arma siempre suena *click*
- Retoca un par de `item_states` a armas con similitudes con el revolver.
- El punching bag tiene densidad. 

## Why It's Good For The Game
Mejora tooooodooo al respecto de tomar rehenes! Era tan facil antes como comerte 2 disparos y desarmar a tu agresor, ya no mas. Las escopetas ganan un nuevo feel. Los tasers ya no son armas de stun instantaneo _**no del todo**_, por lo cual abre cancha a mas intercambios de disparos y situaciones mas tensas (Reminder de que el taser no es el unico con insta-stun: flashbangs, flashs, peppersprays, la lista sigue) por favor, evitemos stuns instantáneos de larga distancia.

## Images of changes
Explicacion breve de como funciona
![image](https://user-images.githubusercontent.com/55407528/74785766-7f67f680-5281-11ea-8e17-d646849dd164.png)
-----
Puedes mover al objetivo, siempre que lo tengas agarrado. (GIF ABAJO)
https://gyazo.com/41fbd87f4c389976ca113191d43b8f36
OOOOOOOF (GIF ABAJO)
https://gyazo.com/d7a995ae36805f60ec34888197db6269
Stuns yeah. (GIF ABAJO)
https://gyazo.com/8253355e450308ce44c7b2a8c4d26e15
-----
## Changelog
:cl:
add: Nueva mecanica para las armas de largo alcance "Freeze!".
add: Las escopetas a pointblank empujan!
tweak: La punching bang ahora no puede ser traspasada.
balance: El electrode ahora tiene un delay de 1.5s.
soundadd: Cuando apuntas a alguien en harm con un arma de largo alcance suena un *click*
tweak: El revolver del blueshield ahora tiene una sprite en mano de revolver. Ironico que antes no.
/:cl:

2020-02-18 23:50 UTC, Evankhell561 commented
no pongas cosas que no tienen nada que ver con el pr de armas aca.  estas cosas estan geniales y no nito testear para aprobarlas. Estaria bien que esten en otro pr.

```
Cuando apuntas a alguien en harm_intent con un arma suena el iconico click ya saben como los cliches esos que cuando suben un arma siempre suena click
Retoca un par de item_states a armas con similitudes con el revolver.
El punching bag tiene densidad.
```

2020-02-19 12:25 UTC, Evankhell561 requested changes

2020-02-19 12:25 UTC, Evankhell561 commented on code/datums/components/gunpoint.dm
> +#define GUNPOINT_MULT_STAGE_3 2.5
Hispania.

2020-02-19 12:25 UTC, Evankhell561 commented on code/datums/status_effects/neutral.dm
> +/datum/status_effect/heldup
Todos estos codigos nuevos a hispania

2020-02-19 12:25 UTC, Evankhell561 commented on code/modules/projectiles/gun.dm
> -
Regresa esto

2020-02-19 12:25 UTC, Evankhell561 commented on code/modules/projectiles/projectile/energy.dm
> +				electrode_effect(C)
Cual es el motivo del delay?

2020-02-19 18:10 UTC, SagaStars commented on code/datums/components/gunpoint.dm
> +#define GUNPOINT_MULT_STAGE_3 2.5
Valeee

2020-02-19 18:10 UTC, SagaStars commented on code/datums/status_effects/neutral.dm
> +/datum/status_effect/heldup
Vale, vale

2020-02-19 18:10 UTC, SagaStars commented on code/modules/projectiles/gun.dm
> -
Roger

2020-02-19 20:07 UTC, SagaStars commented on code/modules/projectiles/projectile/energy.dm
> +				electrode_effect(C)
> Los tasers ya no son armas de stun instantaneo no del todo, por lo cual abre cancha a mas intercambios de disparos y situaciones mas tensas (Reminder de que el taser no es el unico con insta-stun: flashbangs, flashs, peppersprays, la lista sigue) por favor, evitemos stuns instantáneos de larga distancia.

Si no te compra del todo puedo argumentarlo mas.

2020-02-20 02:28 UTC, Evankhell561 requested changes
los fix del blue y el saco de box en otro pr porfa.

2020-02-20 02:29 UTC, Evankhell561 commented on code/modules/projectiles/projectile/energy.dm
> +				electrode_effect(C)
lo siento pero no apruebo este cambio. en 1.5s te da tiempo de salir del rango de las torretas o de ir a un punto ciego.

2020-02-20 18:27 UTC, SagaStars commented on code/modules/projectiles/projectile/energy.dm
> +				electrode_effect(C)
Yikes... si es por esa razon entonces podria hacer que las turretas disparen electrodes instantaneos, te vale?

2020-02-20 18:27 UTC, SagaStars commented
> los fix del blue y el saco de box en otro pr porfa.

Valeeee

2020-02-21 13:27 UTC, SagaStars commented on code/modules/projectiles/projectile/energy.dm
> +				electrode_effect(C)
De hecho, Voy a hacer eso ahora mismo

2020-02-24 07:15 UTC, Evankhell561 commented
@SagaStars la idea era que hicieras otro pr con los fix para margearlos más rapidamente.

2020-02-24 13:52 UTC, SagaStars commented
> @SagaStars la idea era que hicieras otro pr con los fix para margearlos más rapidamente.

Haha lo se pero la mea paja. En un rato hago el PR

2020-03-07 03:58 UTC, Evankhell561 requested changes

2020-03-07 03:58 UTC, Evankhell561 commented on code/game/atoms_movable.dm
> +	SEND_SIGNAL(src, COMSIG_LIVING_START_PULL, AM, state, force)
y esto?

2020-03-07 03:58 UTC, Evankhell561 commented on code/modules/mob/living/living.dm
> +		playsound(src, 'sound/weapons/targeton.ogg', 85, 1, -1)
quejesto?

2020-03-07 03:58 UTC, Evankhell561 commented on code/modules/mob/living/living.dm
> +	SEND_SIGNAL(src, COMSIG_LIVING_START_PULL, AM, state, force)
why?

2020-03-07 03:58 UTC, Evankhell561 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	item_state = "revolver"
y este cambio?

2020-03-07 03:58 UTC, Evankhell561 commented on code/modules/projectiles/projectile/energy.dm
> +/obj/item/projectile/energy/electrode
hispania

2020-03-07 03:58 UTC, Evankhell561 commented on code/modules/projectiles/projectile/energy.dm
> +/obj/item/projectile/energy/electrode/on_hit(var/atom/target, var/blocked = 0)
hispania

2020-03-07 03:58 UTC, Evankhell561 commented on code/modules/projectiles/projectile/energy.dm
> +/obj/item/projectile/energy/electrode/proc/electrode_effect(mob/living/carbon/C)
hispania

2020-03-07 03:58 UTC, Evankhell561 commented on code/modules/projectiles/projectile/energy.dm
> +/obj/item/projectile/energy/electrode/proc/apply_stun(mob/living/carbon/C)
hispania

2020-03-07 03:58 UTC, Evankhell561 commented on code/modules/ruins/objects_and_mobs/gym.dm
> -	density = TRUE
why?

2020-03-07 04:01 UTC, Evankhell561 requested changes

2020-03-07 04:01 UTC, Evankhell561 commented on code/modules/projectiles/ammunition/energy.dm
> +/obj/item/ammo_casing/energy/turret_electrode
hispania

2020-03-07 04:38 UTC, SagaStars commented on code/game/atoms_movable.dm
> +	SEND_SIGNAL(src, COMSIG_LIVING_START_PULL, AM, state, force)
es lo que llama el proc, codigo chad de tg.

2020-03-07 04:43 UTC, SagaStars commented on code/modules/mob/living/living.dm
> +		playsound(src, 'sound/weapons/targeton.ogg', 85, 1, -1)
de aqui viene el sonido del *clicks* cuando te apuntan, supongo que quedo tan viejito el codigo que el´A << 'sound/weapons/targeton.ogg'´ dejo de funcionar.

2020-03-07 04:43 UTC, SagaStars commented on code/modules/mob/living/living.dm
> +	SEND_SIGNAL(src, COMSIG_LIVING_START_PULL, AM, state, force)
es lo que llama el proc, codigo chad de tg, again.

2020-03-07 05:00 UTC, SagaStars commented on code/modules/ruins/objects_and_mobs/gym.dm
> -	density = TRUE
why

2020-03-07 05:00 UTC, SagaStars commented on code/modules/projectiles/ammunition/energy.dm
> +/obj/item/ammo_casing/energy/turret_electrode
ASSSSSAAAAAAAAAAAAAAAAAAAAAA

2020-03-07 05:00 UTC, SagaStars commented on code/modules/projectiles/projectile/energy.dm
> +/obj/item/projectile/energy/electrode/proc/apply_stun(mob/living/carbon/C)
ASSSSSAAAAAAAAAAAAAAAAAAAAAA

2020-03-07 05:00 UTC, SagaStars commented on code/modules/projectiles/projectile/energy.dm
> +/obj/item/projectile/energy/electrode/proc/electrode_effect(mob/living/carbon/C)
ASSSSSAAAAAAAAAAAAAAAAAAAAAA

2020-03-07 05:00 UTC, SagaStars commented on code/modules/projectiles/projectile/energy.dm
> +/obj/item/projectile/energy/electrode/on_hit(var/atom/target, var/blocked = 0)
ASSSSSAAAAAAAAAAAAAAAAAAAAAA

2020-03-07 05:00 UTC, SagaStars commented on code/modules/projectiles/projectile/energy.dm
> +/obj/item/projectile/energy/electrode
ASSSSSAAAAAAAAAAAAAAAAAAAAAA

2020-03-07 05:01 UTC, SagaStars commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	item_state = "revolver"
la concha sumare-. crei que los habia quitado todos, importa si este se queda?

2020-03-07 14:40 UTC, Evankhell561 commented on code/modules/ruins/objects_and_mobs/gym.dm
> -	density = TRUE
por qué le quitas la decndidad a esto?

2020-03-09 21:12 UTC, SagaStars commented on code/modules/ruins/objects_and_mobs/gym.dm
> -	density = TRUE
mejor dicho, COMO. No queria hacer eso-

2020-03-09 21:56 UTC, SagaStars commented
Creo que ya, ire haciendo esos arreglitos rapidos que habia quitado

2020-04-07 17:30 UTC, SagaStars commented
Demasiados conflictos y para evitar problemas mejor espero a que se actualize paradise y vuelvo a hacer el PR

2020-04-07 17:30 UTC, closed without merging