Add LMG Armeria GAMMA
Helixis/Paradise pull request #409
Opened 2020-02-19 22:24 UTC by Spircen

## What Does This PR Do
Agrega una LMG a la armería gamma. A la par agrega nuestro Z2 para futuras PRs trabajar ahi.

## Why It's Good For The Game
Por el momento da una buena multitud de armas pero una LMG ofrece la capacidad de no tener necesidad constante de recargar un proyectil tan seguido como el resto y agrega la gran capacidad de fuego a cambio de eliminar parte del armamento abordo. Eliminando 1 pistola, 1 escopeta y 1 energy gun que una LMG hace bastante daño solo con una ráfaga. 

## Images of changes

                                Gamma Armeria
![image](https://user-images.githubusercontent.com/46639834/74882169-3a50cc80-5334-11ea-98c1-06a92a0b7c94.png)

## Changelog
:cl:
tweak: LMG a Armería Gamma
/:cl:

2020-02-19 22:26 UTC, Evankhell561 requested changes
La armeria se caracteriza por tener sus armas grandes en los closets para que sea el warden el que las entregue... es una mierda eso pero es asi. además te ahorras el tener que crear un uevo mapa para este cambio tan pequeño. Solo mete el arma en el closet.

2020-02-20 00:48 UTC, Spircen commented
La LMG tiene un bug al estar dentro de un clóset pero ya lo hago. Igualmente la entidad de clóset de armas existe por si sola, a nivel de code no existe una new() del objeto clóset es meterlas dentro del mapa si o si.

2020-02-20 02:23 UTC, Evankhell561 commented
> pero ya lo hago. Igualmente la entidad de clóset de armas existe por si sola, a nivel de si o si.

> La LMG tiene un bug al estar dentro de un clóset 

que tipo de bug?

>a nivel de code no existe una new() del objeto clóset es meterlas dentro del mapa 

estos closets siempre me parecieron raros. los objetos que tienen dentro estan en el mapa? :thonk:

2020-02-20 02:39 UTC, Spircen commented
Subo SS de todo lo que marca.

2020-02-20 02:40 UTC, Spircen commented
![image](https://user-images.githubusercontent.com/46639834/74895728-11423300-5358-11ea-8522-3cdc846ab57e.png)

Así es como existen las armas de la armería. El item sobre el locker.

2020-02-20 02:47 UTC, Spircen commented
![image](https://user-images.githubusercontent.com/46639834/74896094-f6bc8980-5358-11ea-9f1b-a5607ab7a83b.png)

![image](https://user-images.githubusercontent.com/46639834/74896098-fd4b0100-5358-11ea-99b3-9b4059d9b791.png)

Este es el bug del sprite al meter la LMG

2020-03-16 01:38 UTC, closed without merging