Wooden Sword (WIP)
Helixis/Paradise pull request #422
Opened 2020-02-22 19:03 UTC by Danaleja2005

## What Does This PR Do
Este PR añade una espada hecha con cinta adhesiva y madera, que quita un total de 7 de daño bruto y tiene un chance de bloquear ataques en un 40%, (Por alguna razón que yo no se,aveces stunea por unos 6 o 7 segundos cuando ataca)

## Images of changes
![image](https://user-images.githubusercontent.com/43283605/75097726-7da17a00-5584-11ea-91b4-dc8f22f79c44.png)

## Changelog
:cl:
add: Añade una nueva arma "espada de madera, hecha con madera y cinta adhesiva"
add: Añade la receta de la espada de madera al menu de crafting
/:cl:

2020-02-22 19:45 UTC, Nicaragua1 commented
"bloquear ataques en un 40%"

Really. Tremenda la espadita de juguete veremos a toda la crew usarla si es asi de fuerte

2020-02-22 19:47 UTC, Danaleja2005 commented
Realmente no se si el valor 40 en block chance sea un porcentaje, pero los otros devs me dijieron que pusiera esa cantidad

2020-02-22 19:52 UTC, SagaStars commented
Basicamente, el palo de monje del chaplain de descuento

2020-02-23 02:56 UTC, Danaleja2005 commented
por cierto @Evankhell561 realmente no tengo idea porque travis da error, en mi repo no sale ningun error

2020-02-23 07:02 UTC, Evankhell561 commented
> por cierto @Evankhell561 realmente no tengo idea porque travis da error, en mi repo no sale ningun error

porque compilaste con el visual estudio seguramente.

2020-02-23 16:19 UTC, Evankhell561 requested changes

2020-02-23 16:19 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +/obj/item/spear/woodensword
por qué necesitas que la espada tenga el codigo de una lanza?

2020-02-23 16:19 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	block_chance = 40
por qué un porcentaje de block tan alto? esto es basicamente un escudo.

2020-02-23 17:58 UTC, Danaleja2005 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +/obj/item/spear/woodensword
Lo puse ahi, para ver si se le quitaba el stun que tenia, pero no se le quito

2020-02-23 17:58 UTC, Danaleja2005 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	block_chance = 40
Me dijieron que pusiera ese porcentaje, solo me sugirieron y que le quitara force que antes tenia 10

2020-02-23 17:59 UTC, Danaleja2005 commented
y no compile con vc, es con dream maker y no sale error alguno @Evankhell561

2020-02-23 18:07 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	block_chance = 40
el porcentaje de esquivar con una espada estaria bien para un espadachin, no para un cualquiera con un palo amarrado con cinta y en especial un porcentaje tan alto como el de un escudo. luego revisaré las otras armas que se puedan craftear y veré que valores pueden ser más apropiados.

2020-02-23 18:08 UTC, Evankhell561 requested changes

2020-02-23 18:08 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +/obj/item/spear/woodensword
si el que sea una lanza no le afecta en nada, no lo hagas una lanza.

2020-02-23 18:52 UTC, Danaleja2005 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +/obj/item/spear/woodensword
entonces lo pongo en melee?

2020-02-23 18:54 UTC, Danaleja2005 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	block_chance = 40
![image](https://user-images.githubusercontent.com/43283605/75117954-67f78780-564c-11ea-9792-6fb71031a9cd.png)
este es el del rapier, creo que 15 es un buen porcentaje

2020-02-23 18:57 UTC, Evankhell561 requested changes

2020-02-23 18:57 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +///Melee Weapons of Hispania///
daniel, tu error es que este dm no tiene el check puesto. 
en la lista de cambios deberia aparecer el paradise.dme incluyendo este dm y no es asi.

2020-03-01 20:38 UTC, closed without merging