Fix Acceso a Maint CMO
Helixis/Paradise pull request #426
Opened 2020-02-24 02:37 UTC by Spircen

## What Does This PR Do
Da acceso a mantenimiento al CMO el cual por el momento no contaba con este.

## Why It's Good For The Game
Repara el acceso faltante al CMO, todo el departamento cuenta con acceso a maint menos el CMO. Este era un problema viejo que no se había reparado hace rato. 

## Images of changes

                                             Nibba CMO on door
![image](https://user-images.githubusercontent.com/46639834/75125716-1109a680-567c-11ea-8038-1caee73d46a7.png)

## Changelog
:cl:
tweak: Acceso a maint CMO
/:cl:

2020-02-24 02:55 UTC, SagaStars commented
Ehem ya que estamos hay un par de heads y jobs que no tienen accesos a maint podrias aprovechar para darles los accesos, habia un PR #292  que fue aceptado y todo pero la cagaron con el travis y no termino siendo aceptado 
![5FAC4A3F-4C74-4F34-A1A8-F22EADEC3164](https://user-images.githubusercontent.com/55407528/75126276-8e8ae200-568f-11ea-9391-31d14fbb30c8.jpeg)
kek

2020-02-24 04:16 UTC, Spircen commented
Jum, me imagino alomejor por que el Magistrado debería de contar con acceso a mantenimiento. Pero los cientificos y el RD no me parece que lo deban de tener. Que un CMO lo tenga es por que hay gente que unicamente juega CMO y repetidas veces no pueden rescatar personal por que no tienen acceso a mantenimiento. Que tus subordinados tengan acceso a maint pero tu no es algo que no tiene sentido. Igualmente voy a revisar la cadena de mando del magistrado para ver si deberían.

2020-02-24 06:55 UTC, Evankhell561 commented
>Repara el acceso faltante al CMO, todo el departamento de med cuenta con acceso a maint menos el CMO. Este era un problema viejo que no se había reparado hace rato.

viendo el code, me parece que el unico de med con acceso a maint es el paramedico. si es asi el cmo no tendria que tener acceso. Si todos sus subordinados lo tienen como dices entonces se aprueba esto.

2020-02-24 06:57 UTC, Evankhell561 commented
> Ehem ya que estamos hay un par de heads y jobs que no tienen accesos a maint podrias aprovechar para darles los accesos, habia un PR #292 que fue aceptado y todo pero la cagaron con el travis y no termino siendo aceptado
> ![5FAC4A3F-4C74-4F34-A1A8-F22EADEC3164](https://user-images.githubusercontent.com/55407528/75126276-8e8ae200-568f-11ea-9391-31d14fbb30c8.jpeg)
> kek

el pr #292  fue cancelado por el mismo autor. no fue ni aprobado ni rechazado.

2020-02-24 06:58 UTC, Evankhell561 commented
>Pero los cientificos y el RD no me parece que lo deban de tener. 

El RD tiene un subordinado con acceso a maint como el cmo, y ambos tienen algo que buscar en maint... no digo que el RD tenga que tener acceso digo que es equivalente una cosa con la otra.

2020-02-24 07:02 UTC, Evankhell561 commented
> Repara el acceso faltante al CMO, todo el departamento de med cuenta con acceso a maint menos el CMO. Este era un problema viejo que no se había reparado hace rato.

tengo que testear pero no creo que esto sea un error.

2020-02-24 07:50 UTC, Spircen commented
En la lista de minimal access aparece que debe de tener acceso a maint tunnels. A la par si das a view file te puedes percatar abajo esta el datum de medical doctor el cual marca tiene acceso a maint tunnels.

2020-02-24 14:16 UTC, Evankhell561 commented
> En la lista de minimal access aparece que debe de tener acceso a maint tunnels. A la par si das a view file te puedes percatar abajo esta el datum de medical doctor el cual marca tiene acceso a maint tunnels.

Bien, el cmo tiene el access_maint_tunnels dos veces en el minimal_acces. Borra uno

2020-02-24 14:17 UTC, Evankhell561 requested changes

2020-02-24 14:17 UTC, Evankhell561 commented on code/game/jobs/job/medical.dm
>  			access_keycard_auth, access_sec_doors, access_psychiatrist, access_maint_tunnels, access_paramedic, access_mineral_storeroom, access_maint_tunnels)
aca hay dos access_maint_tunnels. borra uno.

2020-02-25 03:21 UTC, Spircen commented on code/game/jobs/job/medical.dm
>  			access_keycard_auth, access_sec_doors, access_psychiatrist, access_maint_tunnels, access_paramedic, access_mineral_storeroom, access_maint_tunnels)
Vale, ya lo muevo.

2020-02-25 12:40 UTC, merged