Mas Readys = mas modos de juego
Helixis/Paradise pull request #427
Opened 2020-02-24 04:59 UTC by Nicaragua1

- Tiempo para comenzar la ronda de 240 -> 350

- Notificación con sonido para los olvidadizos que se ponen a hablar por discord y tienen la musica desactivada del juego..   50 segundos antes de que comience la ronda

- Pequeña traduccion

:cl:
add:  Reminder de Ready Up
/:cl:

2020-02-24 05:42 UTC, Spircen commented
Tengo mis dudas respecto a si es necesario añadir el sonido a un tiempo de duración como este. Los sonidos globales son reservados para votaciones o situaciones importantes, el hacerlo una constante para el inicio de turno en especial sabiendo que es un ruido fuerte puede incomodar a los jugadores. Recomendaría cambiarlo por un sonido mas ameno que el actual.

2020-02-24 08:40 UTC, Nicaragua1 commented
Si se te ocurre otro sonido es bienvenido

2020-02-24 18:08 UTC, Nicaragua1 commented
- Los que clickeen ready no recibiran reminders de poner ready ni seran molestados

- Agregados 2 sonidos
Uno que se escucha faltando 100 segundos para que empiece que dice "you better get ready"
Cuando falten 50 segundos un sonido un poquito mas ruidoso de cuenta regresiva.

- Testeado. Listo para mergear

2020-02-26 18:09 UTC, Evankhell561 requested changes

2020-02-26 18:09 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +	var/pregame_timestart = 350			// Time it takes for the server to start the game
Esto es en segugos? si es así, bajalo a 300.

2020-02-27 02:18 UTC, Nicaragua1 commented on code/controllers/configuration.dm
> +	var/pregame_timestart = 350			// Time it takes for the server to start the game
si es en segugos , ya lo bajo ami tambien me entro la duda si quizas era mucho

2020-03-23 17:52 UTC, Spircen commented on code/controllers/subsystem/ticker.dm
> +			spawn((config.pregame_timestart * 10) - 500)
Este sonido de cuenta regresiva debería de ser global. Si un jugador no dio ready a este momento y únicamente el lo escucha solamente lo pones incomodo. Pero si la gente lo escucha de forma global y ya dieron ready los emocionas y les das ese rush de querer comenzar a jugar ya y si andaban en otra ventana se vienen a la partida.

2020-03-23 18:01 UTC, Spircen commented on code/controllers/subsystem/ticker.dm
> +			spawn((config.pregame_timestart * 10) - 1000)
¿Y por que el uso de spawn en el mensaje de bienvenida en lugar de una condicional como en la linea 100 de este mismo archivo?

2020-03-23 18:26 UTC, Spircen commented
Agregando, fui a testear tus cambios y como tal funcionan. Pero el código tiene una estructura de If entre estados, tu agregas tus cambios en GAME_STATE_STARTUP cuando las acciones que suceden al esperar en el lobby están dentro de GAME_STATE_PREGAME tus cambios funcionan pero deberían de estar en PREGAME como en la linea 100 con el tip random que tira.

2020-03-24 23:17 UTC, Nicaragua1 commented on code/controllers/subsystem/ticker.dm
> +			spawn((config.pregame_timestart * 10) - 500)
No me parece que haya que molestar a los que ya dieron ready.. Sobre todo si estan escuchando musica u algo. Al principio capaz no moleste pero la gente se cansaria rapido

2020-03-24 23:20 UTC, Nicaragua1 commented on code/controllers/subsystem/ticker.dm
> +			spawn((config.pregame_timestart * 10) - 500)
Aun asi si varios quieren hacerlo global , pues no tengo problema

2020-03-24 23:25 UTC, Nicaragua1 commented on code/controllers/subsystem/ticker.dm
> +			spawn((config.pregame_timestart * 10) - 1000)
Buen punto

2020-04-17 05:43 UTC, Spircen commented
La vez pasada revise este PR y todo estaba en orden. Actualiza la branch y revisa que solo envíes los cambios marcados que estaban antes, recuerda configurar tu github desktop para que solo envié los cambios en LS. 

Aquí te dejo un enlace de ejemplo sobre como aplicarlo: https://www.ittechnical.solutions/2019/09/warning-lf-will-be-replaced-by-crlf-in.html?m=1

2020-10-19 02:25 UTC, closed without merging