Re- Balance de Eventos
Helixis/Paradise pull request #430
Opened 2020-02-24 07:21 UTC by Nicaragua1

Inspirado en un PR de Aurora Station https://github.com/Aurorastation/Aurora.3/pull/591

La chance de eventos que manejamos no es acorde a nuestra Pop actual. Por ejemplo nunca ha ocurrido el caso de que lleguemos a los 80 jugadores conectados. 
Por ese motivo se modificaron las cifras mas acordes a un medium-low pop y tambien se ajustaron los eventos mas interesantes para que salgan mas seguido y darle cosas para hacer a los departamentos mas poblados.

En general agrega mas variedad al pool y se notara mucho sobre todo en las rondas de extended.

:cl:
tweak: Modificadas chances de eventos aleatorios
/:cl:

2020-02-24 07:54 UTC, Spircen commented
¿No les puedes pedir prestado el excel o lo haces tu xD? En ese mismo archivo viene la formula de las probabilidades por evento y el como afecta el peso de un objeto a la formula. Es noche y me da paja hacerlo pero cambiar un valor de 100 a 50 o de 0 a 75 no se si se sienta mucho.

2020-02-24 07:57 UTC, Spircen commented
En especial en cosas como las Space Vine que veo que pasan de 250 a 50, no quiero ver una estación a la hora atascada de Space Vines.

2020-02-24 08:07 UTC, Nicaragua1 commented
La chance de space vines es menor. Ese es el numero base.
En general los eventos van a ocurrir mas seguido entonces mantener 250 las space vines seria muy caotico. Los cambios estan basados en el PR de aurora ya que es una pop mas acorde a la nuestra. No son numeros inventados por mi.

2020-02-27 01:27 UTC, Nicaragua1 commented
@Evankhell561  podrias echarle un vistazo a este PR ?  Creo que es de los mas urgentes para testear en extended que estan muy estancadas en eventos. Se estan volviendo muy monotonas las semanas de extended

2020-02-27 01:32 UTC, Evankhell561 requested changes

2020-02-27 01:32 UTC, Evankhell561 commented on code/modules/events/event_container.dm
> +		new /datum/event_meta(EVENT_LEVEL_MUNDANE, "Money Lotto",		/datum/event/money_lotto, 		10, 		list(ASSIGNMENT_ANY = 1), 1, 5,  15),
que es este evento y por qué lo estás activando?

2020-02-27 22:51 UTC, Evankhell561 commented
nica, estas solicitando una review caundo ya te di una.

2020-02-27 23:00 UTC, Tilk1 reviewed
> nica, estas solicitando una review caundo ya te di una.

Esque no manejo bien esto. Entonces que opinas del cambio

2020-02-27 23:00 UTC, Tilk1 commented on code/modules/events/event_container.dm
> +		new /datum/event_meta(EVENT_LEVEL_MUNDANE, "Money Lotto",		/datum/event/money_lotto, 		10, 		list(ASSIGNMENT_ANY = 1), 1, 5,  15),
El money lotto? Le sube la chance apenas un poco.  Es un evento que alguien random de la estacion gana muchisimo space cash. Ya estaba activado. La base 0 no significa que este desactivado. Los desactivados son con //

2020-02-28 03:17 UTC, Evankhell561 requested changes

2020-02-28 03:17 UTC, Evankhell561 commented on code/modules/events/event_container.dm
> +			if(0 to 5)
por qué modificas estos valores? de buenas a primeras me parece contraproducente.

2020-02-29 23:00 UTC, Nicaragua1 commented on code/modules/events/event_container.dm
> +			if(0 to 5)
Esta hecho de acuerdo a la POP del server.  En paradise se considera que la estacion esta "Llena" cuando tienen 80 jugadores o mas en el crew manifest.  Ese numero jamas lo alcanzamos nosotros y 30 es mas acorde a nuestra estacion llena

2020-03-01 11:50 UTC, Evankhell561 commented on code/modules/events/event_container.dm
> +			if(0 to 5)
Tengo mis dudas ayer teniamos 61.

2020-03-01 12:50 UTC, Nicaragua1 commented on code/modules/events/event_container.dm
> +			if(0 to 5)
Bien subire las cifras

2020-10-19 02:25 UTC, closed without merging