Tweak Sentarse en Stool
Helixis/Paradise pull request #435
Opened 2020-02-28 23:03 UTC by Spircen

## What Does This PR Do
Vuelve a los Stool, entidades donde uno puede tomar asiento al ser objeto tipo silla.

## Why It's Good For The Game
Los asientos actualmente no funcionan como sillas a pesar de ser sillas y muchas veces la gente se empuja entre ellas en la barra por no poder hacer buckle. 

## Images of changes
![image](https://user-images.githubusercontent.com/46639834/75593830-3582cb80-5a4c-11ea-919a-7e8acd36c59c.png)

## Changelog
:cl:
tweak: Stool can buckle
/:cl:

2020-02-28 23:04 UTC, Spircen commented
Sigue el problema actualmente y por el momento por mi lógica se que sirve, pero testear no se puede por el problema de BYOND y la incapacidad de poder interactuar con Items en la beta actual. A su vez intente correr el repo actual de paradise oficial en la beta y también da el error con ellos. Esperemos BYOND lo resuelva pronto.

2020-03-03 00:16 UTC, Evankhell561 requested changes

2020-03-03 00:16 UTC, Evankhell561 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	can_buckle = TRUE
Según yo podras revertir todos los cambios y solo comentar esta linea

2020-03-03 21:26 UTC, Spircen commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	can_buckle = TRUE
Si, ya fui a hacer los cambios correctos y funciona pero ahora tengo un problema con los sprites, se ven... poco realistas por así decirlo.

2020-03-04 04:47 UTC, merged