Wooden Sword (WIP)
Helixis/Paradise pull request #442
Opened 2020-03-01 23:53 UTC by Danaleja2005

## What Does This PR Do
Este PR añade una espada hecha con cinta adhesiva y madera, que quita un total de 5 de daño, 
y tiene un chance de 20 de bloquear ataques melee, se puede craftear en el menú de crafteo

## Images of changes
![image](https://user-images.githubusercontent.com/43283605/75097726-7da17a00-5584-11ea-91b4-dc8f22f79c44.png)

## Changelog
:cl:
add: Añade una nueva arma "espada de madera, hecha con madera y cinta adhesiva"
add: Añade la receta de la espada de madera al menu de crafting
/:cl:

2020-03-01 23:56 UTC, Evankhell561 requested changes

2020-03-01 23:56 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	force = 5
sube esto a ocho

2020-03-01 23:57 UTC, Evankhell561 requested changes

2020-03-01 23:57 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +        final_block_chance = 20
ponle final_block_chance += 20

2020-03-02 10:52 UTC, Danaleja2005 commented
@Evankhell561 Testado, bloquea los golpes a melee, y objetos arrojados

2020-03-02 11:04 UTC, Evankhell561 commented
Lo crafteaste también?

2020-03-02 11:14 UTC, Danaleja2005 commented
si

2020-03-02 11:16 UTC, merged