Add Custom items a loadout [WIP]
Helixis/Paradise pull request #444
Opened 2020-03-02 05:06 UTC by Spircen

## What Does This PR Do
Añade ropa, mochila y accesorios diversos al loadout sacada de custom items.

## Why It's Good For The Game
Esta ropa de otra forma no se puede aparecer mas que por adminspawn, esta es una parte. El objetivo que tengo actualmente es traer todo lo que hay disponible en custom items al juego de una forma. 

## Images of changes
                                              SS de toda la ropa a agregar en loadout
![image](https://user-images.githubusercontent.com/46639834/75646793-69a6e980-5c10-11ea-9948-44ee9dd52dac.png)

## Changelog
:cl:
add: Custom Items a loadout
/:cl:

2020-03-02 05:15 UTC, SpiritualShadow commented
Eso significa que puedes spawnear con una welding mask?

2020-03-02 05:16 UTC, Spircen commented
No, es un objeto que debes ocupar sobre una welding mask

2020-03-02 05:19 UTC, SpiritualShadow commented
Aaah cool

2020-03-02 11:02 UTC, Evankhell561 commented
No sé man. El load out parece sobre cargado ya. Y si haces una máquina como el Xtra?

2020-03-02 18:47 UTC, Spircen commented
Por el momento ampliar esa sección permite más personalización a los personajes, si voy a agregar una máquina y también otras mecánicas de crafteo por qué hay muchos más custom ítems que aún no agrego. Tu dale wachin que la gente quiere poner guapo a su personaje ándale uwu

Así ya luego agregamos lootboxes ò3ó

2020-03-02 18:48 UTC, Spircen commented
Aquí tome los ítems más normales y nada llamativos en cosas como sus colores, ya en otro PR de hoy voy a agregar más cosas y una nueva máquina

2020-03-03 00:14 UTC, Evankhell561 requested changes
Por qué algunos tienen coste y otro no?

2020-03-03 00:23 UTC, Spircen commented
El costo es una propiedad heredada de el tipo de objeto que es. Se agrega en vox por que al ser una nuevo objeto de categoría, este necesita un costo a pasar a los objetos hijos que genera. Por eso los jumpsuits y otras cosas no tienen, por que ese tipo de objeto ya existe y tiene un costo predeterminado

2020-03-07 03:32 UTC, Evankhell561 requested changes

2020-03-07 03:32 UTC, Evankhell561 commented on code/modules/customitems/item_defines.dm
> +	displays_id = 1
pon TRUE en vez de 1.

2020-03-07 03:42 UTC, Evankhell561 requested changes

2020-03-07 03:42 UTC, Evankhell561 commented on code/HISPANIA/modules/client/preference/loadout/loadout_uniform.dm
> +/datum/gear/uniform/sci
esto es un uniforme de ciencias?

2020-03-07 03:42 UTC, Evankhell561 commented on code/HISPANIA/modules/client/preference/loadout/loadout_suit.dm
> +/datum/gear/suit/old_jack23
otra ruta repetida?

2020-03-07 03:42 UTC, Evankhell561 commented on code/HISPANIA/modules/client/preference/loadout/loadout_suit.dm
> +/datum/gear/suit/fox_jacket
no es una ruta repetica?

2020-03-07 03:42 UTC, Evankhell561 commented on code/HISPANIA/modules/client/preference/loadout/loadout_uniform.dm
> +/datum/gear/uniform/nerd_turtle
soy yo o veo doble?

2020-03-07 03:42 UTC, Evankhell561 commented on code/HISPANIA/modules/client/preference/loadout/loadout_uniform.dm
> +/datum/gear/uniform/nerd_turtle_blue
de nuevo?

2020-03-07 16:42 UTC, Spircen commented on code/modules/customitems/item_defines.dm
> +	displays_id = 1
Cambiado a true

2020-03-07 16:46 UTC, Spircen commented on code/HISPANIA/modules/client/preference/loadout/loadout_suit.dm
> +/datum/gear/suit/old_jack23
Cambiado, es literalmente el mismo item de arriba.

2020-03-07 16:46 UTC, Spircen commented on code/HISPANIA/modules/client/preference/loadout/loadout_suit.dm
> +/datum/gear/suit/fox_jacket
Cambiado, este item si es distinto

2020-03-07 16:47 UTC, Spircen commented on code/HISPANIA/modules/client/preference/loadout/loadout_uniform.dm
> +/datum/gear/uniform/sci
No, es un uniforme genérico, modificado.

2020-03-07 16:47 UTC, Spircen commented on code/HISPANIA/modules/client/preference/loadout/loadout_uniform.dm
> +/datum/gear/uniform/nerd_turtle
Eliminado, si es el mismo uwu

2020-03-07 16:48 UTC, Spircen commented on code/HISPANIA/modules/client/preference/loadout/loadout_uniform.dm
> +/datum/gear/uniform/nerd_turtle_blue
Sip, modificado.

2020-03-07 16:48 UTC, Spircen commented on code/modules/customitems/item_defines.dm
> +	displays_id = 1
Modificado en todos a true

2020-03-07 17:02 UTC, Evankhell561 requested changes

2020-03-07 17:02 UTC, Evankhell561 commented on code/HISPANIA/modules/client/preference/loadout/loadout_hat.dm
> +/datum/gear/hat/green_beret
repetido?

2020-03-07 17:04 UTC, Spircen commented on code/HISPANIA/modules/client/preference/loadout/loadout_hat.dm
> +/datum/gear/hat/green_beret
Oh que chuchas uwu

2020-03-07 22:26 UTC, merged