Add Brigh Physician Back
Helixis/Paradise pull request #447
Opened 2020-03-03 20:22 UTC by Spircen

## What Does This PR Do
Reañade el Trabajo de Brig Physician

## Why It's Good For The Game
La comunidad esta creciendo actualmente y desean poder contar con este trabajo nuevamente. A su vez revisando el PR donde se realiza el cambio cuenta con modificaciones a Z2 y a mi parecer es mas sencillo hacer el PR a un Revert con discards. 

## Images of changes
                                                  Menú de Selección
![image](https://user-images.githubusercontent.com/46639834/75815665-6bc88f80-5d59-11ea-8675-8a97360e99e6.png)

                                                  Preview Personaje
![image](https://user-images.githubusercontent.com/46639834/75815680-72570700-5d59-11ea-948b-d7db1cc3073a.png)

                                                  Spawn Point Operativo
![image](https://user-images.githubusercontent.com/46639834/75815710-813db980-5d59-11ea-8d81-956d09914791.png)

## Changelog
:cl:
add: Brig Physician regresa a selección de trabajos
/:cl:

2020-03-03 20:34 UTC, Nicaragua1 commented
Agregado este job solo el warden y el hos deberia tener acceso a la mini medbay de brig. (Y obvio el brig physician)

2020-03-03 20:39 UTC, Spircen commented
No me parece buena idea, si bien su area de trabajo es medica su contacto usualmente es oficial de seguridad -> Prisionero -> Brig Physician. Si un prisionero llega a stunearlo dentro un oficial de seguridad solo no puede entrar a ayudarlo y tiene que esperar un warden o un HoS.

2020-03-04 00:51 UTC, Evankhell561 requested changes

2020-03-04 00:51 UTC, Evankhell561 commented on code/game/jobs/job/security.dm
> +	access = list(access_security, access_sec_doors, access_brig, access_court, access_medical, access_morgue, access_surgery, access_chemistry, access_maint_tunnels)
No creo que deba tener acceso a brig.

2020-03-04 00:54 UTC, Spircen commented on code/game/jobs/job/security.dm
> +	access = list(access_security, access_sec_doors, access_brig, access_court, access_medical, access_morgue, access_surgery, access_chemistry, access_maint_tunnels)
Pero si es un doctor luego los de perma se matan ellos solos. Es vital que pueda entrar a la zona de perma en especial por que su SOP estipula que el debe estar en las ejecuciones.

2020-03-04 00:59 UTC, Evankhell561 commented on code/game/jobs/job/security.dm
> +	access = list(access_security, access_sec_doors, access_brig, access_court, access_medical, access_morgue, access_surgery, access_chemistry, access_maint_tunnels)
Sorry lo confundí con otro acceso. Todo bien.

2020-03-04 00:59 UTC, Spircen commented on code/game/jobs/job/security.dm
> +	access = list(access_security, access_sec_doors, access_brig, access_court, access_medical, access_morgue, access_surgery, access_chemistry, access_maint_tunnels)
No te preocupes uwu

2020-03-04 04:44 UTC, merged