Un tipo de cuchillos nuevos... Saben que significa?
Helixis/Paradise pull request #448
Opened 2020-03-03 21:30 UTC by SagaStars

_Seudo-Port de bay, creditos para ellos de las sprites_
**SERA UN DUELO A MUERTE CON CUCHILLOS**
![image](https://user-images.githubusercontent.com/55407528/75817917-5f026680-5d6e-11ea-91c5-a9276e5c0482.png)

- Añade un nuevo tipo de cuchillo... Un cuchillo plegable, el cual vendra de dos maneras:
**Normales:** Vienen en 3 tipos que solo cambian la sprite: como una navaja suiza, uno rustico y otro como un butterfly. 12 de daño y se podran conseguir en el xtra y en el loadout. Pueden guardarse en el bolsillo.
**Combate:** Haran 20 de daño y solo se pueden obtener en la armeria gamma (Vienen 3). O como objeto de traidor (Valor de 2 TC, como la energy dager) se ve super gangster tho.
**_Puedes cambiarle el color con alt+click, solo funciona una vez_**
- Se le sube un `2` de daño al cuchillo del chef, ahora quita lo mismo que el folding knife. QUITABA 10 **WHEEZE**.
## Why It's Good For The Game
Tanto como por rol y combate enriqueze la experiencia de una ligera manera, deja mejor me explico en vez de hablar paja. El hecho de portar un cuchillo plegable le sube como un +5 de intimidación a tu pj, te deja expresar mucho mejor la agresividad o paranoia que traes y es una mucho mejor alternativa para amenzar (en terminos de rol) que usando un stun prod y un par de zipties. Los robos de ID para agarrar dinero seran mas roleables, ejem PELEA A MUERTE CON CUCHILLOS. Y cosas asi, ya podras rolear bien al **GUACHAFAS**
El subidon de daño al cuchillo del chef era para que quedara igual que el folding knife, la razon de por la cual hace 12 de daño el folding knife? Meramente por que lo hace ligeramente mas efectivo contra mobs, ya que su hp aveces terminan en 5 en vez de 0 por lo cual se le facilitan un poco. _COUGHS, COUGHS EL CUCHILLO DEL MINERO HACE 15 DE DAÑO_

## Images of changes
![image](https://user-images.githubusercontent.com/55407528/75819860-ba822380-5d71-11ea-9e43-38f013b31538.png)
![image](https://user-images.githubusercontent.com/55407528/75821390-8c521300-5d74-11ea-8069-fc483304490c.png)

## Changelog
:cl:
add: Cuchillos plegables hell yeah, agarratelo en un xtra o en loadout
tweak: El cuchillo del chef ahora hace 12 de daño
/:cl:

2020-03-03 21:34 UTC, SagaStars commented
Como sea, planeo hacer que funcione para cirujias ghetto pero por el bien de evitar conflictos esperare  por el rework de cirujia de paradise.

2020-03-05 22:27 UTC, SagaStars commented
Ahi ta

2020-03-06 21:17 UTC, Evankhell561 requested changes

2020-03-06 21:17 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/folding.dm
> +	var/backstab_bonus = 4
donde no veo que esta variable haga nada.

2020-03-06 21:17 UTC, Evankhell561 commented on code/game/objects/items/weapons/kitchen.dm
> +	throwforce = 12
que tiene que ver esto con tu pr?

2020-03-06 21:17 UTC, Evankhell561 commented on code/modules/clothing/spacesuits/miscellaneous.dm
> -
devuelve esto

2020-03-06 21:17 UTC, Evankhell561 commented on code/modules/clothing/suits/jobs.dm
> -
devuelve esta linea

2020-03-06 21:17 UTC, Evankhell561 commented on code/modules/clothing/suits/jobs.dm
> -
y esta

2020-03-06 21:22 UTC, SagaStars commented on code/HISPANIA/game/objects/items/folding.dm
> +	var/backstab_bonus = 4
My bad, planeaba añadir una mecanica para backstabbear pero me heche para atras luego

2020-03-06 21:24 UTC, SagaStars commented on code/game/objects/items/weapons/kitchen.dm
> +	throwforce = 12
Para nivelarlo con los cuchillos que acabo de poner

2020-03-06 21:25 UTC, SagaStars commented on code/modules/clothing/spacesuits/miscellaneous.dm
> -
Oookaaay

2020-03-06 21:25 UTC, SagaStars commented on code/modules/clothing/suits/jobs.dm
> -
OOOKAAAY

2020-03-06 21:25 UTC, SagaStars commented on code/modules/clothing/suits/jobs.dm
> -
AAAAAAAAAAAAAAAA

2020-03-06 21:27 UTC, Evankhell561 commented on code/game/objects/items/weapons/kitchen.dm
> +	throwforce = 12
Si eso quieres hacer entonces bajale el daño a tus nuevos chuchillos, no le subas el daño a algo viejo.

2020-03-06 21:30 UTC, Evankhell561 requested changes

2020-03-06 21:30 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/folding.dm
> +	origin_tech = "materials=3;combat=4"
está bien los materiales pero darle combate 4 a esto es demasiado. las armas lasers tienen combate 4. No deberia un chichillo tener la misma tecnologia de combate de un arma laser.

2020-03-06 21:36 UTC, SagaStars commented on code/game/objects/items/weapons/kitchen.dm
> +	throwforce = 12
Es que ya estaba suavecito de daño desde antes solo piensa en que una espada normal como las del chaplain hacen 15 de daño, al fin al cabo +2 daño es una chucha, solo ayuda para con mobs que terminan en cifras como 48 cosas asi. _(no se si lo dije muchas veces pero, EL CUCHILLO DEL MINERO HACE 15 REEEEE :panic:)_

2020-03-06 21:40 UTC, SagaStars commented on code/HISPANIA/game/objects/items/folding.dm
> +	origin_tech = "materials=3;combat=4"
Well, yo no decidi esto. Son los niveles de tecnologia de los cuchillos de combate que vienen en la shuttle del codigo gamma.

2020-03-06 22:36 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/folding.dm
> +	origin_tech = "materials=3;combat=4"
entiendo. bien.

2020-03-07 03:46 UTC, SagaStars commented on code/game/objects/items/weapons/kitchen.dm
> +	throwforce = 12
![image0-6](https://user-images.githubusercontent.com/55407528/76136138-a144d580-6004-11ea-86ab-f7c7cad8baf0.png)

2020-03-07 22:59 UTC, Evankhell561 commented on code/game/objects/items/weapons/kitchen.dm
> +	throwforce = 12
Así hay más variedad

2020-03-08 01:19 UTC, SagaStars commented on code/game/objects/items/weapons/kitchen.dm
> +	throwforce = 12
Que?

2020-03-08 01:36 UTC, SagaStars commented on code/game/objects/items/weapons/kitchen.dm
> +	throwforce = 12
POOOR FAVOR EVAN, SON 2 PUNTITOS AAAAAAAAAAAA

2020-03-08 02:59 UTC, Evankhell561 requested changes

2020-03-08 02:59 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/folding.dm
> +/proc/overlay_image(icon,icon_state,color,flags)
Define esteproc a nivel de tus cuchillos. No lo hagas global.

2020-03-08 02:59 UTC, Evankhell561 commented on code/modules/clothing/suits/jobs.dm
> +
Regresa esta linea

2020-03-08 03:42 UTC, Spircen commented on code/modules/clothing/suits/jobs.dm
> +
¡Revisa el PR de la chamaca de nothing! Va a llorar uwu

2020-03-08 15:12 UTC, SagaStars commented on code/HISPANIA/game/objects/items/folding.dm
> +/proc/overlay_image(icon,icon_state,color,flags)
Understandable, aunque podria ser util globalmente y lo pongo en la carpeta de procs... hm, nah

2020-03-08 15:13 UTC, SagaStars commented on code/HISPANIA/game/objects/items/folding.dm
> +/proc/overlay_image(icon,icon_state,color,flags)
Ya lo hago exclusivo del cuchillo

2020-03-08 15:14 UTC, SagaStars commented on code/modules/clothing/suits/jobs.dm
> +
Evan, estas lineas estan malditas pero lo volvere a intentar

2020-03-14 00:01 UTC, SagaStars commented
Jefecito, va a venir a ver?

2020-03-14 17:07 UTC, SagaStars commented
Respecto a las preguntas que me hicistes:
# - Que peso tienen? Su peso deberia reducirse cuando está enfundado y aumentar cuando no.
Son tiny, por lo cual caben en bolsillo. Y correcto cuando se abre aumenta su tamaño a normal, y cuando se cierra se encoje.
![image](https://user-images.githubusercontent.com/55407528/76686805-9dace200-65f4-11ea-95ab-89ce26351196.png)

# - Que se diferencian estos cuchillos de combate nuevos de los cuchillos de combate?
Ademas de que se puedan plegar... pues no mucho, pero como habian tan pocos cuchillos en la armeria gamma (Solo 3) y teniamos esta bella sprite, pues aproveche.

2020-03-14 17:24 UTC, SagaStars commented
> Ademas de que se puedan plegar... pues no mucho, pero como habian tan pocos cuchillos en la armeria gamma (Solo 3) y teniamos esta bella sprite, pues aproveche.

Se me olvido decirlo, puse 3 mas.

2020-03-21 02:39 UTC, Evankhell561 commented on _maps/map_files/cyberiad/z2.dmm
>  /obj/item/kitchen/knife/combat,
retira los cambios de cyberiad/z2, no usamos este mapa.

2020-03-21 02:41 UTC, Evankhell561 requested changes

2020-03-21 02:41 UTC, Evankhell561 commented on _maps/map_files/cyberiad/z2.dmm
> +/obj/item/kitchen/knife/folding/combat/tacticool,
no usamos el z2 de cyberiad sino el de hispania, estos cambios no son necesarios. y preferiria que no loas hicieras.

2020-03-21 03:02 UTC, SagaStars commented on _maps/map_files/cyberiad/z2.dmm
> +/obj/item/kitchen/knife/folding/combat/tacticool,
L i s t o

2020-03-22 03:52 UTC, Evankhell561 commented
cuando los cuchillos de combate tuyos están cerrados tienen el daño por lanzamiento en 20 y cuando están abiertos tienen el daño por lanzamiento en 15

2020-03-22 03:55 UTC, Evankhell561 requested changes
estos dos cuchillos se supone hacen el mismo daño sin embargo no lo pareciera. uno es notablemente más grande que el otro y el otro a penas se ve. 
![image](https://user-images.githubusercontent.com/49106866/77241896-49df6180-6bcf-11ea-8f39-84d181b98976.png)
![image](https://user-images.githubusercontent.com/49106866/77241914-8612c200-6bcf-11ea-8885-3a7696963449.png)

2020-03-22 15:35 UTC, Evankhell561 requested changes

2020-03-22 15:35 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/folding.dm
> +		sharp = 1
TRUE

2020-03-22 15:35 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/folding.dm
> +/obj/item/kitchen/knife/folding/combat //master obj
Usas este item en algún lado? Donde lo encuentro?
Si lo unico que hace es servir de objeto padre admin spawn olvídalo. Mete una de sus variantes funcionales acá.

2020-03-22 21:04 UTC, Evankhell561 requested changes
pon el true, arregla el changelogy creo que ya quedo

2020-03-25 00:13 UTC, Evankhell561 commented
El changelog

2020-03-25 00:14 UTC, Evankhell561 requested changes
El changelog.

2020-03-25 02:39 UTC, Evankhell561 commented
Margearia esto ahora pero no he testeado el tema de los colores. Y no sé si al dar altclick aparezca un tipo de menú dandote a elegir entre blanco y #fadfca por ejemplo. Si pasas ss de eso ayudaría.

2020-03-26 20:22 UTC, SagaStars commented
> Margearia esto ahora pero no he testeado el tema de los colores. Y no sé si al dar altclick aparezca un tipo de menú dandote a elegir entre blanco y #fadfca por ejemplo. Si pasas ss de eso ayudaría.

![image](https://user-images.githubusercontent.com/55407528/77692790-a8b12c00-6f7d-11ea-89fd-5b4fae4a73c8.png)

2020-03-27 03:45 UTC, merged