Porteo algunas recetas de otros codes Parte 1/?
Helixis/Paradise pull request #455
Opened 2020-03-06 12:24 UTC by N0thy

## What Does This PR Do
Añade varías recetas (porteadas) de TG

## _Recetas añadidas:_

###  **Pancake.** (Gracias a @Evankhell561 y a @Ume-D <3)
![pancake_1](https://user-images.githubusercontent.com/53350410/73140450-5a64d700-4079-11ea-8771-36a9bb212a9a.png)![pancake_2](https://user-images.githubusercontent.com/53350410/73140451-5a64d700-4079-11ea-839c-3a93fcec1736.png)![pancake_3](https://user-images.githubusercontent.com/53350410/73140452-5a64d700-4079-11ea-97e9-1415dff6413a.png)

**cómo cocinarlo:**
Añade un flatdough, 5 de azúcar y 1 de sal al Oven.

###  **Tostada.**
  ![toast](https://user-images.githubusercontent.com/53350410/73609139-043cea00-45cb-11ea-9475-36f1cd955f62.png)

**cómo cocinarlo:**
Añade un BreadSlice al Grill

###  **Tostada con mantequilla.**
![](https://tgstation13.org/wiki//images/4/40/Butteredtoast.png)

**cómo cocinarlo:**
Añade una tostada y 5 unidades de mantequilla al Grill.

###  **Mayonesa.**
![Mayonnaise](https://user-images.githubusercontent.com/53350410/73609198-9e049700-45cb-11ea-8499-a2100f910a39.png)

**cómo cocinarlo:**
Añade 30 unidades de

2020-03-08 12:27 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/food/condiments.dm
> +	name = "Mayonnaise"
Mayúsculas

2020-03-09 20:30 UTC, Ume-D commented on code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
> +	desc = "Is a slice of bread but toasted."
Lo correcto sería ¨It´s a slice...¨, no ¨IS a slice...¨

2020-03-11 00:51 UTC, Ume-D commented
Te faltó agregar el reagent mayonesa, de otro modo al cocinar mayonesa sale el recipiente vacio

2020-04-06 00:18 UTC, N0thy commented
I want to cry.
I'm gonna to cry.

:cry:

2020-04-10 22:58 UTC, Evankhell561 requested changes

2020-04-10 22:58 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/recipes/recipes_mixer.dm
> +	result= /obj/item/reagent_containers/food/condiment/mayonnaise
añade un espacio entre el result y el igual result =

2020-04-10 22:58 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/recipes/recipes_mixer.dm
>  	result= /obj/item/reagent_containers/food/snacks/butter
añade un espacio acá también result =

2020-04-11 17:41 UTC, merged