Garronte el búho
Helixis/Paradise pull request #460
Opened 2020-03-08 23:08 UTC by Jinouga19

## What Does This PR Do
 Añade un nuevo buhó en la oficina del chaplain, con los ojos muy grandes con los cuales cuidara la iglesia cuando no estes.
Añade una cama para la nueva mascota.

## Why It's Good For The Game
 Me parece que el trabajo de chaplain es un poco solitario y al tener un búho tienes mas compañía y puedes rolear mas.

## Images of changes
 Garronte en la oficina del chaplain: 

![Buho6](https://user-images.githubusercontent.com/61878952/76172776-717b0680-6199-11ea-985b-5f6cb5b29018.PNG)

Garronte de frente: 

![Buho1](https://user-images.githubusercontent.com/61878952/76172791-92dbf280-6199-11ea-802e-54062cf45bc6.PNG)

Garronte de espaldas: 

![Buho2](https://user-images.githubusercontent.com/61878952/76172799-a0917800-6199-11ea-8da0-c2ec70fce930.PNG)

Garronte de los lados: 

![Buho3](https://user-images.githubusercontent.com/61878952/76172803-aedf9400-6199-11ea-8440-4eae08d303ef.PNG) 

![Buho4](https://user-images.githubusercontent.com/61878952/76172807-b141ee00-6199-11ea-9521-4a41f167a03d.PNG)

Garronte muerto: 

![Buho5](https://user-images.githubusercontent.com/61878952/76172833-dd5d6f00-6199-11ea-8984-73608929f605.PNG)

## Changelog
:cl:
add: Añade un búho como la mascota del chaplain.
add: Añade una cama para la nueva mascota.
/:cl:

2020-03-08 23:10 UTC, Spircen commented on _maps/arena_template.dmm.backup
> +"a" = (/turf/unsimulated/wall,/area/space)
Este no hay que enviarlo uwu

2020-03-08 23:10 UTC, Spircen commented on _maps/arena_template.dmm.backup
> +"a" = (/turf/unsimulated/wall,/area/space)
Tampoco envíes el de _maps/map_backups/MinaGate.dmm.backup que no me deja comentar.

2020-03-08 23:12 UTC, Silverexperience commented on code/HISPANIA/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	desc = "A comfy-looking duck bed. You can even strap your pet in, in case the gravity turns off."
Dice que es una cama comoda de pato. ¿No deberia ser de búho?

2020-03-08 23:13 UTC, Jinouga19 commented on _maps/arena_template.dmm.backup
> +"a" = (/turf/unsimulated/wall,/area/space)
Vale, lo quito entonces no?

2020-03-08 23:13 UTC, Jinouga19 commented on code/HISPANIA/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	desc = "A comfy-looking duck bed. You can even strap your pet in, in case the gravity turns off."
Habia cogido la descripcion del de la cama de Duck. Creia que lo habia cambiado, gracias por avisar

2020-03-08 23:14 UTC, Silverexperience commented on code/HISPANIA/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	desc = "A comfy-looking duck bed. You can even strap your pet in, in case the gravity turns off."
Tambien en los emotes pone suspirar, no se si lo quieres asi o es por coger el mob de duck

2020-03-08 23:15 UTC, Spircen commented on _maps/arena_template.dmm.backup
> +"a" = (/turf/unsimulated/wall,/area/space)
Sip, borra los dos archivos del PR. A la par que ahorita vemos como hacemos lo de que map mergue no te funciona.

2020-03-08 23:18 UTC, Jinouga19 commented on code/HISPANIA/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	desc = "A comfy-looking duck bed. You can even strap your pet in, in case the gravity turns off."
No, ese lo quería así. Me pareció gracioso

2020-03-08 23:21 UTC, Jinouga19 commented
¿Sabéis como se puede hacer para que el búho sea controlado por fantasmas.? Como runtime, Ian, etc...

2020-03-08 23:26 UTC, Spircen commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	speak_emote = list("sighs")
Este mas el emote_hear y el emote_see hay que cambiarlos a un ruido especifico que hagan los buhos. No se que ruido hacen los buhos eso si.

2020-03-08 23:43 UTC, Jinouga19 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	speak_emote = list("sighs")
Mm, luego miro

2020-03-08 23:44 UTC, Silverexperience commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	speak_emote = list("sighs")
Los búhos creo que hacen hoot.

2020-03-08 23:56 UTC, Spircen commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	speak_emote = list("sighs")
HOOTERS

2020-03-09 01:22 UTC, Spircen commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	speak = list("Hoot.","Hoot?","Hoot!.","Cough"
Te falto cerrar esta lista.

2020-03-09 01:23 UTC, Spircen commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	speak = list("Hoot.","Hoot?","Hoot!.","Cough"
Y solamente con el hoot es suficiente, no lo entenderá la gente. Esta parte esta de mas.

2020-03-09 01:38 UTC, Evankhell561 requested changes

2020-03-09 01:38 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	speak = list("Hoot.","Hoot?","Hoot!.","Cough")
no pongas un punto luego de !
y pon el punto en la ultima "Cough."

2020-03-09 02:47 UTC, Jinouga19 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	speak = list("Hoot.","Hoot?","Hoot!.","Cough")
gracias, ya lo he cambiado

2020-03-09 12:19 UTC, Jinouga19 commented
Porque me la han cerrado? No les ha gustado?

2020-03-09 20:26 UTC, Jinouga19 commented
No voy a cambiar nada mas, ya estaría terminado con todos los cambios hechos.

2020-03-10 13:17 UTC, Jinouga19 commented
Porque dice que hay conflictos en icons/hispania/mob/animals.dmi?

2020-03-12 03:18 UTC, DanaDririon commented
Porque hubo otro PR que hizo cambios en ese archivo, entonces tu PR no tiene esos cambios, provocando conflictos

2020-03-13 02:00 UTC, Jinouga19 commented
Entonces que hago, deberia cambiarlo?

2020-03-17 20:01 UTC, Jinouga19 commented
Cierro el PR y lo abro en uno nuevo ya que he tenido problemas al sincronizar el master.... ( no lo tenia bien sincronizado y no se me updateaba) siento las molestias.

2020-03-17 20:01 UTC, closed without merging