Add Binoculares M/S/B
Helixis/Paradise pull request #483
Opened 2020-03-17 06:12 UTC by Spircen

## What Does This PR Do
Agrega binoculares como posible objeto a comprar en la maquina de recompensas para los mineros, añade dos binoculares para el departamento de seguridad en su SecTech y añade el diseño de Binoculares Bluespace para la sección de ciencias. 

## Why It's Good For The Game
Actualmente hay pocas formas de acceder a un aumento de visión que no consistan en un arma, esto hace que los jugadores tengan la posibilidad de evitar peligros y medir riesgos antes de entrar en algún área, a los seguratas la posibilidad de revisar departamentos sin tener que ir hasta el fondo de uno y a los científicos les da una nueva herramienta que pueden ocupar para sus experimentos o en caso de que se rompan cámaras por toxinas. 

Al no ser tecnologías muy avanzadas no llevan carga de valores tecnológicos. 

## Images of changes

                                       Binoculares de Seguridad
![image](https://user-images.githubusercontent.com/46639834/76826815-02c62a80-67e3-11ea-9a10-6c3fd0100ba6.png)

                                      Modelos de Binoculares
![image](https://user-images.githubusercontent.com/46639834/76826746-e2966b80-67e2-11ea-9d88-9ed46b68ef37.png)

                                         Equipamiento de mineria
![image](https://user-images.githubusercontent.com/46639834/76826772-ede99700-67e2-11ea-86f0-86ca179b16f1.png)

                                                   SecTech
![image](https://user-images.githubusercontent.com/46639834/76827033-7ec07280-67e3-11ea-9fae-f2bb778f6cb1.png)

                                              Prolathe Design
![image](https://user-images.githubusercontent.com/46639834/76827213-f2fb1600-67e3-11ea-8a95-25eda2878fb6.png)

## Changelog
:cl:
add: Binoculares a SecTech, Mining y Bluespace Research
/:cl:

2020-03-17 06:41 UTC, SagaStars commented
Esto es... Bastante poggers, buuen post lince +5

2020-03-18 18:01 UTC, Evankhell561 requested changes

2020-03-18 18:01 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +	throwforce = 5.0
No es necesario los decimales

2020-03-18 23:05 UTC, Evankhell561 requested changes

2020-03-18 23:05 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +	if(zoomed == FALSE)
puedes hacer acá `if(!zoomed)`

2020-03-18 23:24 UTC, Spircen commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +	if(zoomed == FALSE)
Jum, me puse a buscar algo que explicara por que es mejor un !x a un x == FALSE y no encontré mucho. Solamente un articulo, igual voy a hacer el cambio en la condicional. 

https://softwareengineering.stackexchange.com/questions/136908/why-use-boolean-variable-over-boolean-variable-false

2020-03-19 01:56 UTC, Spircen commented
Test

2020-03-19 01:56 UTC, Spircen commented
Its alive

2020-03-21 01:46 UTC, Evankhell561 requested changes

2020-03-21 01:46 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +	zoom(user,FALSE)
Agrega ..() al final del proc

2020-03-21 01:46 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +/obj/item/device/binoculars/bluespace
Esto deberia tener origen tecnológico.

2020-03-21 02:31 UTC, Spircen commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +	zoom(user,FALSE)
Agregado uwu

2020-03-21 02:32 UTC, Spircen commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +/obj/item/device/binoculars/bluespace
Vale, el resto las dejare como dummys en ese aspecto, pero si les agrego sus materiales para que el auto se las coma.

2020-03-21 02:33 UTC, Spircen commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +	materials = list(MAT_METAL=750, MAT_GLASS=300, MAT_SILVER=50, MAT_TITANIUM=25)
Reforzados con silver y titanio para la dura superficie de lavaland. Te juro que no fue un mistake que se me paso.

2020-03-21 02:38 UTC, Spircen commented
Test de niveles para RnD y de materiales incluidos.
![image](https://user-images.githubusercontent.com/46639834/77217769-a452c200-6aea-11ea-903e-7a4a8a4af1af.png)

2020-03-21 02:53 UTC, Evankhell561 commented
Arreglaste lo del zoon al morir?

2020-03-21 02:55 UTC, Spircen commented
Las condiciones para que eso suceden son pocas, osea tiene que ser algo que al estar de pie te haga insta ghost. Solo ghosteando y con un delete de admin te causaría eso. El problema incluso sucede con los rifles de francotirador.

2020-03-21 02:56 UTC, Evankhell561 commented
> Las condiciones para que eso suceden son pocas, osea tiene que ser algo que al estar de pie te haga insta ghost. Solo ghosteando y con un delete de admin te causaría eso. El problema incluso sucede con los rifles de francotirador.

entiendo, bien entonces.

2020-03-22 15:49 UTC, Evankhell561 requested changes

2020-03-22 15:49 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +/obj/item/device/binoculars/attack_self(mob/user)
Añade acá una descripción de lo que el personaje hace al hacer el attack_self "llevas los binoculares a tus ojos"
"Retiras los binoculares" algo así.

2020-03-26 16:40 UTC, Spircen commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +/obj/item/device/binoculars/attack_self(mob/user)
Listo

![image](https://user-images.githubusercontent.com/46639834/77672208-39701380-6f4e-11ea-86d6-5dfed282ca75.png)

2020-03-26 16:44 UTC, Spircen commented on code/HISPANIA/game/objects/items/divices/binoculars.dm
> +/obj/item/device/binoculars/attack_self(mob/user)
Ahora si, listo uwu

2020-03-27 16:39 UTC, Evankhell561 requested changes
Son 4 binoculares arregla el changelog y listo.

2020-03-27 18:19 UTC, Spircen commented
Ya quedo arreglado, anexe el autolathe a la lista de lugares donde se agrega.

2020-03-27 18:23 UTC, merged