Add SurgicalCart
Helixis/Paradise pull request #486
Opened 2020-03-17 22:03 UTC by Spircen

## What Does This PR Do
Añade las mesas de cirugía, estas pueden guardar las herramientas básicas de un cirujano, es un objeto que se puede mover alrededor y puede ser fijado al suelo con una wrench. A su par hace el cambio por ellos en el mapa.

## Why It's Good For The Game
Las mesas de cirugía si bien existen como tal, no permite un correcto orden para el uso de cada uno de las herramientas, esto hace que las herramientas puedan ser tomadas desde un menu que genera una ventana y nos ayuda a un mejor orden y evitamos guardar herramientas de cirugía en una mochila. 

YA solo me faltan los sprites de Dana

## Images of changes

                                             Carrito de Cirujano 
![image](https://user-images.githubusercontent.com/46639834/76905976-a7d71680-6868-11ea-9b63-0a486783f06a.png)

                                    Mensajes en chat al tomar o dejar algo. 
![image](https://user-images.githubusercontent.com/46639834/76906036-c1785e00-6868-11ea-82e0-1bd4f313527d.png)

## Changelog
:cl:
add: SurgicalCart
/:cl:

2020-03-18 03:05 UTC, Spircen commented
Pa'pruebas

2020-03-18 03:06 UTC, Spircen commented
Pa'pruebas otra vez uwu

2020-03-18 04:10 UTC, SagaStars commented
MESA DE CIRUJIA EN LA QUE SE PONEN INSTRUMENTOS DE CIRUJIA? DUDE QUEEE AHSJKHASL COMO ASHKASHJ QUEEE

2020-03-18 04:17 UTC, Spircen commented
Si dude, esas mesas tan bobas y no hacen nada, estas si te agarran tus herramientas y no andas con una mochila en mano al operar.

2020-03-18 04:22 UTC, SagaStars commented
**Ahora puedo verme mas profesional cuando le este estripando el higado al payaso, poggers!**. Pero ya en serio, estaria genial que pongas lo de las `overlays` tipo engicart que aparescan las herramientas en la mesita o algo, se que da terrible paja pero va a quedar cul.

2020-03-18 04:23 UTC, Spircen commented
Si, por eso ahi dice que faltan los sprites de danaleja xd

2020-03-18 04:24 UTC, SagaStars commented
> Si, por eso ahi dice que faltan los sprites de danaleja xd

Uy perdon que toi ciego asjlk

2020-03-22 21:01 UTC, Evankhell561 requested changes

2020-03-22 21:01 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	density = 1
TRUE

2020-03-22 21:01 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	anchored = 0
FALSE

2020-03-22 23:41 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	density = 1
Va que va.

2020-03-22 23:42 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	anchored = 0
Va que va uwu

2020-03-25 00:09 UTC, Evankhell561 requested changes
Solo te recuerdo que acordamos que crearias un objeto hijo que ya venga con todas las herramientas listas para usar y lo pondrias en el mapa. Junto con mantener la  mesa de Paradise en el menú de craft.

2020-03-25 00:10 UTC, Evankhell561 requested changes

2020-03-25 00:10 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	can_buckle = 1
TRUE

2020-03-25 00:11 UTC, Spircen commented
Si me acuerdo de eso, pero no entiendo por que no funciona cuando intento asignar valores a cada uno de los mytool que tengo dentro del carrito. Intente el obj/carrito/full/New() y luego de eso daba un mytool=tool o tambien un new tool

2020-03-25 00:50 UTC, Evankhell561 requested changes

2020-03-25 00:50 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	if(!I.is_robot_module())
Y esta comprobación toda fea?

2020-03-25 00:51 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	if(!I.is_robot_module())
Es para que los borgs no puedan poner sus brazos en el carrito.

2020-03-25 01:12 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	if(!I.is_robot_module())
Oh, los borgs médicos. Bien.

2020-03-25 01:46 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	if(!I.is_robot_module())
Va que va, ahi va el ultimo commit.

2020-03-25 02:14 UTC, Evankhell561 requested changes

2020-03-25 02:14 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +		else if(istype(I, /obj/item/wrench))
Pasa esto a wrench_act y terminas.

2020-03-25 15:46 UTC, Evankhell561 requested changes

2020-03-25 15:46 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +		anchored = 1
TRUE

2020-03-25 15:46 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +			anchored = 0
FALSE

2020-03-25 15:46 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +		if(anchored)
Soy yo o este if(anchored) está dentro fe un if(!anchored)?

2020-03-25 20:02 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +		if(anchored)
Va que va, ya quedo cambiado por un else y reubicado.

2020-03-25 20:02 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +			anchored = 0
Listo.

2020-03-25 20:02 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +		anchored = 1
Listo

2020-03-25 20:03 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +		else if(istype(I, /obj/item/wrench))
Este else if lo tengo que dejar aquí de otra forma cuando entro a wrench act me tira el mensaje de que no puedo poner una wrench en el carrito.

2020-03-25 20:05 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +		else if(istype(I, /obj/item/wrench))
Aunque solo sucede esto si ocupas herramientas en help intent y no en harm.

2020-03-25 21:18 UTC, Evankhell561 requested changes

2020-03-25 21:18 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +		else if(istype(I, /obj/item/wrench))
Esta linea es necesaria? Para el welder no la tienes.
En caso de ser necesaria pon un return abajo de ella.

2020-03-26 00:34 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	updateUsrDialog()
creo que ya quedo, solo me pregunto para qué es este proc.

2020-03-26 02:13 UTC, Spircen commented on code/HISPANIA/game/objects/structures/medicart.dm
> +	updateUsrDialog()
Va que va, me costo un poco pero lo encontré. Esta función hace que si otro usuario esta viendo el carrito de cirugías se le actualice el texto de dentro y no pueda tomar un item que ya fue tomado anteriormente de el mismo. 

![image](https://user-images.githubusercontent.com/46639834/77603185-063d6e00-6ed5-11ea-9d7c-2c1ad313e4fe.png)

2020-03-26 10:55 UTC, merged