Garronte el Búho
Helixis/Paradise pull request #487
Opened 2020-03-17 23:19 UTC by Jinouga19

## What Does This PR Do
Añade un nuevo buhó en la oficina del chaplain, con los ojos muy grandes con los cuales cuidara la iglesia cuando no estes con su particular sonido.
Añade una cama para la nueva mascota.
Añade su emote con un sonido incluido.

## Why It's Good For The Game
Me parece que el trabajo de chaplain es un poco solitario y al tener un búho tienes mas compañía y puedes rolear mas. Ademas la puedes controlar si eres un fantasma. 

## Images of changes

### Garronte en la oficina del chaplain:
![Buho6](https://user-images.githubusercontent.com/61878952/76910156-86e4e480-68ad-11ea-8db2-f140dea3e8a8.PNG)
### Garronte de frente:
![Buho1](https://user-images.githubusercontent.com/61878952/76910231-be539100-68ad-11ea-982f-b4baed283342.PNG)
### Garronte de espaldas:
![Buho2](https://user-images.githubusercontent.com/61878952/76910244-cad7e980-68ad-11ea-9bdf-54d7fdc637ff.PNG)
### Garronte de los lados:
![Buho3](https://user-images.githubusercontent.com/61878952/76910257-d3302480-68ad-11ea-8d06-7ef3226ee3c4.PNG) 
![Buho4](https://user-images.githubusercontent.com/61878952/76910268-d75c4200-68ad-11ea-8f7f-8afb06119f90.PNG)
### Garronte muerto:
![Buho5](https://user-images.githubusercontent.com/61878952/76910294-ed6a0280-68ad-11ea-8faf-87c258d71a4c.PNG)

## Changelog
:cl:
add: Añade un búho como la mascota del chaplain.
add: Añade una cama para la nueva mascota.
add: Añade un nuevo emote (*hoot) con su sonido propio.
/:cl:

2020-03-18 03:01 UTC, Spircen commented
Chevere, todo parece listo para ser mergeado.

2020-03-18 16:59 UTC, Jinouga19 commented
Ya no voy a tocar nada mas. A si que ya estaría listo :D

2020-03-19 00:31 UTC, Evankhell561 requested changes

2020-03-19 00:31 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	obj_damage = 5
Uhm no sé si deberias bajar esto o directamente quitar esta variable.

2020-03-19 00:31 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	density = 1
TRUE en vez de 1

2020-03-19 00:31 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	can_collar = 0
FALSE en vez de 0

2020-03-19 00:31 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	gold_core_spawnable = NO_SPAWN
Quita esta linea porque no hace falta.

2020-03-19 00:31 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +/mob/living/simple_animal/friendly/owl/emote(act, m_type = 1, message = null, force)
Testeaste este emote?

2020-03-19 00:31 UTC, Evankhell561 commented on code/modules/mob/transform_procs.dm
> +		return 1
Cambia el 1por TRUE

2020-03-19 01:48 UTC, Jinouga19 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	obj_damage = 5
que hago con la variable? la de damage_coeff?

2020-03-19 01:48 UTC, Jinouga19 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	gold_core_spawnable = NO_SPAWN
que linea especificamente

2020-03-19 01:48 UTC, Jinouga19 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +/mob/living/simple_animal/friendly/owl/emote(act, m_type = 1, message = null, force)
si, con sonido y todo y funciona

2020-03-19 01:58 UTC, Jinouga19 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	density = 1
listo

2020-03-19 01:58 UTC, Jinouga19 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	can_collar = 0
listo

2020-03-19 02:00 UTC, Jinouga19 commented on code/modules/mob/transform_procs.dm
> +		return 1
todos tienen 1... no entiendo el porque del TRUE si el uno es lo mismo, ya esta cambiado

2020-03-19 02:02 UTC, Jinouga19 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	obj_damage = 5
supongo que la que he dicho. quitada

2020-03-19 13:37 UTC, Jinouga19 commented on code/HISPANIA/modules/mob/living/simple_animal/friendly/owl.dm
> +	gold_core_spawnable = NO_SPAWN
listo

2020-03-19 19:33 UTC, Jinouga19 commented
Ya hice los cambios y te pedi revision

2020-03-21 02:54 UTC, Evankhell561 requested changes
¿Todo bien pero no puedo hacer el hoot emote, seguro que testeaste eso?

2020-03-21 10:35 UTC, Jinouga19 commented
> ¿Todo bien pero no puedo hacer el hoot emote, seguro que testeaste eso?

Te dejo un vídeo que acabo de hacer, lo he compilado en la ultima versión que te deje y sin cambiar ningún archivo ni nada, lo acabo de testear y funciona. A partir del segundo 0:57 se puede ver de que si hace el emote *hoot con su sonido caracteristico https://www.youtube.com/watch?v=jK9_5sVH5y8&feature=youtu.be

2020-03-21 14:04 UTC, merged