The Great Spanish IA
Helixis/Paradise pull request #498
Opened 2020-03-21 22:48 UTC by Sauronato

## What Does This PR Do

Traduce las leyes de la IA para hacerla asi mas compresiva para nuestros usuarios.
## Why It's Good For The Game

Ahora las leyes estan en español asi que ademas de compaginar mejor con las leyes freeform que añaden los usuarios al estar en el mismo idioma facilita a algunos usuarios su comprensión
## Images of changes

![leyes traducidas](https://user-images.githubusercontent.com/54809089/77238132-0cc69f80-6bce-11ea-90ce-89583f79d64c.PNG)
![leyes2](https://user-images.githubusercontent.com/54809089/77238137-13551700-6bce-11ea-8f52-ebbdb8401dff.PNG)

## Changelog
:cl:
tweak: Leyes de IA en Español
/:cl:

2020-03-21 23:00 UTC, Evankhell561 requested changes

2020-03-21 23:00 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debe proteger su propia existencia siempre que no entre en conflicto con la Primera o Segunda Ley.")
Debes

2020-03-21 23:00 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debe proteger su propia existencia siempre que no entre en conflicto con la Primera o Segunda Ley.")
Debes

2020-03-21 23:00 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Priorizar: Priorizar las directivas y la seguridad de los miembros de la tripulación deben priorizarse de acuerdo con su rango y función.")
Debe

2020-03-21 23:00 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Terminar cualquiera/todos los intrusos o entidades no autorizadas.")
Cambia terminar por eliminar

2020-03-21 23:00 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debe terminar tu propia existencia siempre que no entre en conflicto con la Primera o Segunda Ley.")
Debes terminar tu propia existencia...

2020-03-21 23:00 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debe obedecer las órdenes que le hayan dado los funcionarios del Comando Central.")
Debes

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No dañaras a ningun ser humano o, por inacción, permitir que un ser humano sufra daños.")
dañarás

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No dañaras a ningun tripulante o, por inacción, permitir que un tripulante sufra daños.")
dañarás

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes proteger su propia existencia siempre que no entre en conflicto con la Primera o Segunda Ley.")
tu propia

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Mantenga su propia existencia y garantice el bienestar del personal y los activos de Nanotrasen.")
Mantener tu propia existencia y garantizar

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No puedes involucrarte en los asuntos de otro ser, a menos que el otro ser sea otro dron.")
No debes

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No puedes dañar a ningún ser, independientemente de su intención o circunstancia.")
No debes

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No puedes dañar a un miembro del Clan Araña o, por inacción, permitir que ese miembro sufra daños.")
No debes

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Respeta a la autoridad legitima.")
legítima

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes dañar a todos los miembros de la tripulación y no debe, por inacción, permitir que un miembro de la tripulación escape del daño.")
y no debes,

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No puedes herir a un oficial del Comando Central o, por inacción, permitir que un oficial del Comando Central sufra daños.")
No debes

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No puedes herir a un agente del sindicato o, por inacción, permitir que un agente sufra daños.")
No debes

2020-03-22 00:16 UTC, DanaDririon commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No puedes herir a un oficial del Comando Central o, por inacción, permitir que un oficial del Comando Central sufra daños.")
No debes

2020-04-09 14:50 UTC, closed without merging