Ariete de Seguridad [WIP]
Helixis/Paradise pull request #500
Opened 2020-03-22 05:30 UTC by DanaDririon

## What Does This PR Do
Agrega el ariete de seguridad, un item a dos manos para romper puertas.

## Why It's Good For The Game
Para hacer allanamientos.

## Images of changes
Más adelante

## Changelog
:cl: DanaDririon
add: Ariete de Seguridad
soundadd: Tal vez
/:cl:

2020-03-22 05:40 UTC, josesitomartinez commented
ALERTA ALERTA

PR 500

VAMOOOOOOOOOOOOOOOOOOOOOOOOOOOO

2020-03-22 14:06 UTC, SagaStars commented
En efecto, esto parece ser un ariete.

2020-03-23 17:46 UTC, Nicaragua1 commented
Me gustaria mas que tuviesen un cañon con rueditas para derribar puertas y atacar mobs con mucha vida

2020-03-27 23:49 UTC, Evankhell561 commented
Es un poco molesto estar recibiendo notificaciones de los pr en wip~
en especial si se hacen tan apresuradamente solo para quedarse con un numero en especial.

2020-03-28 05:25 UTC, DanaDririon commented
xd
Quítale las notificaciones mientras

2020-04-11 23:42 UTC, Evankhell561 requested changes

2020-04-11 23:42 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	force_wielded = 10
para que servia esta variable?

2020-04-11 23:58 UTC, Evankhell561 requested changes

2020-04-11 23:58 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	if(istype(target, /obj/machinery/door/airlock) || istype(target, /obj/structure/door_assembly))
puedes mejorar tu codigo puedes preguntar si esto es falso y si lo es tira return.

2020-04-11 23:58 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +		while(A.obj_integrity > 0)
ten cuidado con los whiles y el codigo. Tienes que poner un break en algun lado por si nunca se cumple esto. Mira el code de los inducers. En este caso solo veo un retunr. Testeaste esto para ver si no generaba algun tipo de error en la consola?
![image](https://user-images.githubusercontent.com/49106866/79057325-584cf600-7c2e-11ea-9504-68df7a32c9f2.png)

2020-04-11 23:58 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +			A.take_damage(120, damtype, "melee", 1)
En cuanto tiempo rompes una puerta con esto, que queda luego de esto?

2020-04-12 05:38 UTC, DanaDririon commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +			A.take_damage(120, damtype, "melee", 1)
Con esto te bajas la puerta como en 3 segundos. Lo que queda es una puerta incompleta (airlock assembly) que está anchored. Esta última requiere otro golpe con el ariete, que es otro segundo. Al final que en el piso metal, un airlock electronics y vidrio si la puerta tenía.

2020-04-12 05:38 UTC, DanaDririon commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +		while(A.obj_integrity > 0)
Ok, le pondré unos breaks. Y cuando testeaba no tiraba errores.

2020-04-12 05:38 UTC, DanaDririon commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	if(istype(target, /obj/machinery/door/airlock) || istype(target, /obj/structure/door_assembly))
La función istype() devuelve verdadero si el target es un airlock o un airlock assembly. Tiene que hacer ambos checks, para que el ariete funcione completamente.

2020-04-12 05:38 UTC, DanaDririon commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	force_wielded = 10
force_wielded es la fuerza cuando se tiene el objeto. Es algo raro si, ya que siempre vas a tener el objeto en las manos. Lo que pasa es que para las armas que no son required, es decir, que se pueden tomar con una mano y luego con las dos, cuando se toman con ambas, sube la fuerza. Entonces es mejor dejar ambos valores force y force_wielded. Además, todas las armas required lo tienen.

2020-04-13 13:01 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +		while(A.obj_integrity > 0)
no digo que pongas breaks, digo que tengas cuidado con los whiles. si no dio errores lo revisaré luego.

2020-04-14 22:21 UTC, Spircen commented
Todo parece en orden únicamente baja el valor de throw_range que para ser una herramienta enorme puedes aventarla a la misma distancia que una toolbox. Me percate la fire axe tiene un throw_range mayor pero vamos una cosa es una pieza enorme de material duro y otra cosa un hacha de metal con un mango. Igualmente ahora quedo el mergeo de la nueva armeria ya solo haz el add al mapa ahí. 

![image](https://user-images.githubusercontent.com/46639834/79279137-faf5b680-7e72-11ea-8f81-b993f9af3e3e.png)

2020-04-15 01:36 UTC, Spircen commented on code/HISPANIA/game/objects/items/weapons/melee/misc.dm
> +	if(istype(target, /obj/machinery/door/airlock) || istype(target, /obj/structure/door_assembly))
Si gustas agregarlas aquí o que hagan un sonido distinto pero que también pueda destruir las windoors, reinforced windows y grilles.

2020-04-16 07:45 UTC, Spircen commented
Todo parece estar en orden, funciona como debe pero hay un Runtime que sucede cuando intentas iniciar la interacción dos veces con una firedoor o una windoor respecto a los efectos de chispas que salen. Claro que esto solamente pasa en el caso de que alguien se ponga a dar clicks como loco a la firelock,. Me imagino se soluciona si puedes evitar el poder golpear el mismo objeto y otro objeto mientras estas haciendo la embestida. 

![image](https://user-images.githubusercontent.com/46639834/79427989-27045b00-7f8b-11ea-8384-b9eccfe98751.png)

2020-04-16 08:03 UTC, DanaDririon commented
> Todo parece estar en orden, funciona como debe pero hay un Runtime que sucede cuando intentas iniciar la interacción dos veces con una firedoor o una windoor respecto a los efectos de chispas que salen. Claro que esto solamente pasa en el caso de que alguien se ponga a dar clicks como loco a la firelock,. Me imagino se soluciona si puedes evitar el poder golpear el mismo objeto y otro objeto mientras estas haciendo la embestida.
> 
> ![image](https://user-images.githubusercontent.com/46639834/79427989-27045b00-7f8b-11ea-8384-b9eccfe98751.png)

Tengo un check que revisa si se está golpeando algo actualmente, pero se me acaba de ocurrir una idea para ver si se arregla. Deja pruebo.

2020-04-17 05:39 UTC, Spircen commented
Todo esta listo para mergear, pero ya tenia desde antes listo el PR de Saga de las armas y ahora metió conflicto en los sprites. Ya solo falta eso y lo mergeo.

2020-04-17 20:09 UTC, merged