Security Cadets!
Helixis/Paradise pull request #51
Opened 2019-04-06 17:03 UTC by Nicaragua1

**Habemus nuevo job, los cadetes de seguridad desbloqueados desde el dia 1 para que los nuevos puedan practicar sin armas muy nocivas.**

![L0vfZOQ](https://user-images.githubusercontent.com/24284918/55672710-84dc6e00-5874-11e9-83dd-79ab11c82f8d.png)

Aprendan como es el trabajo y vayan siempre acompañados de oficiales con titulo completo
- No pueden poner condenas
- Spawnean con un pepper spray y un flash
- No poseen taser ni tienen acceso a los lockers de sec, sin embargo si el warden lo considera puede hacerlos practicar con armas y bajo su supervision.

![QQwDsGk](https://user-images.githubusercontent.com/24284918/55672726-c240fb80-5874-11e9-9f0c-5957239fc9fe.png)

:cl:
add: nuevo job, security cadets!
/:cl:

2019-04-06 17:08 UTC, Evankhell561 commented
me gusta, no se si sea la mejor manera de resolver el problema porque sigues necesitando de un sec que te enseñe pero me gusta. es como quien quiere ir de asistente en sec. el problema puede ser que entren sin haber ni un sec y luego no puedan hacer arrestos. de ultima los heads que esten pueden darle trabajo poniendoles accesos de sec.

2019-04-06 17:10 UTC, Evankhell561 commented
tambien. yo habia pensado en algo asi como crear el departamento legal (solo estaria reflejado en el manifiesto). donde incluiria a magistrado, a los iaa y al nt rep. estos dos serian algo asi como los heads departamentales porque los iaa podrian consultar con ellos y todos tienen en comun informar a NT

2019-04-06 18:24 UTC, iRyzor commented
Este pr lo veo viable si pones que sólo puedan haber cadetes si hay oficiles/warden/hos en el turno.

2019-04-08 13:53 UTC, Danaleja2005 commented
me gusta este nuevo rol , pero no me gusta mucho es sprite de los cadetes , no deberian llevar beret ya que todavia no son sec aprobados , podria hacer unos nuevos uniformes mas de cadetes para el rol y un sombrero o gora tambien

2019-04-08 17:28 UTC, Nicaragua1 commented
El uniforme es una camisa y una boina roja. Cosa que actualmente los sec officers jamas usan. Normalmente usan cascos y armaduras. Pero si quieres spritear algo mas bonito es totalmente bienvenida la propuesta

2019-04-08 17:44 UTC, Danaleja2005 commented
si lo hare cuando pueda , pero creo que el color de el uniforme deberia ser diferente , estaba pensando pantalon azul con rayas rojas en las partes laterales y camisa manga corta de color blanca con un distintivo gris con rojo ( para representar que son cadetes)

2019-04-08 18:14 UTC, Nicaragua1 commented
Y que tal unos pantalonsillos cortos?

2019-04-08 18:23 UTC, Danaleja2005 commented
mmm no me parece , los cadetes que he visto irl , van vestidos con un pantalon azulado oscuro , camisa blanca y una gorra policiaca

2019-04-20 21:13 UTC, Kotiro22 commented
Creo que deberían tener algo mas, algo único, esta bien el puesto para aprendices, pero para aprender esta el puesto de asistente, quiero decir actualmente no son mas que assitant que han ido a seguridad a aprender, solo que ya van sin esa parte del rol, literalmente desde mi punto de vista esto se puede suplir con rol de una manera muy fácil, vas a seguridad y te dan lo mismo, que de igual manera, con esto, estas forzando a seguridad en si a hacer de canguro y, por mucho que este bien ayudar a los nuevos, no todo el mundo sabe y esta un poco feo en mi opinión, querer entrar a hacer de seguridad o pod pilot o lo que quieras ser y tener que hacer de canguro/mentor de un cadete por rol, seria un poco forzado.

2020-02-25 16:46 UTC, Nicaragua1 commented
**Este PR ha revivido!**

> me gusta, no se si sea la mejor manera de resolver el problema porque sigues necesitando de un sec que te enseñe pero me gusta. es como quien quiere ir de asistente en sec. el problema puede ser que entren sin haber ni un sec y luego no puedan hacer arrestos. de ultima los heads que esten pueden darle trabajo poniendoles accesos de sec.

Se agrego justamente la sugerencia de Evan de hacer que los cadetes puedan entrar solo habiendo minimo 3 en seguridad. (Sin contar otros cadetes obvio)

2020-02-25 18:42 UTC, SagaStars commented
> ```
>                                         **Este PR ha revivido!**
> ```
> 
> > me gusta, no se si sea la mejor manera de resolver el problema porque sigues necesitando de un sec que te enseñe pero me gusta. es como quien quiere ir de asistente en sec. el problema puede ser que entren sin haber ni un sec y luego no puedan hacer arrestos. de ultima los heads que esten pueden darle trabajo poniendoles accesos de sec.
> 
> Se agrego justamente la sugerencia de Evan de hacer que los cadetes puedan entrar solo habiendo minimo 3 en seguridad. (Sin contar otros cadetes obvio)

3 me parece mucho... le bajaria a 2.

2020-02-26 18:02 UTC, Evankhell561 requested changes

2020-02-26 18:02 UTC, Evankhell561 commented on code/game/jobs/job/security.dm
> +/datum/job/intern_sec
esto a hispania

2020-03-01 03:11 UTC, Nicaragua1 commented
En breve subo los sprites diseñados para el job por dana

2020-03-01 11:48 UTC, Evankhell561 requested changes

2020-03-01 11:48 UTC, Evankhell561 commented on code/game/jobs/job/security.dm
> +/datum/outfit/job/intern_sec
Esto también

2020-05-03 03:54 UTC, Evankhell561 requested changes

2020-05-03 03:54 UTC, Evankhell561 commented on code/modules/mob/new_player/new_player.dm
> +			cuenta += (officer.current_positions + warden.current_positions + hos.current_positions + detective.current_positions)
No necesitas estos paréntesis.

2020-05-03 03:54 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +	var/secCadetratio = 3 // Cuantos sec officer para habilitar un cadete?
Mayúsculas

2020-10-13 20:03 UTC, Silverexperience reviewed
No se si sigues aqui para terminar el PR, si estas avisa.

2020-10-19 02:25 UTC, closed without merging