Cambio a requerimentos de gamemodes
Helixis/Paradise pull request #510
Opened 2020-03-24 02:19 UTC by DanaDririon

## What Does This PR Do
Cambia algunos requerimentos de antag, para que sean acorde a nuestra comunidad.

## Why It's Good For The Game
Dale man, 4 antags con 0 sec? xd

## Images of changes

## Changelog
:cl: DanaDririon
tweak: Cambio a requerimentos de algunos gamemodes
/:cl:

2020-03-24 12:48 UTC, Evankhell561 requested changes

2020-03-24 12:48 UTC, Evankhell561 commented on code/game/gamemodes/nuclear/nuclear.dm
> +	required_enemies = 3
Mejor solo sube la cantidad de readys a 24 y pon el requiered a 4 y el recomendado dejalo en 5

2020-03-24 12:54 UTC, Evankhell561 requested changes

2020-03-24 12:54 UTC, Evankhell561 commented on code/game/gamemodes/changeling/changeling.dm
> +	changeling_amount = 1 + round(num_players() / 15)
Ya que también estás bajando el cap de antags cambiatodostus /15 por entre /12.

2020-03-24 17:08 UTC, Spircen commented
A su vez recuerda que se toma en cuenta el archivo config al cual nosotros no tenemos acceso por motivos de seguridad. En la sección de config example, ahi esta el archivo de config.txt ese puede hacer algunos cuantos overrride a las cosas que estas agregando aquí y eso únicamente Hessica y Ume tienen acceso.

2020-03-24 17:26 UTC, DanaDririon commented
> A su vez recuerda que se toma en cuenta el archivo config al cual nosotros no tenemos acceso por motivos de seguridad. En la sección de config example, ahi esta el archivo de config.txt ese puede hacer algunos cuantos overrride a las cosas que estas agregando aquí y eso únicamente Hessica y Ume tienen acceso.

See, pero teniendo esto me conformo.

2020-03-24 23:01 UTC, Nicaragua1 commented
Puedes agregar el required players de meteors a 0 o 1?  
Es un modo que esta fuera de rotacion y siempre que un admin quiere colocarlo por votacion / manualmente no puede y tiene que andar forzando el evento de meteoritos.

El resto me parece buen cambio

2020-03-27 01:24 UTC, Evankhell561 requested changes

2020-03-27 01:24 UTC, Evankhell561 commented on code/game/gamemodes/blob/blob.dm
> +	required_players = 14
No entiendo por qué subes todos los demás y bajas este.

2020-03-27 01:24 UTC, Evankhell561 commented on code/game/gamemodes/blob/blob.dm
> +	var/blobwincount = 600
Que determina esta variable?

2020-03-27 01:24 UTC, Evankhell561 commented on code/game/gamemodes/nuclear/nuclear.dm
> +	required_enemies = 4
Estaba pensando que la cantidad de enemigos requeridos son los enemigos que requieres para iniciar el modo de juego así que si lo bajas es más probable que se active el modo de juego.

2020-03-27 01:24 UTC, Evankhell561 commented on code/game/gamemodes/cult/cult.dm
> +	required_enemies = 2
Esto hará más probable de que se active el modo de juego solo que posiblemente con menos enemigos

2020-03-27 02:26 UTC, DanaDririon commented on code/game/gamemodes/blob/blob.dm
> +	var/blobwincount = 600
Cuantos bloques de blob se necesitan para ganar como blob.
Había visto un comentario de que habría que subirle y estaba de acuerdo.

2020-03-27 02:27 UTC, DanaDririon commented on code/game/gamemodes/cult/cult.dm
> +	required_enemies = 2
Sip, eso mismo.
Si no estás de acuerdo es entendible.

2020-03-27 02:28 UTC, DanaDririon commented on code/game/gamemodes/nuclear/nuclear.dm
> +	required_enemies = 4
Sip, es más probable. Pero aún necesitas 24 readys.
Puedo cambiarlo si quieres.

2020-03-27 02:28 UTC, DanaDririon commented on code/game/gamemodes/blob/blob.dm
> +	required_players = 14
Blob es un modo de juego balanceado y me gustaría verlo más.

2020-03-27 03:33 UTC, Evankhell561 commented on code/game/gamemodes/blob/blob.dm
> +	var/blobwincount = 600
solo pon 500.

2020-03-27 03:33 UTC, Evankhell561 commented on code/game/gamemodes/blob/blob.dm
> +	required_players = 14
nel, dejalo en 15

2020-03-27 16:54 UTC, merged