Add Plantas nuevas y mutaciones
Helixis/Paradise pull request #524
Opened 2020-03-29 03:10 UTC by Spircen

## What Does This PR Do
Agrega múltiples nuevas plantas y mutaciones a petición de Hessica quien ya contaba con todos sus sprites hechos y las ideas de que deberían de hacer cada una de estas. Las nuevas plantas son: 

- Agave: Sirve para destilar Tequila con el barril de fermentado
- Anona: Tiene mutación a Reticulata y produce jugo de Anona
- Anonna Reticulata: Produce mutageno inestable 
- Prickly Pear: Cactus dulce con bastantes nutrientes, puede mutar a San Pedro
- San Pedro: Cactus bastante nutritivo que puede hacer bastante daño al ser lanzado, muta a Peyote
- Peyote: Cactus alucinógeno puramente LSD 
- Bombonaut: Mutación del coco, pero explosivo
- Kiwi: Fruta dulce que puede generar jugo de Kiwi y muta a un huevo de kiwi
- Actual Kiwi: Fruta que al ser usada genera un Kiwi
- Mango: Fruta dulce que genera jugo de Mango
- Mate: Planta que permite generar futuras bebidas
- Champignon: Mutación de Chanterelle, hongo sin toxinas para pizzas.
- Nispero: Fruta perfecta para bebidas alcoholicas
- Peach: Linda fruta bastante THICC
- Bell Pepper: Perfecta para tus pizzas
- Ricinus: Permite crear Castor Oil reagent que cura daño bruto y quemaduras.
- Strawberry : La deliciosa fruta de la pasión. 

Aun debo de modificar las etapas de crecimiento de cada una y modificar algunos sprites que ya no ocupare pero las plantas son funcionales sin problemas. 

## Why It's Good For The Game
Agrega nueva variedad a la multitud de plantas que ya existen a la par que genera plantas que son bastantes conocidas en la vida real pero inexistentes, a la par que varias personas suelen tener ideas perfectas que generan para sus personajes pero no se logran cumplir por falta de algunas plantas de este catalogo y... casi no suelo hacer PRs de comida, variedad, diversión y mas sabor. 

## Images of changes

                                    Nuevas Plantas
![image](https://user-images.githubusercontent.com/46639834/77839267-64b65680-7138-11ea-8472-8b0e84ec1fc3.png)

                                 Agregamos a maquina
![image](https://user-images.githubusercontent.com/46639834/77839282-80216180-7138-11ea-8050-213c0dbf3d28.png)

## Changelog
:cl:
add: Nuevas plantas y mutaciones
/:cl:

2020-03-29 03:17 UTC, DanaDririon commented on code/HISPANIA/modules/hydroponics/grown/cactus.dm
> +	reagents_add = list("lsd" = 1)
Ojo, si le pones 1 significa 100%, lo que significa a su vez que tendrá las mismas unidades del reagente que la potencia.
80 potencia = 80u de lsd

2020-03-29 03:18 UTC, Spircen commented on code/HISPANIA/modules/hydroponics/grown/cactus.dm
> +	reagents_add = list("lsd" = 1)
Si, es Peyote. Se supone que siempre tenga esa cantidad máxima de drogas.

2020-03-29 03:19 UTC, DanaDririon commented on code/HISPANIA/modules/hydroponics/grown/cactus.dm
> +	reagents_add = list("lsd" = 1)
top kek

2020-03-29 03:20 UTC, DanaDririon commented
No agranda la química de hydro, pero me gustan las plantas
+1

2020-04-01 03:53 UTC, SagaStars commented
Ahora hay que sacarle buen provecho al chef y al bartender

2020-04-03 04:59 UTC, DanaDririon requested changes

2020-04-03 04:59 UTC, DanaDririon commented on code/HISPANIA/modules/hydroponics/grown/cactus.dm
> +	mutatelist = list(/obj/item/seeds/prickly_pear/san_pedro/peyote)
Aquí creo que el mutate list lo debes dejar vacío, porque esto está haciendo que la planta mute en sí misma.

2020-04-03 04:59 UTC, DanaDririon commented on code/HISPANIA/modules/hydroponics/grown/coconut.dm
> +	desc = "These seeds grow into cocount palms"
typo

2020-04-03 04:59 UTC, DanaDririon commented on code/HISPANIA/modules/hydroponics/grown/kiwi.dm
> +
Aquí también tienes que poner la lista de mutación vacía, porque lo está heredando el del otro.
También puedes borrar las variables species, reagents_add y growing icon, que las hereda

2020-04-03 05:06 UTC, DanaDririon commented
El resto se ve bien 👍 
Mientras que pruebes todas las plantas y que funcionen bien, apruebo

2020-04-03 16:11 UTC, Spircen commented on code/HISPANIA/modules/hydroponics/grown/cactus.dm
> +	mutatelist = list(/obj/item/seeds/prickly_pear/san_pedro/peyote)
Ah cierto, aquí se me paso la mutación.

2020-04-03 16:12 UTC, Spircen commented on code/HISPANIA/modules/hydroponics/grown/kiwi.dm
> +
Vale, voy a hacer eso con las plantas que mutan.

2020-04-03 16:12 UTC, Spircen commented on code/HISPANIA/modules/hydroponics/grown/coconut.dm
> +	desc = "These seeds grow into cocount palms"
Ya lo cambio

2020-04-03 16:35 UTC, DanaDririon requested changes

2020-04-03 16:35 UTC, DanaDririon commented on code/HISPANIA/modules/hydroponics/grown/coconut.dm
> +	desc = "These seeds grow into cocount palms."
Me refería a _coco**un**t_ xd

2020-04-03 16:35 UTC, DanaDririon commented on code/HISPANIA/modules/hydroponics/grown/peach.dm
> +	potency = 9
Y también encuentro que en general pones potencia baja
Recuerda que este valor va de 0 a 100, entonces entre potencia 3 o potencia 9 no hay mucha diferencia

2020-04-03 17:15 UTC, Spircen commented on code/HISPANIA/modules/hydroponics/grown/coconut.dm
> +	desc = "These seeds grow into cocount palms."
Ah ya, ahi quedo xd

2020-04-03 17:15 UTC, Spircen commented on code/HISPANIA/modules/hydroponics/grown/peach.dm
> +	potency = 9
Ya cambie el resto de todos en potency

2020-04-06 19:18 UTC, DanaDririon requested changes

2020-04-06 19:18 UTC, DanaDririon commented on code/HISPANIA/modules/hydroponics/grown/peach.dm
> +	potency = 75
Potencia 75 sin tener que mutar una planta :dab:

2020-04-07 20:48 UTC, Spircen commented on code/HISPANIA/modules/hydroponics/grown/peach.dm
> +	potency = 75
New meta chi cheñol

2020-04-13 00:52 UTC, Spircen commented
Listo, potencias bajadas, sprites agregados a las bebidas para que no sean vasos de "What...?"

2020-04-16 21:07 UTC, DanaDririon commented
Apruebo como está el PR ahora 👍

2020-04-17 21:49 UTC, merged