Ultra Chad peste negra, Version 9000.
Helixis/Paradise pull request #533
Opened 2020-03-31 21:39 UTC by Silverexperience

## What Does This PR Do
Aumenta la probabilidad de que aparezcan los fleas y soluciona un bug que hacia que los fleas no te pudieran infectar. Aunque recuerdo que antes, al testearlo, funcionaba.

## Why It's Good For The Game
Fijandome en la probabilidad del slot machine, los fleas estan casi como la probabilidad de ganar un millon de creditos, cosa que solo se veia cada 7 años, y ahora almenos tienen algo mas de probablidades de salir, para que no parezca adminspawn.
A nadie le gustan los bugs.

## Changelog
:cl:
tweak: Retoca la probabilidad de los fleas.
fix: Soluciona el error que hacia que los fleas no contagiaran.
/:cl:

2020-03-31 22:24 UTC, Evankhell561 requested changes

2020-03-31 22:24 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +		if(prob(0.5))
Está es la del e-n no?
Ponle un prob(10) abajo de este.

2020-03-31 22:30 UTC, Silverexperience commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +		if(prob(0.5))
¿Que dentro de la probablidad haya otra probablidad?

2020-03-31 23:12 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +		if(prob(0.5))
Yep.

2020-03-31 23:47 UTC, Silverexperience commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +		if(prob(0.5))
La probabilidadinception a sido completada.

2020-03-31 23:58 UTC, Silverexperience commented on code/modules/mob/living/simple_animal/friendly/dog.dm
> +		if(prob(0.5))
La probabilidadinception a sido completada.

2020-04-01 03:39 UTC, SagaStars commented
> El umbral de 95 porciento.

Definitvamente los commits son la verdadera meme zone, buena referencia lince +10
![D404290C-5D85-4BBE-A29E-8D63816AC5B7](https://user-images.githubusercontent.com/55407528/78096837-b6651800-73a8-11ea-9249-365476d13e87.jpeg)

2020-04-01 04:04 UTC, Evankhell561 requested changes

2020-04-01 04:04 UTC, Evankhell561 commented on code/modules/food_and_drinks/food.dm
> +					if(prob(5))
Deberías hacer lo mismo acá (lo de prob(10)) si quieres mantener la misma proporción de veces que sale este evento.

2020-04-01 10:28 UTC, Silverexperience commented on code/modules/food_and_drinks/food.dm
> +					if(prob(5))
Prefiero que el evento de las pulgas salga mas que la de pulgas roboticas, no la misma proporción.

2020-04-01 10:33 UTC, Evankhell561 commented on code/modules/food_and_drinks/food.dm
> +					if(prob(5))
Uhm. No sé. Sé que como lo creaste quieres verlo más pero a mi me gusta que sea así tan raro de ver. Además de que aumentaste 10 veces la probabilidad. Como mucho ponle prob(1)

2020-04-01 10:36 UTC, Silverexperience commented on code/modules/food_and_drinks/food.dm
> +					if(prob(5))
Lo dejare en 1

2020-04-03 19:24 UTC, Evankhell561 commented
A futuro quiero que hagas una forma de protegerse de las pulgas o de matarlas rápido.

2020-04-03 19:24 UTC, merged

2020-04-03 22:05 UTC, Silverexperience commented
> 
> 
> A futuro quiero que hagas una forma de protegerse de las pulgas o de matarlas rápido.

El matamoscas del janitor los mata de un golpe, y con una palanca tambien las puedes matar de un golpe.