Add Whistle
Helixis/Paradise pull request #535
Opened 2020-04-01 03:09 UTC by Spircen

## What Does This PR Do
Agrega silbatos al juego, herramientas que se pueden ocupar en mano activa con un CD alto para poder evitar spam, con la existencia de el audio direccional y un sonido bastante alto. Es una herramienta que solamente se puede conseguir en los lockers de CMO, RD, HoS, HoP y Capitán.

## Why It's Good For The Game
Actualmente los heads cuentan con un megáfono para poder instruir a grupos grandes de instrucciones, el silbato existe para poder funcionar como herramienta de control direccional de multitudes a la par que una opción para pedir auxilio. 

Espero que con esta herramienta logren tener un control mejorado durante las emergencias a la par que una herramienta mas para su trabajo de control dentro la estación.

## Images of changes

                                      Texto visible y alto, pruebas en DS
![image](https://user-images.githubusercontent.com/46639834/78095289-c58d9b00-7393-11ea-94d3-1c2b2e19a001.png)

## Changelog
:cl:
add: Whistle
add: Whistles disponibles en lockers de CMO, RD, HoS, HoP y Capitán
/:cl:

2020-04-01 08:59 UTC, Jinouga19 commented
y el CE no tiene silbato?

2020-04-01 16:18 UTC, Spircen commented
Si giene, solo olvide agregarlo al CL

2020-04-15 11:51 UTC, Evankhell561 requested changes

2020-04-15 11:51 UTC, Evankhell561 commented on code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
> +	new /obj/item/whistle(src)
Haz todos estos adds a hispania.

2020-04-21 00:11 UTC, Evankhell561 requested changes

2020-04-21 00:11 UTC, Evankhell561 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/whistle(src)
y este

2020-04-23 20:35 UTC, Silverexperience requested changes
El ruido de los silbatos no es muy alto, y evan quiere un mensaje cuando lo intentas tocar con el delay.

2020-04-25 16:48 UTC, Silverexperience approved these changes

2020-04-25 17:02 UTC, Evankhell561 approved these changes

2020-04-25 17:06 UTC, merged