Mas modelos del peluche slime
Helixis/Paradise pull request #547
Opened 2020-04-02 03:58 UTC by X404ErrorX

## What Does This PR Do
Agrega 5 modelos del peluche slime de distintos colores, deja el original intacto por lo tanto con este cambio tendríamos 6 modelos del peluche slime en el juego, estos se pueden ganar de manera aleatoria en los juegos de la árcade o con tickets en la vendedora de juguetes (ramdom plushie).

## Why It's Good For The Game
Variedad en los colores del peluche de slime.

## Images of changes

![image](https://user-images.githubusercontent.com/61291554/78208569-14fac680-747b-11ea-8fcf-b5e88ceb54c3.png)

## Changelog
:cl:X404ErrorX
add: 5 modelos extra del peluche de slime.
imageadd: 5 nuevos sprites del plushie slime.
/:cl:

2020-04-02 15:37 UTC, Danaleja2005 commented on code/game/objects/items/toys.dm
> +	item_state = "plushie_slime_pink"
Yo sugiero que hagas todos los peluches hijos de el peluche de slime, me refiero a esto slimeplushie/pink, y asi te ahorras tener que colocar la desc en cada una, ademas, creo que esto deberia ir en hispania, donde metiste los iconos?

2020-04-02 20:05 UTC, X404ErrorX commented on code/game/objects/items/toys.dm
> +	item_state = "plushie_slime_pink"
Los iconos están en la Icon/obj/toy.dmi. Sobre lo de la desc, tienen que tener todos la misma, hice las pruebas y asi fue, todos tienen la misma desc pero su nombre cambia como tenia planeado, ¿a eso es a lo que te refieres?

2020-04-02 22:18 UTC, Danaleja2005 commented on code/game/objects/items/toys.dm
> +	item_state = "plushie_slime_pink"
lo que te queria decir, es que es innecesario que hagas slimeplushiecyan,slimeplushiepink, solo debes meterlos dentro de slimeplushie y cambiar los iconos el nombre, pero no es necesario colocar la desc ya que se hereda, osea debes hacer es esto, slimeplushie/pink, slimeplushie/cyan y asi con los otros ( y colocas el nombre, iconos y ya), también creo que deberias meter los iconos en la carpeta de hispania

2020-04-02 22:33 UTC, Evankhell561 requested changes

2020-04-02 22:33 UTC, Evankhell561 commented on code/game/objects/items/toys.dm
> +/obj/item/toy/plushie/slimeplushiepink
Sigue las recomendaciones de dana. Mete todo esto a hispania y los sprites también.

2020-04-02 22:44 UTC, Danaleja2005 commented
Mira Evan hice mi primer review yupi

2020-04-03 03:34 UTC, Nicaragua1 commented
Estos no son slimes.  Son porings

2020-10-19 02:25 UTC, closed without merging