Add Princess Of Terror Spiders Eggs Kit a Uplink (Hijack Only)
Helixis/Paradise pull request #553
Opened 2020-04-04 01:07 UTC by Spircen

## What Does This PR Do
Agrega un nuevo kit disponible a la zona de soporte para los traidores que tienen como objetivo hijack, este consiste en un huevo de princesa de terror spiders al ocuparlo genera un ruido alrededor de 5 tiles desde su base y tras 30 segundos aparece una Princesa del Terror y ofrece el puesto a Ghost. Tiene un costo de 20 TCs. La princesa NO sirve al traidor, es totalmente libre de cualquier sembrar terror a su gusto.

## Why It's Good For The Game
Sabemos que las Terror Spiders son como tal un experimento generado por el Sindicato pero actualmente únicamente existen como evento y su gateway, tiene bastante lógica que el sindicato pueda disponer de ellas para agentes con misiones tan complicadas como ejecutar un hijack. Considero que esto puede preparar nuevos modos de juego y no es una forma segura de jugar por que no sabes si hay un ghost dispuesto a tomar control de ella ademas de que su costo es el total de todos tus TCs considerando el desastre que puede o NO puede causar.

## Images of changes

                             Uplink Direction and Eggs plus manual
![image](https://user-images.githubusercontent.com/46639834/78415305-1a245680-75de-11ea-9bf1-682565e2a0be.png)

                             Aviso a Administración de uso de objeto
![image](https://user-images.githubusercontent.com/46639834/78415310-26101880-75de-11ea-978a-d01cc8600d4e.png)

                               Manual de uso hecho por yo merengues
![image](https://user-images.githubusercontent.com/46639834/78415319-32947100-75de-11ea-871b-25a5ead76222.png)

## Changelog
:cl:
add: Princess Of Terror Spiders Eggs Kit 
/:cl:

2020-04-04 01:25 UTC, SagaStars commented
Niceeee

2020-04-04 01:31 UTC, Capitan-Dev commented
Nice

2020-04-04 01:43 UTC, Spircen commented
Denada, era algo que tenia planeado hace tiempo.

2020-04-14 01:50 UTC, Evankhell561 requested changes

2020-04-14 01:50 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/miscellaneous/spawn_eggs.dm
> +	spawn(300)
Haz que suene la alarma unos minutos luego de que estas niñas nazcan y listo. El tiempo entre el nacimiento y la alarma debe ser menos al del evento de las terrors o 60 segundos superior a ese tiempo (considerando que es una sola araña).

2020-04-22 06:57 UTC, Spircen commented on code/HISPANIA/game/objects/items/miscellaneous/spawn_eggs.dm
> +	spawn(300)
Ya quedo


![image](https://user-images.githubusercontent.com/46639834/79950340-8c999100-843c-11ea-8f11-cc2ba09be753.png)

2020-04-22 11:53 UTC, Evankhell561 requested changes

2020-04-22 11:53 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/miscellaneous/spawn_eggs.dm
> +		GLOB.command_announcement.Announce("Confirmed outbreak of level 3 biohazard aboard [station_name()]. All personnel must contain the outbreak.", "Biohazard Alert", 'sound/effects/siren-spooky.ogg')
creo que este code hará sonar la alarma independientemente de si la spider nace o no. Igual la testearé a ver.

2020-04-22 19:55 UTC, Spircen commented on code/HISPANIA/game/objects/items/miscellaneous/spawn_eggs.dm
> +		GLOB.command_announcement.Announce("Confirmed outbreak of level 3 biohazard aboard [station_name()]. All personnel must contain the outbreak.", "Biohazard Alert", 'sound/effects/siren-spooky.ogg')
Suena 2.2 minutos después en realidad. Considerando que spawn es un salta esta linea hasta que pasen X de tiempo. Igual realmente esta bien. Sucede lo mismo con las terror si las matan antes que suene la alarma.

2020-04-22 22:53 UTC, Evankhell561 requested changes

2020-04-22 22:53 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/miscellaneous/spawn_eggs.dm
> +			playsound(src, 'sound/hispania/effects/princesa.ogg', 70, 7)
mejor inicia en conteo de la alarma justo despues de que nazca. osea por acá.

2020-04-22 23:07 UTC, Spircen commented on code/HISPANIA/game/objects/items/miscellaneous/spawn_eggs.dm
> +			playsound(src, 'sound/hispania/effects/princesa.ogg', 70, 7)
Lo movere debajo del delete para asegurar que el huevo sea borrado y entonces comienza.

2020-04-26 16:39 UTC, Evankhell561 requested changes

2020-04-26 16:39 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/miscellaneous/spawn_eggs.dm
> +				GLOB.command_announcement.Announce("Confirmed outbreak of level 3 biohazard aboard [station_name()]. All personnel must contain the outbreak.", "Biohazard Alert", 'sound/effects/siren-spooky.ogg'
Estuve 20 minutos testeando y liberé a 9 arañas, cada una luego de que naciera la otra, no escuche ningun anuncio. si tu disces que lo oyes le pediré a silver que lo revise a ver si soy solo yo. Por otro lado, haz que en anuncio suene si y solo sí la araña nació en el z 1, 3 o 5.

2020-05-02 02:00 UTC, Spircen commented
Este alomejor sale un dia xd los sprites estan ahi

2020-10-07 07:38 UTC, Spircen commented
Voy a reparar esto, estaba divertido.

2020-10-07 08:13 UTC, Spircen commented on code/HISPANIA/game/objects/items/miscellaneous/spawn_eggs.dm
> +				GLOB.command_announcement.Announce("Confirmed outbreak of level 3 biohazard aboard [station_name()]. All personnel must contain the outbreak.", "Biohazard Alert", 'sound/effects/siren-spooky.ogg'
Bueno según yo lo acabo de probar y ya funciona. 

![image](https://user-images.githubusercontent.com/46639834/95305059-19010a00-084b-11eb-98bf-80bbc1e0e971.png)

2020-10-07 08:34 UTC, Spircen commented
Ya quedo, valida si la araña se encuentra en el Sector 1 y anuncia la alerta de nivel 3 encaso de estarlo. Igualmente recuerda darle a iniciar shift cuando hagas las pruebas.

2020-10-13 21:13 UTC, Silverexperience requested changes
- El tiempo que tarda en dar la alarma es bastante bajo. No da tiempo ni a moverse 10 tiles.

- En el papel que te da cambia el "REMEMBER THEY ARE NOT YOUR FRIENDS" a un color rojo.

2020-10-19 02:25 UTC, closed without merging