Arreglos en un par de rutas en la policetape + Ahora se puede guardar en belts de utility y de sec
Helixis/Paradise pull request #571
Opened 2020-04-07 19:09 UTC by SagaStars

El titulo es bastante auto explicativo, quito un par de rutas extra que no hacen ningun bien y ahora se pueden almacenar en belts.

## Changelog
:cl:
tweak: tweaked a few things
/:cl:

2020-04-11 18:12 UTC, Evankhell561 requested changes

2020-04-11 18:12 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/policetape.dm
>  	max_integrity = 10
el item base ya tiene la integridad en 10, no necesitas decirlo de nuevo.

2020-04-11 18:13 UTC, Evankhell561 requested changes

2020-04-11 18:13 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/policetape.dm
>  	req_access = list(ACCESS_CENT_SPECOPS)
¿por qué requieres acceso para esto, sirve para algo?

2020-04-11 19:39 UTC, SagaStars commented on code/HISPANIA/game/objects/items/policetape.dm
>  	req_access = list(ACCESS_CENT_SPECOPS)
Los accesos hacen que no tengas que levantar la cinta para poder pasar por ella, en bay actualmente todos los de rango de segurata pueden pasar por la cinta sin problema, como a mi no me gusta esa idea de que los seguratas puedan atravesarlo por que si solo se lo deje a los del ERT para tocar menos code.

2020-04-11 19:39 UTC, SagaStars commented on code/HISPANIA/game/objects/items/policetape.dm
>  	max_integrity = 10
Sicierto

2020-04-12 01:55 UTC, SagaStars commented
Maldigo al que cambio rutas de las arañas

2020-04-15 22:24 UTC, Spircen commented
Me salto este runtime la primera vez que la ocupe pero ya no se repite como antes. Otra duda ¿Deberían de ser amarillas ambas en el suelo? Por ultimo si me muevo en diagonal puedo poner tapes en el suelo pero no las muestra a no ser que las ponga a los lados contrario a donde me quiera mover, esto ultimo no me manda runtimes y creo no haya que resolverlo por que al fin y al cabo no afecta al code pero si se te ocurre una forma de resolverlo adelante. 

![image](https://user-images.githubusercontent.com/46639834/79394624-93586d80-7f3d-11ea-9408-615d32baa584.png)

2020-04-16 20:44 UTC, SagaStars commented
>¿Deberían de ser amarillas ambas en el suelo?

2020-04-16 21:12 UTC, merged