[Map Changes] Brig-Phyisician Office (Cyberiad)
Helixis/Paradise pull request #580
Opened 2020-04-09 01:00 UTC by Spircen

## What Does This PR Do
Elimina un NanoMed Plus de Medbay para poder agregarlo a la oficina del Brig Phyisician, proporciona una pequeña bandeja de morgue a su área, una chaqueta de fuerza, desfribilador de pared y caja de sangre a la par que un space cleaner. Por ultimo agrega instrumentaría básica a su locker y cambia su acceso para que solo el pueda acceder. 

## Why It's Good For The Game
Desde que agregamos el cargo los brig physician desde un inicio de turno deben asistir a medbay para completar su instrumentaría si bien el cargo NO ES una sustitución total para medbay, si debería de poder acceder a herramientas básicas desde su área de trabajo, no agrego una cryo, clonadora o sala de cirugías por que ya esta instrumentaría es mas especifica y debería ya sea solicitar a un ingeniero le cree esto o desplazarse a medbay para realizar la cirugía. 

## Images of changes

                                         Nueva Sala
![image](https://user-images.githubusercontent.com/46639834/78847071-59ceb200-79d3-11ea-9dd5-d4eb67eced9a.png)

## Changelog
:cl:
tweak: Brig Physician Office Changes
/:cl:

2020-04-09 01:00 UTC, Spircen commented
Cambios Sugeridos en https://github.com/Helixis/Paradise/issues/560

2020-04-09 01:07 UTC, SagaStars commented
Eh, me gustaria saber cual de todos los nanomeds quitastes si no te importaria

2020-04-09 01:34 UTC, Spircen commented
El del recibidor de medbay.

2020-04-09 03:06 UTC, Evankhell561 requested changes

2020-04-09 03:06 UTC, Evankhell561 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/storage/box/autoinjectors(src)
Haz estas adiciones al closet desde hispania.

2020-04-09 21:20 UTC, Spircen commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/storage/box/autoinjectors(src)
Listo.

2020-04-15 11:55 UTC, Evankhell561 requested changes
Por razones que ya expliqué en discord no creo que sea apropiado que haya acá una bandeja de la morhue. Se me ocurre que puedas añadir un body scanner pero tú verás.

2020-04-17 00:02 UTC, Silverexperience requested changes
No veo ningun problema, salvo que la chaqueta de fuerza le falta su bozal para que no se suiciden mordiendose la lengua o hablen.

2020-04-17 01:26 UTC, Spircen commented
Claro, me parece que ya hay uno dentro de la sala de ejecuciones pero lo voy a mover.

2020-04-18 00:25 UTC, Silverexperience approved these changes

2020-04-18 00:28 UTC, Evankhell561 approved these changes

2020-04-18 00:36 UTC, merged