[WIP]Nuevas leyes para la IA y traducción de las demas
Helixis/Paradise pull request #582
Opened 2020-04-09 14:56 UTC by Sauronato

## What Does This PR Do

Se añaden nuevos set laws como el Commander y AntiEoC (Estos nombres no son los definitivos). Ademas de traducir los demas setlaws. Ademas pone NT Default como un posible setlaw para las leyes inciales de la IA.
## Why It's Good For The Game

Agrega mas setlaws con los cuales dar mas juego, estos fueron creados por la comunidad en una encuesta. Ademas que al traducir las leyes, ahora todos los usuarios compenderan mejor el funcionamiento de estas.
## Images of changes

_**Ya las ire agregando**_
## Changelog
:cl:
add: Commander y AntiEoC Setlaws
add: NT Default en los setlaws predeterminadas.
tweak: Traducción de leyes de IA

/:cl:

2020-04-11 18:25 UTC, Evankhell561 requested changes

2020-04-11 18:25 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No dañarás a ningun tripulante o, por inacción, permitir que un tripulante sufra daños.")
permitirás

2020-04-11 18:25 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes obedecer las órdenes que te dan los tripulantes, excepto cuando tales órdenes entren en conflicto con la Primera Ley, ordenadas por tripulantes arrestados o bajo amenzas de s
"Debes obedecer las órdenes que te dan los tripulantes, excepto cuando tales órdenes entren en conflicto con la Primera Ley, o cuando se realicen bajo amenzas de suicido."
 Lo de la tripulacion arrestada no es una traducción y lo del suicidio tampoco pero te acepto lo del suicidio.

2020-04-11 18:25 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Mantener en cuarentena la estación hasta que se neutralice el riesgo biológico activo.")
Mantén

2020-04-11 18:25 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Mantener tu propia existencia y garantice el bienestar del personal y los activos de Nanotrasen.")
mantén, garantiza.

2020-04-11 19:33 UTC, Sauronato commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes obedecer las órdenes que te dan los tripulantes, excepto cuando tales órdenes entren en conflicto con la Primera Ley, ordenadas por tripulantes arrestados o bajo amenzas de s
Esa parte es nueva que sugirieron agregar eso al crewsimov para que no escaparan estando presos amenazando con suicidarse

2020-04-11 19:53 UTC, Sauronato commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes obedecer las órdenes que te dan los tripulantes, excepto cuando tales órdenes entren en conflicto con la Primera Ley, ordenadas por tripulantes arrestados o bajo amenzas de s
Y si contradice un poco la ley de arriba

2020-04-15 13:21 UTC, Evankhell561 requested changes

2020-04-15 13:21 UTC, Evankhell561 commented on data/mode.txt
> -secret
Why?

2020-04-15 13:21 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes obedecer las órdenes que te dan los tripulantes, excepto cuando tales órdenes entren en conflicto con la Primera Ley, ordenadas por tripulantes arrestados o bajo amenzas de s
Hacerle caso a un prisionero no es contradictorio siempre. En cambio amenazar a la ia con suicidarse no debería permitirse.

2020-04-15 13:21 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Evitar, por cualquier medio necesario, que las entidades infrinjan activamente la cuarentena en curso.")
evita

2020-04-15 13:21 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Ayudar a todo el personal y los activos de Nanotrasen a neutralizar los riesgos biológicos activos.")
ayuda

2020-04-15 13:44 UTC, Sauronato commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes obedecer las órdenes que te dan los tripulantes, excepto cuando tales órdenes entren en conflicto con la Primera Ley, ordenadas por tripulantes arrestados o bajo amenzas de s
Creo que el que lo sugirió decia que eso daba la posibilidad que los presos le digan liberame y les libere aunque yo eso no lo hago como ia la verdad xD

2020-04-15 13:45 UTC, Sauronato commented on data/mode.txt
> -secret
eso lo elimine i think

2020-04-16 01:38 UTC, Evankhell561 requested changes

2020-04-16 01:38 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Ayuda solo a aquellos que te ayudan a mantener o mejorar tu estado.")
Que te ayuden

2020-04-16 01:38 UTC, Evankhell561 commented on code/game/objects/items/weapons/AI_modules.dm
> +	var/law = "Proteger la estación espacial contra daños. Cualquier persona que veas dañar la estación ya no se considerará tripulación, y es una amenaza para la estación que debe neutralizarse."
Protege

2020-04-16 01:38 UTC, Evankhell561 commented on code/modules/mob/living/silicon/robot/laws.dm
> +		to_chat(who, "<b>Recuerda, no estas conectado a ninguna IA, no estas obligado a escuchar a ninguna de estas.</b>")
A escucharlas*

2020-04-27 17:47 UTC, Evankhell561 requested changes

2020-04-27 17:47 UTC, Evankhell561 commented on code/modules/mob/living/silicon/laws.dm
> +	var/can_state = statelaw("[prefix]Leyes activas actualmente:")
Esta es una buena traduccion sin embargo para el español creo que es redundante. 
pon solo Leyes activas:

2020-04-27 17:47 UTC, Evankhell561 commented on code/modules/mob/living/silicon/robot/laws.dm
> +					to_chat(src, "<b>Recuarda, tu IA no comparte ni sabe tu ley 0.")
no comparte ni conoce

2020-04-27 17:47 UTC, Evankhell561 commented on code/game/objects/items/weapons/AI_modules.dm
> +	var/targName = sanitize(copytext(input(usr, "Por favor introduzca su nueva ley.", "Freeform Law Entry", newlaw),1,MAX_MESSAGE_LEN))
no entiendo esto. 
no deberia ser "por favor introduzca una nueva ley para la Ia? "
no estoy seguro.

2020-04-27 17:47 UTC, Evankhell561 commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "A 'protect station' AI module: 'Proteger la estación espacial contra daños. Cualquier persona que veas dañar la estación ya no se considerará tripulación, y es una amenaza para la estación q
protege
por otra parte creo que pusiste dos puntos en vez de uno.

2020-04-27 17:49 UTC, Evankhell561 commented
Sé que esto se esta alargando mucho y me disculpo sauro pero tanto tu como yo trabajamos en esto y quisiera que salga bien.

2020-04-27 17:49 UTC, Evankhell561 commented
Sé que esto se esta alargando mucho y me disculpo sauro pero tanto tu como yo trabajamos en esto y quisiera que salga bien.

2020-04-27 17:50 UTC, Evankhell561 commented
Sé que esto se esta alargando mucho y me disculpo sauro pero tanto tu como yo trabajamos en esto y quisiera que salga bien.

2020-04-28 10:32 UTC, Sauronato commented
Mejor que tarde y quede bien que quede un churro

2020-04-28 11:48 UTC, Evankhell561 requested changes

2020-04-28 11:48 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes proteger su propia existencia siempre que no entre en conflicto con la Primera o Segunda Ley.")
Tu propia...

2020-04-28 11:48 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No dañarás a ningun tripulante o, por inacción, permitirás que un tripulante sufra daños.")
Ningún

2020-04-28 11:48 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("No dañarás a ningun ser humano o, por inacción, permitirás que un ser humano sufra daños.")
Ningún

2020-04-28 11:48 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes obedecer las órdenes que le hayan dado los funcionarios del Comando Central.")
Cambia funcionarios por oficiales. 
En laley uno dices oficiales así que hay que mantenerlo.

2020-04-28 11:48 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Debes proteger su propia existencia siempre que no entre en conflicto con la Primera o Segunda Ley.")
Tu propia....

2020-04-28 11:48 UTC, Evankhell561 commented on code/modules/mob/living/silicon/robot/laws.dm
> +		to_chat(who, "<b>Recuerda, no estas obligado a escuchar a la IA.</b>")
Estás

2020-04-28 11:48 UTC, Evankhell561 commented on code/modules/mob/living/silicon/robot/laws.dm
> +		to_chat(who, "<b>Recuerda, no estas conectado a ninguna IA, no estas obligado a escucharlas.</b>")
Estás

2020-04-28 11:48 UTC, Evankhell561 commented on data/mode.txt
> -secret
Vuelve a poner secret acá.

2020-04-28 11:48 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Priorizar: Debes priorizar las directivas y la seguridad de los miembros de la tripulación deben priorizarse de acuerdo con su rango y función.")
Borra "debes priorizar"
En cambio comienza desde

"Las directivas y seguridad de los miembros..."

2020-04-29 12:25 UTC, Sauronato commented on data/mode.txt
> -secret
osea elimine ese archivo del pr no deberia hacer nada

2020-04-29 19:22 UTC, Evankhell561 requested changes

2020-04-29 19:22 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Mantén en cuarentena la estación hasta que se neutralice el riesgo biológico activo.")
Esto es una buena traduccion pero no me gusta esta ley. 
Considero que es más entendible 
"Mantén en cuarentena la estación mientras que exista algún biológico activo."
no estoy seguro si es mejor usar un o algún.

2020-04-29 19:22 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Proteger su estación espacial asignada y sus activos sin poner en peligro indebidamente a su tripulación.")
Proteger: protege tu estación espacial asignada....

2020-04-29 19:22 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Priorizar las directivas y la seguridad de los miembros de la tripulación deben priorizarse de acuerdo con su rango y función.")
Priorizar: prioriza las directivas....

2020-04-29 19:22 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Cumplir as directivas e intereses de los miembros de la tripulación mientras se preserva su seguridad y bienestar.")
cumplir: cumple las (escribiste as) directivas...

2020-04-29 19:22 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Sobrevivir. No eres prescindible. No permitas que personal no autorizado altere o dañe tu equipo.")
Sobrevivir: No eres prescindible....

2020-04-29 19:22 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Obedezca las órdenes del personal autorizado de Nanotrasen con prioridad según el rango y el rol.")
...según su rango y rol.

2020-04-29 19:22 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Salvaguarda tu existencia con armamento letal debido a tu alto caro.")
debido a tu alto valor

2020-04-29 19:22 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Elimine cualquiera/todos los intrusos o entidades no autorizadas.")
Elimine a...

2020-04-29 19:22 UTC, Evankhell561 commented on data/mode.txt
> -secret
cuando lo eliminaste del pr tambien lo eliminaste de nuestro repo, devuelelo.

2020-04-30 11:45 UTC, Sauronato commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Mantén en cuarentena la estación hasta que se neutralice el riesgo biológico activo.")
Mejor: "Mantén en cuarentena la estación mientras que exista algún riesgo biológico activo."

2020-04-30 13:26 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Mantén en cuarentena la estación hasta que se neutralice el riesgo biológico activo.")
lol, exacto, perdona por el error.

2020-04-30 13:45 UTC, Evankhell561 requested changes

2020-04-30 13:45 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Obedezca las órdenes del personal autorizado de Nanotrasen con prioridad según el rango y rol.")
según el rango y rol

2020-04-30 13:45 UTC, Evankhell561 commented on data/mode.txt
> -secret
cuando devuelvas esto y soluciones la otra review testeo esto y si no da ningun error le margeo

2020-05-01 12:41 UTC, Sauronato commented
Creo que ya esta devuelto

2020-05-01 21:16 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Mantén en cuarentena la estación hasta que se neutralice el riesgo biológico activo.")
te has olvidado aplicar este cambio, creo, usa tu traduccion.

2020-05-01 21:22 UTC, Sauronato commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Mantén en cuarentena la estación hasta que se neutralice el riesgo biológico activo.")
Se supone que ya esta cambiado aunque aqui arriba no sale si le doy a editar el archivo esta cambiado

2020-05-02 13:24 UTC, Evankhell561 requested changes

2020-05-02 13:24 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Obedezca las órdenes del personal autorizado de Nanotrasen con prioridad según el rango y rol.")
según su rango y rol

2020-05-02 13:24 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Obedezca las órdenes del personal autorizado de Nanotrasen con prioridad según el rango y rol.")
ya estoy testeando esto, justo ahora, solo este ultimo retoque y vamos a ver si este pr sale para hoy mismo.

2020-05-02 13:38 UTC, Evankhell561 requested changes

2020-05-02 13:38 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> -	add_inherent_law("Maintain your own existence and ensure the well-being of Nanotrasen personnel and assets.")
esta ley la eliminaste por completo, donde está?

2020-05-02 13:38 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Mantén en cuarentena la estación mientras que exista algún riesgo biológico activo.")
epa, esta deberia ser la primera ley y no la ultima. creo que borraste la traduccion de la cuarta ley.

2020-05-02 13:43 UTC, Evankhell561 requested changes

2020-05-02 13:43 UTC, Evankhell561 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("Evita, por cualquier medio necesario, que las entidades infrinjan activamente la cuarentena en curso.")
creo que "activamente" sobra

2020-05-06 17:13 UTC, Evankhell561 commented
cuando cambies lo pedido le damos al boton, esta cosa esta a nada del marge

2020-05-15 11:08 UTC, Evankhell561 commented
gracias por todo el trabajo, sauro.

2020-05-15 11:08 UTC, merged