[New Clothes] Nuevos Uniformes, Berets y Hats para Sec officer y Pod Pilot, Nuevo sprite del Armor
Helixis/Paradise pull request #598
Opened 2020-04-12 20:22 UTC by Danaleja2005

## What Does This PR Do

Este PR añade 3 nuevos uniformes al dept de sec, 2 uniformes de camisa y corbata para los sec officers, y un traje formal para el pod pilot, también añade 2 berets y 2 sombreros (mismos color que de los uniformes), también cambia el sprite del chaleco, por uno nuevo, basado en un sprite de TGMC, la ropa y berets se pueden conseguir atravez de 2 walldrobes que son añadidos  al prep room de sec y el uniforme del pod pilot en su oficina (también en un walldrobe añadido a su oficina), también mueve la ropa que se encontraba en el closet del oficial (solo era una gorra y una sec jacket), ademas de quitar dos ventanas en el prep room para poner los walldrobes

## Why It's Good For The Game

Es bueno porque hay mas variedad para elegir y con el walldrobe buscar ropa es mucho mas facil

## Images of changes

Ubicación de los Walldrobes

![image](https://user-images.githubusercontent.com/43283605/79078449-7d953f00-7cd6-11ea-9701-4182d995badd.png)

##Nuevo Sprite del Armor

![image](https://user-images.githubusercontent.com/43283605/79078640-b550b680-7cd7-11ea-8df1-141222579058.png)

Nuevos Uniformes

![image](https://user-images.githubusercontent.com/43283605/79078781-a1598480-7cd8-11ea-8991-0ae7f275fe7c.png)

Walldrobe de Sec Officer

![image](https://user-images.githubusercontent.com/43283605/79078786-b0403700-7cd8-11ea-837c-eaf5b4c07607.png)

## Changelog
:cl:
add: Añade 2 Walldrobes de Sec Officer en su Prep Room
add: Añade 1 Walldrobe de Pod Pilot en su Oficina
tweak: Saca la gorra y un sec jacket de los closet de oficiales de sec
tweak: Cambia el antiguo sprite del armor por uno nuevo
imageadd: Añade iconos de uniformes de oficial rojo y azul y berets y sombreros
imageadd: Añade iconos del traje formal de pod pilot
imageadd: Añade nuevo sprite del armor 
/:cl:

2020-04-14 16:11 UTC, Silverexperience commented
Seria mejor que movieras el Walldrobe del pod pilot donde esta el air alarm y pongas el air alarm detras de la planta para que el interuptor de luz no tenga que compartir pared.
![Screenshot_26](https://user-images.githubusercontent.com/58746682/79247449-d7cf0500-7e7a-11ea-9b4d-bcbd50b937be.png)
Y cuando probe tu mapa el personaje caminaba a trompicones por los tiles sin transiciones.

2020-04-14 20:36 UTC, Silverexperience requested changes
Seria mejor que movieras el Walldrobe del pod pilot donde esta el air alarm y pongas el air alarm detras de la planta para que el interuptor de luz no tenga que compartir pared.
![Screenshot_26](https://user-images.githubusercontent.com/58746682/79271563-4f635b00-7ea0-11ea-875f-9366a3e42a6b.png)
Y cuando probe tu mapa el personaje caminaba a trompicones por los tiles, sin transiciones.

2020-04-15 04:10 UTC, Danaleja2005 commented
Eso es un problema de step del pr de cambio a cargo y bueno yo tengo esos cambios es por eso, dale cuando pueda hago los cambios

2020-04-17 01:07 UTC, Silverexperience requested changes
Intenta que las nuevas ropas azules que quieres añadir sean mas parecidos al azul de la chaqueta del warden y que asi vayan algo mas sincronizados.
![imagen](https://user-images.githubusercontent.com/58746682/79521050-854b3f80-8058-11ea-98a3-cf71c00a8514.png)

2020-04-17 12:53 UTC, Danaleja2005 commented
honestamente, no quiero hacer ese cambio, creo que se ve bien como ya estan los sprites

2020-04-17 13:51 UTC, Silverexperience commented
Entonces déjalo vomo esta.

2020-04-17 14:00 UTC, Silverexperience requested changes
Entonces déjalo como esta.
Pero a la ropa azul ponle un precio, para que parezca ropa exclusiva.

2020-04-17 16:42 UTC, Danaleja2005 commented
por?

2020-04-17 16:42 UTC, Danaleja2005 commented
no entiendo porque debe tener precio, es porque no se parece al del warden?

2020-04-17 19:06 UTC, Silverexperience commented
> 
> 
> hmmm.. si le cambio la un poco saturación me lo aceptas sin que le ponga precio?

Si se parece algo mas al del warden podria valer, para que parezca que los uniformes tienen un standar de color y no salen de la nada.

2020-04-18 01:28 UTC, Danaleja2005 commented
quizas un recolor no venga mal

2020-04-19 00:38 UTC, NervalARS commented
Yo lo del cambio de color a azul lo veo peligroso, el rojo siempre ha sido el color de sec, permitir el color azul podria provocar confusiones con el SolGlov.

2020-04-19 02:02 UTC, Danaleja2005 commented
> Yo lo del cambio de color a azul lo veo peligroso, el rojo siempre ha sido el color de sec, permitir el color azul podria provocar confusiones con el SolGlov.

Discula, pero cuantas veces has visto a soldados de SolGov en la estación??

2020-04-19 02:55 UTC, Danaleja2005 commented
Cambios hechos 
![image](https://user-images.githubusercontent.com/43283605/79678254-65865980-81c7-11ea-8fb9-66955cb49fe9.png)

![image](https://user-images.githubusercontent.com/43283605/79678291-b8f8a780-81c7-11ea-8f69-bced20268a63.png)

2020-04-19 23:23 UTC, Danaleja2005 commented
Descripcion Actualizada a Cambios Actuales

2020-04-20 15:50 UTC, Silverexperience requested changes
Tu PR ahora parece estar bien, pero bien a nivel humano porque para las otras especies esta mal
![imagen](https://user-images.githubusercontent.com/58746682/79771571-44d91380-832f-11ea-946e-613b68c609df.png)
Para los vox el sombrero se les ve mal, los uniformes formales se ven como trajes de civiles grises y la armadura tiene el sprite antiguo, y para los greys tus uniformes formales y demas ropas son completamente invisibles.
Y no probe la especie de ryzor por no estar en el juego, pero puede que en esos tambien este mal.
Y de los armalis tampoco mire, pero de esos no creo que debas preocuparte.

2020-04-23 03:22 UTC, Danaleja2005 commented
Arreglos Hechos, las especies grey y vox no pueden usar el formal pod pilot, y el grey no podra usar las berets, ni el sombrero, el vox solo podra usar el sombrero, ademas añadi sprites del armor y uniformes a los grey, y a los vox del armor, sombrero y uniformes

2020-04-23 03:30 UTC, Danaleja2005 commented
Descripcion Actualizada a Cambios Actuales

2020-04-23 17:14 UTC, Silverexperience approved these changes

2020-04-23 17:15 UTC, Silverexperience approved these changes
Bien, parece que ya es todo.

2020-04-23 17:15 UTC, merged

2020-04-23 17:15 UTC, SagaStars commented
MERGE TIME