Nuevas leyes para sinteticos
Helixis/Paradise pull request #602
Opened 2020-04-13 12:39 UTC by Sauronato

## What Does This PR Do

Añade dos nuevas leyes para los sinteticos, AntiEoC y Commander, estas consisten en una ley centrada en eliminar amenazas EoC de la estación y Commander un crewsimov pero de comando
## Why It's Good For The Game

Añade mas variedad de leyes al juego y ademas estas han sido creadas por la comunidad
## Images of changes

![commander](https://user-images.githubusercontent.com/54809089/79121004-919f7600-7d94-11ea-8e15-a8df9f602581.PNG)(Las leyes de esta estan cambiadas)
![antieoc](https://user-images.githubusercontent.com/54809089/79121010-93693980-7d94-11ea-8dd9-0985e0105f02.PNG)

## Changelog
:cl:
add: Anti-EoC y Commander setlaws
/:cl:

2020-04-13 12:40 UTC, Sauronato commented
Se me olvido añadir que como no puedo usar el mapmerge estas por ahora solo se podran tener creandolas en el protolathe

2020-04-14 01:05 UTC, Evankhell561 requested changes

2020-04-14 01:05 UTC, Evankhell561 commented on code/HISPANIA/datums/ai_law_sets.dm
> +	add_inherent_law("Se ha de eliminzar la amenaza hostil lo m�s rapido posible. Sin tener en cuenta los posibles gastos de la estaci�n que puedan suponer.")
Elimina a...

2020-04-14 01:05 UTC, Evankhell561 commented on code/HISPANIA/datums/ai_law_sets.dm
> +	add_inherent_law("Eliminar la amenaza tiene prioridad sobre tu propia vida.")
Bien escrito esto puede ir en la ley 1.

2020-04-14 01:05 UTC, Evankhell561 commented on code/HISPANIA/datums/ai_law_sets.dm
> +	add_inherent_law("Cualquier actividad sospechosa, por �nfima que sea, sera motivo de llevarse a seguridad.")
Esto no se entiende bien.

2020-04-14 01:05 UTC, Evankhell561 commented on code/HISPANIA/datums/ai_law_sets.dm
> +	add_inherent_law("No da�ar�s a ningun miembro de comando o, por inacci�n, permitir que un tripulante sufra da�os.")
Tripulante?

2020-04-14 01:05 UTC, Evankhell561 commented on code/HISPANIA/datums/ai_law_sets.dm
> +	selectable = 1
Que haceesta variable?

2020-04-14 01:05 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/AI_modules.dm
> +/datum/design/corporate_module
Esto mo va en este dm

2020-04-14 01:05 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/AI_modules.dm
> +/datum/design/corporate_module
Este tampoco

2020-04-14 19:17 UTC, Sauronato commented on code/HISPANIA/datums/ai_law_sets.dm
> +	selectable = 1
hace se se pueda meter en la ia, la tienen todos los setlaws

2020-04-14 19:17 UTC, Sauronato commented on code/HISPANIA/game/objects/items/weapons/AI_modules.dm
> +/datum/design/corporate_module
Ahora los muevo :D

2020-04-16 01:31 UTC, Evankhell561 requested changes

2020-04-16 01:31 UTC, Evankhell561 commented on code/HISPANIA/datums/ai_law_sets.dm
> +	add_inherent_law("Los no reconocidos como tripulacion han de ser eliminados inmediatamente, y su cuerpo se llevara a seguridad donde los heads decidirán su futuro.")
1. Esto parece un sop y no una ley. 2. Con esto, si no hay sec obligas a la ia a custodiar el cadáver toda la partida.

2020-04-16 01:31 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/AI_module_designs.dm
> +//Designs
Quita la mayuscula en el nombre de este dm.

2020-04-29 18:43 UTC, Evankhell561 requested changes

2020-04-29 18:43 UTC, Evankhell561 commented on code/HISPANIA/datums/ai_law_sets.dm
> +	add_inherent_law("En caso de que se genere una amenaza contra el personal de comando, esta debe ser neutralizada lo mas rapido posible.")
esto es realmente necesario? con las tres primeras leyes ya cubre la proteccion de los heads, solo impulsa a la ia a acabar con todo lo que ella considere una amenaza. Digo esta bien si la idea es que la ia este forzada a jugar agresiva pero no sé si es la intención. (necesario no es)

2020-04-29 18:43 UTC, Evankhell561 commented on code/HISPANIA/datums/ai_law_sets.dm
> +	add_inherent_law("Debes obedecer las órdenes que te dan los miembros de comando, excepto cuando tales órdenes entren en conflicto con la Primera Ley.")
que te den...
den, futuro.

2020-04-29 18:43 UTC, Evankhell561 commented on code/HISPANIA/datums/ai_law_sets.dm
> +	add_inherent_law("No dañarás a ningun miembro de comando o, por inacción, permitir que un miembro de comando sufra daños.")
ningún

2020-04-29 19:26 UTC, Evankhell561 requested changes

2020-04-29 19:26 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/AI_modules.dm
> +	origin_tech = "programming=5;materials=5"
puedes bajar esto a 4 o subir el reqtech a seis en el diseño

2020-04-29 19:26 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/AI_modules.dm
> +	origin_tech = "programming=5;materials=5;combat=5"
puedes bajar esto a 4 o subir el reqtech a seis en el diseño

2020-04-29 19:26 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/ai_module_designs.dm
> +	req_tech = list("programming" = 5, "materials" = 5)
esto esta bien pero el origin tech es igual a este lo que no esta mal si ambos fueran nivel 4 pero no puedo tener un diseño cuyo requerimiento sea igual a su origen de nivel 5 o superior (sube esto o baja el origin tech

2020-10-19 02:25 UTC, closed without merging