berets de varios colores por 300... )¿?
Helixis/Paradise pull request #603
Opened 2020-04-13 22:06 UTC by N0thy

## What Does This PR Do
añade varios berets de diferentes colores al xtra
## Why It's Good For The Game
Si no te gusta el beret que llevas, solo por 300 puedes llevarte otro igual... ¡pero de diferente color!
## Images of changes
![image](https://user-images.githubusercontent.com/53350410/79165540-a0614980-7de3-11ea-823f-f4a513bcf201.png)
![image](https://user-images.githubusercontent.com/53350410/79165562-ace5a200-7de3-11ea-927b-3dcbbed217ae.png)

## Changelog Nothing
:cl:
add: berets de diferentes colores al Xtra
/:cl:

2020-04-13 22:07 UTC, N0thy commented
Referente al Green beret, yo no le puse mayúscula aaaaaaaaa

2020-04-14 20:31 UTC, Silverexperience requested changes
Deberias meter los berets donde se encuentran los demas berets para tener un cierto orden.

2020-04-14 22:20 UTC, Silverexperience commented
Y seria mejor que antes de mover los berets esperes al PR de vendigs de spircen para no tener conflictos luego con el hatlord.

2020-04-14 22:27 UTC, Silverexperience commented
Tambien, si solo existen esos berets, podrias hacer tu unos propios berets de más colores para que haya mas variedad que esos 4 y el rojo.

2020-04-14 23:08 UTC, Silverexperience commented
Spircen puso los berets a 100 creditos, seria mejor que para que todos tengan el mismo precio pusieras 100 tambien, solo quizas si añades algun beret con colores especiales podrias aumentarle algo el precio.

2020-04-25 19:51 UTC, Spircen commented
Bueno nos confirmaron que dejaras de trabajar en tus PR así que procederé a cerrarlos.

2020-04-25 19:51 UTC, closed without merging