Dorime version jojos, el renacimiento.
Helixis/Paradise pull request #615
Opened 2020-04-18 22:53 UTC by Silverexperience

## What Does This PR Do
Añade un holoparasito al capellan y unas cartas del tarot.

**La carta del tarot divina**: Una carta del tarot, que solo puede ser usado por el capellan, para llamar a fantasmas a ser su holoparasito sagrado, si no eres capellan te hace daño al intetar usarlo.
**El holoparasito**: Un holoparasito solamente del capellan con un sprite unico, que no hace daño pero tiene bastante resistencia, pudiendo servir como escudo. Puede atacar a los revenant ademas de quitar runas y santificar el agua.Tiene poderes de curacion pero solo a la gente bendecida y despues de 5 curaciones tiene un cooldown de 5 minutos.

PD: El Holoparasito esta a medio probar por la falta de dos jugadores en el server privado.
Disculpen las molestias.

## Why It's Good For The Game
Mas variedad de cosas para el capellan, para que esta gente pueda inventarse aun mas religiones y no veamos la tipicas religiones sangrientas que se copian de Nar'sie.

## Images of changes
### `Carta del tarot del capellan`
![imagen](https://user-images.githubusercontent.com/58746682/78171327-92f7a700-7454-11ea-9712-835273dafe95.png)
### `Carta del tarot del capellan utilizada por el capellan`
![imagen](https://user-images.githubusercontent.com/58746682/78171421-af93df00-7454-11ea-99d4-0baa64fb701e.png)
### `Carta del tarot del capellan utilizada por alguien no capellan`
![imagen](https://user-images.githubusercontent.com/58746682/78171472-c5a19f80-7454-11ea-91ee-96c93690be44.png)
### `Holoparasito del capellan`
![imagen](https://user-images.githubusercontent.com/58746682/78171540-e10caa80-7454-11ea-96f9-50589de87507.png)
![imagen](https://user-images.githubusercontent.com/58746682/78171575-ef5ac680-7454-11ea-8606-12146c592d7e.png)
### `Nuevo objeto en el null rod del capellan`
![imagen](https://user-images.githubusercontent.com/58746682/78171736-35178f00-7455-11ea-921a-21db2ce68244.png)
### `Holoparasito quitando runa`
![imagen](https://user-images.githubusercontent.com/58746682/78192851-4ecacd80-7479-11ea-956e-ec6d6f835897.png)
![imagen](https://user-images.githubusercontent.com/58746682/78192880-61450700-7479-11ea-897c-0edf1d7dd89d.png)
### `Holoparasito matando un revenant`
![imagen](https://user-images.githubusercontent.com/58746682/78197239-0ca78900-7485-11ea-90f7-82c855a24e2b.png)
### `Holoparasito brillando amarillo`
![imagen](https://user-images.githubusercontent.com/58746682/78273848-ab78c780-750f-11ea-8c3e-9d23b9fcd9e4.png)
### `Holoparasito bendiciendo agua`
![imagen](https://user-images.githubusercontent.com/58746682/78274028-e549ce00-750f-11ea-96b3-871050353ac4.png)

## Changelog
:cl:
add: Holoparasito para el capellan
imageadd: Sprite del holoparasito y su carta.
/:cl:

2020-04-29 22:37 UTC, Ume-D commented
Faltó la foto del holoparasito en sus vacaciones

2020-10-16 16:30 UTC, Evankhell561 requested changes

2020-10-16 16:30 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/holyparasite.dm
> +	if(user.mind.isholy == FALSE)
if(!user.mind.isholy)

2020-10-16 16:30 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/holyparasite.dm
> +	if(used == TRUE)
if(used)

2020-10-16 16:30 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/holyparasite.dm
> +	var/mob/dead/observer/theghost = null
var/mob/dead/observer/theghost

2020-10-16 16:30 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/holyparasite.dm
> +	var/mob/living/simple_animal/hostile/guardian/G = /mob/living/simple_animal/hostile/guardian/holy
Este code no debería funcionar.

2020-10-19 02:25 UTC, closed without merging