Balance MouthCover(?) -> Cant eat or drink
Helixis/Paradise pull request #616
Opened 2020-04-19 02:24 UTC by Spircen

## What Does This PR Do
Agrega una validación en la cual si tu boca esta cubierta no puedes comer o beber. Esto no aplica para vox o plasmaman por razones de balance a la par que los parches tampoco son afectados. 

## Why It's Good For The Game
Me parece un balance considerablemente justo, esto se hace a partir del uso de las FLAGS que posee la ropa esto quiere decir que si desajustas una mascara obviamente te dejara comer en cuanto la retirar de tu rostro. Haciendo que esa funcionalidad tenga algo de uso. No, esto no quiere decir que si tienes un cigarro en la boca no puedes comer. 

Referente a la pregunta de ¿Y los spacesuits por que no entran? Pues es facil, aqui hay todo un archivo entero de una mision de [Apollo 15](https://www.hq.nasa.gov/alsj/alsj-DrinkFood.html) donde muestra un hardsuit no bloquea la capacidad de beber o comer.

## Images of changes

               Vox y Plasmaman pueden comer sin problemas y ser alimentados
![image](https://user-images.githubusercontent.com/46639834/79677758-256caa00-81ba-11ea-8c21-dd47b866e650.png)

                                                         Sad Boy
![image](https://user-images.githubusercontent.com/46639834/79677772-43d2a580-81ba-11ea-9a7a-6233b219396c.png)

## Changelog
:cl:
tweak: MouthCover -> Cant eat or drink
/:cl:

2020-04-19 02:41 UTC, Evankhell561 commented
Uhm, osea que si tienes algo que te cubra la boca no puedes comer. Me gusta este cambio, solo que no lo veo como si fuera algo de balance, yo lo veia más como un tweak, un cambio vaya pero supongo que es un tecnicismo.

2020-04-19 02:42 UTC, Spircen commented
Igual ya no existe el tag de balance dentro del changelog 😢

2020-04-19 02:43 UTC, Evankhell561 commented
> Igual ya no existe el tag de balance dentro del changelog

Yo aun lo uso, aun sirve en el hispachangelog. La diferencia entre uno y otro es poca realmente.

2020-04-19 02:46 UTC, Spircen commented
Solamente olvide el cambiar el head a weak_mask la propiedad que tiene. Las mascaras de los vox van ahi, no como los cascos de los plasmamen

2020-04-19 03:28 UTC, SoulAnima commented
¿Que va a ocurrir con las pastillas?

2020-04-19 04:27 UTC, Spircen commented
Se puede agregar al list de cosas que pasan esta condicional pero a mi parecer me agrada mas la idea de que tengan que retirar una mascara para poder consumir la pastilla.

2020-04-19 14:59 UTC, Evankhell561 requested changes
si pudieras decir como haces que ignore a los vox y plasmaman estaria bien.
Edit: Ya lo vi.

2020-04-19 15:18 UTC, SoulAnima commented
> Se puede agregar al list de cosas que pasan esta condicional pero a mi parecer me agrada mas la idea de que tengan que retirar una mascara para poder consumir la pastilla.

Lo digo mas que nada por que me parece que queda muy antinatural tener que sacarle la mascara de anestesia a alguien en medio de una operación o desfribilacion para curarle oxyloss/daño cerebral o de lo contrario tener que moler medicamentos que vienen por default en pastillas

2020-04-19 16:18 UTC, SagaStars commented
> Lo digo mas que nada por que me parece que queda muy antinatural tener que sacarle la mascara de anestesia a alguien en medio de una operación o desfribilacion para curarle oxyloss/daño cerebral o de lo contrario tener que moler medicamentos que vienen por default en pastillas.

No lo veo mas antinatural todo lo contrario antes era antinatural XD, ahora se tendria que moler los medicamentos y inyectarselos a los pacientes en caso de que esten con mascarilla lo que en mi opinion le da una nueva complejidad a medbay.

2020-04-19 16:29 UTC, SoulAnima commented
> > Lo digo mas que nada por que me parece que queda muy antinatural tener que sacarle la mascara de anestesia a alguien en medio de una operación o desfribilacion para curarle oxyloss/daño cerebral o de lo contrario tener que moler medicamentos que vienen por default en pastillas.
> 
> No lo veo mas antinatural todo lo contrario antes era antinatural XD, ahora se tendria que moler los medicamentos y inyectarselos a los pacientes en caso de que esten con mascarilla lo que en mi opinion le da una nueva complejidad a medbay.

Me parece complicar todo más por nada, de por si esas cosas requieren reacción rápida

2020-04-19 16:56 UTC, Evankhell561 commented
> Me parece complicar todo más por nada, de por si esas cosas requieren reacción rápida


Y es entendible pero si tu argumento es este no digas que no te gusta porque es antinatural.

2020-04-19 17:52 UTC, SoulAnima commented
> > Me parece complicar todo más por nada, de por si esas cosas requieren reacción rápida
> 
> Y es entendible pero si tu argumento es este no digas que no te gusta porque es antinatural.

Me exprese mal entonces, perdón

2020-04-20 01:26 UTC, Diegoflores31 commented
@SagaStars  bro medbay a las justas puede con su propia existencia y les vas a malograr mas la vida xd

2020-05-02 02:01 UTC, Spircen commented
Haha funny

2020-05-02 02:01 UTC, closed without merging