Fix Genetista Hispania
Helixis/Paradise pull request #623
Opened 2020-04-20 09:25 UTC by Spircen

## What Does This PR Do
Evita que el genetista tenga acceso a research y pueda contar con la rama de conocimientos que eso conlleva. 

## Why It's Good For The Game
Con los updates de accesos a variables globales algunos cuantos se nos pasaron, me impresiono que hasta el momento nadie reporto este cargo como erroneo. Actualmente en base a las reglas el genetista podría ejercer en la reparación de IPCs en base a las reglas. Recordemos que el genetista de hispania pertenece únicamente a Medbay, no a ciencias. 

## Images of changes

                                Sad Geneticist
![image](https://user-images.githubusercontent.com/46639834/79736036-d0ff2280-82be-11ea-93e5-07d9ef2b8dd2.png)

## Changelog
:cl:
fix: Flags de Genetista
/:cl:

2020-04-20 11:16 UTC, Evankhell561 requested changes

2020-04-20 11:16 UTC, Evankhell561 commented on code/game/jobs/job/medical.dm
> -	minimal_access = list(ACCESS_MEDICAL, ACCESS_MORGUE, ACCESS_GENETICS, ACCESS_RESEARCH, ACCESS_MAINT_TUNNELS)
Por qué modificas esto? No veo que tengan que ver con ciencias

2020-04-20 11:16 UTC, Evankhell561 commented on code/game/jobs/jobs.dm
> +	//"Geneticist",	//Nosotros no tenemos genetista de ciencias por balance
Esto sigue en med, verdad?

2020-04-20 11:16 UTC, Evankhell561 commented on code/game/jobs/job/medical.dm
> +	//department_flag = JOBCAT_MEDSCI
Creo que todos los jibs deben tener esta variable. Asuguerate de que tenga la misma que los docs

2020-04-20 21:42 UTC, Spircen commented on code/game/jobs/job/medical.dm
> +	//department_flag = JOBCAT_MEDSCI
Si, debo cambiar eso.

2020-04-20 21:42 UTC, Spircen commented on code/game/jobs/job/medical.dm
> -	minimal_access = list(ACCESS_MEDICAL, ACCESS_MORGUE, ACCESS_GENETICS, ACCESS_RESEARCH, ACCESS_MAINT_TUNNELS)
ACCESS_RESEARCH literalmente dice esto.

2020-04-20 21:43 UTC, Spircen commented on code/game/jobs/jobs.dm
> +	//"Geneticist",	//Nosotros no tenemos genetista de ciencias por balance
Si, está en el mismo archivo. Lo puedes abrir y ver.

2020-04-20 23:59 UTC, Evankhell561 requested changes

2020-04-20 23:59 UTC, Evankhell561 commented on code/game/jobs/job/medical.dm
> +	minimal_access = list(ACCESS_MEDICAL, ACCESS_CHEMISTRY, ACCESS_MAINT_TUNNELS, ACCESS_MINERAL_STOREROOM)
spir, me refiero a esto, quitas el access ACCESS_RESEARCH, bien. pero por qué quitas el access_genetics y lo cambias por el ACCESS_CHEMISTRY?

2020-04-21 02:10 UTC, Spircen commented on code/game/jobs/job/medical.dm
> +	minimal_access = list(ACCESS_MEDICAL, ACCESS_CHEMISTRY, ACCESS_MAINT_TUNNELS, ACCESS_MINERAL_STOREROOM)
Ah eso es fácil de explicar, la puerta que no tenemos en hispania pero existe en paradise la cual enlaza genetica y ciencias utiliza ese acceso. Minimal acces reponde a la pregunta "¿Tienes acceso a X y Y?" mientras que access solamente responde a la pregunta "¿Tienes acceso a X?"

2020-04-21 02:10 UTC, Spircen commented on code/game/jobs/job/medical.dm
> +	minimal_access = list(ACCESS_MEDICAL, ACCESS_CHEMISTRY, ACCESS_MAINT_TUNNELS, ACCESS_MINERAL_STOREROOM)
Pasa lo mismo para la morgue y robotica.

2020-04-21 18:23 UTC, merged