Los escudos empujan en disarm :0 + Re-sprite al escudo de sec (RIOT).
Helixis/Paradise pull request #625
Opened 2020-04-20 19:50 UTC by SagaStars

- Nueva sprite para el riot shield.
- Los escudos ahora son capaces de empujar a mobs, esto solo se puede efectuar en `disarm_intent`. Empujan 1 tile hacia atras y no se puede efectuar si el mob esta incapacitado o en rest.

### Why It's Good For The Game
- La sprite actual no pegaba en nada con el riot suit, asi que pense que estaria bien de cambiarla también, ademas queda mas en claro que el escudo cubre un 49% osea la mitad del cuerpo no como antes que solo te protegia un brazo.
- El riot shield esta hecho para control de masas, que seria mejor que darles la capacidad de echar a la gente atrás empujando con el? Ahora podemos montarnos nuestra buena linea de defensa y hacer retroceder a los civiles, Gloria a Nanotrasen.

### Images of changes
### Buen samaritano protege al navy de ronda de una woopsie doopsie araña.
----
![image](https://user-images.githubusercontent.com/55407528/79792763-76e17a00-831d-11ea-8349-25792230f4f5.png)
----
### Nueva sprite para el riot shield.
----
![image](https://user-images.githubusercontent.com/55407528/79792885-ae502680-831d-11ea-95c0-97449066fadc.png)
![image](https://user-images.githubusercontent.com/55407528/79792896-b1e3ad80-831d-11ea-9b38-0f8506553a85.png)
![image](https://user-images.githubusercontent.com/55407528/79792906-b740f800-831d-11ea-85a8-c7c9eed37096.png)

## Changelog
:cl:
add: Nueva sprite para el riot shield.
tweak: Los escudos ahora son capaces de empujar con disarm a mobs.
/:cl:

2020-04-22 01:50 UTC, Evankhell561 commented
Hace daño cuando empuja?

2020-04-22 01:54 UTC, Evankhell561 requested changes
Me gusta esto de empujar civiles, de resto solo voy a revisar que todo esté en orden.

2020-04-22 17:11 UTC, SagaStars commented
Bueno, no hace daño a menos que el civil choque con una pared.

2020-04-25 23:10 UTC, Spircen commented
Todo en orden, solo resuelve los conflictos de el dmi y lo mergeo. Como detalle es que si empujas en diagonal no te empuja en diagonal te empuja en X o Y no existe Z.

2020-04-26 19:34 UTC, SagaStars commented
Se supone que ya arregle el conflicto. Y no puedo darle al boton de resolve conflicts tho.

2020-04-26 19:38 UTC, Spircen commented
Copia y pega los archivos marcados en conflicto de tu branch master a tu branch de este PR da un commit luego de eso agrega tus nuevos sprites y da otro commit. Eso debería solucionarlo.

2020-04-26 20:41 UTC, SagaStars commented
Me van a dar algo estos conflictos

2020-04-26 20:43 UTC, SagaStars commented
Nos ahorramos problemas y vuelvo a hacer el PR?

2020-04-26 21:28 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/weapons/shields.dm
> +/obj/item/shield/attack(mob/target, mob/living/user)
Hay hay algo que no habia notado, este code no solo va a afectar a los escudos riot sino a todos los escudos. No veo a un escudo de enetgia empujando a nadie. Deberias añadir tambien una variable, algo como "empuje = TRUE" y que este proc verifique si esa variable está activa o no para decidir si empuja.

2020-04-26 22:35 UTC, Evankhell561 commented
> Nos ahorramos problemas y vuelvo a hacer el PR?

como veas

2020-04-26 22:46 UTC, SagaStars commented
Si.

2020-04-26 22:46 UTC, closed without merging