[wip] RnD rebalance v2
Helixis/Paradise pull request #627
Opened 2020-04-21 11:16 UTC by Evankhell561

## What Does This PR Do
1. Reduce la cantidad de materiales por shett en un 25%
3. Aumentará la cantidad de materiales iniciales en robotica mecainica y rnd para que el inicio de la ronda permanezca igual.
2. cambios varios para compensar esta perdida con otra cosa, por ejemplo reducir los tiempos muertos de las consolas de RnD.

## Why It's Good For The Game
Porque siempre me dicen que un solo minero da abasto para cubrir todas las necesidades de materiales de la estcion, Esto ayudará a justificar la gran cantidad de mineros que tenemos, y hará que todos tengan que pensarlo dos veces antes de imprimir cosas inecesarias.

## Images of changes

## Changelog
:cl:
tweak: se obtiene menos cantide minerales por shett
tweak: las consolas de rnd son más rapidas
tweak: aumenta la cantidad de minerales iniciales en mecanica, rnd y robotica
/:cl:

2020-04-21 19:32 UTC, Spircen commented
Cursed PR

2020-04-21 19:34 UTC, Evankhell561 commented
> Cursed PR

Nuestro code sabe que esto es un nerf a ciencias y por eso no deja que este pr avance.

2020-04-28 23:03 UTC, Spircen commented on _maps/map_files/hispania/hispania.dmm
> +	step_x = 0;
Los step_x y step_y borra estos dos con el notepad.

2020-05-02 14:12 UTC, Silverexperience requested changes
En los materiales de bananium y tranquillité no deberían dar menos materiales por shett, ya hay bastantes pocos para que ahora sean menos material.

2020-05-02 20:51 UTC, Evankhell561 commented
> En los materiales de bananium y tranquillité no deberían dar menos materiales por shett, ya hay bastantes pocos para que ahora sean menos material.

Estoy deacuerdo contigo e iba a cumplir tu peticion pero para hacerla necesitaria hacer un millon de cambios en el codigo. Además es cierto que es limitado la cantidad de esos materiales pero una vez llegas al asteroide donde estan las naves payaso y mimo, tienes de sobra para toda la partida debido a que tampoco tienen muchos usos en rnd.

2020-10-19 02:25 UTC, closed without merging