Cambios a cargo
Helixis/Paradise pull request #628
Opened 2020-04-21 19:12 UTC by Evankhell561

## What Does This PR Do
1. Los mineros ya no tienen acceso al area de la shttle de cargo ni a los bots de cargo
2. El QM tiene una maquina para despedir a sus subordinados en cargo (aunque sigue sin ser un head)

## Why It's Good For The Game
1. cargo es uno de los depas más usados, y ser minero ic es igual a ser un tecnico de cargo pero con armas. Y eso está mal, entonces ahora los tecnicos tienen la ventaja de tener más accesos que los mineros (estaba pensando en quitarles a los mineros el acceso a maint tambien ya que no veo para que los necesitan, en cambio un tecnico de cargo los puede usar para ir a destrabar sus bots y para tomar una ruta rapida para entregar un pedido pero solo lo haré si lo solicitan)
2. El QM siempre será un chiste si no tiene esto.

## Images of changes

## Changelog
:cl:
add: consola de despidos para el QM (el qm puede despedir)
tweak: Los mineros no pueden entrar a la zona de la shuttle de cargo
tweak: los mineros no controlan los bots de cargo.
/:cl:

2020-04-21 19:18 UTC, Evankhell561 commented
Esto tiene muchas implicaciones, hará que el QM esté atado a las mismas reglas administrativas que los heads por lo que tendrá que poner orden. Luego se supone el qm guarde las reliquias que traen de lavaland pero los mineros tienen sus mismos accesos y su oficina no es lo suficientemente grande así que ahora puede usar el almacen de cargo. También da una razon extra (aunque pequeña para entrar de qm y no de minero).
Esto también lo presento como una alternativa a #622 debido a que consider oque ese pr no toca el fondo del tema.

2020-04-21 19:19 UTC, N0thy commented
Solo diré que en lavaland hay un pequeño maint-
espero no afecte... Aunque tampoco veo mucha razón de quitarselos.

2020-04-21 19:22 UTC, Evankhell561 commented
> Solo diré que en lavaland hay un pequeño maint-
> espero no afecte... Aunque tampoco veo mucha razón de quitarselos.

Ciertamente no hay mucha razon para quitarselos, ya pensé en otra cosa.

2020-04-21 19:56 UTC, DarkWolfKai commented
Sabes, andaba esperando esto ya que las primeras veces entro a paradise ya estaba esto, y solo me pregunte, cuanto mas tiempo tardariamos en implementar lo de los accesos de minero (ya que ahi ni puedes hacer jackshit)

2020-04-25 22:25 UTC, Silverexperience requested changes
No vi ninguna bolsa de mineros con el que aparezca el QM.
Si los mineros no pueden ir dodne la shuttle de cargo, los encargados de cargo no deberian poder ir a lavaland.

2020-04-26 13:20 UTC, Evankhell561 commented
> No vi ninguna bolsa de mineros con el que aparezca el QM.

Ya fixee lo de la bolsa del QM.

> Si los mineros no pueden ir donde la shuttle de cargo, los encargados de cargo no deberian poder ir a lavaland.

La diferencia es que los los tecnicos de cargo podrian ir a la base minera a llevarles algo a los mineros o estos le pueden pedir que trasporten cosas desde su base a la estacion para no tener que dejar de minar y el trabajo de los tecnicos es recibir y trasportar cosas. Tambien podrian dejar pasar a un ingeniero en caso de que haya fallas electricas o estructurales. Como tambien ir a rescatar a un minero muerto en la base.

Adicionalmente casos en los que ya un job tiene más accesos que otro dentro de su propio departamento ya existen y son incluso más abusivos que esto por las razones que expliqué con anterioridad y posterior a este parrafo. 

Otra cosa a tomar en cosideracion es que un tecnico de que intente ir a minar sin herramientas es hombre muerto mientras que un minero con accesos puede hacer el mismo trabajo que un tecnico. Sumado a que los mineros no deberian tener acceso al almacen para que el QM pueda guardar ahi los objetos y reliquias de la lavand.

2020-04-26 16:58 UTC, Silverexperience approved these changes
Bien, tiene mi aprovado.

2020-04-27 19:32 UTC, Spircen approved these changes
Todo funciona hasta donde lo pude testear. Me parece algo raro que solo exista una maquina para despidos pero me imagino bajo que situaciones tendrá utilidad.

2020-04-27 19:32 UTC, merged