Add Protein Bar (Survival Box)
Helixis/Paradise pull request #640
Opened 2020-04-25 22:57 UTC by Spircen

## What Does This PR Do
Agrega una barra de proteína al juego la cual no se puede crear y es un objeto único de las cajas de inicio que proporciona NT al ser parte de la tripulación y como el sindicato también es una agencia que se preocupa por sus agentes ellos también la poseen. 

## Why It's Good For The Game
Desde que se agrego la Hipoglucemia la escalada de muertes causadas ya sea por desconexiones repentinas o gente que se va SSD y no se alimentan bien antes de dormir suben, con esta barra nutritiva proporcionada por Nanotrasen esperamos la causa de muertes baje a la par que mejore el desempeño de la tripulación. 

## Images of changes

                                              PROTEIN
![image](https://user-images.githubusercontent.com/46639834/80292709-f2786800-871d-11ea-9352-bae3d1b2ce83.png)

## Changelog
:cl:
add: Protein Bar
add: Protein Bar a Survival Box 
/:cl:

2020-04-26 00:17 UTC, Evankhell561 commented
En vez de esto preferiria que hicieras un update de las maquinas de comida y revertir los cambios al chocolate y al hot choco, y a la sopa de pollo tambien.

2020-04-26 00:28 UTC, Spircen commented
Si, esto es parte de varios cambios. Esto es solo una parte, planeo agregar mas comidas dentro de las dispensadoras de comida que traigo de BayStation a la par que objetos que ya existen como los flask.

2020-04-26 00:33 UTC, Evankhell561 commented
> Si, esto es parte de varios cambios. Esto es solo una parte, planeo agregar mas comidas dentro de las dispensadoras de comida que traigo de BayStation a la par que objetos que ya existen como los flask.

ahm, tampoco me gustaria que metieras muchas cosas en las dispensadoras becasue el chef y los otros jobs que tienen acceso a comidas que alimenten tengan valor y algo que hacer con ellas.

2020-04-26 00:36 UTC, Evankhell561 requested changes

2020-04-26 00:36 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
> +	junkiness = 25
este es el debuff de las golocinas, no?

2020-04-26 00:36 UTC, Evankhell561 commented on code/game/objects/items/weapons/storage/boxes.dm
> +		new /obj/item/reagent_containers/food/snacks/proteinbar(src)
preferirias que movieras esto y las crowbar a hispania.

2020-04-26 00:36 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
> +/obj/item/reagent_containers/food/snacks/proteinbar
en total cuanto de hambre te da una barra de esto?

2020-04-26 19:55 UTC, Spircen commented on code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
> +	junkiness = 25
Si

2020-04-26 19:56 UTC, Spircen commented on code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
> +/obj/item/reagent_containers/food/snacks/proteinbar
Te llena por completo si estas desnutrido.

2020-04-26 20:00 UTC, Spircen commented on code/game/objects/items/weapons/storage/boxes.dm
> +		new /obj/item/reagent_containers/food/snacks/proteinbar(src)
Listo

2020-04-28 23:52 UTC, merged

2020-04-29 00:52 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
> +	bitesize = 5
no quedamos en 2 mordidas al final?
por qué retiraste el debuff de las golocinas, me parecia un buen aditivo para que la gente no se comiera la barra proteinica a menos que lo necesitara.

2020-04-29 00:53 UTC, Spircen commented on code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
> +	bitesize = 5
Bitesize es cuanto muerdes no cuanto debes morder

2020-04-29 00:55 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/food/foods/other_snacks.dm
> +	bitesize = 5
Bien perfecto, y el debuff de las risas?