[Cambio de Estación Espacial] Cambio de diseño  (Cyberiad a Delta)
Helixis/Paradise pull request #650
Opened 2020-04-29 02:57 UTC by Spircen

## What Does This PR Do
Repara los errores los cuales no hacen que delta sea totalmente operativa para que podamos experimentar este diseño distinto de estación espacial. Varios cambios son aportados por Dana y esperamos ver esta estacion para el update que viene el dia 30 de Abril. 

## Why It's Good For The Game
La variedad de estaciones es una prioridad considerable para poder dar nuevas experiencias a los jugadores, a la par que cambiar los puntos de interes y poder proporcionar distintos ambientes de trabajo a todos los departamentos. 

## Images of changes

En cuanto salga de WIP aqui subo las SS

                               Un dia con cafeina y esto queda

![unnamed](https://user-images.githubusercontent.com/46639834/80556978-011f8300-899b-11ea-8560-b518eede8364.gif)

## Changelog
:cl:
add: Delta Base Station
/:cl:

2020-04-29 11:34 UTC, Evankhell561 commented
![image](https://user-images.githubusercontent.com/49106866/80591425-ae21ec00-89eb-11ea-80cc-315d9c72db51.png)
Esta es un area de reunion en medio del pasillo, no creo que deba estar ahi. Deja las sillas si quieres pero pegalas más a las paredes.

2020-04-29 11:36 UTC, Spircen commented
Eso ni es mio, por mi lo borro. Ahora mismo estoy teniendo una revelacion y sube mi IQ mientras intento entender el sistema de disposals y por que no funciona.

2020-04-29 11:37 UTC, Evankhell561 commented
si no habrá nada más en esta mesa, separa un poco los objetos que estan amontonados la tile del sur.

![image](https://user-images.githubusercontent.com/49106866/80591713-25578000-89ec-11ea-9acd-ccdef3fdfc91.png)

2020-04-29 11:45 UTC, Evankhell561 requested changes
![image](https://user-images.githubusercontent.com/49106866/80591906-82533600-89ec-11ea-8bbc-c0877c768baa.png)
veo una ablative armor en la armeria. Nosotros usamos un ablatibe technimierdas.

2020-04-29 11:49 UTC, Evankhell561 requested changes
veo tiles moradas en med

2020-04-29 12:02 UTC, Evankhell561 requested changes
![image](https://user-images.githubusercontent.com/49106866/80593563-7321b780-89ef-11ea-9060-4d1b1faea270.png)
Estos materiales eran para el autolathe que estaba frente a ciencias, a mi me gustaba el autolathe ahi porque sentia que toda la crew tenia acceso a el. Era algo que lo diferenciaba de hispania. Pero en fin, lo dejaras dentro de cargo esos materiales extra no tienen sentido, o reposicionalos dentro o no los añadas. También la cantidad de materiales dentro de ciencais deberia ser igual de hispania. la ultima vez que revisé no eran iguales en robotica (antes de este pr).

2020-04-29 12:09 UTC, Spircen commented
No sé por qué te desgastas si aún tengo el WIP, la de errores que aún hay que reparar y aún así andas de cherry pick en mi trabajo de casi 6 horas. 

STFU

2020-04-29 12:25 UTC, Evankhell561 commented
> No sé por qué te desgastas si aún tengo el WIP, la de errores que aún hay que reparar y aún así andas de cherry pick en mi trabajo de casi 6 horas.
> 
> STFU

Oh, te autoasignaste el wip, no lo vi. Normalmente lo ponemos en el titulo cuando hacemos un pr, tambien vi que habias dicho que solo pasarias ss cuando termines los cambios. Si aun esta en construccion adelante.

2020-04-29 17:47 UTC, Evankhell561 requested changes

2020-04-29 17:47 UTC, Evankhell561 commented on _maps/delta.dm
> +	#include "map_files\Delta\z2.dmm"
deja el nombre del archivo en minusculas

2020-04-29 17:47 UTC, Evankhell561 commented on _maps/delta.dm
> +	#define MAP_NAME "Hispania"
El nombre se queda como Kerberos. Hispania es nuestro otro mapa

2020-04-29 17:47 UTC, Evankhell561 commented on code/modules/map_fluff/delta.dm
> +	name = "Hispania"
lo mismo aca y en las lineas anteriores, hispania es nuestro otro mapa, no este.

2020-04-29 23:07 UTC, Spircen commented on _maps/delta.dm
> +	#include "map_files\Delta\z2.dmm"
No, eso no pasa travis.

2020-04-29 23:08 UTC, Spircen commented on _maps/delta.dm
> +	#define MAP_NAME "Hispania"
El map name se ocupa para el control de trafico y referencias a station name IC

2020-04-29 23:08 UTC, Spircen commented on code/modules/map_fluff/delta.dm
> +	name = "Hispania"
Lo mismo de arriba

2020-04-30 00:05 UTC, Spircen commented
Aquí están los cambios que habían pedido hace rato, ya que esta cosa pase y en PR que viene subo los cambios extras que pidan aquí que ya se esta sumando mucho en un solo PR 

![image](https://user-images.githubusercontent.com/46639834/80658669-5b2c5100-8a4c-11ea-9ca3-1eb34f879cc4.png)

2020-04-30 00:11 UTC, Evankhell561 commented on _maps/delta.dm
> +	#define MAP_NAME "Hispania"
claro pero antes de esto decia "trafic blabla Kerberos", verdad?

2020-04-30 00:18 UTC, Evankhell561 requested changes

2020-04-30 00:18 UTC, Evankhell561 commented on _maps/delta.dm
> +	#define MAP_NAME "Hispania"
Lo que quiero decir es, este no es el NSS HISPANIA. Este es el NSS Kerberos. Quizá en el futuro haya que butizarlo distinto. But, de momento sigue siendo el NSS Kerbero.

2020-04-30 00:19 UTC, Spircen commented
Literalmente hay unas placas que dicen NSS Hispania por que ese es el nombre tanto del server como la estación.

2020-04-30 00:25 UTC, Evankhell561 commented
> Literalmente hay unas placas que dicen NSS Hispania por que ese es el nombre tanto del server como la estación.

Las placas las acabas de poner. Que nuestro servidor se llame asi no significa que ese nombre deba estar en todos nuestros mapas. El NSS HISPANIA ya existe y no es este. Es una segunda estacion funcional para nuestro servidor, eso sí, no significa que tenga que llamarse igual a la anterior.

2020-04-30 00:34 UTC, Spircen commented
Oh god entonces que quieres ¿Que quite todo y se llame kerberos? Yo quiero que se llame hispania y podamos hacer uso de las placas que tenemos.

2020-04-30 00:47 UTC, Evankhell561 commented
> Oh god entonces que quieres ¿Que quite todo y se llame kerberos? Yo quiero que se llame hispania y podamos hacer uso de las placas que tenemos.

Hacemos uso de las placas que tenemos en el NSS HISPANIA, este no es el NSS hispania. Es el segundo mapa de nuestra comunidad.

2020-05-02 02:01 UTC, Spircen commented
*dabea*

2020-05-02 02:01 UTC, closed without merging