Gordo Franses amara este PR
Helixis/Paradise pull request #655
Opened 2020-05-02 00:52 UTC by SagaStars

![YES](https://user-images.githubusercontent.com/55407528/80851120-a893f400-8bed-11ea-88fa-abe280021e2b.png)

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
fix: fixed a few things
wip: added a few works in progress
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
experiment: added an experimental thingy
/:cl:

2020-05-02 00:59 UTC, SagaStars commented
Changelog listo, le di a ctrl + enter por accidente en vez de shift + enter hehe

2020-05-02 01:45 UTC, Evankhell561 requested changes

2020-05-02 01:45 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/recipes/recipes_candy.dm
> +		/obj/item/reagent_containers/food/snacks/grown/citrus/lemon,
no deberias añadir tambien un beaker, un vaso o algo donde no sé, poner el jugo?

2020-05-02 01:51 UTC, Evankhell561 commented
a ver saguita todo bien pero falta algo, necesitas añadir al pr los recipes de las comidas para que alguien pueda pasar esto a la wii

2020-05-02 02:25 UTC, SagaStars commented on code/HISPANIA/modules/food_and_drinks/recipes/recipes_candy.dm
> +		/obj/item/reagent_containers/food/snacks/grown/citrus/lemon,
EHEM `reagents = list("sugar" = 10, "cornoil" = 5)`

2020-05-02 02:25 UTC, SagaStars commented
> a ver saguita todo bien pero falta algo, necesitas añadir al pr los recipes de las comidas para que alguien pueda pasar esto a la wiki

Mergealo y me pongo con la wiki, es estupido poner las recetas de algo que ni esta en el juego c:

2020-05-02 02:26 UTC, SagaStars commented on code/HISPANIA/modules/food_and_drinks/recipes/recipes_candy.dm
> +		/obj/item/reagent_containers/food/snacks/grown/citrus/lemon,
Si no me entendistes, ya usa un beaker con azucar y aceite de maiz

2020-05-02 02:56 UTC, Evankhell561 commented
> Mergealo y me pongo con la wiki, es estupido poner las recetas de algo que ni esta en el juego c:
Oh, welp, a reptil le pedi lo mismo y me las dio rapido, así es como le gusta a Evan Franses que se hagan las cosas iré a ver su pr, bye.

2020-05-02 03:03 UTC, SagaStars commented
CHANGOS
![image](https://user-images.githubusercontent.com/55407528/80853585-f44f9900-8bff-11ea-97f5-ed89e4392299.png)

2020-05-02 03:22 UTC, SagaStars commented
Ya las recetas estan en la desc del PR evansito

2020-05-02 03:23 UTC, SagaStars commented
> Oh, welp, a reptil le pedi lo mismo y me las dio rapido, así es como le gusta a Evan Franses que se hagan las cosas iré a ver su pr, bye.

Ya esta :pensive:

2020-05-02 04:19 UTC, Evankhell561 commented
Bien saga pero hay conflictos por acá

2020-05-02 20:27 UTC, Evankhell561 requested changes

2020-05-02 20:27 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
> +	slice_path = /obj/item/reagent_containers/food/snacks/cheeseanonnacakeslice
pon algo que identifique que esto es un slice en el path. ejemplo: "/obj/item/reagent_containers/food/snacks/slicecake/cheeseanonnacakeslice"

2020-05-02 20:27 UTC, Evankhell561 commented on code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
> +/obj/item/reagent_containers/food/snacks/cheeseanonnacakeslice
lo mismo de arriba

2020-05-02 20:29 UTC, SagaStars commented on code/HISPANIA/modules/food_and_drinks/food/foods/baked_goods.dm
> +	slice_path = /obj/item/reagent_containers/food/snacks/cheeseanonnacakeslice
Entendido

2020-05-02 23:38 UTC, Evankhell561 commented
Encuentro este pr pasable pero necesitaré una segunda opinion.

2020-05-03 14:35 UTC, SagaStars commented
#661

2020-05-03 14:36 UTC, closed without merging