Slimegalleta
Helixis/Paradise pull request #656
Opened 2020-05-02 21:50 UTC by josesitomartinez

## What Does This PR Do
Agrega algunos de los cores consuming del crossbreeding.
(grey, purple, dark blue, cerulean, pyrite, red)
https://docs.google.com/spreadsheets/d/1RqHaHGT8xs1ucHPGSkuKfXaJa9injnEcItbKhou3C8o/edit#gid=0
## Why It's Good For The Game
Seguimos agregando cosas del crossbreeding, poco a poco lo tenemos listo.

## Images of changes
![image](https://user-images.githubusercontent.com/43261137/80540683-c48e6000-8977-11ea-8280-03081f3dc651.png)

> ### Aca con mis medallas de maestro Pokemon

## Changelog
:cl:
add: Añade algunos cores consuming
/:cl:

2020-05-02 23:05 UTC, Silverexperience requested changes

2020-05-02 23:05 UTC, Silverexperience commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/consuming.dm
> +	M.adjustToxLoss(-5) //To heal slimepeople.
Quitaria el comentario de //To heal slimepeople.

2020-05-02 23:05 UTC, Silverexperience commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/consuming.dm
> +	var/tastemessage = "paint remover"
Añaderia algo para poder quitarte el efecto.

2020-05-02 23:05 UTC, Silverexperience commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/consuming.dm
> +	taste = "fruit jam and cough medicine"
Si cura todos los tipos de daños, no creo que tenga sabor a medicina para la tos.

2020-05-03 01:31 UTC, josesitomartinez commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/consuming.dm
> +	taste = "fruit jam and cough medicine"
yeah chief, no voy a cambiar eso

2020-05-03 01:43 UTC, Silverexperience commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/consuming.dm
> +	taste = "fruit jam and cough medicine"
Bien, si no quieres dejalo así, solo era por si se te ocurria algo mejor que jarabe oara la tos

2020-05-03 01:44 UTC, josesitomartinez commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/consuming.dm
> +	var/tastemessage = "paint remover"
no tengo la capacidad para codear eso

2020-05-03 01:45 UTC, Silverexperience commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/consuming.dm
> +	var/tastemessage = "paint remover"
¿Y nl querías aprender?
Siempre puedes pedirle a alguien que lo haga por ti o te enseñe.
O si quieres miro yo como hacerlo y lo hago en un futuro PR.

2020-05-03 01:53 UTC, josesitomartinez commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/consuming.dm
> +	var/tastemessage = "paint remover"
es que indirectamente le dije a evan para que me enseñara y no me enseño un coño

2020-05-03 01:59 UTC, Silverexperience commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/consuming.dm
> +	var/tastemessage = "paint remover"
Ya dije que si quieres en un futuro lo y lo intenti hacer por mi cuenta, o pide a alguien que te ayude que no sea evan.
Es solo que aunque pueda ser gracioso el estar de un color puede llegar a incomodar si no lo quisiste, y necesitaríamos algo, aunque sea difícil de hacer, que quite los colores.
Podria ser algo simple como darse una ducha, o algo mas complejo como hablar con un payaso sin que te resbale, las posiblidades son grandes. 
Me parece que hay algo que sirve oara quitar efectos dentro del codigo, tampoco se muy bien como funciona esto del color pero es probable que si pones color = null quizas se reinicia.

2020-05-03 14:22 UTC, merged