Quirks 2.0: Ahora es personal
Helixis/Paradise pull request #659
Opened 2020-05-03 03:37 UTC by Evankhell561

## What Does This PR Do
Ahora los quirks trascienden a la muerte, manteniendose aun despues de la clonación. 

## Why It's Good For The Game
Si eras clonado los traits se perdian, cosa que no tenia sentido porque son rasgos inherente del pj.
También ayudará a que los quirks sean más utiles en el futuro para futuros proyectos. 

## Advertencia
Este pr no ha sido testeado pero tengo absoluta confianza en mis habilidades de PROcoder

## Changelog
:cl:
tweak: los Quirks ahora se mantienen aún después de la clonacion
/:cl:

2020-05-03 15:20 UTC, Silverexperience requested changes
Lo estuve testeado, y cuando sali de la clonadora con el quirk de pacifismo le di una paliza al CMO que me clono.

2020-05-03 16:15 UTC, Evankhell561 commented
> Lo estuve testeado, y cuando sali de la clonadora con el quirk de pacifismo le di una paliza al CMO que me clono.

Cambié el codigo, a ver ahora

2020-05-03 22:22 UTC, Silverexperience requested changes
Lo estuve testeando, y nada mas salir de clonacion mi personaje pacifico le rompio los huesos a la doctora.

2020-05-04 01:39 UTC, Evankhell561 commented
> Lo estuve testeando, y nada mas salir de clonacion mi personaje pacifico le rompio los huesos a la doctora.

silver, guapo. ahora si funcionará, tengo una corazonada.

2020-05-04 05:50 UTC, Evankhell561 commented
> Lo estuve testeando, y nada mas salir de clonacion mi personaje pacifico le rompio los huesos a la doctora.

dime que ahora sí perduran a la clonacion por favor.

2020-05-04 13:53 UTC, Silverexperience requested changes
Ahora si que se guardan los traits, pero genera runtimes al solo crearse una persona, incluso sin traits.
![imagen](https://user-images.githubusercontent.com/58746682/80973175-52a69280-8e1f-11ea-9e21-fd0cfe3d37aa.png)

2020-05-04 17:04 UTC, Evankhell561 commented
> Ahora si que se guardan los traits, pero genera runtimes al solo crearse una persona, incluso sin traits.
> ![imagen](https://user-images.githubusercontent.com/58746682/80973175-52a69280-8e1f-11ea-9e21-fd0cfe3d37aa.png)

creo que esto es debido a que si se crea una mente que no haya tenido un cuerpo anteior, le estoy pidiendo al juego que transfiera sus quirks de su anterior cuerpo al nuevo

2020-05-04 18:41 UTC, Evankhell561 commented
Tambien quisiera saber si puedo dejar nombres y descripciones en español, además de que quiero recibir feedback con respecto a que seria adecuado en cada una de ellas.

2020-05-04 19:51 UTC, Silverexperience commented
> 
> 
> Tambien quisiera saber si puedo dejar nombres y descripciones en español, además de que quiero recibir feedback con respecto a que seria adecuado en cada una de ellas.

No veo mal que esten en español los nombres, aunque si quisieras tener un code totalmente igual puedes ponerlo en inges.
El quirk de mimo no lo veo muy bien porque al final le quita parte de lo unico que tiene ese trabajo.

2020-05-04 19:57 UTC, Evankhell561 commented
> El quirk de mimo no lo veo muy bien porque al final le quita parte de lo unico que tiene ese trabajo.
Lo estaba dudando sí pero el payaso es una modificacion genetica, puedes modificar tus genes para ello, en cambio el mimo es... unico. además de que existiran habilidades interdepartamentales un ingeniero podrá tomar el quirk de cirujano y así. A mi forma de verlo solo debemos jugar bien con los puntos

2020-05-04 20:53 UTC, Silverexperience commented
> 
> 
> > El quirk de mimo no lo veo muy bien porque al final le quita parte de lo unico que tiene ese trabajo.
> 
> Lo estaba dudando sí pero el payaso es una modificacion genetica, puedes modificar tus genes para ello y no por eso la gente deja de jugar payaso, en cambio el mimo es... unico. además de que existiran habilidades interdepartamentales, un ingeniero podrá tomar el quirk de cirujano y así. A mi forma de verlo solo debemos jugar bien con los puntos.

Pero la voz del payaso no caracteriza al payaso, las habilidades del mimo son una gran parte de lo que es ser mimo.

2020-05-04 20:57 UTC, Evankhell561 commented
> > > El quirk de mimo no lo veo muy bien porque al final le quita parte de lo unico que tiene ese trabajo.
> > 
> > 
> > Lo estaba dudando sí pero el payaso es una modificacion genetica, puedes modificar tus genes para ello y no por eso la gente deja de jugar payaso, en cambio el mimo es... unico. además de que existiran habilidades interdepartamentales, un ingeniero podrá tomar el quirk de cirujano y así. A mi forma de verlo solo debemos jugar bien con los puntos.
> 
> Pero la voz del payaso no caracteriza al payaso, las habilidades del mimo son una gran parte de lo que es ser mimo.

uhm pues, la voz del payaso no es lo unico que tiene ser payaso, esto tambien hace que puedas golpearte a ti mismo con armas a mele y caer solo por que sí. but, si así lo prefieres lo retiro. tampoco es que estoy muy ligado a ese quirk.

2020-05-04 21:08 UTC, Silverexperience commented
> 
> 
> > > > El quirk de mimo no lo veo muy bien porque al final le quita parte de lo unico que tiene ese trabajo.
> > > 
> > > 
> > > Lo estaba dudando sí pero el payaso es una modificacion genetica, puedes modificar tus genes para ello y no por eso la gente deja de jugar payaso, en cambio el mimo es... unico. además de que existiran habilidades interdepartamentales, un ingeniero podrá tomar el quirk de cirujano y así. A mi forma de verlo solo debemos jugar bien con los puntos.
> > 
> > 
> > Pero la voz del payaso no caracteriza al payaso, las habilidades del mimo son una gran parte de lo que es ser mimo.
> 
> uhm pues, la voz del payaso no es lo unico que tiene ser payaso, esto tambien hace que puedas golpearte a ti mismo con armas a mele y caer solo por que sí. but, si así lo prefieres lo retiro. tampoco es que estoy muy ligado a ese quirk.

Sera mejor dejar a los payaso y a los mimos de manera unica, aunque si podrias hacer un quirk de torpe y que haga lo mismo que describes del payaso.

2020-05-04 21:16 UTC, Evankhell561 commented
> Sera mejor dejar a los payaso y a los mimos de manera unica, aunque si podrias hacer un quirk de torpe y que haga lo mismo que describes del payaso.

Lo haré, just, cualquier genetista puede convertirte en payaso con el gen adecuado asi que ya de por sí el gen payaso no es algo unico but, retiraré esos dos en la proxima version.

2020-05-04 21:21 UTC, Silverexperience commented
> 
> 
> > Sera mejor dejar a los payaso y a los mimos de manera unica, aunque si podrias hacer un quirk de torpe y que haga lo mismo que describes del payaso.
> 
> Lo haré, just, cualquier genetista puede convertirte en payaso con el gen adecuado asi que ya de por sí el gen payaso no es algo unico but, retiraré esos dos en la proxima version.

Que yo sepa solo te da voz de comic sans e igualmente el gen no lo tienes desde el inicio.

2020-05-04 21:28 UTC, Evankhell561 commented
> Que yo sepa solo te da voz de comic sans e igualmente el gen no lo tienes desde el inicio.

Nel, el gen te da la voz más todo lo demás que hace a un payaso payaso
![image](https://user-images.githubusercontent.com/49106866/81015354-8b993400-8e2c-11ea-8c4a-9e27f5faacda.png)

But, como he dicho, lo quitaré. Solo estaba ahi porque queria más quirks negativos. Y también me gusta el razonamiento que me has dado.

2020-05-14 20:48 UTC, Silverexperience requested changes

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	desc = "Tienes las mimsas habilidades de construccion que... no sabes constuir nada"
Pon: El uso de herramientas se te dificulta.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	medical_record_text = "Al paciente le cuesta realizar habilidades manuales."
Deberías borrar todos los medical_record_text si no tienen utilidad alguna.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Esto del maincra no se te daba tan mal.</span>"
Pon mejor: Esto de craftear no se te daba tan mal.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	desc = "Parece que eres tan torpe como nadie, debes tener algun cromosoma extra"
Quita el tan y como nadie.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Eres evan, cuidado al caminar!</span>"
Cambia evan por torpe.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Pues esto de trabajar no era nada del otro mundo.</span>"
Sera mejor que pongas: Te sientes habilidoso.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +/datum/quirk/manco
Ya te puedes quitar las manos sin este quirk.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	lose_text = "<span class='notice'>Conducir un ripley es como andar en bicicleta decian.</span>"
Falta la tilde en decían.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	lose_text = "<span class='notice'>Conducir un pod es como andar en bicicleta decian.</span>"
Lo mismo de la tilde en decían.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	subclass = "POD" //tiene la misma clase  que el mech pilot pero diferente supclase
En el comentario pusiste supclase en vez de subclase.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	lose_text = "<span class='notice'>Ya no tienes tanta resitencia como antes.</span>"
Pusiste resitencia en vez de resistencia.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	name = "Estomago fuerte"
Seria mejor impasible.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	lose_text = "<span class='notice'>Los lores fuertes hacen revolver el estomago.</span>"
Pusiste lores en vez de olores.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	name = "Crujano Veterano"
Te falta la i en Cirujano.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	desc = "Tienes mucha experiencia haciendo cirugias."
Cirguías lleva tilde en la segunda i.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	gain_text = "<span class='notice'>Por qu� disperar con un arma cuando puedes disparar con dos?.</span>"
Te falta la interrogación inicial y disperar se escribe disparar.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	lose_text = "<span class='notice'>Al parecer disprar con dos armas no era tan facil despues de todo.</span>"
Escribiste mal disparar, fácil lleva tilde y después tambien tiene tilde.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	name = "Tirador PRO"
Seria mejor Tirador veterano, al igual que el cirujano.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/neutral.dm
> +	desc = "No puedes saborear nada! Las comidas de hace dos semanas te siguen dando indigestion."
Te falta la exclamación inicial e indigestión lleva tilde en la o, y no entiendo que tiene que ver el "Las comidas de hace dos semanas te siguen dando indigestion."

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Pues parece que al final .</span>"
¿Esto esta incompleto?

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/neutral.dm
> +	gain_text = "<span class='notice'>No puedes saborear nada!</span>"
Te falta en los dos la exclamación del principio.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	desc = "Est�s capacitado para manejrar armas grandes."
Pusiste manejrar en vez de manejar.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	gain_text = "<span class='notice'>Tu punteria aumenta!</span>"
Te falta la exclamación inicial y puntería lleva tilde.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	lose_text = "<span class='notice'>Tu punteria ya no es lo que era.</span>"
puntería lleva tilde.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +/datum/quirk/llamaazul
No creo que los quirks tengan que tener artes marciales.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	desc = "tienes implantado un implante de nutrici�n."
Falta la mayuscula inicial.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	gain_text = "<span class='notice'>Tienes un implante de nutricion en el cuerpo.</span>"
Nutrición lleva tilde en la o.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/positive.dm
> +	lose_text = "<span class='notice'>Sientes... hambre?.</span>"
Falta la interrogación inicial.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/game/jobs/job/medical.dm
> +//FORENCE - JOB DE ROL
Pusiste FORENCE en vez de Forense.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/game/jobs/job/medical.dm
> +//QUIMICO  - JOB DE ROL
Químico lleva tilde en la primera i.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/game/jobs/job/medical.dm
> +//VIROLOGO - JOB DE ROL
Virólogo lleva tilde en la primera o.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/game/jobs/job/medical.dm
> +//SIQUIATRA  - JOB DE ROL
Se escribe Psiquiatra.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/game/jobs/job/medical.dm
> +//PARAMEDICO - JOB DE ESPECIAL
Paramédico lleva tilde en la e.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/game/jobs/job/medical.dm
> +	H.add_quirk(/datum/quirk/podpilot) //PARA RESACATES ESPACIALES
Pusiste RESACATES en vez de rescates.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/game/jobs/job/science.dm
> +//CIENTIFICO
Científico lleva tilde en la segunda i.

2020-05-14 20:48 UTC, Silverexperience commented on code/game/objects/items/tools/tool_behaviour.dm
> +		to_chat(user, "<span class='notice'>no sabrias usar esta herramienta aunque quisieras.</span>")
Faltaría la mayúscula inicial y sabrías lleva tilde.

2020-05-14 20:48 UTC, Silverexperience commented on code/modules/mob/living/carbon/human/human.dm
> +			to_chat(src, "<span class='warning'>Tu fobia a las armas de fuego no te deja apretar el gatillo!</span>")
La exclamación inicial.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	name = "Guns fobia"
Pon mejor: Hoplofobia.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Puedes defenderte a ti mismo nuevamente.</span>"
A ti mismo seria mejor quitarlo, con defenderte ya se entiende que eres tu al que puedes defender.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	medical_record_text = "El paciente es inusualmente pacifico y no hará nada que pueda dañar físicamente a otros."
Pacífico lleva tilde en la primera i.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Recuerdas eso... disparos, no de nuevo!</span>"
Faltaría la interrogación antes de no.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Pues disparar es hasta divertido, quien lo diria.</span>"
Diría lleva tilde en la segunda i.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Tus habilidades manuales son basura!</span>"
Faltaría la exclamación inicial.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Al parecer esto de la mecanica no era tan dificil</span>"
Mecánica y difícil llevan tilde, uno en la primera a y el otro en la segunda i.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>No podrias ni craftear un barco de papel</span>"
Podrías lleva tilde en la i, además falta el punto final.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +	name = "Craftear, que es eso?"
Seria mejor que pongas: Desmañado.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
> +//GENETICA
Genética lleva tilde en la segunda e.

2020-05-14 20:48 UTC, Silverexperience commented on code/HISPANIA/datums/traits/negative.dm
>  	desc = "The thought of violence makes you sick. So much so, in fact, that you can't hurt anyone."
Aún tienes descripciones en ingles.

2020-05-15 01:13 UTC, Evankhell561 commented on code/HISPANIA/datums/traits/negative.dm
> +//GENETICA
esto es un comentario de code e.e
lo dejaré asi para que se pueda visualisar bien desde el navegador

2020-05-15 01:13 UTC, Evankhell561 commented on code/HISPANIA/datums/traits/negative.dm
>  	desc = "The thought of violence makes you sick. So much so, in fact, that you can't hurt anyone."
listo

2020-05-15 19:18 UTC, Evankhell561 commented
Silver, no le puedo poner tiles a los nombres ni descriciones porque causan bugs visuales, tampoco puedo poner ñ. Estas cosas solo se las puedo colocar a los textos ic, que aparecen ic. los que estan marcados como span

2020-05-20 02:06 UTC, Silverexperience approved these changes
Esperemos que funcione.

2020-05-20 02:06 UTC, merged