El Gordo Franses volverá a amar este PR.
Helixis/Paradise pull request #661
Opened 2020-05-03 14:35 UTC by SagaStars

12 Comidas nuevas de 4 frutas nuevas, este PR es parte de la bounty hispania: https://spacestation13.es/Foro/showthread.php?tid=785&pid=2007#pid2007
![YES](https://user-images.githubusercontent.com/55407528/80851120-a893f400-8bed-11ea-88fa-abe280021e2b.png)

## Recetas de bebidas (Mezclando sin herramientas)

**Super-Healthy Prickly Pear Juice**
5u de azucar, 5u de cactusjuice, 5u de lemonjuice y 1u de ice
**Refined Nispero Juice**
10u de azucar, 1u de lemonjuice, 1u de nispero y 1u de ice
**Anonna Cream**
5u de azucar, 5u de water, 1u de anonna, 2u de cornoil
**Anonna and Blueberries**
1u de berryjuice y 1u de anonna

----
## Recetas de Horno

**Cheese Anonna Cake**
3 doughs, 1 cheesewedge, 1 anonna. 5u de milk y 15u de azucar.
**Pancake de Mermelada**
1 flatdough, 1 nispero, 1 berries. 5u de azucar y 1u de sodiumchloride

----
## Recetas de Microondas

**Ensalada de Cactus**
1 cabbage, 1 tomato, 1 pricklypear. 1u de sodiumchloride y 1u de blackpepper

----
### Recetas de Candy

**Mousse**
1 avocado. 5u de azucar, 5u de leche y 5u de cocoa
**Nispero Candy**
1 nispero, 1 lemon. 10u de azucar y 5u de cornoil

----
### Recetas de Grill

**Filete con Cactus**
1 meat/synthmeat, 1 pricklypear. 1u de sodiumchloride y 1u de blackpepper

----
### Recetas de Tablecraft(Sandwichs)

**Avocado Sandwich**
2 avocadoslice, 2 toast y 1 mayonnaise
**Bacon Rolls**
1 avocadoslice y 1 bacon

## Changelog
:cl:
add: Sandwich of Avocado
add: Salad of Pickly Pear
add: Mousse
add: Cheese Anonna Cake
add: Smoothie of Prickly Pear
add: Glass of Anonna Cream
add: Bacon Rolls
add: Filetes con Cactus
add: Cóctel of Anonna and Blueberries
add: Nispero Candy
add: Glass of Refined Nispero Juice
add: Pancake de Mermelada
add: Prickly Pear Cactus Juice
fix: Un par de typos de bebidas de hispania
/:cl:

2020-05-03 15:23 UTC, Silverexperience requested changes
Pon en el changelog los imageadd de los sprite.

2020-05-03 17:16 UTC, Silverexperience requested changes
Las diferentes frutas que añades y que dan un un juice, deberian funcionar con juice
El mousses no sale si completas la receta.
Deberias dar a entender mejor que es en Nispero Candy y el palstic-cup
Tienes unos runtimes por la falta de definiciones en los ingredientes.

2020-05-03 17:19 UTC, Evankhell561 commented
> Las diferentes frutas que añades y que daun un juice, deberian funcionar con juice
> El mousses no sale si completas la receta.
> Deberias dar a entender mejor que es en Nispero Candy y el palstic-cup
> Tienes unos runtimes por la falta de definiciones en los ingredientes.

Lo que yo decia, estas comidas fueron hechas por un chef amateur.

2020-05-03 19:20 UTC, SagaStars commented
Asi se ven ahora:
![image](https://user-images.githubusercontent.com/55407528/80923355-363c2480-8d51-11ea-82b3-cb2df4335cd8.png)

2020-05-03 22:59 UTC, Silverexperience requested changes
Podrias poner comentarios en lo que añades en paradise, para que se sepa lo que es nuestro y lo que no.
Saltan estos warnings.
![imagen](https://user-images.githubusercontent.com/58746682/80928081-74adff80-8da2-11ea-8c4b-a4059e464106.png)

2020-05-04 00:15 UTC, Silverexperience approved these changes

2020-05-04 00:25 UTC, merged