Cambia la edad mínima y restringe los jobs por edades
Helixis/Paradise pull request #682
Opened 2020-10-13 19:45 UTC by Ume-D

## What Does This PR Do
Cambia la edad mínima de 18 a 15, y restringe los jobs según la edad del personaje.
Capitán: +30 años
Comando: +25 años
Resto de jobs: +18 años
Civil: Sin restricción

## Why It's Good For The Game
Ahora puedes tener tu personaje snowflake de menor de edad visitando una estación espacial, pero no tendrás un HoS de 17 años o un CE de 20 en comando, ni un CMO de 15 en el quirófano.

## Changelog
:cl:
tweak: Cambia la edad mínima y restringe los jobs por edades
/:cl:

2020-10-13 20:09 UTC, Spircen commented on code/game/jobs/job/security.dm
> +	minimal_captain_character_age = 1
Antes en este DM borraste la linea de minimal_player_age = 21 ¿Por que ahora no?

2020-10-13 20:10 UTC, Spircen commented on code/game/jobs/job/supervisor.dm
> +	minimal_captain_character_age = 1
Lo mismo de borrar la minimal_player_age =30

2020-10-13 20:12 UTC, Spircen commented on code/modules/mob/new_player/new_player.dm
> +
Espacio de mas

2020-10-13 20:15 UTC, Spircen requested changes
Pocos detalles que faltan borrar para que sea igual que tu anterior par de PRs fuera de eso todo parece estar igual que antes lo voy a testear mientras tanto. Igualmente no se si siga aquel detalle referente a que no se aplicaba al iniciar ronda nueva pero si después. 

Y referente al Travis parece ser que esta atorado en una nueva funcionalidad que pasa cada que se le da la gana no te preocupes por la X en el PR por el momento.

2020-10-13 21:17 UTC, Ume-D commented on code/game/jobs/job/security.dm
> +	minimal_captain_character_age = 1
minimal_player_age es la variable de cuantos días debe tener la cuenta en el server para poder jugar ese job, además de las horas de comando/otro job necesarias. Antes lo borré por accidente y como no lo usabamos no me molesté en hacer otro commit arreglándolo. Prefiero dejarlo como está por defecto porque así lo puse Hess.

2020-10-13 21:36 UTC, Spircen commented
Todo funciona de maravilla y sin problemas, olvide en mi anterior Review anexar que documentes los cambios hechos sobre los DM de Paradise. Recomiendo que ocupes un formato similar a 

///Restricciones de edad
[Codigo]
///Fin de Restricciones de edad

2020-10-13 21:37 UTC, Spircen commented
Lo de arriba para cambios grandes para cambios de una sola linea los puedes anexar al final.

2020-10-13 23:24 UTC, Cocacolagua commented
estaría bien en el futuro diferentes restricciones por diferentes razas, IPC trabajando desde que fueron creados, y drask trabajando cuando ya tienen centenas de años

2020-10-14 13:23 UTC, merged

2020-10-14 13:28 UTC, Evankhell561 commented
> estaría bien en el futuro diferentes restricciones por diferentes razas, IPC trabajando desde que fueron creados, y drask trabajando cuando ya tienen centenas de años

Apoyo la moción con toda violencia. Diferentes razas deberían tener distintas edades mínimas. Tampoco estoy deacuerdo en subir la raza mínima de algunos Jobs más allá de la edad mínima. Eso limita algunas situaciones de rol. Lo que se debería hacer es que los jugadores con mayor edad en cargos de comando tengan prioridad con los de menor edad.

2020-10-14 13:28 UTC, Evankhell561 commented
But, esto fue aprobado así aúnque tenía más cambios que en su versión original vale verga la vida.