Tweak Cambiar nivel de alarma como head
Helixis/Paradise pull request #697
Opened 2020-10-19 05:12 UTC by Spircen

## What Does This PR Do
Habilita a los heads la posibilidad de cambiar el nivel de alarma.

## Why It's Good For The Game
Como sabemos no siempre contamos con todos los heads abordo y es importante que los cargos de comando puedan establecer el control cuando se ve necesario.

## Images of changes

                                                            ¡CHI CHEÑOL!
![image](https://user-images.githubusercontent.com/46639834/96404130-bb03e900-119f-11eb-9b65-12d5715e5b20.png)

## Changelog
:cl:
tweak: Consola de Comunicaciones 
/:cl:

2020-10-19 19:18 UTC, Evankhell561 commented
wait, puedes explicar como funciona ahora? yo habia hecho estos cambios anteriormente y no tuve que tocar la ui.

2020-10-19 19:36 UTC, Evankhell561 requested changes

2020-10-19 19:36 UTC, Evankhell561 commented on tgui/packages/tgui/public/tgui.bundle.js
> -if(!document.createEvent){var t,n=!0,o=!1,r="__IE8__"+Math.random(),a=Object.defineProperty||function(e,t,n){e[t]=n.value},i=Object.defineProperties||function(t,n){for(var o in n)if(l.call(n,o))try{a
parece que borraste la linea de abajo.

2020-10-19 20:23 UTC, Spircen commented on tgui/packages/tgui/public/tgui.bundle.js
> -if(!document.createEvent){var t,n=!0,o=!1,r="__IE8__"+Math.random(),a=Object.defineProperty||function(e,t,n){e[t]=n.value},i=Object.defineProperties||function(t,n){for(var o in n)if(l.call(n,o))try{a
No te voy a mentir esto es un desmadre, pero funciona esa es la linea que deja el compilador de TGUI imagina que es como el Map Merge

2020-10-19 20:37 UTC, Spircen commented on tgui/packages/tgui/interfaces/CommunicationsComputer.js
> +        disabled={!data.authenticated
Esta sección es la que activa ciertos textos en base al nivel de autentificacion que recibe, Authmax es para capitán y se baja a authenticated para que los heads puedan ver esto.

2020-10-19 20:37 UTC, Spircen commented on tgui/packages/tgui/interfaces/CommunicationsComputer.js
> -                <LabeledList.Item label="Current Alert"
Aquí se encuentra originalmente el nivel de alarma y como cambiarlo pero en esta categoría esta separada como Captain Only asi que lo mejor es reposicionarla debido a que ya no es este el caso.

2020-10-19 20:38 UTC, Spircen commented on tgui/packages/tgui/interfaces/CommunicationsComputer.js
> +                <LabeledList.Item label="Current Alert"
Reposicionamos a Command Staff la nueva sección de cambio de alarma.

2020-10-19 20:53 UTC, Evankhell561 requested changes
tus cambios están bonitos spircen y si estoy fuera un code independiente te lo aceptaria sin dudarlo. Dejame unos dias que esté libre para testear esto y ver si hay una forma más friendly de hacer este cambio pero con menos lineas de código. Si la hay seguro será una manera menos bonita pero quizá más faciles de que no se pierda.

2020-10-19 21:03 UTC, Spircen commented
Esto lo único que implica es que tenemos que compilar un archivo cada que vayamos a hacer Commits externos para que el paquete de TGUI que incluye todas las interfaces este al tanto con este cambio.

2020-10-20 01:49 UTC, Evankhell561 approved these changes

2020-10-20 01:49 UTC, Evankhell561 commented on tgui/packages/tgui/interfaces/CommunicationsComputer.js
> +        disabled={!data.authenticated
El tema es que paradise esta constantemente cambiando el tg ui y mantener estos cambios puede ser lioso. Lo mejor seria solo cambies esta linea. Y que  renombres la sección de only capitan a "cosas de alto riesgo" "cosas de gran importancia" o algo asi. Tu modo es mucho mejor, claro está pero la idea es que estos cambios perduren para rato y con mi sugerencia será más sencillo de que no se pierdan.

2020-10-20 19:42 UTC, Evankhell561 requested changes

2020-10-20 19:42 UTC, Evankhell561 commented on code/game/objects/effects/spawners/lootdrop.dm
> +/obj/effect/spawner/lootdrop/Initialize(mapload)
esta cammio me mola porque soy fanatico de este tipo de cambios but, why? es algo que se perdio de paradise? 
si no arregla nada, y tampoco es un cambio que este en paradise tampoco deberia estar en este pr, ni ninguno de hispania, realmente.

2020-10-20 19:43 UTC, Spircen commented on code/game/objects/effects/spawners/lootdrop.dm
> +/obj/effect/spawner/lootdrop/Initialize(mapload)
Si, se perdió durante el mergeo masivo de cosas. Esto esta de esta forma en Paradise.

2020-10-20 19:45 UTC, Spircen commented on code/game/objects/effects/spawners/lootdrop.dm
> +/obj/effect/spawner/lootdrop/Initialize(mapload)
No, wait fui a revisar

2020-10-20 20:22 UTC, merged