Add Nuevas Armas y Ampliaciones a SpacePods
Helixis/Paradise pull request #698
Opened 2020-10-19 17:52 UTC by Spircen

## What Does This PR Do
Añade nuevos items a la lista de herramientas y armas que puede tener una SpacePod a la par que balancea los valores de consumo actuales que tiene el equipamento de estas: 

![image](https://user-images.githubusercontent.com/46639834/77133632-5aee6e00-6a29-11ea-8a56-741325bc8390.png) Placas de Refuerzo = Añade mas vida a la SpacePod

![image](https://user-images.githubusercontent.com/46639834/77133654-73f71f00-6a29-11ea-9ca4-3ef05811c302.png) Cortador de Plasma = Dos rayos de plasmacutter similar al de mecha

![image](https://user-images.githubusercontent.com/46639834/77133675-8f622a00-6a29-11ea-87dc-165977ab9353.png) Inmolator = Dos rifles de calor que hacen arder a lo que golpean.

![image](https://user-images.githubusercontent.com/46639834/77133706-a6a11780-6a29-11ea-9ac8-a477e8606084.png) Rifle de iones = Cañon dual de iones igual a el Ion Rifle de armeria

![image](https://user-images.githubusercontent.com/46639834/77133736-c0daf580-6a29-11ea-8506-24b80f09d894.png) LMG = Rifle de balas con un cooldown bajo.

Sistemas miscelaneos: 
Asientos para hasta 3 o 4 usuarios en una SpacePod. Cada uno es un modulo diferente y una versión mejorada de bluespace la cual permite mas almacenamiento en la SpacePod

![image](https://user-images.githubusercontent.com/46639834/77133760-da7c3d00-6a29-11ea-9229-febd4852edaa.png)

## Why It's Good For The Game
Añadir mas armamento a las SpacePods y balancear sus valores de consumo de energía en base a cuanto pueden hacer las vuelve un método mas viable para lidear con múltiples amenazas, esta es la primera parte de una serie de PRs con el fin de poder mejorar las SpacePods

## Images of changes

                                Modelos Disponibles en SpacePod Fabricator
![image](https://user-images.githubusercontent.com/46639834/77133882-65f5ce00-6a2a-11ea-9686-ab77879919b5.png)

                                     Test de nuevos asientos extras
![image](https://user-images.githubusercontent.com/46639834/77133917-802fac00-6a2a-11ea-8b31-18817936c003.png)

                                   Prueba de multiples nuevas armas
![image](https://user-images.githubusercontent.com/46639834/77133995-c97ffb80-6a2a-11ea-8952-fd8fe86791b5.png)

## Changelog
:cl:
add: Nuevas Armas y herramientas a SpacePod 
/:cl:

2020-10-19 19:28 UTC, Evankhell561 requested changes

2020-10-19 19:28 UTC, Evankhell561 commented on code/HISPANIA/modules/spacepods/equipment.dm
> +	used = 1
para qué pones esto en uno si lo vas a eliminar luego?

2020-10-19 19:28 UTC, Evankhell561 commented on code/modules/spacepods/equipment.dm
> -	shot_cost = 400
bajar diez veces un valor no me parece muy adecuado. La razon de que los pods tengan un costo de disparo tan alto es la seguridad que posees al disparar desde afuera de la estacion sin que puedan responderte el fuego sin riesgo por abrir una brecha. So, como mucho reduce esto a la mitad. Además, con que alguien mejore la bateria del pod provocaré un problema grande.

2020-10-19 19:28 UTC, Evankhell561 commented on code/HISPANIA/modules/spacepods/equipment.dm
> +	shot_cost = 30
lo mismo que con la otra review de costos.

2020-10-19 19:28 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/spacepod_designs.dm
> +	req_tech = list("combat" = 6, "magnets" = 5, "materials" = 5)
todo equipamento de pods deberia incluir ingeneria. (si es que aun existe esa tech)

2020-10-19 19:34 UTC, Evankhell561 requested changes

2020-10-19 19:34 UTC, Evankhell561 commented on code/HISPANIA/modules/spacepods/equipment.dm
> +/obj/item/fluff/plates_spacepod //Placas de refuerzo
esto es un tipo de objeto que no deberia existir en cuanto a balance, todo equipamento del pod deberia tener un costo, todos los otros llenan un hueco (para los mehcas pasa lo mismo) porque segun como está esto es una mejora que sí o sí tienes que ponerle a tu pod.

2020-10-19 19:34 UTC, Evankhell561 commented on code/HISPANIA/modules/spacepods/equipment.dm
> +	pod.health = 500
1.  esto es la vida actual del pod o la vida maxima del pod?
2. si es la vida actual entonces por ponerle este refuerzo habras reparado el pod, si es la vida maxima entonces tu pod estará proporcionalmente dañado. 
3. deberia sumar vida, no fijar vida.
4. lo de la review de arriba.
5. los mechas tienen una especie de mejora que les proporciona una reduccion de daño, estaria mejor que esto y tambien llenan un hueco en el equipamento.

2020-10-19 19:35 UTC, Evankhell561 requested changes
no es una exigencia pero estarai bueno que aunque sea le pusieras un pixel de color distinto a los sprites para que no se confundan con el equipo de mechas. (o al menos que no se vean iguales)

2020-10-19 19:37 UTC, Spircen commented on code/modules/spacepods/equipment.dm
> -	shot_cost = 400
No creo, actualmente lo único que se compara es un Mecha pero a diferencia de ellos para cargar una Pod debes de bajarte y cambiar la batería, usualmente solo tienes la capacidad de disparar una Energy Gun y con eso te quedas sin batería por completo abordo de ella. 

Incluso aun con una batería mejorada sigue siendo mas viable desplazarte en un jetpack con energy guns en la mochila, es una SpacePod no una energy gun con escudos. 

En comparación te muestro la diferencia abismal que hay en el consumo de una space pod contra un mecha: 
![image](https://user-images.githubusercontent.com/46639834/96503183-8122f900-1218-11eb-9b31-bbfca47e3851.png)
![image](https://user-images.githubusercontent.com/46639834/96503216-8d0ebb00-1218-11eb-80db-fe19f6333b52.png)

2020-10-19 19:38 UTC, Evankhell561 requested changes

2020-10-19 19:38 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/spacepod_designs.dm
> +	materials = list(MAT_METAL=10000,MAT_GLASS=5000,MAT_GOLD=1000,MAT_SILVER=2000)
todo lo que diga bluespace debe ser construido con al menos un poco de cristal bluespace.

2020-10-19 19:48 UTC, Evankhell561 requested changes

2020-10-19 19:48 UTC, Evankhell561 commented on code/modules/spacepods/equipment.dm
> -	shot_cost = 400
porque el mecha lo puedes combatir tierra tierra. pero un pod puede bombardearte espacio-tierra.

2020-10-19 19:48 UTC, Evankhell561 commented on code/modules/spacepods/equipment.dm
> -	shot_cost = 400
Sin mencionar que el balance de los mechas tambien está hecho como el culo, no lo niego. Pero se compensa con el la lentitud, más vulnerabilidad al poder combatirlo en la misma area. aún asi, un bufo de disparar el doble de veces es adecuado. si luego parece insuficiente intentamos modificar un poco más los valores, pero bajar de 100 a 10 es excesivo. 
Tambien, una bateria comun tiene 10k de carga, en cargo existen baterias de 15k de carga y en rnd desbloqueas una de 20k de carga con solo apretar un boton. Si disparas un laser de 200 de costo, tienes facilmente unos 100 disparos con la beria de 20k, cosa que me parece suficiente para un pod promedio. una mejorada ocuparia unos 200 disparos. Sin mencionar de todas las otras implicaciones que he mencionado. Aun asi, para este pr como mucho será la mitad ya que tambien estas incluyendo juguetes nuevos.

2020-10-19 19:49 UTC, Spircen commented on code/HISPANIA/modules/spacepods/equipment.dm
> +	pod.health = 500
Tengo que revisar por que si, debe de curar la SpacePod cuando este dañada al instalar estas placas aunque tiene sentido considerando que es un aumento a vida máxima y al instarlas repara, sumado a que solo se puede instalar una vez. 

Y no es igual que los mechas, no quiero agregar una reducción de daño a las SpacePods pues este componente es una placa permanente que se elimina no algo que se agrega al equipamiento modular.

2020-10-19 19:50 UTC, Evankhell561 requested changes

2020-10-19 19:50 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/spacepod_designs.dm
> +	locked = 1
el capitan y la emga podian desbloquear la seguridad del protolathe y el autolathe. No pido que hagas lo mismo acá pero seria una buena inclusion. para que un capitan habilite el armamento en un uso desesperado o para que los antags no tengan que gastar su emag poco a poco.

2020-10-19 19:51 UTC, Spircen commented
Un mecha se puede reparar, cargar, proteger de atmos y dar acceso a radio local sin necesidad de bajar de el a diferencia de una SpacePod, una SpacePod no puede ni entrar a la estación y donde te metas en un espacio 1x1 listo escapaste de ella.

2020-10-19 19:54 UTC, Evankhell561 commented on code/HISPANIA/modules/spacepods/equipment.dm
> +	pod.health = 500
Precisamente sugeria que lo ocupes como equipamiento modular, y si puede tener sentido que se cure pero es que si tiene más vida que eso estas reduciendole la vida, tambien checkea lo de la vida maxima y la actual.

2020-10-19 20:00 UTC, Spircen commented on code/HISPANIA/modules/research/designs/spacepod_designs.dm
> +	req_tech = list("combat" = 6, "magnets" = 5, "materials" = 5)
Lo agregare solo en los que considero es útil, quiero decir los componentes base no requieren ingeniería. 

![image](https://user-images.githubusercontent.com/46639834/96505457-c1d04180-121b-11eb-921e-57f4101f64f2.png)

2020-10-19 20:02 UTC, Spircen commented on code/HISPANIA/modules/spacepods/equipment.dm
> +/obj/item/fluff/plates_spacepod //Placas de refuerzo
El punto de esto es poder generar otra SpacePod similar a la de Seguridad por que actualmente esa Pod únicamente existe como objeto único y es imposible poder generar otra si es que esta explota, la puedo poner en los niveles mas alto de Research pero considero el subir la vida útil de una SpacePod como mejora es necesario.

2020-10-19 20:04 UTC, Spircen commented on code/HISPANIA/modules/research/designs/spacepod_designs.dm
> +	materials = list(MAT_METAL=10000,MAT_GLASS=5000,MAT_GOLD=1000,MAT_SILVER=2000)
No creo, quiero decir tu mismo llegaste a tener objetos que subían con Bluespace pero no requieren Bluespace. 

![image](https://user-images.githubusercontent.com/46639834/96505862-55097700-121c-11eb-8151-721c3e9c57ca.png)

2020-10-19 20:06 UTC, Evankhell561 commented
> Un mecha se puede reparar, cargar, proteger de atmos y dar acceso a radio local sin necesidad de bajar de el a diferencia de una SpacePod, una SpacePod no puede ni entrar a la estación y donde te metas en un espacio 1x1 listo escapaste de ella.

para ser reparado necesitas ir al robotista, para ser recargado tambien, si quieres repararte a distancia unas un modulo que te gasta un hueco, si quieres recargarte a distancia usas una bateria especial, al igual que un pod, las utilidades del atmos es para un mecha de trabajo diseñado especificamente para ello. aun asi, la comparacion con el mecha fue solo por 1. una mejora que no ocupa huecos y 2. Quien ha sacado la coparativa en cuanto a otras cosas ha sido tu y te he contestado pero no es el punto. El asunto es, estas aplicando un buff de x10 y estás ampliando el arsenal de cosas que puede hacer. aplica primero uno x2 como mucho.

2020-10-19 20:13 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/spacepod_designs.dm
> +	materials = list(MAT_METAL=10000,MAT_GLASS=5000,MAT_GOLD=1000,MAT_SILVER=2000)
eso es porque la funcionalidad bluespace está en el core bluespace que necesitas para que esa cosa pueda teleportar a alguien, no es una funcionalidad por defecto. En este caso eso no es una armadura bluespace, es una armadura reactiva que puede ser bluespace si le añades un componente bluespace..
y esto es usado para medir frecuencias bluespace pero no tiene que ver con compimir el espacio o manipularlo.
![image](https://user-images.githubusercontent.com/49106866/96506598-e7fadf00-1225-11eb-9390-88097626890c.png)

2020-10-19 20:16 UTC, Spircen commented on code/HISPANIA/modules/research/designs/spacepod_designs.dm
> +	materials = list(MAT_METAL=10000,MAT_GLASS=5000,MAT_GOLD=1000,MAT_SILVER=2000)
Vale, lo agregare.

2020-10-19 20:16 UTC, Spircen commented
En ese caso hare la mejora a la mitad únicamente.

2020-10-19 20:22 UTC, Evankhell561 commented
> En ese caso hare la mejora a la mitad únicamente.

funciona para mí, si en el futuro todos dicen que sigue siendo excesivo y tu tienes flojera de arreglarlo me dices "te lo dije" y yo aplico otro buff.

2020-10-21 20:39 UTC, Spircen commented
Dejare de momento solo las armas y en el próximo PR que haga relacionado con las SpacePods traeré de regreso esta herramienta de Placas Reforzadas

2020-10-21 20:43 UTC, Spircen commented on code/HISPANIA/modules/research/designs/spacepod_designs.dm
> +	locked = 1
El emag no tiene limite de usos me parece, igualmente puedes abrir cajas de seguridad con una Energy Sword

2020-10-21 21:59 UTC, Evankhell561 commented on code/HISPANIA/modules/research/designs/spacepod_designs.dm
> +	locked = 1
No te preocupes. Era sólo un comentario. Puedo hacerlo yo luego.

2020-10-31 05:09 UTC, merged