Armadura de HoS alternativa estilo Desert Ranger/Los Angeles Riot suit.
Helixis/Paradise pull request #699
Opened 2020-10-20 15:34 UTC by X404ErrorX

Este PR agrega una armadura alternativa al HoS con el estilo de la armadura de los Rangers veteranos de Fallout New Vegas.

Esta armadura tiene las mismas stats que la Armored de HoS normal, y el helmet tiene las mismas stats de un riot helmet.

**Esta armadura se puede conseguir en el Walldrobe de la oficinal del HoS.**

Armadura en combate.

![](https://cdn.discordapp.com/attachments/339954056653045761/768127906764423209/unknown.png)

En el suelo.

![](https://cdn.discordapp.com/attachments/339954056653045761/768128279436984351/unknown.png)

Con/sin las partes.

![](https://cdn.discordapp.com/attachments/339954056653045761/768129271880744970/unknown.png)

2020-10-20 18:15 UTC, SagaStars commented
La sprites se ven bastante guays a excepcion de la version de object del casco que es muy claro a comparación de teniendola puesta, quizas ponerla un poco mas oscura y poner mas redonda la parte de arriba que se ve un poco irregular. Btw cuando vayas a poner SC de las sprites, no te pongas cosas como lentes, mochilas, cabello. Así se puede admirar mucho mejor la sprite sin tener que abrir tu branch.

Y parece que ya te has dado cuenta pero igual, se te ha colado uno de los cambios de gamemode, quizás un maintainer pueda solucionar eso 👀

2020-10-20 18:30 UTC, X404ErrorX commented
Anoto el tema de las capturas, sobre lo del sprite mas blanco, lo deje así ya que si lo modificaba para que se viera mas obscuro quedaba muy parecido a la mascara de swat, es un sprite original de Fallout 13 con modificaciones que hice yo mismo, si te parece algo muy necesario puedo re hacerlo mas obscuro, sobre lo del gamemode no se bien como paso, si algún mainteiner puede quitar eso me haría un gran favor.

2020-10-20 18:38 UTC, Evankhell561 commented
> La sprites se ven bastante guays a excepcion de la version de object del casco que es muy claro a comparación de teniendola puesta, quizas ponerla un poco mas oscura y poner mas redonda la parte de arriba que se ve un poco irregular. Btw cuando vayas a poner SC de las sprites, no te pongas cosas como lentes, mochilas, cabello. Así se puede admirar mucho mejor la sprite sin tener que abrir tu branch.
> 
> Y parece que ya te has dado cuenta pero igual, se te ha colado uno de los cambios de gamemode, quizás un maintainer pueda solucionar eso 👀

saga, nadie puede cambiar un pr ajeno. eso es un mito.

2020-10-20 18:40 UTC, Silverexperience requested changes
Pon el changelog.

¿A los Vox y demás especies tambiën se les ve bien el casco?

2020-10-20 18:40 UTC, Silverexperience commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/rangerh
Esto puedes meterlo en carpetas de hispania.

2020-10-20 18:40 UTC, Silverexperience commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/hos/ranger
Esto puedes meterlo en carpetas de hispania.

2020-10-20 18:40 UTC, Silverexperience commented on code/modules/clothing/head/helmet.dm
> +	hispania_icon = TRUE
No hace falta poner hispania_icons pùedes simplemente cambiar la ruta.
Esto en los dos.

2020-10-20 18:48 UTC, Evankhell561 commented
> No hace falta poner hispania_icons pùedes simplemente cambiar la ruta.
Esto en los dos.

no entiendo por que le pides quitar el hispania icons y en cambio hacer el cambio de tura si de ambas formas funciona.

2020-10-20 18:55 UTC, Silverexperience commented on code/modules/clothing/head/helmet.dm
> +	hispania_icon = TRUE
Pero dejalo como quieras.

2020-10-20 20:29 UTC, Evankhell561 requested changes

2020-10-20 20:29 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/head/helmets.dm
> +/obj/item/clothing/head/helmet/rangerh
/obj/item/clothing/head/helmet/riot/rangerh

2020-10-20 20:29 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/head/helmets.dm
> +	desc = "It's a helmet specifically designed to protect against close range attacks."
borra esta linea

2020-10-20 20:29 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/head/helmets.dm
> +	dog_fashion = null
borra esto

2020-10-20 20:29 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/head/helmets.dm
> +	strip_delay = 80
borra esto

2020-10-20 20:29 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/head/helmets.dm
> +	flags_inv = HIDEMASK|HIDEEARS|HIDEEYES|HIDEFACE
para qué es esto? ahi dice que se verá abajo de la mascara, oidos ojos y la cara... te parece bien?

2020-10-20 20:29 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/head/helmets.dm
> +	armor = list("melee" = 50, "bullet" = 10, "laser" = 10, "energy" = 10, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 80, "acid" = 80)
borra esto

2020-10-20 20:29 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/head/helmets.dm
> +	flags = BLOCKHAIR
no sé para que es esto pero si no es para nada especia puedes y deberias borrarlo

2020-10-20 20:32 UTC, Evankhell561 requested changes

2020-10-20 20:32 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/head/helmets.dm
> +	flags_cover = HEADCOVERSEYES | HEADCOVERSMOUTH
borra esto

2020-10-20 20:32 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/armor.dm
> +	flags_inv = 0
si no sabes para que es esto... deberias borrarlo.

2020-10-20 20:32 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/armor.dm
> +	ignore_suitadjust = 1
para qué sirve esto?

2020-10-20 21:26 UTC, Evankhell561 approved these changes
no he testeado esto pero ya revisé el codigo y no añade ningun elemento que balancear mas alla de sprites nuevo. por mi está bien.

2020-10-20 22:24 UTC, Silverexperience requested changes
- Añade un changelog.

- Las armaduras en el vending de TGUi se ven mal.
![imagen](https://user-images.githubusercontent.com/58746682/96651039-43b38e00-1334-11eb-80bf-8fd0c4376959.png)


- Hay más especies donde el casco se ve mal: en los tajaran, en los vuplkanin, en los unathi, en el voxarmalis y los drask donde literalmente el sprite del casco es invisible.
![imagen](https://user-images.githubusercontent.com/58746682/96649359-419c0000-1331-11eb-80dd-37817cb181f3.png)
![imagen](https://user-images.githubusercontent.com/58746682/96649501-86c03200-1331-11eb-8767-e2b822bf3b86.png)
![imagen](https://user-images.githubusercontent.com/58746682/96650598-6e511700-1333-11eb-9c8a-d60c9e45bfb3.png)
![imagen](https://user-images.githubusercontent.com/58746682/96649681-e0c0f780-1331-11eb-843d-d91a564fc781.png)
![imagen](https://user-images.githubusercontent.com/58746682/96650348-08fd2600-1333-11eb-8eec-ac63261002f0.png)

- En los murghal el traje se ve mal.

- Los objetos no tienen sprites cuando se equipan en la mano. No se si eso lo quieres asi.

2020-10-20 23:47 UTC, Evankhell561 requested changes
para arreglar el problema que causa el tgui puedes sacar estas ropas del waldrobe y meterlas en el closet del hos.

2020-10-20 23:57 UTC, X404ErrorX commented
Preferiría que se quedara en el Wall, no es un error muy grave o que vaya a molestar en gran medida, además de esta manera toda la ropa esta ordenada en el walldrobe.

2020-10-21 00:53 UTC, SagaStars commented
> para arreglar el problema que causa el tgui puedes sacar estas ropas del waldrobe y meterlas en el closet del hos.

No hay otra solución?

2020-10-21 01:51 UTC, Evankhell561 commented
> Preferiría que se quedara en el Wall, no es un error muy grave o que vaya a molestar en gran medida, además de esta manera toda la ropa esta ordenada en el walldrobe.

welp. si fuera alguien más le pediria que repare lo del tg ui en su ropa pero por mí está bien. meter ropa en el closet luego de tanto trabajo ordenando el walldrobe ta feo además de que ya no hay ropa en esos closets y antes del tgui tampoco podias ver el sprite de la ropa.

2020-10-22 04:55 UTC, Evankhell561 approved these changes
como dije antes, en cuanto a codigo ya funciona bien. just, hay que ir a teastear si funciona bien el ponerse la ropa. en cuanto a lo del nanoui no me importa que se vea borroso porque ya antes no se veia el sprite en la preview y no podemos exigir eso acá y meterlo en el closet arruina la organizacion que habiamos hecho antes.

2020-10-23 01:51 UTC, merged