Cambia el revolver del detective
Helixis/Paradise pull request #704
Opened 2020-10-23 02:03 UTC by Cocacolagua

## What Does This PR Do
El revolver del detective vuelve a tener su stun pequeño, pero ahora solo da 20 de stamina.

## Why It's Good For The Game
Los cambios que hice al revolver en paradise era por problemas del validhunting y el detective, ya que siempre hay seguridad para hacer el trabajo de cazar antags. El problema es qué acá el detective comunmente es el unico miembro de seguridad, y el revolver triste no va a frenar a nadie. Ahora van a tener que salvar y apuntar bien para stamina-crit, pero un disparo lo hará más facil.

## Changelog
:cl:
tweak: El revolver del detective vuelve a stunnear, pero hace menos daño de stamina.
/:cl:

2020-10-23 02:06 UTC, SagaStars commented
![Pog!](https://user-images.githubusercontent.com/55407528/96948053-ba769580-14b2-11eb-8a4b-d9da0084829a.png)

2020-10-23 02:06 UTC, Cocacolagua commented
woo

2020-10-23 02:07 UTC, Evankhell561 requested changes

2020-10-23 02:07 UTC, Evankhell561 commented on code/modules/projectiles/projectile/bullets.dm
> -	weaken = 3
por qué nerfeas esto?

2020-10-23 02:07 UTC, Evankhell561 commented on code/modules/projectiles/projectile/bullets.dm
> +	weaken = 3
eso no hará que instantaneamente tumbe a alguien?

2020-10-23 02:07 UTC, Cocacolagua commented on code/modules/projectiles/projectile/bullets.dm
> -	weaken = 3
es un subtype del revolver del detective, sería repetir el mismo valor

2020-10-23 02:08 UTC, Cocacolagua commented on code/modules/projectiles/projectile/bullets.dm
> +	weaken = 3
mhm, pero hace menos daño de stamina, entonces costara dejarlos en el piso

2020-10-23 09:07 UTC, X404ErrorX commented
El revolver del detective anteriormente estaba bastante roto, antes con un solo disparo era capaz de stunear a alguien durante 3 segundos, no era un tiempo muy alto pero lo suficiente como para golpearlo con un stunt baston o volver a dispararle, casi no tenia cadencia de fuego y su rango era prácticamente ilimitado, por estas cosas en Para se decidió nerfearlo, actualmente se necesitan 3 disparos para stunear a alguien y funciona por daño de stamina como un disabler, a mi en un principio me molesto el cambio ya que yo jugaba mucho detective pero al ver que el arma en verdad estaba muy fuerte incluso mas que el taser, un arma de oficial de seguridad. por esto no estoy muy seguro si es bueno hacerle un buff a este arma ya que el detective en primer lugar no tendría que tener tanto poder como para cazar, su trabajo es investigar y a mi parecer el balance que le dieron los coders de Para esta bastante ajustado al meta y a los roles, por otro lado si alguien en una ronda se mete de detective viendo que no hay ningun oficial de seguridad, warden, HoS no va a tener accesos a las celdas por lo que no va a poder efectuar arrestar por lo que quizas es mejor que se planteen dos veces si van a entrar con ese rol antes que dar un buff algo peligroso a un arma por una razón como esta.

2020-10-23 16:01 UTC, Evankhell561 commented
> El revolver del detective anteriormente estaba bastante roto, antes con un solo disparo era capaz de stunear a alguien durante 3 segundos, no era un tiempo muy alto pero lo suficiente como para golpearlo con un stunt baston o volver a dispararle, casi no tenia cadencia de fuego y su rango era prácticamente ilimitado, por estas cosas en Para se decidió nerfearlo, actualmente se necesitan 3 disparos para stunear a alguien y funciona por daño de stamina como un disabler, a mi en un principio me molesto el cambio ya que yo jugaba mucho detective pero al ver que el arma en verdad estaba muy fuerte incluso mas que el taser, un arma de oficial de seguridad. por esto no estoy muy seguro si es bueno hacerle un buff a este arma 
Tienes razón acá error.


> ya que el detective en primer lugar no tendría que tener tanto poder como para cazar, su trabajo es investigar y a mi parecer el balance que le dieron los coders de Para esta bastante ajustado al meta y a los roles, por otro lado si alguien en una ronda se mete de detective viendo que no hay ningun oficial de seguridad, warden, HoS no va a tener accesos a las celdas por lo que no va a poder efectuar arrestar por lo que quizas es mejor que se planteen dos veces si van a entrar con ese rol antes que dar un buff algo peligroso a un arma por una razón como esta.

Pero esto es hipócrita nosotros le damos acceso a rnd a los robotisras y acceso a atmos a los mecánicos y todo los roles de un departamento tienen all access a sus departamentos.


Mi opinión es que no buffees el arma del Detective pero en cambio les des acceso a la cárcel para que pueda arrestar gente si está solo. Sin embargo no voy a exigir nada acá. Que los otros maintainers o el prefecto tengan la última palabras.

2020-10-28 11:25 UTC, Spircen commented
Regrésala a como estaba originalmente es una revolver y es un objeto único en el juego, yo no tengo ningún problema en ver un detective acabar con nuke ops en dos tiros.

2020-10-28 12:56 UTC, Evankhell561 commented
> Regrésala a como estaba originalmente es una revolver y es un objeto único en el juego, yo no tengo ningún problema en ver un detective acabar con nuke ops en dos tiros.

Con estos cambios ya está tan fuerte como antes, no?

2020-10-31 22:20 UTC, merged