Nuevos emotes con sonidos & reparar squish slimes.
Helixis/Paradise pull request #712
Opened 2020-10-25 13:25 UTC by X404ErrorX

### ## What Does This PR Do

Este PR agrega 3 nuevos emotes con sonidos propios, modifica dos ya existentes y repara un problema algo viejo con un emote propio de la raza Slime People.

## Why It's Good For The Game

Usar los emotes es divertido y mas si hacen algun sonido gracioso o inmersivo por esto mismo este PR modifica lo siguente.

Nuevos emotes
*meow: Un maullido de gato
*bark: Un ladrido de perro
*noseb: (nose boop) tocarle la nariz a alguien y que se escuche un boop. (o la propia.)

Emotes modificados
*sniff: ahora tiene un sonido
*sneeze: ahora tiene el mismo sonido que el *squish (solo Slime People)

Paso a explicar el problema con el squish, este sonido/emote es propio de la raza slime. Antes de que Paradise los reworkeara y les diera pulmones los slimes solo tenían un sonido al enfermar que era el Squish ya que el *cough sustituía al *sneeze por que ellos en ese momento no respiraban, era algo asi como su gracia y era refrescante ver esa diferencia entre razas ademas de algo gracioso escuchar ese ruidito peculiar, pero desde el rework al respirar no se les hizo el sustituto correspondiente en en el codigo, solo se les dejo el *sneeze normal en lugar de hacer que este sonara como *squish, no se si habrá sido a posta este cambio pero a mi parecer es mejor que los slimes tengan su Squish para mantener esas diferencias entre razas.

### **No tengo manera de pasar los sonidos por aqui, git por alguna razon no me deja, si alguien quiere escuchar los .oog puede mencionarme por el canal de discord en el chat de codigo o por mensaje directo en discord.**

## Images of changes

Nuevo *help
![](https://cdn.discordapp.com/attachments/339954056653045761/769892521740206100/unknown.png)

Algunos de los textos (el mimo, el mute y la muzzle tienen los correspondiente)
![](https://cdn.discordapp.com/attachments/339954056653045761/769893035492114442/unknown.png)

## Changelog
:cl:
add: Nuevos emotes *meow *bark *noseb
tweak: Los slimes vuelven a toser con su *squish, ahora el sniff tiene sonido
soundadd: Nuevos sonidos para emotes
/:cl:

2020-10-25 13:35 UTC, Evankhell561 requested changes

2020-10-25 13:35 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/emote.dm
> +			playsound(loc, 'sound/hispania/effects/emotes/meow.ogg', 50, 1, frequency = get_age_pitch())
Este código está muy mal hecho. No puedo guiarte por acá porque estoy en mi celular pero por discord podría decirte cómo arreglarlo. De cualquier forma este pr no debe ser margeado en su estado actual.

2020-10-27 20:08 UTC, PotatoTheDeveloper commented on code/modules/mob/living/carbon/human/emote.dm
> +			playsound(loc, 'sound/hispania/effects/emotes/meow.ogg', 50, 1, frequency = get_age_pitch())
if("meow", "meows")
    if(miming)
        message = "<B>[src]</B> meows silently."
        m_type = 1
    else
        if(!muzzled)
           message = "<B>[src]</B> make noise"
           m_type = 2
        else
           message = "<B>[src]</B> makes a strong noise."
           m_type = 2
    else
        message = "<B>[src]</B> meow like a cat!"
        playsound(loc, 'sound/hispania/effects/emotes/meow.ogg', 50, 1, frequency = get_age_pitch())
        m_type = 1


ERROR PONE ESTO ASI ANTES DE QUE EVAN EXPLOTE AL VER LOS ERRORES

2020-10-30 23:11 UTC, Sikroth commented on code/modules/mob/living/carbon/human/emote.dm
> +					message = "<B>[src] boops [M] nose!"
"[src] boops [M]'s nose!"

gramática

2020-10-30 23:12 UTC, Sikroth commented on code/modules/mob/living/carbon/human/emote.dm
> +					message = "<B>[src] boops [p_them()] nose!"
"[src] boops [p_their()] own nose!"

si no me equivoco p_their() existe, y es el pronombre correcto

2020-10-31 02:50 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/emote.dm
> +			playsound(loc, 'sound/hispania/effects/emotes/meow.ogg', 50, 1, frequency = get_age_pitch())
perdon por la review rapida, mal hecha y agrevisa. Lo que quise decir es que segun tu codigo el sonido se esta generando aun antes de que se compruebe si debe sonar o no. Como sea, siver te recomendó ver otros ejemplos de emotes con sonidos, siguelos.

2020-11-23 20:23 UTC, closed without merging

2020-11-23 20:33 UTC, Evankhell561 commented
se requirieron 3 aprendices de codigo, y 2 maintainers para hacer que esta cosa funcione y ninguno pudo. el pr maldito.

2020-11-23 20:35 UTC, X404ErrorX commented
Poder puedo arreglarlo pero perdí interés en este pr, quizás en el futuro lo haga pero con mas emotes.