[Map Change] Expansión a Libreria (Cyberiad)
Helixis/Paradise pull request #713
Opened 2020-10-28 10:55 UTC by Spircen

## What Does This PR Do
Hace mas grande el departamento de Librería dando nuevos display cases con contenido aleatorio dummy a los cuales solo el bibliotecario tiene acceso, de esta forma esperamos puedan tener mas oportunidades para hacer roleplay a la par que tener un departamento mejor equipado. A la par que agrega ventanas reforzadas para poder dar mas privacidad detrás del escritorio. 

## Why It's Good For The Game
Actualmente contamos con varios nuevos jugadores que se ven atraídos a este rol como reporteros pero se dan casos donde la gente se salta la mesa para poder tomar poder de su estación de noticias o como que tienen que ir a dar una vuelta entera a la estación para poder conseguir crayones o papel. Con estos cambios entregamos mas privacidad a el bibliotecario y le damos mas recursos para que pueda hacer sus labores de forma mas optima. 

A la par que agregamos una maquina de café instantáneo de cortesía para que tengan una razón mas para poder visitar la biblioteca.

## Images of changes

![LIBRARY](https://user-images.githubusercontent.com/46639834/97426948-b34bef00-18d9-11eb-98bb-81c7482a114b.png)

## Changelog
:cl:
add: Biblioteca Expandida
/:cl:

2020-10-28 10:58 UTC, Spircen commented on _maps/map_files/hispania/hispania.dmm
> +/obj/item/book/codex_gigas,
No se ve en la imagen pero aquí se puede notar que sigue existiendo esta debajo de la grabadora.

2020-10-31 14:32 UTC, Silverexperience requested changes
- Solo tiene dentro un aspirador de aire. Cuando estaba abierto no importaba pero ahora cerrado puede causar problemas.
![imagen](https://user-images.githubusercontent.com/58746682/97781494-1ebce780-1b8c-11eb-9d43-b43b13ffcf20.png)

- Hay una zona invisible para las camaras.
![imagen](https://user-images.githubusercontent.com/58746682/97781684-5ed09a00-1b8d-11eb-8e9e-6d2108264681.png)

- Faltaria un holopad para la IA.
![imagen](https://user-images.githubusercontent.com/58746682/97781800-0f3e9e00-1b8e-11eb-8c72-ae58b4f30015.png)

2020-10-31 23:42 UTC, Spircen commented
Así queda con el ultimo commit. 

![image](https://user-images.githubusercontent.com/46639834/97792187-76fde480-1ba0-11eb-8704-04276c4980cd.png)
![changes](https://user-images.githubusercontent.com/46639834/97792190-7e24f280-1ba0-11eb-952f-5665223d420a.png)

2020-11-01 16:23 UTC, Silverexperience approved these changes

2020-11-01 22:22 UTC, merged