Add Timbres de pared
Helixis/Paradise pull request #716
Opened 2020-10-29 09:43 UTC by Spircen

## What Does This PR Do
Agrega timbres de pared a la lista de crafteo de Plasteel y el objeto en cuestión. Estos funcionan solo instalando el frame a la pared libre y listo cuentas con un timbre bastante visible que se deconstruye con una wrench. 

## Why It's Good For The Game
Actualmente contamos con timbres pero no son visualmente fácil de ubicar en los departamentos con esto espero que la gente deje de tener el retraso de tocar todas las puertas cada que necesitan entrar a un departamento. Por el momento este PR aun no hace el Add de los timbres al mapa debido a que tengo otro PR de mapeo asi que esperare que el de libreria sea aprobado para luego hacer el mapeo aquí. 

## Images of changes
![image](https://user-images.githubusercontent.com/46639834/97551482-a80bc880-1998-11eb-98b0-080e570efb2f.png)
![image](https://user-images.githubusercontent.com/46639834/97551519-b0fc9a00-1998-11eb-80b3-f4ae39e8b0c6.png)
![image](https://user-images.githubusercontent.com/46639834/97551560-bfe34c80-1998-11eb-89d0-e5e6af30cafb.png)
![Bells](https://user-images.githubusercontent.com/46639834/97551574-c40f6a00-1998-11eb-80cc-3732fae35a9d.png)

## Changelog
:cl:
add: Timbres de Pared
/:cl:

2020-10-29 10:50 UTC, Evankhell561 requested changes

2020-10-29 10:50 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/miscellaneous/mounted_bell.dm
> +/obj/machinery/big_bell/deconstruct(disassembled = TRUE)
De buenas a primeras creo que este proc debería ir dentro del wrench act. Y acá deberías colocar el mensaje de deconstrucción.

2020-10-29 10:50 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/miscellaneous/mounted_bell.dm
> +/obj/machinery/big_bell/attack_hand(mob/user as mob)
Quita el as mob

2020-10-29 10:50 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/miscellaneous/mounted_bell.dm
> +	return
Quita este return.

2020-10-29 10:50 UTC, Evankhell561 commented on code/HISPANIA/game/objects/items/miscellaneous/mounted_bell.dm
> +	var/obj/machinery/big_bell/newbell
Declara está variable luego de la confirmación de que usó bien la herramienta... (Línea 6)

2020-10-31 02:51 UTC, Evankhell561 commented
por cierto? por qué los tienes en wip? me gustaria tambien que reposiciones el timbre de mesa de med a un lugar más visible, está bastante escondido.

2020-11-17 18:31 UTC, Spircen commented on code/HISPANIA/game/objects/items/miscellaneous/mounted_bell.dm
> +/obj/machinery/big_bell/deconstruct(disassembled = TRUE)
Esto sirve para los Swarmers, así se los pueden comer y desaparece.

2020-11-22 09:10 UTC, closed without merging