Cross update
Helixis/Paradise pull request #720
Opened 2020-10-31 04:56 UTC by Evankhell561

#What Does This PR Do
añade las galletas blue, yellow, metal, adamantina y silver del slime cross asi como otros pocos cross extra y refactoriza las ganancias energeticas dadas por otros efectos del cruce de slimes.

#Why It's Good For The Game
Por un slime cross cada vez más completo

Images of changes
## Changelog
:cl:
add: crossgalleta azul
add: crossgalleta metalica
add: crossgalleta amarilla
add: crossgalleta adamantina
add: cross estabilizado azul
add: trait noslipwater
add: cross estabilizado plateado
add: reactivo nutriente estabilizado
twaak: cross energy refactor
/:cl:

2020-11-01 18:02 UTC, Silverexperience requested changes
- Las galletas que te hacen inmune a resbalarte e invocan agua a tu arededor, al final cuando se desactivan puedes resbalarte porque el efecto de inmunidad termina antes que el de invocar agua.

- El core azul stabilizado tarda un rato en aplicarse y puedes resbalarte en esos instantes.

- Los efectos de tener mas resistencia al fuego parece que no se pierden.
![imagen](https://user-images.githubusercontent.com/58746682/97810478-6880fd00-1c74-11eb-94b5-9f1fe6495785.png)

- ¿Como funciona lo de cross energy refactor?

2020-11-01 22:20 UTC, Evankhell561 commented
> * ¿Como funciona lo de cross energy refactor?

basicamente ahora la ganancia de energia de esos slimes es una ganacia plana y no porcentual. queda igual para las baterias basicas pero las mejoradas recibiran menos energia en proporcion.

2020-11-01 23:11 UTC, Evankhell561 commented
> * La  el core azul stabilizado tarda un rato en aplicarse y puedes resbalarte en esos instantes.

esto es... muy raro porque se aplica al instante.

2020-12-07 03:34 UTC, Evankhell561 commented
confictos

2021-02-22 03:39 UTC, Evankhell561 commented
> Las galletas que te hacen inmune a resbalarte e invocan agua a tu arededor, al final cuando se desactivan puedes resbalarte porque el efecto de inmunidad termina antes que el de invocar agua.

fixed

2021-02-22 05:42 UTC, Evankhell561 commented
Ya arreglé todos los problemas menos el  que causa que puedas resbalarte en 0.1s segundos antes de aplicar el efecto como tal y no puedo solucionar eso, sin embargo, ya arreglé todo lo demás y mucho más.

2021-02-25 03:06 UTC, Evankhell561 commented
Tiempo limite cumplido, avisé por discord.

2021-02-25 03:06 UTC, Evankhell561 commented
Agradecer también a @Silverexperience por darse cuenta de errores que de otra forma no habria podido notar. se te quiere mucho.

2021-02-25 03:06 UTC, merged