Momento Ropa, Cambia el Sprite del RD por uno mas bonito y le añade dos uniformes mas (WIP)
Helixis/Paradise pull request #725
Opened 2020-11-02 01:52 UTC by Danaleja2005

## What Does This PR Do

Añade dos uniformes para el RD y cambia ese sprite feo que tenia el traje estandar del RD antes

## Why It's Good For The Game

Sprites mas bonitos y variedad yay

## Images of changes

![image](https://user-images.githubusercontent.com/43283605/97095093-41e61500-1629-11eb-8a92-62ab31dc2f95.png)

## Changelog
:cl: Danaleja2005
add: 2 Uniformes Nuevos para el RD
tweak: Cambia el Sprite del Traje del RD
imageadd: Añade los Sprites para los trajes nuevo y el nuevo sprite del traje del RD
/:cl:

2020-11-02 02:10 UTC, Evankhell561 requested changes

2020-11-02 02:10 UTC, Evankhell561 commented on code/modules/clothing/under/jobs/medsci.dm
> +/*	icon_state = "director"
comenta el por qué modificas esto.

2020-11-02 02:10 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/under/jobs/medsci.dm
> +	hispania_icon = TRUE
ya no usamos el hispania icon. o al menos ya no es suficiente. tienes que especificar todas las rutas relacionadas a este sprite.

2020-11-30 13:47 UTC, SagaStars requested changes
El RD no deberia tener que pagar por su ropa formal, ningun walldrobe de head deberia tener precios, quitale los precios.

2020-11-30 13:50 UTC, Danaleja2005 commented
> El RD no deberia tener que pagar por su ropa formal, ningun walldrobe de head deberia tener precios, quitale los precios.

Hm no lo se, se podría decir que es ropa exclusiva, el uniforme es con el que ya vienen ademas, asi no se compra todos los uniformes el mismo RD para terminar usando uno solo, pero no see..

2020-11-30 13:52 UTC, Danaleja2005 commented
Sabes esta bien lo hare

2020-11-30 14:06 UTC, Evankhell561 requested changes

2020-11-30 14:06 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/under/jobs/medsci.dm
> +	hispania_icon = TRUE
le diste a solucionar conversacion pero no hiciste caso.

2020-11-30 14:08 UTC, Danaleja2005 commented on code/HISPANIA/modules/clothing/under/jobs/medsci.dm
> +	hispania_icon = TRUE
tan simple como que si funciona el Hispa_icon, lo unico es que no se ven todas las dirs en el vending por el tgui

2020-11-30 14:08 UTC, SagaStars commented on code/HISPANIA/modules/clothing/under/jobs/medsci.dm
> +	hispania_icon = TRUE
grande dana

2020-11-30 14:19 UTC, Danaleja2005 commented on code/HISPANIA/modules/clothing/under/jobs/medsci.dm
> +	hispania_icon = TRUE
bueno lo dije mal se ven todas las dirs y no el icon del objeto porque? ni idea

2020-11-30 14:34 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/under/jobs/medsci.dm
> +	hispania_icon = TRUE
solo añade una variable llamada icon donde diga donde está el objeto. el hispania icon esta a punto de ser eliminado de la ropa.

2020-11-30 14:36 UTC, Danaleja2005 commented on code/HISPANIA/modules/clothing/under/jobs/medsci.dm
> +	hispania_icon = TRUE
why

2020-12-01 01:31 UTC, Danaleja2005 commented
Lo ultimo hecho, espero mi instamerge :handshake:

2020-12-01 01:38 UTC, Evankhell561 commented on code/modules/clothing/under/jobs/medsci.dm
> +/*	icon_state = "director"
amo que ahyas movido las variables de una ruta a hispania, eso es tener mucha IQ. muchos no conocen que esto es posible. 10/10

2020-12-01 01:39 UTC, SagaStars commented on code/modules/clothing/under/jobs/medsci.dm
> +/*	icon_state = "director"
🎊

2020-12-01 01:39 UTC, SagaStars approved these changes

2020-12-01 01:55 UTC, merged