Add Advanced Roller Bed
Helixis/Paradise pull request #738
Opened 2020-11-10 19:09 UTC by Spircen

## What Does This PR Do
Añade una receta a la categoría miscelánea de crafteo para una Advanced Roller Bed (ARB), esta roller bed entra dentro del modificador para ser considerad equivalente a una cama de cirugías por el multiplicador de probabilidad de cirugías pero no es portable como la Bluespace Roller Bed (BRB). A su vez añade la ARB y la BRB a sus respectivos equipamientos equivalentes para el ERT Amber, Rojo y Gamma. Por ultimo agrega la ARB y la BRB a la condicional de la probabilidad de cirugias. 

ARB Recipe: (5) Cable Coil, (1) Roller Bed Folded, (10) Rods de Metal, (1) Health Analyzer /// Tools: Screw and Wrench

## Why It's Good For The Game
Hace mas viable la cirugía en distintos puntos de la estación cuando no se puede conseguir una mesa de cirugías y sabiendo que los doctores no saben armar mesas de cirugías esto les hace mas sencillos poder desplazarse para hacer cirugías. Por ultimo agregando equipamiento a su nivel a los miembros de ERT espero puedan hacer mejor su trabajo. 

## Images of changes

![image](https://user-images.githubusercontent.com/46639834/98716030-87f0e780-2350-11eb-9760-ab3d2a48d150.png)
![image](https://user-images.githubusercontent.com/46639834/98717287-79a3cb00-2352-11eb-9df8-e604c6d18428.png)
![image](https://user-images.githubusercontent.com/46639834/98719850-e40a3a80-2355-11eb-9066-f35ff3ea970b.png)

## Changelog
:cl:
add: Advanced Roller Bed
tweak: ERT Equipamiento Medico
tweak: Multiplicador de cirugías
/:cl:

2020-11-11 05:37 UTC, Evankhell561 requested changes
En general no me parece que esto sea una buena idea ya que ocupa la misma función de una mesa normal pero la puedes colocarla en un sitio más estrategico. También hace que en vez de tener un paramédico que traiga los heridos a med en su ambulancia ahora tendremos cirujanos a domicilio. Cosa que no me termina de convencer Salvo para el ert. Y aún así, reemplazar la rollers bed normal con una fija para ellos tampoco me agrada. Quizá como equipamiento extra.

2020-11-11 05:50 UTC, Spircen commented
Literalmente los puntos que dices los cubre la SoP en la mayoría de los casos. 

Respecto a paramedicos:
![image](https://user-images.githubusercontent.com/46639834/98773729-26ac3100-23af-11eb-9cdc-4288d787887c.png)

Respecto a doctores:
![image](https://user-images.githubusercontent.com/46639834/98773825-5f4c0a80-23af-11eb-89b1-53ac04ff764c.png)

Esto implica que si seguridad ve a personal haciendo esto en circunstancias no apropiadas o cuando la sala de cirugías esta disponible pueden arrestar.

2020-11-17 06:18 UTC, Evankhell561 requested changes

2020-11-17 06:18 UTC, Evankhell561 commented on code/modules/surgery/helpers.dm
> +	if(locate(/obj/machinery/optable, T) || locate(/obj/structure/bed/roller/advanced, T) || locate(/obj/structure/bed/roller/bluespace, T)) //Modificador para roller beds avanzadas
no veo por qué deba estar acá la bluespace ya que esta tiene su propio nicho al ser portable. como mucho colocarla en el multiplicador de 0.8.

2020-11-17 06:18 UTC, Evankhell561 commented on code/game/objects/items/weapons/storage/firstaid.dm
> +	new /obj/item/roller/advanced(src) //Hispania Roller Bed
no veo por qué esto tenga que ser la roller por defecto

2020-11-17 06:18 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/stool_bed_chair_nest/bed.dm
> +	var/obj/structure/bed/roller/advanced/R = new /obj/structure/bed/roller/advanced(user.loc)
var/obj/structure/bed/roller/advanced/R = new (user.loc)

2020-11-17 18:36 UTC, Spircen commented on code/modules/surgery/helpers.dm
> +	if(locate(/obj/machinery/optable, T) || locate(/obj/structure/bed/roller/advanced, T) || locate(/obj/structure/bed/roller/bluespace, T)) //Modificador para roller beds avanzadas
Listo, modificador agregado.

2020-11-17 18:36 UTC, Spircen commented on code/game/objects/items/weapons/storage/firstaid.dm
> +	new /obj/item/roller/advanced(src) //Hispania Roller Bed
Este es un objeto admin spawn only y existe bajo el nombre de "field surgery kit" a mi parecer si es un equipo de cirugía de campo debería contar con la cama para operar.

2020-11-17 21:27 UTC, Evankhell561 approved these changes
todo parece estar en orden.

2020-11-17 21:48 UTC, merged