Quirk Terminator
Helixis/Paradise pull request #740
Opened 2020-11-10 23:07 UTC by NervalARS

Se añade el quirk terminator, para los IPC

## What Does This PR Do
Añade un quirk, el cual cambia la resistencia de los IPC pero los vuelve mas lentos. 

Ahora si el quirk esta activo, la resistencia al daño bruto y de quemaduras sera de 0.8. EL movement delay pasa a ser de 2.

## Why It's Good For The Game
Les da una segunda opción a los IPC, ser mas resistentes a costa de su velocidad.

## Images of changes

## Changelog
:cl:
add: Quirk Terminator
/:cl:

2020-11-11 00:22 UTC, Evankhell561 requested changes

2020-11-11 00:22 UTC, Evankhell561 commented on code/HISPANIA/datums/traits/neutral.dm
> +/datum/quirk/terminator/add()
Pon está ruta un poco más abajo.

2020-11-11 00:22 UTC, Evankhell561 commented on code/HISPANIA/datums/traits/neutral.dm
> +	desc = "Eres un IPC que has sido usado para la guerra. Eres resistente, pero tosco y lento."
Específica que solo funciona en ipcs.

2020-11-11 00:22 UTC, Evankhell561 commented on code/HISPANIA/datums/traits/neutral.dm
> +		quirk_holder.dna.species.speed_mod = 2
Pon un espacio a al final del dm.

2020-11-11 05:11 UTC, Evankhell561 approved these changes

2020-11-11 05:15 UTC, Evankhell561 approved these changes
Creo que este es un buen paso en el hispacode. El uso de quirks para personalizar a tu monigote espacial casi siempre es una buena adicción.

2020-11-11 18:30 UTC, Silverexperience requested changes
Aunque a los humanos no les funcione se los puedes seguir poniendo y sale el mensaje.

Los demas quirks estan en ingles.

2020-12-07 03:34 UTC, Evankhell561 commented
confictos

2021-02-06 21:35 UTC, Evankhell561 commented
en este momento este pr no cumple ninguna review, que fueron hechas hace mucho, no ha asido actualizado, tiene conflictos, y por sobre todo, un pr similar fue margeado
https://github.com/Helixis/Paradise/pull/803
es por ello que cierro este pr.

2021-02-06 21:35 UTC, closed without merging