Sprites feos de armas adios, nuevos sprites feos de armas saludos.
Helixis/Paradise pull request #742
Opened 2020-11-12 21:57 UTC by SagaStars

- Se cambian las sprites de la energy gun y laser gun.
- Nuevo modo de disparo para la laser gun:
      **Spray:** Un modo de disparo de "escopeta" que disparan 10 lasers en miniaturas gastando la mitad de energia del arma, solo dando para 2 disparos, cada bala quita 5 de daño y tiene un delay de 30 por disparo que es el doble del delay que el de un electrode, mucho tiempo por lo cual no termina siendo mejor que una escopeta normal.
- Las laser guns ahora hacen 27 de daño PERO se les sube el precio de energia quitandole 2 disparos dejandolo con solo 10 (La subida de daño viene para dejar el mismo output de daño total **22.5x12 = 270** y **27x10 = 270**) ademas de darle un delay de 15 segundos, el mismo delay que un electrode.
- Cambio a la sprite de el riot helmet y cambio de color de la pantalla azul del bulletproof helmet a rojo.
## Why It's Good For The Game
La laser gun recibe mas cariño y deja de ser una sombra de la energy gun que solo se le da los seguratas por que se acabaron las armas, ahora quedan como un arma mas efectiva para objetivas que van solos o pesados. Dejando asi que sea mas lenta en fire-rate y mas poder, a la par de un modo de descarga útil para asegurar un disparo sin hacer mucho daño.

No creo que tenga que explicar por que cambiar las sprites sea algo positivo. :vomit:

![PR](https://user-images.githubusercontent.com/55407528/98999227-d1d2fc80-250d-11eb-8dd1-c553d631b53e.png)

## Changelog
:cl:
add: Spray mode para la laser gun.
imageadd: Cambios a las sprites de armas de: lasergun y energygun.
imageadd: Nuevo riot helmet y cambio de color al bulletproof helmet.
tweak: Delay de disparo para la munición scatter y normal de la laser gun.
tweak: Mayor gasto de energia y daño de la lasergun.
/:cl:

2020-11-12 22:59 UTC, Cocacolagua reviewed
ronaldinho soccer

2020-11-14 03:18 UTC, Evankhell561 requested changes
puedes por favorcito hacer los sprites a parte para poder juzgarlos sin tener que considerar tus cambios al balance? se te agradece la gerencia.

2020-11-14 17:45 UTC, SagaStars commented
> puedes por favorcito hacer los sprites a parte para poder juzgarlos sin tener que considerar tus cambios al balance? se te agradece la gerencia.

Aqui va solo con los cambios de sprites.

2020-11-15 13:43 UTC, Evankhell561 requested changes

2020-11-15 13:43 UTC, Evankhell561 commented on code/modules/clothing/head/helmet.dm
> +	hispania_icon = TRUE
Esto no es suficiente para que se visualicen correctamente. Sigue el ejemplo de spricen en su pr de arreglar la visualización de la ropa en los vending.

2020-11-15 13:43 UTC, Evankhell561 commented on code/modules/projectiles/guns/energy/nuclear.dm
> -	ammo_x_offset = 1
Why?

2020-11-15 14:01 UTC, SagaStars commented on code/modules/clothing/head/helmet.dm
> +	hispania_icon = TRUE
Arreglao

2020-11-15 14:07 UTC, SagaStars commented on code/modules/projectiles/guns/energy/nuclear.dm
> -	ammo_x_offset = 1
Para que este acorde la municion a la sprite. Sin el offset toda la municion se acumula en 4 pixeles.

2020-11-16 19:18 UTC, Evankhell561 requested changes

2020-11-16 19:18 UTC, Evankhell561 commented on code/modules/clothing/head/helmet.dm
> +	item_state = "swat"
Sería mejor que tú sprite tenga el mismo nombre que el sprite de Paradise.

2020-11-16 21:00 UTC, SagaStars commented on code/modules/clothing/head/helmet.dm
> +	item_state = "swat"
Piénsalo mas como un fix, el hecho de que tuviera `-alt` solo hacia mas confuso encontrar el hat, asi es como deberia estar.

2020-11-16 23:43 UTC, Evankhell561 commented on code/modules/clothing/head/helmet.dm
> +	item_state = "swat"
Está bien pero si este cambio se revierte por x motivo será aún más difícil de reparar

2020-11-17 00:04 UTC, SagaStars commented on code/modules/clothing/head/helmet.dm
> +	item_state = "swat"
Muchos cambios de hispania ya son así, cual es la diferencia? En todo caso yo los reparare.

2020-11-17 02:22 UTC, Evankhell561 commented on code/modules/clothing/head/helmet.dm
> +	item_state = "swat"
El único que recuerdo hizo algo parecido fue silver con el cangrejo y el mismo dijo que mantener los nombres del sprite sería lo mejor. También los otros cambios de nombres de sprites han Sido fixes directamente en dmis de Paradise. Quizá me haya olvidado de uno pero en general no está bien.

2020-11-17 02:25 UTC, SagaStars commented on code/modules/clothing/head/helmet.dm
> +	item_state = "swat"
Bien tu ganas lo pondré como antes.

2020-11-17 12:20 UTC, Danaleja2005 commented
Sugerencias de Cambios a los Sprites

1ero.Sugiero que le añadas es dos pixeles a las partes rojas para que se vea mejor porque como ahora no me agrada del todo como se ve, no esta mal pero puede verse mejor con mi arreglito

![image](https://user-images.githubusercontent.com/43283605/99388728-680b7780-28ac-11eb-8346-3959211d6e8d.png)
(Tu version

![image](https://user-images.githubusercontent.com/43283605/99388443-f7645b00-28ab-11eb-8689-f17209990f11.png)
(Mi version

2do. Esta parte la verdad se me hacia un poco extraño y a mi parecer le falta detalle mi forma de como yo lo arreglaria sera poniendo estos detallitos simples 

![image](https://user-images.githubusercontent.com/43283605/99388669-532ee400-28ac-11eb-9655-8e3d30f3c35c.png)
(Tu version)

![image](https://user-images.githubusercontent.com/43283605/99388694-5c1fb580-28ac-11eb-9350-e28507f0cfa0.png)
(Mi version)

2020-11-17 13:20 UTC, SagaStars commented
@Danaleja2005
 Revisión de Sprites:
-------------
Se acomoda el mango como primera sugerencia presentada.
![image](https://user-images.githubusercontent.com/55407528/99394566-79a54d00-28b5-11eb-9e31-13848505943c.png)
La segunda sugerencia ha sido tomado a medias, la parte del mango en el barril se ha modificado pero no se ha hecho una separación entre el medidor de munición y el barril, se ve mucho mejor con una transición limpia sin otro relieve, no me convenció en lo absoluto. Así estaría viéndose ahora:
![image](https://user-images.githubusercontent.com/55407528/99394720-b83b0780-28b5-11eb-8dc2-22125895be2c.png)
![image](https://user-images.githubusercontent.com/55407528/99394744-c12bd900-28b5-11eb-955b-9de16320e3ba.png)

2020-11-17 14:30 UTC, Danaleja2005 commented
Se ve mejor, me sirve

![image](https://user-images.githubusercontent.com/43283605/99402408-b24a2400-28bf-11eb-8e39-7d1cf68ef34d.png)

2020-11-17 14:55 UTC, merged