Plataformas (BASE, NO UTILIZABLE IC)
Helixis/Paradise pull request #745
Opened 2020-11-13 04:12 UTC by Danaleja2005

Solo añado esto para que los mappers de centauri puedan usar como vista previa, no es funcional solo es base 

:cl:
add: Plataforma WIP
wip: codigo de plataforma WIP
imageadd: añade sprites de plataforma metal una y metal2
/:cl:

2020-11-24 01:27 UTC, Evankhell561 requested changes

2020-11-24 01:27 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/platform.dm
> +    var/decon_speed = null
no pongas = null al declarar una variable 
```suggestion
    var/decon_speed
```

2020-11-24 01:27 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/platform.dm
> +    name = "Metal Platform 2"
no pongas 2 en el nombre, lol. ponle algo como "coronel plataforma" o algo asi

2020-11-26 02:46 UTC, Danaleja2005 commented
No tengo idea en lo absoluto de que vida y que resistencia tendra o debería tener @Evankhell561

2020-11-26 13:27 UTC, Evankhell561 requested changes
Esta era mi review hasta que me di cuenta que esto era un wip, por favor convierte este pr en draft

2020-11-26 13:27 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/platform.dm
> +    return
```suggestion
/obj/structure/platform/proc/CheckLayer() // Para saber si el icono debe ir encima del mob o no
    if(dir == NORTH)
        layer = ABOVE_MOB_LAYER
    if(corner && dir == SOUTH)
        layer = ABOVE_MOB_LAYER
```

2020-11-26 13:27 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/platform.dm
> +
elimina esta linea en blanco

2020-11-27 17:44 UTC, Evankhell561 requested changes

2020-11-27 17:44 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/platform.dm
> +    desc =  " A metal platform"
hay espacios raros acá.

2020-11-27 18:47 UTC, Evankhell561 requested changes

2020-11-27 18:47 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/platform.dm
> +    desc =  "A robust platform corner made of plasteel, more resistance for hazard sites"
espacios raros

2020-11-27 18:47 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/platform.dm
> +    desc =  " A metal platform corner"
espacios raros

2020-11-27 18:47 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/platform.dm
> +    name = "Metal Platform Corner"
espacios raros al final

2020-11-27 18:47 UTC, Evankhell561 commented on code/HISPANIA/game/objects/structures/platform.dm
> +/obj/structure/platform/metal2/corner
nombre de ruta poco intuitivo (por el 2)

2020-11-27 18:57 UTC, Evankhell561 requested changes
en general parece que has usando cuatro espacios en vez de tabs a lo largo del pr. cambialo por favor.

2020-12-03 19:28 UTC, closed without merging