Nuevas WinterCoats || Edición Seguridad
Helixis/Paradise pull request #752
Opened 2020-11-17 19:23 UTC by SagaStars

- Se agregan 4 wintercoats nuevas para los siguientes puestos:
`◘ Warden`
`◘ HoS`
`◘ Brig Physician`
`◘ Detective`
Vienen con sus defensas acordes a los suits del job, en otras palabras el wintercoat del warden tiene la misma armadura que la armored jacket del warden, eso si, bajándole la defensa a todas las wintercoats cosas como la resistencia de fuego y ácido, a excepción del HoS que se queda con la mismas estadísticas. Pueden ser obtenidas por el loadout, no hay otro metodo.

- Se le da defensa a la hoods de los wintercoats de sec para que no sea un sacrificio de armadura por estética, quiero reiterar que la diferencia entre las wintercoats y las armaduras de sec es que estas tienen mucha menor resistencia contra el fuego y ácido.

_Intentare sacar mas para los demás departamentos._

## Why It's Good For The Game
Mas ropa siempre pinta bien ademas de que poder darle un tremendo uso para el mapa de nieve cuando este terminado.

---------
#### `Como siempre la imagen en paint.`
---------
![PR](https://user-images.githubusercontent.com/55407528/99436920-1aacfb80-28e8-11eb-80b5-47d83e7b6448.png)

## Changelog
:cl:
add: Cuatro nuevos newcoats para el departamento de sec, obtenibles por el loadout.
tweak: Las hoods de wintercoats de sec tienen defensas similares a las de sus hats ordinarios.
/:cl:

2020-11-17 19:29 UTC, josesitomartinez commented
Ok

2020-11-17 21:28 UTC, Evankhell561 commented
Uhm no sé mucho de estas cosas pero estoy interesado, deja llamar a un amigo que sabe más de esto que yo para tener la opinion de un experto.

2020-11-17 21:40 UTC, Evankhell561 requested changes

2020-11-17 21:40 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	hispania_icon = TRUE
el hispania icon esta casi obsoleto, asegurate de que tenga la variable icon en una ruta hispana

2020-11-17 21:40 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|ARMS
tendré que esperar a revisar esto a ver si esta todo en orden

2020-11-17 21:40 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 30, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 25, "acid" = 25)
lo mismo aca

2020-11-17 21:40 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +/obj/item/clothing/suit/hooded/armor
me pregunto si tus sprites nuevos se ven en razas no humanas

2020-11-17 21:40 UTC, Evankhell561 commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 15, "bullet" = 10, "laser" = 15, "energy" = 5, "bomb" = 15, "bio" = 0, "rad" = 0, "fire" = 15, "acid" = 15)
why?

2020-11-17 21:40 UTC, Evankhell561 commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 35, "bullet" = 30, "laser" = 30,"energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 15, "acid" = 25)
why?

2020-11-17 22:18 UTC, SagaStars commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 35, "bullet" = 30, "laser" = 30,"energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 15, "acid" = 25)
"Se le da defensa a la hoods de los wintercoats de sec para que no sea un sacrificio de armadura por estética, quiero reiterar que la diferencia entre las wintercoats y las armaduras de sec es que estas tienen mucha menor resistencia contra el fuego y ácido"
Lo puse en la desc.

2020-11-17 22:19 UTC, SagaStars commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 15, "bullet" = 10, "laser" = 15, "energy" = 5, "bomb" = 15, "bio" = 0, "rad" = 0, "fire" = 15, "acid" = 15)
Estan hechas de cuero, es bastante logico y necesitan una desventaja ya siendo que tienen las mismas propiedades que una armadura normal y te protegen del frio.

2020-11-17 22:21 UTC, SagaStars commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	hispania_icon = TRUE
vale

2020-11-17 22:21 UTC, SagaStars commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	body_parts_covered = UPPER_TORSO|LOWER_TORSO|ARMS
bien

2020-11-17 22:23 UTC, SagaStars commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 30, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 25, "acid" = 25)
Que cosa?

2020-11-17 22:23 UTC, SagaStars commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +/obj/item/clothing/suit/hooded/armor
No sabria decirte, voy a ver luego.

2020-11-19 02:40 UTC, SagaStars commented
Si se ven en razas y ahora tienen nuevo `sprite_sheet` para lo vox (10 sprites mas) para que este acorde con las wintercoats de paradise.
![image](https://user-images.githubusercontent.com/55407528/99613708-6ea20800-29ee-11eb-9911-47d34ee6c7f7.png)

2020-11-20 23:03 UTC, Spircen approved these changes
Todo en orden, me agrada la idea de tener mas ropa de invierno para los futuros cambios.  

Agrega comentarios solo a las líneas de código que modificaste en el DM de paradise. No es vital pero ayuda a que el Head Coder haga las actualizaciones a la branch mas fácil en caso de conflictos.

2020-11-20 23:06 UTC, SagaStars commented
> Todo en orden, me agrada la idea de tener mas ropa de invierno para los futuros cambios.
> 
> Agrega comentarios solo a las líneas de código que modificaste en el DM de paradise. No es vital pero ayuda a que el Head Coder haga las actualizaciones a la branch mas fácil en caso de conflictos.

Que bueno que apoyes la noción, ahi viene commit nuevo.

2020-11-22 08:03 UTC, Evankhell561 submitted a review, later dismissed

2020-11-22 08:03 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 30, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 25, "acid" = 25)
Esto es basicamente una version mejorada de un /obj/item/clothing/suit/armor/vest/security. añadir menos defensas al fuego y al acido para compensar la proteccion al frio está bien. pero eso no compensa el que tambien proteja las manos, a diferencia de un traje normal de seguridad que solo protege el torso. Y esto no está bien. Ya no se trata de sacrificar defensa por estetica sino de ganar proteccion adicional en ciertas partes del cuerpo

2020-11-22 08:06 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 30, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 25, "acid" = 25)
wait, esto es apra warden :thonk: pense que al ser la version normal seria apra el sec officer normal

2020-11-22 08:15 UTC, Evankhell561 requested changes
> Se le da defensa a la hoods de los wintercoats de sec para que no sea un sacrificio de armadura por estética, quiero reiterar que la diferencia entre las wintercoats y las armaduras de sec es que estas tienen mucha menor resistencia contra el fuego y ácido.

preferiria que esto no se cambie, aunque podrias ponerle defensas limitadas.

2020-11-22 08:15 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	hoodtype = /obj/item/clothing/head/hooded/winterhood/security
ponle un casquito más acorde a un abrigo con pocas defensa como este.

2020-11-22 08:22 UTC, Evankhell561 requested changes, later dismissed

2020-11-22 08:22 UTC, Evankhell561 commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 30, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 70, "acid" = 90)
creo que todos estos abrigos deberian tener menos proteccion al fuego que los suits ordinarios.

2020-11-22 16:19 UTC, SagaStars commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	hoodtype = /obj/item/clothing/head/hooded/winterhood/security
no es necesario y despropositaria la hood, ya de por si los brig physicians se ponen security helmets, para que se pondrian la hood en vez de un helmet?

2020-11-22 16:26 UTC, SagaStars commented on code/HISPANIA/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 30, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 70, "acid" = 90)
Opino que el hos deberia ser el unico sin deficit en la resistencia de acido y fuego, vamos que la va a necesitar mas que los demas y la contextura del traje no parece nada flameable. De igual manera su hood que si esta hecha de puro cuero por lo que no es tan resistente al fuego y acido.

2020-11-22 16:31 UTC, SagaStars commented
> preferiria que esto no se cambie, aunque podrias ponerle defensas limitadas.

Por que no? Y ya tienen las defensas limitidas en aspectos de fuego y acido.

En mi vida he visto a alguien usando una wintercoat de sec poniendose la capucha, es completamente inutil y es el equivalente a ponerte neko ears, tendrias que tener intenciones suicidas o ser Kans.

Ademas de que ya tenemos boinas y gorras reforzadas con las mismas defensas que security helmets y incluso mejores(las del HoS), **por que no capuchas?**

2020-11-27 19:13 UTC, Evankhell561 commented
> > preferiria que esto no se cambie, aunque podrias ponerle defensas limitadas.
> 
> Por que no? Y ya tienen las defensas limitidas en aspectos de fuego y acido.
> 
> En mi vida he visto a alguien usando una wintercoat de sec poniendose la capucha, es completamente inutil y es el equivalente a ponerte neko ears, tendrias que tener intenciones suicidas o ser Kans.
> 
> Ademas de que ya tenemos boinas y gorras reforzadas con las mismas defensas que security helmets y incluso mejores(las del HoS), **por que no capuchas?**

entonces hagamos que toda la ropa tenga mucha armadura para ver a gente usandola en combate y ver más variedad.

2020-11-27 20:50 UTC, SagaStars commented
> entonces hagamos que toda la ropa tenga mucha armadura para ver a gente usandola en combate y ver más variedad.

Okay, entiendes de que estamos hablando de seguridad? Entenderia este punto en cualquier otro departamento, pero seguridad? Malas defensas = Muerte = Antag Suelto + Un oficial menos = shitround y solo hay de 1 a 3 oficiales por ronda, tengo que explicarme mas?

Si las hoods de seguridad no tienen defensas para que van a existir, para hacer que un oficial muera mas rapido? Es idiotico y es el problema que tienen las hoods de wintercoats de sec, es relleno inutil. Con darle esas defensas llegan a ser viables pero no lo recomendables, no se que le ves de negativo, ya tienen hasta una desventaja de stats.

2020-11-27 22:37 UTC, Evankhell561 commented
> > entonces hagamos que toda la ropa tenga mucha armadura para ver a gente usandola en combate y ver más variedad.
> 
> Okay, entiendes de que estamos hablando de seguridad? Entenderia este punto en cualquier otro departamento, pero seguridad? Malas defensas = Muerte = Antag Suelto + Un oficial menos = shitround y solo hay de 1 a 3 oficiales por ronda, tengo que explicarme mas?
> 
> Si las hoods de seguridad no tienen defensas para que van a existir, para hacer que un oficial muera mas rapido? Es idiotico y es el problema que tienen las hoods de wintercoats de sec, es relleno inutil. Con darle esas defensas llegan a ser viables pero no lo recomendables, no se que le ves de negativo, ya tienen hasta una desventaja de stats.

Existen para verse cool. Por lo mismo que se le permite a plamaman, ipcs y otras razas debiles en combate estar en sec. Se supone que los wintercoats son como trajes bonitos para el frio con un motivo departamental. tu no solo quieres darles defensa de combate sino que tambien quieres equiparar un equipamento hecho para aguantar balas con equipamento que usas en invierno. sino que quieres hacer que un gorrito que te pones para cubrirte las orejas te proteja de la misma forma que un caso diseñado para aguantar balas. Como sea, si no quieres dar tu brazo a torcer, genial pero a mi no me parece bien esto asi que tocará esperar a que silver lo revise.

2020-11-27 22:51 UTC, SagaStars commented
>Quieres hacer que un gorrito que te pones para cubrirte las orejas te proteja de la misma forma que un caso diseñado para aguantar balas.

La cosa es que hay muchos objetos asi en sec, como la boina y gorra del HoS que protegen hasta aun mas que un security helmet, ya es algo normal. Lo mejor seria mantener la consistencia imo.

Bueno, a esperar la opinion de silver :eyes:

* rapido por favor que quiero hacer las otras winter coats de los demas deparmentos*

2020-11-27 22:58 UTC, Evankhell561 commented
> > Quieres hacer que un gorrito que te pones para cubrirte las orejas te proteja de la misma forma que un caso diseñado para aguantar balas.
> 
> La cosa es que hay muchos objetos asi en sec, como la boina y gorra del HoS que protegen hasta aun mas que un security helmet, ya es algo normal. Lo mejor seria mantener la consistencia imo.
> 
> Bueno, a esperar la opinion de silver 👀
> 
> _rapido por favor que quiero hacer las otras winter coats de los demas deparmentos_

Y yo no soy fan de esas cosas, es paradise quien las ha metido ahi y no nosotros, si fuera por mi las revertiria. ;o quiero continuar esa politica y si alguien quiere cambiarla me pareceria bien. Tampoco es la primera vez que tengamos una politica contraria a paradise por ejemplo. Genetista, accesos, roles de los jobs.

2020-11-27 22:59 UTC, Evankhell561 commented
> _rapido por favor que quiero hacer las otras winter coats de los demas deparmentos_

no veo que te detenga a hacer no sé, un pr con ya sabes, sprites que serán basicamente instamargeados y... luego ponernos a discutir sobre balance.

2020-11-28 02:11 UTC, SagaStars commented
> > _rapido por favor que quiero hacer las otras winter coats de los demas deparmentos_
> 
> no veo que te detenga a hacer no sé, un pr con ya sabes, sprites que serán basicamente instamargeados y... luego ponernos a discutir sobre balance.

Me pregunto cuantos cambios de balance traera saga del futuro en su proximo PR 🤔

2020-12-07 03:35 UTC, Evankhell561 commented
conflictos

2020-12-10 04:29 UTC, closed without merging