Tweak MouthCover(?) -> Cant eat or drink
Helixis/Paradise pull request #755
Opened 2020-11-18 06:35 UTC by Spircen

## What Does This PR Do
Agrega una validación en la cual si tu boca esta cubierta no puedes comer o beber. Esto no aplica para vox o plasmaman por razones de balance a la par que los parches tampoco son afectados. Para evitar que este PR sea muy disruptivo a mecánicas actuales de momento las píldoras también pueden ser insertadas digeridas con mascara puesta.

## Why It's Good For The Game
Me parece un balance considerablemente justo, esto se hace a partir del uso de las FLAGS que posee la ropa esto quiere decir que si desajustas una mascara obviamente te dejara comer en cuanto la retirar de tu rostro. Haciendo que esa funcionalidad tenga algo de uso. No, esto no quiere decir que si tienes un cigarro en la boca no puedes comer. 

Referente a la pregunta de ¿Y los spacesuits por que no entran? Pues es facil, aqui hay todo un archivo entero de una mision de [Apollo 15](https://www.hq.nasa.gov/alsj/alsj-DrinkFood.html) donde muestra un hardsuit no bloquea la capacidad de beber o comer.

## Images of changes

![image](https://user-images.githubusercontent.com/46639834/99493826-8bc6d000-2935-11eb-9972-66221916829b.png)

## Changelog
:cl:
tweak: MouthCover(?) -> Cant eat or drink
/:cl:

2020-11-21 00:59 UTC, Evankhell561 commented on code/modules/mob/living/carbon/carbon.dm
> +		if(wear_mask && (wear_mask.flags_cover & MASKCOVERSMOUTH) && !wear_mask.mask_adjusted)
que es wear_mask.mask_adjusted?

2020-11-21 01:02 UTC, Evankhell561 requested changes

2020-11-21 01:02 UTC, Evankhell561 commented on code/modules/mob/living/carbon/carbon.dm
> +	///Validacion de mascara INICIO by Spircen
puedes meter todo tu codigo nuevo en un proc nuevo de los carbon.
/mob/living/carbon/proc/can_eat(var/obj/item/reagent_containers/food/toEat, mob/user, var/bitesize_override)
y este proc debe retornar true o false.
y en el proc eay de paradise solo pones 
`if(!can_eat(toEat, user, bitesize_override)
    return FALSE`
esto evitara todas estas lineas de codigo en un archivo de paradise y lo cambiará por 3 simples lineas.

2020-11-22 07:40 UTC, Spircen commented on code/modules/mob/living/carbon/carbon.dm
> +		if(wear_mask && (wear_mask.flags_cover & MASKCOVERSMOUTH) && !wear_mask.mask_adjusted)
Puedes tener una mascara ajustada para desbloquear la boca pero actualmente no hacia nada por que realmente no llegas a necesitar quitar la mascara mas que para cosas estéticas.

2020-11-22 07:40 UTC, Spircen commented on code/modules/mob/living/carbon/carbon.dm
> +	///Validacion de mascara INICIO by Spircen
Podría pero hacer enrutamiento de procesos en cosas que se ocupan tan seguido como la comida el cual requiere una validación solo hace que consuma mas procesamiento, prefiero todo quede de esta forma.

2020-11-22 07:46 UTC, Evankhell561 commented on code/modules/mob/living/carbon/carbon.dm
> +	///Validacion de mascara INICIO by Spircen
meter esto a un proc no afectará el consumo de recursos en lo absoluto. hazlo de la manera en que lo pido.

2020-11-22 08:56 UTC, Evankhell561 requested changes

2020-11-22 08:56 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/carbon/carbon.dm
> +				covered = 1
```suggestion
		if((C.head && (C.head.flags_cover & HEADCOVERSMOUTH)) || (C.wear_mask && (C.wear_mask.flags_cover & MASKCOVERSMOUTH) && !C.wear_mask.mask_adjusted))
			if(!(istype(wear_mask, /obj/item/clothing/mask/breath) && (istype(head, /obj/item/clothing/head/helmet/space/plasmaman) || isvox(src))))
				covered = TRUE
```

2020-11-22 09:00 UTC, Evankhell561 requested changes

2020-11-22 09:00 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/carbon/carbon.dm
> +	var/skip_check = 0
usa TRUES Y FALSES cuando necesites booleanos

2020-11-22 09:00 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/carbon/carbon.dm
> +		var/snowflek = 0
esta variable es innecesaria

2020-11-22 09:10 UTC, closed without merging