Nuevos Kinetic Accelerators especializados.
Helixis/Paradise pull request #762
Opened 2020-11-21 02:20 UTC by X404ErrorX

## What Does This PR Do
Este Pr agrega 6 nuevos Kinetic Accelerators con características únicas.

## Why It's Good For The Game
Estos nuevos KA dan muchas nuevas posibilidades a los jugadores de minería para crear sus propias builds y probar distintas maneras de enfrentar los retos de lavaland pudiendo hacer que su KA se adapte mejor a lo que el necesita o quiere conseguir.

Este PR es un port de Skyrat con varias modificaciones de jugabilidad y sprites.

## Images of changes

![](https://media.discordapp.net/attachments/339954056653045761/779490326024159242/unknown.png)

Tipos de KAs y sus precios:

Kinetic Accelerator Premium: Este KA es una versión del KA básico, dispone de un pequeño aumento de daño, rango y enfriamiento, dispone de la misma cantidad de espacio. un KA versátil aunque bastante caro. Precio: 8.000.

![](https://cdn.discordapp.com/attachments/339954056653045761/779493610747199509/unknown.png)

Rapid Kinetic Accelerator: Este KA se basa en la velocidad de ataque, tiene un alcance escaso y un daño bastante inferior pero su velocidad al disparar es muy buena, tiene un espacio reducido por lo que no es muy modificable aun así se le pueden poner algunos modkits. Precio: 15.000.

![](https://cdn.discordapp.com/attachments/339954056653045761/779493667098198036/unknown.png)

Heavy Kinetic Accelerator: Sin duda el KA con mas daño de todos, este robusto KA puede disparar con gran potencia para producir gran daño, el problema es que se sacrifican su velocidad de ataque y su rango para conseguir esto, solo es capaz de disparar a dos tiles de distancia y cada mucho tiempo ademas de no tener espacio casi para modificarlo, aun así es un KA muy util para quien quiera arriesgarse a combatir de cerca pero que no quiere usar un Kc. Precio: 15.000.

![](https://cdn.discordapp.com/attachments/339954056653045761/779493578975215616/unknown.png)

Precise Kinetic Accelerator: El KA con mas rango de todos, este KA fue modificado para poder disparar a gran distancia por lo que se le agrego una mira telescópica con el objetivo de que funcione como un rifle de francotirador, por el otro lado su velocidad de ataque es bastante inferior al resto de KAs y su daño no es demasiado alto, ademas de que su espacio para modificar es bastante bajo, Un Ka para quien no se quiera arriesgar mucho y tenga paciencia. Precio: 15.000.

![](https://cdn.discordapp.com/attachments/339954056653045761/779493690912538624/unknown.png)

Modular Kinetic Accelerator: Una versión aun mejorada del Premium KA, con espacio extra para modificaciones sin duda el KA mas versátil de todos aunque bastante caro, cualquiera que lo quiera adquirir tendrá que ahorrar bastantes puntos o minar mucho para conseguirlo. Precio: 20.000.

![](https://cdn.discordapp.com/attachments/339954056653045761/779493523454951504/unknown.png)

Custom Kinetic Accelerator: Esto mas que un KA es un kit que te permite crear tu propio KA a tu gusto, Inicia con estatus prácticamente inexistentes pero con una gran cantidad de espacio para modificarlo, es un KA sumamente caro sumando su precio y las partes que hay que comprar pero para quien tenga muchos puntos ahorrados le sera interesante. Precio: 30.000

![](https://cdn.discordapp.com/attachments/339954056653045761/779493719623598140/unknown.png)

## Changelog
:cl:
add: Nuevos Kinetic Accelerators.
/:cl:

2020-11-21 03:15 UTC, Evankhell561 requested changes

2020-11-21 03:15 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +/obj/item/ammo_casing/energy/kinetic/premium
que hace esto aca?

2020-11-21 03:24 UTC, Evankhell561 requested changes

2020-11-21 03:24 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	icon_state = null
esto es inecesario

2020-11-21 03:24 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage_type = BRUTE
innecesario

2020-11-21 03:24 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	flag = "bomb"
innecesario

2020-11-21 03:24 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	log_override = TRUE
innecesario

2020-11-21 03:24 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	flag = "bomb"
innecesario

2020-11-21 03:24 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage_type = BRUTE
innecesario

2020-11-21 03:24 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	name = "kinetic force"
innecesario

2020-11-21 03:26 UTC, Evankhell561 requested changes

2020-11-21 03:26 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	log_override = TRUE
innecesario

2020-11-21 03:26 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage_type = BRUTE
innecesario

2020-11-21 03:26 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	flag = "bomb"
innecesario

2020-11-21 03:27 UTC, Evankhell561 requested changes
intenta no modificar dmis de paradise

2020-11-21 03:30 UTC, Evankhell561 requested changes

2020-11-21 03:30 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	item_state = "kineticgun"
innecesario

2020-11-21 03:30 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	icon = 'icons/obj/guns/energy.dmi'
mueve esto a hispania

2020-11-21 03:34 UTC, Evankhell561 requested changes

2020-11-21 03:34 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	name = "premium accelerator"
en todos los nombres pon kinetic accelerator y no solo accelerator

2020-11-21 03:34 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	icon = 'icons/hispania/obj/guns/energy.dmi'
aca pusiste bien la ruta y arriba no, raro.

2020-11-21 03:34 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	item_state = "kineticgun"
innecesario.

2020-11-21 03:34 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +/obj/item/gun/energy/kinetic_accelerator/premiumka
se supone que estos son kinetics especializados pero este primium original es simplemente superior a uno normal, no tiene ninguna especializacion.

2020-11-21 03:34 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	item_state = "kineticgun"
innecesario.

2020-11-21 03:35 UTC, Evankhell561 requested changes

2020-11-21 03:35 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage_type = BRUTE
innecesario.

2020-11-21 03:35 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	flag = "bomb"
innecesario.

2020-11-21 03:35 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	log_override = TRUE
innecesario.

2020-11-21 03:37 UTC, Evankhell561 requested changes

2020-11-21 03:37 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	log_override = TRUE
innecesario.

2020-11-21 03:37 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	flag = "bomb"
innecesario.

2020-11-21 03:37 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage_type = BRUTE
innecesario.

2020-11-21 03:37 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	log_override = TRUE
innecesario.

2020-11-21 03:37 UTC, Evankhell561 requested changes

2020-11-21 03:37 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	flag = "bomb"
innecesario.

2020-11-21 03:37 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage_type = BRUTE
innecesario.

2020-11-22 07:20 UTC, Evankhell561 requested changes

2020-11-22 07:20 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	flag = "bomb"
esto aun no ha sido borrado.

2020-11-22 07:20 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	damage_type = BRUTE
ni esto

2020-11-22 07:20 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	icon_state = null
ni esto

2020-11-22 07:20 UTC, Evankhell561 commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	item_state = "kineticgun"
esto aun no ha sido borrado

2020-11-22 07:28 UTC, X404ErrorX commented on code/HISPANIA/modules/projectiles/guns/energy/kinetic_accelerator.dm
> +	flag = "bomb"
El premium Ka prefiero dejarlo de esa manera para que sea mas fácil su modificación en un futuro en caso de que alguien lo necesite, asi lo tendrá a mano y de paso le sera mas entendible como funciona el código, lo mismo con los otros dos Request changes.

2020-12-07 03:34 UTC, Evankhell561 commented
conflictos

2020-12-16 22:47 UTC, closed without merging