Warping crossbreeding
Helixis/Paradise pull request #764
Opened 2020-11-22 19:55 UTC by josesitomartinez

## What Does This PR Do
Me vuelvo loco y añado mas cosas para el crossbreeding, en este caso los tipo warping.

Entre los cores agregados tenemos:

Gris: Al colocar 8 extractos de slime sobre la runa, genera un slime adulto del mismo color.
Naranja: Cualquier persona que pase sobre la runa se prendera en fuego.
Azul: Crea una runa que resbala a todo el que pase por encima.
Morado: Genera un advanced trauma kit o un advance burn kit al colocar tela o plastico sobre la runa.
Metal: La runa se comporta como una pared invisible
Amarillo: Funciona como un generador, recargando el apc del area donde se encuentre la runa.
Morado oscuro: La runa funciona como un cristal que lentamente genera plasma dust
Azul oscuro: Toda persona que pase encima de la runa vera como su temperatura corporal disminuye
Plata: Absorbe los nutrientes de cualquier comida que sea colocada en la runa. Cuando una persona pase por encima de esta, los nutrientes pasaran a su cuerpo hasta que se llene
Bluespace: La última persona que camine sobre la runa intercambiará su posicion con la siguiente persona que la pise.
Pirita: Al pasar sobre la runa, la persona cambiara a un color aleatorio
Aceite: Esta runa funciona como una barrera que evita el paso de atmos
Negro: Funciona igual que la bluespace, simplemente que intercambia las especies de las dos personas que pisen la runa

## Why It's Good For The Game
Añade mas cosas para que xenobiologia sea mas divertida. Ademas, nadie esta usando el cross y creo que esto es una buena manera de recordarle a la gente que esta mecanica todavia existe

## Images of changes
LO

## Changelog
:cl:
add: warping crossbreeding
/:cl:

2020-11-23 05:25 UTC, Evankhell561 requested changes

2020-11-23 05:25 UTC, Evankhell561 commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/warping.dm
> +		second_person = null
creo que si no pones una nueva linea aca no pasa el bot

2020-11-23 05:31 UTC, Evankhell561 requested changes

2020-11-23 05:31 UTC, Evankhell561 commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/warping.dm
> +/obj/effect/warped_rune/greyspace/Destroy()
```suggestion
/obj/effect/warped_rune/greyspace/Destroy()
	STOP_PROCESSMIERDAS(SSprocessing, src)
```

2020-11-23 05:40 UTC, Evankhell561 requested changes
en general donde haya un `START_PROCESSING` en el Initialize debes poner un `STOP_PROCESSING` en el proc Destroy.

2020-11-26 13:32 UTC, Evankhell561 requested changes
DEJAD DE HACER PUTOS PRS EN WIP. En fin puedes convertirlo en draft, por favor?

2020-11-26 13:55 UTC, josesitomartinez commented
no

2020-11-26 13:57 UTC, Evankhell561 requested changes

2020-11-26 13:57 UTC, Evankhell561 commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/charged.dm
> -/obj/item/slimecross/charged/gold/Destroy()
why?

2020-11-26 13:58 UTC, josesitomartinez commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/charged.dm
> -/obj/item/slimecross/charged/gold/Destroy()
ese core no existe, es un codigo basura que quedo en medio de todo

2020-11-26 14:14 UTC, TotoMC-13 commented
[Ni idea que hago aca pero hola](https://thumbs.dreamstime.com/z/trollface-internet-troll-d-illustration-laughing-head-isolated-41981991.jpg)

2020-11-26 14:15 UTC, Evankhell561 requested changes

2020-11-26 14:15 UTC, Evankhell561 commented on code/modules/research/xenobiology/xenobiology.dm
> +			Uses = 5
```suggestion
			Uses = max(Uses,5)
```

2020-11-27 18:55 UTC, Evankhell561 requested changes

2020-11-27 18:55 UTC, Evankhell561 commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/warping.dm
> +    STOP_PROCESSING(SSprocessing, src)
creo que estas usando espacios en vez de taps aca.

2020-11-27 18:55 UTC, Evankhell561 commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/warping.dm
> +    .=..()
y aca

2020-11-27 18:55 UTC, Evankhell561 commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/warping.dm
> +    desc = "Everyone is everywhere at once, yet so far away from each other"
reemplaza todos los 4 espacios en tu code por tabs, donde haga falta

2020-11-27 19:17 UTC, Evankhell561 requested changes

2020-11-27 19:17 UTC, Evankhell561 commented on code/HISPANIA/modules/research/xenobiology/crossbreeding/burning.dm
> +	reagents.remove_reagent("plasma_dust",  10)
```suggestion
	if(!reagents.has_reagent("plasma_dust", 10))
		to_chat(user, "<span class='warning'>This extract needs to be full of plasma to activate!</span>")
		return
	reagents.remove_reagent("plasma_dust", 10)
```

2020-11-27 19:22 UTC, merged