Nuevas criaturas Lava Imp & shambling miner, Lavaland mobs.
Helixis/Paradise pull request #765
Opened 2020-11-22 20:23 UTC by X404ErrorX

## What Does This PR Do
Este Pr agrega nuevas criaturas a lavaland con sus propios trofeos de Crusher, habilidades y tendrills

## Why It's Good For The Game
Estas nuevas criaturas darán mas variedad a la cantidad de posibles encuentros y combates que tendrán los mineros ademas de ofrecer 2 nuevos trofeos para los jugadores de Crusher.

Criaturas:

Imp: Un pequeño demonio que forma parte de los muchos servidores del rey Bubblegum habita lavaland y atacara a cualquiera que no este invitado a este mundo, si alguien se encuentra con el lo mas probable es que este intente hacerlo volar con una potente bola de fuego si esto no función usara sus propias garras para asesinar a sus victimas. El trofeo de esta criatura es el "Imp Skull"

![](https://cdn.discordapp.com/attachments/339954056653045761/780162929273077760/unknown.png)
 
Shambling miner: Esta criatura anteriormente era un minero pero fue consumido por la tormera y ahora no es mas que una carcasa de lo que fue, este minero recorrerá lavaland enloquecido y con el único objetivo de asesinar a cualquiera que no este bajo el yugo de la legion. El trofeo de esta criatura es "mask of a shambling miner"

![](https://cdn.discordapp.com/attachments/339954056653045761/780165624318918666/unknown.png)

## Images of changes

## Changelog
:cl:
add: Imp Lavaland mob
add: Shambling miner Lavaland mob
/:cl:

2020-11-23 05:26 UTC, Evankhell561 requested changes

2020-11-23 05:26 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +	ranged = 0
FALSE

2020-11-23 05:28 UTC, Evankhell561 requested changes

2020-11-23 05:28 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/imp.dm
> +	ranged = 1
TRUE

2020-11-23 20:48 UTC, Evankhell561 requested changes

2020-11-23 20:48 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +		new /obj/item/twohanded/kinetic_crusher(src.loc)
```suggestion
/mob/living/simple_animal/hostile/asteroid/miner/death(gibbed)
	if(prob(15))
		new /obj/item/twohanded/kinetic_crusher(src.loc)
	. = ..()
```

2020-12-01 14:00 UTC, SagaStars requested changes
## SAGA 👏  PR 👏  REVIEW
Aqui viene la lista de cambios que tienes que hacer, preparate.

**IMPS:** El mob esta bien, no es muy fuerte ni muy debil, toma mucho la distancia como factor para que ellos te derroten, pero hay ciertos detalles.
- El rango de la explosion es de 4 y en un lugar como lavaland que son pasillos de 2 tiles es imposible escapar de estas explosiones y llenan un pasillo de fuego por unos instantes, bajaselo a 1 o 2 haciendo un nuevo hijo de la ruta del proyectil.
- Cambiarle la sprite de muerto por que simplemente es fome, te dejo aqui un ejemplo:
![imp_dead](https://user-images.githubusercontent.com/55407528/100747663-bcd4e500-33b8-11eb-98f6-5a20feaf78ac.png)

**SHAMBLING MINER:** Okay, este si tiene sus problemas por que no veo a donde apunta el mob, en los comentarios dice que es lento y tanky, luego es super rapido y pega duro y encima spawnea en todos lados (Habian como 20). Quiero saber tu punto de como quieres que sea el mob, si va a ser uno tanky y lento, o la bestialidad que tenemos ahora que es basicamente un blood drunk jr.
- ![image](https://user-images.githubusercontent.com/55407528/100748431-b1ce8480-33b9-11eb-9f41-d5f38b0808a3.png) **LENTO???**
- Imposible de escapar de el, es estupidamente rapido y va a acabar con muchos mineros a early, van a triplicar el death rate de muertes a 10 minutos de partida ya te lo digo lol.
- P-Por que suelta piel de humano? Es una carcasa viviente a este punto ya no deberia de tener piel, se ha de haber descomponido.
- Cuando mueras ponle una sprite como esta:
![miner_dead](https://user-images.githubusercontent.com/55407528/100747667-be061200-33b8-11eb-989d-84592f767f25.png)
Una cascara que ya dejo de ser "poseida" por la tormenta de ceniza, lo veo mucho mas interesante a que simplemente se desplome al suelo. **Y quitarle el `move_force move_resist` cuando muera para que le puedas dar pull** que si no para mover el cuerpo o sacarlo del camino hay que gibbearlo, which makes no sense.
- Un minero saliendo de un tendrill es muy cursed y no tiene mucho sentido a lo establecido con la desc, estaria mejor si solo vagaran por los tuneles sin un spawner, solo tienes que quitar el spawner de la lista de spawns del `asteroid.dm`
- Como ya te habia dicho lo vuelvo a repetir creo que por 3° vez, quitarlos de las tendrills y que solo aparezcan en el mapa sin mas y en cambio subirle la prob del `crusher_drop_mod` en un +20%. (crusher_drop_mod = 45).

------------------------
_Puedes descargar los .png que deje y darle a import en los archivos `.dmi` para pasar las sprites_

Resuelve esta lista que te deje y los demas comentarios y culminamos con luz morada. 👁️ 
------------------------

2020-12-01 14:00 UTC, SagaStars commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +	H.force -= bonus_value
**FAIL.**
Estas sumandole el daño a `force`, no a `force_wielded` haciendo que no haga efecto alguno vaya a arreglarlo.

2020-12-01 14:00 UTC, SagaStars commented on code/game/turfs/simulated/floor/asteroid.dm
> +		SPAWN_MEGAFAUNA = 6, /mob/living/simple_animal/hostile/asteroid/goldgrub = 10, /mob/living/simple_animal/hostile/asteroid/imp = 30, /mob/living/simple_animal/hostile/asteroid/miner = 50,)
```suggestion
		/mob/living/simple_animal/hostile/asteroid/hivelord/legion/random = 30, /obj/structure/spawner/lavaland/legion = 3, /obj/structure/spawner/lavaland/plazmite = 3, /obj/structure/spawner/lavaland/imp = 3, /obj/structure/spawner/lavaland/miner = 1,
		SPAWN_MEGAFAUNA = 6, /mob/living/simple_animal/hostile/asteroid/goldgrub = 10, /mob/living/simple_animal/hostile/asteroid/imp = 30, /mob/living/simple_animal/hostile/asteroid/miner = 20,)
```
Demasiados, demasiados mineros, habian mas mineros que legions y goliaths era ridiculo. Ponselo a 15, deberian de ser raros y para agarrarte por sorpresa, no para encontrarte uno en cada tunel que vayas.

2020-12-01 14:00 UTC, SagaStars commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/imp.dm
> +
hurdurr espacio de mas

2020-12-01 14:00 UTC, SagaStars commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +/obj/item/crusher_trophy/blaster_tubes/mask
Esto esta mal, deberia ser `/obj/item/crusher_trophy/mask`, no `/obj/item/crusher_trophy/blaster_tubes/mask`
la ruta de `blaster_tubes` solo deberia ser usada por los trofeos que cambian el proyectil como tal, el tuyo solo sube el daño a melee.

Quita procs como `on_mark_aplication` y `on_projectile_fire`.

2020-12-01 14:00 UTC, SagaStars commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +	denied_type = /obj/item/crusher_trophy/blaster_tubes/mask
> Esto esta mal, deberia ser /obj/item/crusher_trophy/mask, no /obj/item/crusher_trophy/blaster_tubes/mask
> la ruta de blaster_tubes solo deberia ser usada por los trofeos que cambian el proyectil como tal, el tuyo solo sube el daño a melee.
> 
> Quita procs como on_mark_aplication y on_projectile_fire.

```suggestion
	denied_type = /obj/item/crusher_trophy/mask
```
Recuerda cambiarle la ruta

2020-12-01 18:30 UTC, X404ErrorX commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +/obj/item/crusher_trophy/blaster_tubes/mask
Me explique mal, lo que hace la mascara es que despues de dar la primera detonación el siguiente disparo del kc hace un poco de daño, por eso esta en blaster_tubes

2020-12-01 18:37 UTC, X404ErrorX commented on code/game/turfs/simulated/floor/asteroid.dm
> +		SPAWN_MEGAFAUNA = 6, /mob/living/simple_animal/hostile/asteroid/goldgrub = 10, /mob/living/simple_animal/hostile/asteroid/imp = 30, /mob/living/simple_animal/hostile/asteroid/miner = 50,)
Si te parece puedo quitar el tendril de los mineros y dejalos en 40, si no tinen tendrill tienen que ser bastantes, el resto de criaturas tienen tres tendrills, y ellos solamente, por otro lado podria dejar el tendrill y ponerlos en 20, hay que tener en cuenta que esta criatura hace referencia a los miles de mineros muertos en lavaland, es lógico que sean muchos.

2020-12-01 18:39 UTC, X404ErrorX commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +	H.force -= bonus_value
Lo que hace el daño es el disparo del kc después de una detonación.

2020-12-01 18:42 UTC, X404ErrorX commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/imp.dm
> +
Hablas del ultimo espacio? es la endline

2020-12-01 18:51 UTC, X404ErrorX commented
@SagaStars Con lo del IMP estoy desacuerdo, sobre lo del minero, Quizás la desc no es muy lógica, la quitar, este bicho tiene que ser rápido ya que de otra manera no puede hacer daño a sus enemigos, no es muy complicado tampoco, simplemente necesitas una zona en la cual escapar, su reacción da suficiente tiempo a pensar si vas o no a luchar contra el, sobre lo de que salga en un tendrill, a mi parecer si que tiene sentido, los legions, son prácticamente los mismo que los mineros, también te digo que tampoco hay que buscar mucha logica en lavaland, por que en un planeta volcánico hay rey demonios? o objetos que rompen la realidad? es simplemente un mundo magico. Por ultimo sobre lo de la carne humana, los mineros en algun momento fueron humanos, su carne este descompuesta o no aun esta por algunas zonas dentro del traje, algo de carne se le puede encontrar.

2020-12-01 18:52 UTC, X404ErrorX commented
@SagaStars Estas seguro que el minero no se puede arrastrar cuando muere? en mis test si que podia.

2020-12-01 18:57 UTC, Evankhell561 commented
> @SagaStars Con lo del IMP estoy desacuerdo, sobre lo del minero, Quizás la desc no es muy lógica
incluso los mundos magicos tienen logica. Si pones en una descripcion "es lento" y luego resulta ser rapido es contradictorio. Especialmente si los comentarios lo haces en el codigo y son vistos por los coders y no por los jugadores.

2020-12-01 19:03 UTC, X404ErrorX commented
@Evankhell561  por eso mismo dije que el comentario lo quitaría, sobre la lógica en un mundo mágico, es verdad que la tienen pero suele ser algo subjetiva, igualmente ya di una razón por lo cual es lógico que tengan tendrills.

2020-12-01 19:08 UTC, Evankhell561 commented on code/game/turfs/simulated/floor/asteroid.dm
> +		SPAWN_MEGAFAUNA = 6, /mob/living/simple_animal/hostile/asteroid/goldgrub = 10, /mob/living/simple_animal/hostile/asteroid/imp = 30, /mob/living/simple_animal/hostile/asteroid/miner = 50,)
que sea logico o no es algo más de lore, bien podrias explicarlo diciendo que no todos los mineros muertos han revivido ni usan la misma arma ni se ven iguales... pero creo que la review de saga apunta más al balance en lavaland.

2020-12-01 19:11 UTC, X404ErrorX commented on code/game/turfs/simulated/floor/asteroid.dm
> +		SPAWN_MEGAFAUNA = 6, /mob/living/simple_animal/hostile/asteroid/goldgrub = 10, /mob/living/simple_animal/hostile/asteroid/imp = 30, /mob/living/simple_animal/hostile/asteroid/miner = 50,)
La mía también, 20 mineros sin tendrill son muy pocos.

2020-12-01 19:13 UTC, SagaStars commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/imp.dm
> +
![image](https://user-images.githubusercontent.com/55407528/100783942-d0964080-33e4-11eb-8597-819507ebe63a.png)
Me refiero mas a que lo pongas asi, para que este consistente con el demas code.

2020-12-01 19:39 UTC, SagaStars commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +/obj/item/crusher_trophy/blaster_tubes/mask
Me estas diciendo que este trofeo es basicamente el del MEGAFAUNA colussus con el doble de daño y con la velocidad normal del proyectil? A un mob que quieres que se encuentre por todos lados. La respuesta es "No" busca un mejor efecto.

Ademas el code aun asi sigue sin funcionar por que se ta ha pasado el poner el `deadly shot = TRUE` en el proc de `on_mark_application`

2020-12-01 19:41 UTC, SagaStars commented on code/game/turfs/simulated/floor/asteroid.dm
> +		SPAWN_MEGAFAUNA = 6, /mob/living/simple_animal/hostile/asteroid/goldgrub = 10, /mob/living/simple_animal/hostile/asteroid/imp = 30, /mob/living/simple_animal/hostile/asteroid/miner = 50,)
Pasemos esto a los comentarios de abajo.

2020-12-01 19:54 UTC, X404ErrorX commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +/obj/item/crusher_trophy/blaster_tubes/mask
El colosus mete un slower ademas de un efecto adicional a la bala que lo hace parecer una cuchulla, aunque es verdad que hace demasiado daño en comparación, te parece si se lo bajo a 5?

2020-12-01 20:06 UTC, SagaStars commented
> @SagaStars Con lo del IMP estoy desacuerdo.

Care to explain why not tho

>Este bicho tiene que ser rápido ya que de otra manera no puede hacer daño a sus enemigos, no es muy complicado tampoco, simplemente necesitas una zona en la cual escapar, su reacción da suficiente tiempo a pensar si vas o no a luchar contra el, sobre lo de que salga en un tendrill, a mi parecer si que tiene sentido, los legions, son prácticamente los mismo que los mineros

No, no da tiempo para reconocer el peligro y decidir, solo da tiempo para prepararte que se te va a lanzar sobre ti y eso, es un hecho; si no lo tumbas antes de que se te acerque a ti va a llegar a ti. 

**¿Tengo un problema con que te alcance?**
 No.

 **¿Tengo un problema con que hayan 50 shambling miner con velocidades tan altas que la unica manera de escapar de ellos sea en una speedbike y que si te agarra un shambling miner + cualquier otro mob es gameover?** 
### **Muchos.**

>Por ultimo sobre lo de la carne humana, los mineros en algun momento fueron humanos, su carne este descompuesta o no aun esta por algunas zonas dentro del traje, algo de carne se le puede encontrar.

No estoy en contra con la carne y huesos, pero si con la piel de humano, el tejido humano se descompone muy rapido contradiciendo todo lo que has dicho por que deberia de estar recien muerto para aun tener piel, solo quitala.

2020-12-01 20:25 UTC, X404ErrorX commented
El numero de mineros sera disminuido a 20 solamente mas un tendrill, igualmente, el miner no es tan rapido, es verdad que en algun momento te va a terminar atrapando pero te da tiempo a llevarlo a una zona, tambien podes verlo desde lejos y evitar el combate con el, el 90% si te agarran entre dos es un gameover, si un ojo te ralentiza junto a un goliath lo mas probable es que estes muerto, si un ojo te realentiza junto a un legion no vas a poder atrapar al legion por lo que te va a spamear calaveras y tampoco vas a poder escapar, seguramente de ese encuentro salgas muy mal o muerto, y en este caso es igual, el chiste es estar preparado, lavaland tiene lugares donde minar es mas o menos seguro, cuando ya tenes quipo vas a explorar mas profundamente, lavaland es un complicado hay cosas que te insta matan, simplemente es cuestión de experiencia, que hacer y que no hacer.

2020-12-01 20:27 UTC, SagaStars commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/shamblingminer.dm
> +/obj/item/crusher_trophy/blaster_tubes/mask
Bien, me parece justo.

2020-12-01 20:42 UTC, SagaStars commented
Bien dejalos en 20 y con un tendrill, lo unico que me desagradaba era la existencia de un mob que apenas lo ves tienes que pelear si o si y estuviera en todos lados haciendo las cosas mas lentas por que para avanzar tienes que pelear con este mob, pero si hay menos el problema se arregla supongo.

2020-12-01 21:19 UTC, Evankhell561 requested changes

2020-12-01 21:19 UTC, Evankhell561 commented on code/HISPANIA/modules/mob/living/simple_animal/hostile/mining/imp.dm
> +	exp_fire= 2
```suggestion
	exp_fire = 2
```

2020-12-01 22:11 UTC, SagaStars approved these changes

2020-12-01 22:47 UTC, merged