Fix menciones innecesarias
Helixis/Paradise pull request #775
Opened 2020-11-28 17:02 UTC by TotoMC-13

## What Does This PR Do
Quita algunos mentions innecesarios

## Why It's Good For The Game
Evita que el bot nos torture

tweak: Solo borré la parte que hace que mencione al hispa staff

2020-11-28 22:24 UTC, Evankhell561 commented on code/controllers/subsystem/ticker.dm
> -	SSdiscord.send2discord_simple_noadmins("**\[Info]** Round has started")
raro, uno diria que noadmins significaria "no admins".

2020-11-29 00:26 UTC, TotoMC-13 commented on code/controllers/subsystem/ticker.dm
> -	SSdiscord.send2discord_simple_noadmins("**\[Info]** Round has started")
Es que eso si tiene el noadmins menciona al rol hispastaff, por eso lo quite en varias cosas ya que era innecesario y spameaba menciones

2020-11-29 00:33 UTC, Evankhell561 commented on code/controllers/subsystem/ticker.dm
> -	SSdiscord.send2discord_simple_noadmins("**\[Info]** Round has started")
perfecto

2020-11-29 00:35 UTC, Evankhell561 approved these changes
cuando añadas el comentario margeo esto.

2020-11-29 00:35 UTC, Evankhell561 commented on code/controllers/subsystem/ticker.dm
> +	SSdiscord.send2discord_simple("**\[Info]** Round has started")
Comenta en esta linea //el send2discord_simple_noadmins pienaba a los admins de hispania y sen2discord_simple no lo hace.

2020-11-29 01:19 UTC, Evankhell561 requested changes
también debes arregalr el changelog.

2020-11-29 04:26 UTC, Evankhell561 commented
especifica que es en discord en el changelog.

2020-11-29 16:25 UTC, merged