New round mention
Helixis/Paradise pull request #776
Opened 2020-11-28 18:42 UTC by TotoMC-13

## What Does This PR Do
Menciona al rol new round cuando termina una roda

## Why It's Good For The Game
porque.... [esta es la razón](https://cdn.discordapp.com/attachments/387645048386486273/782314784325894164/image0-1.gif)

tweak: Cambios en un par de archivos, solo agregue una variable

2020-11-28 22:22 UTC, Evankhell561 requested changes

2020-11-28 22:22 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +				if("discord_webhooks_newround_role_id")
mete esta configuracion en el archivo config.txt de la carpeta example para que los que descarguen nuestro repo sepan que existe.

2020-11-28 22:22 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +					discord_newround_role_id = "[value]" // Este comentario no tiene ningun sentido pero, Hola, todo bien?
aca puedes poner como comentario algo como "toma el valor puesto en el archivo config.txt" si pondras un comentario, que sea ilustrativo.

2020-11-28 22:22 UTC, Evankhell561 commented on code/game/gamemodes/game_mode.dm
> +	SSdiscord.send2discord_simple(DISCORD_WEBHOOK_PRIMARY, "Una ronda en modo [name] acaba de terminar - [surviving_total] supervivientes, [ghosts] muertos. <@&[config.discord_newround_role_id]> ")
```suggestion
	SSdiscord.send2discord_simple(DISCORD_WEBHOOK_PRIMARY, "Una ronda en modo [name] acaba de terminar - [surviving_total] supervivientes, [ghosts] muertos. [config.discord_newround_role_id]")
```
no estoy seguro de este cambio pero me parece que si hiciste bien tu trabajo en el archivo de configuracion es mi forma la correcta. de todos modos es solo una sugerencia para mantener todo organizado y en la misma forma de escribir. si en otro archivo escriben esto de la forma en que tu lo haces... pues entonces es asi. aun no he revisado.

2020-11-28 22:22 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +	var/discord_newround_role_id = null // Intentional null usage
no inicialices variables como null. y si vas a comentarla pon algo como "inicia en null pero luego toma el valor del archivo config"

2020-11-28 23:29 UTC, Evankhell561 commented on code/game/gamemodes/game_mode.dm
> +	SSdiscord.send2discord_simple(DISCORD_WEBHOOK_PRIMARY, "Una ronda en modo [name] acaba de terminar - [surviving_total] supervivientes, [ghosts] muertos. <@&[config.discord_newround_role_id]> ")
toma esto como una peticion apra que verifiques algo no una solicitud de cambio.

2020-11-29 00:14 UTC, TotoMC-13 commented on code/game/gamemodes/game_mode.dm
> +	SSdiscord.send2discord_simple(DISCORD_WEBHOOK_PRIMARY, "Una ronda en modo [name] acaba de terminar - [surviving_total] supervivientes, [ghosts] muertos. <@&[config.discord_newround_role_id]> ")
Creería que va como lo puse yo ya que lo único que va en .config es la ID del rol y el @& es la parte que hace que lo mencione
<img width="464" alt="Screenshot_1" src="https://user-images.githubusercontent.com/52181149/100528726-892e6b00-31be-11eb-826d-18eb3613412b.png">

2020-11-29 00:17 UTC, Evankhell561 commented on code/game/gamemodes/game_mode.dm
> +	SSdiscord.send2discord_simple(DISCORD_WEBHOOK_PRIMARY, "Una ronda en modo [name] acaba de terminar - [surviving_total] supervivientes, [ghosts] muertos. <@&[config.discord_newround_role_id]> ")
perfecto.

2020-11-29 00:36 UTC, Evankhell561 requested changes

2020-11-29 00:36 UTC, Evankhell561 commented on code/datums/discord.dm
> +/datum/discord_embed/embed/new_round
wtf

2020-11-29 00:36 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +	var/discord_newround_role_id = null // Intentional null usage, toma el valor del archivo .config
no inicialices una variable como null

2020-11-29 00:37 UTC, TotoMC-13 commented on code/controllers/configuration.dm
> +	var/discord_newround_role_id = null // Intentional null usage, toma el valor del archivo .config
pero si el discord_admin_role_id esta igual

2020-11-29 00:38 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +	var/discord_newround_role_id = null // Intentional null usage, toma el valor del archivo .config
he dicho, no inicialices una variable como null. Que en Paradise practiquen la coprofagia no significa que Hispania tenga que hacerlo.

2020-11-29 00:39 UTC, TotoMC-13 commented on code/controllers/configuration.dm
> +	var/discord_newround_role_id = null // Intentional null usage, toma el valor del archivo .config
Pues entonces que debería poner?

2020-11-29 00:40 UTC, Evankhell561 requested changes

2020-11-29 00:40 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +	var/discord_newround_role_id = null // Intentional null usage, toma el valor del archivo .config
```suggestion
	var/discord_newround_role_id // Intentional null usage, toma el valor del archivo .config
```

2020-11-29 01:02 UTC, Evankhell561 requested changes

2020-11-29 01:02 UTC, Evankhell561 commented on code/datums/discord.dm
> +/datum/discord_embed/embed/new_round
wtfx2

2020-11-29 01:02 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +	var/discord_newround_role_id // Intentional null usage, toma el valor del archivo .config
![image](https://user-images.githubusercontent.com/49106866/100529347-0658e080-31bd-11eb-9cd4-6249e719771e.png)

2020-11-29 01:04 UTC, TotoMC-13 commented on code/datums/discord.dm
> +/datum/discord_embed/embed/new_round
wtfx4

2020-11-29 01:15 UTC, Evankhell561 requested changes

2020-11-29 01:15 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +	var/discord_newround_role_id // Intentional null usage, toma el valor del archivo .config
```suggestion
	var/discord_newround_role_id //toma el valor del archivo config.txt
```

2020-11-29 01:21 UTC, Evankhell561 requested changes
esto estará listo cuando arregles el echanglog

2020-11-29 02:38 UTC, Evankhell561 commented
> add: Agrega una variable y agrega unas líneas en example dentro de config
no pongas esto en el changelog. Deberias poner "ahora el rol que menciona la funcion new round se puede elegir mediante la configuracion.

2020-11-29 04:26 UTC, Evankhell561 commented
tambien especifica que te refieres al bot de discord o la iintegracion con discord

2020-11-29 04:28 UTC, Evankhell561 requested changes

2020-11-29 04:28 UTC, Evankhell561 commented on code/controllers/configuration.dm
> +					discord_newround_role_id = "[value]" // This MUST be a string because BYOND doesnt like massive integers
tambien añade que esta es una variable hispana, el archivo config suele cambiar periodicamente.

2020-11-29 15:57 UTC, TotoMC-13 commented
### Si veo una review mas me voy a suicidar
[A](https://tenor.com/1NJn.gif)

2020-11-29 15:59 UTC, merged