Vida de los Goliath pero bien hecho
Helixis/Paradise pull request #786
Opened 2020-12-03 01:11 UTC by PotatoTheDeveloper

Este pr no es mio, solo lo traje de los pr rechazados de paradise y lo modifique y adapte a nuestro code actual.
Link al pr original: https://github.com/ParadiseSS13/Paradise/pull/13075

## What Does This PR Do
Añade la posibilidad de domesticar goliaths, mejorarlos y su crecimiento desde bebes hasta adultos, sumado a que el ancient goliath ahora es mas dificil de vencer ya que tiene una mecanica especial.

## Why It's Good For The Game
Le añade profundidad a lavaland y es un implemento bastante interesante para esos mineros que quieren usar su tiempo para otras cosas que no sea matar jefes indiscriminadamente o simplemente se sientan solos autisteando en lavaland.

## Changelog
:cl:
add: Añade los goliaths juveniles y subadultos
add: Sistema para domesticar goliaths
add: Goliaths controlados por jugadores
add: Un nuevo tipo de goliath volcanico
add: Nueva habilidad para el Ancient Goliath
tweak: Los goliaths ahora regeneran vida MUY lentamente
/:cl:

2020-12-03 01:16 UTC, Danaleja2005 commented
Otro pr para la misma vaina? muh mal Patata

2020-12-03 01:57 UTC, Evankhell561 requested changes

2020-12-03 01:57 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> -	anchored = TRUE
por qué eliminas esto de paradise? devuelvelo.

2020-12-03 01:57 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	butcher_results = list(/obj/item/reagent_containers/food/snacks/monstermeat/goliath = 2, /obj/item/stack/sheet/animalhide/goliath_hide = 1, /obj/item/stack/sheet/bone = 2)
si no vas a tocar esto apra nada no ponga este espacio acá.

2020-12-03 01:57 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	butcher_results = list(/obj/item/reagent_containers/food/snacks/monstermeat/goliath = 2, /obj/item/stack/sheet/bone = 2)
si no modificas esto apra otra cosa tampoco pongas un espacio. solo dará conflictos.

2020-12-03 01:58 UTC, PotatoTheDeveloper commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> -	anchored = TRUE
evan esta en paradise.....

2020-12-03 01:58 UTC, PotatoTheDeveloper commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	butcher_results = list(/obj/item/reagent_containers/food/snacks/monstermeat/goliath = 2, /obj/item/stack/sheet/animalhide/goliath_hide = 1, /obj/item/stack/sheet/bone = 2)
EVAN QUE PUSE UN LOOT EXTRA

2020-12-03 01:59 UTC, PotatoTheDeveloper commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	butcher_results = list(/obj/item/reagent_containers/food/snacks/monstermeat/goliath = 2, /obj/item/stack/sheet/bone = 2)
EVAN QUE HAY LOOT EXTRA x2

2020-12-03 02:35 UTC, Evankhell561 requested changes

2020-12-03 02:35 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	return INITIALIZE_HINT_QDEL
esto hará que el goliath normal nunca se genere. Es decir que o tienes un anciano (con una prob de 1) o tienes un juvenil con una prob de 10 pero jamas tendrás un goliath normalito. y eso es un problema.

2020-12-03 02:56 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	growth = 599
pon esto en seiscientos y aumentale la vida con respecto al juvenil en 150 extra

2020-12-03 03:01 UTC, Evankhell561 requested changes

2020-12-03 03:01 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +/mob/living/simple_animal/hostile/asteroid/goliath/death()
ya existe el proc death para los goliaths en paradise, fusiona el otro con el tuyo.

2020-12-03 03:03 UTC, Evankhell561 requested changes

2020-12-03 03:03 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	growth = 599
el sub adult deberia tener speed 2

2020-12-03 06:14 UTC, Evankhell561 requested changes, later dismissed

2020-12-03 06:14 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	add_draconian_effect(draconian_overlay)
pon esto antes del ..(gibbed)

2020-12-07 03:50 UTC, Evankhell561 requested changes

2020-12-07 03:50 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	var/draconian = NOT_DRACONIAN // Can be NOT_DRACONIAN, DRACONIAN, FULL_DRACONIAN.
no veo que esto cambie en ningun momento, por qué lo añades?

2020-12-07 03:50 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +#define GROWTH_MAX 1200
envia a estos defines a su propio archivo para que no tengas que repetirlos, tambien deberias quitar el undefine.

2020-12-07 03:50 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	..()
el proc destroy siempre debe retornar algo, ponle . = ..() en vez de ..(), tambien, llamar al pariente debe ser lo ultimo que hagas al usar el proc destroy

2020-12-07 03:59 UTC, Evankhell561 requested changes

2020-12-07 03:59 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	butcher_results = list(/obj/item/reagent_containers/food/snacks/monstermeat/goliath = 2, /obj/item/stack/sheet/bone = 2)
no le des a resolver caundo no has hecho lo que pedi

2020-12-07 03:59 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	if(amount > 0)
why?

2020-12-07 03:59 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	loot = list()
esta lista debe irse llenando a medida que el goliath crece.

2020-12-07 04:02 UTC, Evankhell561 requested changes

2020-12-07 04:02 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	if(draconian == NOT_DRACONIAN)
draconian segun veo en tu code siempre sera igual a not dragonian asi que nunca hará nada

2020-12-07 04:02 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	var/status
declara esta variable en la linea 263, justo antes de que vayas a usarla, no acá.

2020-12-07 04:02 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	var/mob/living/simple_animal/hostile/asteroid/goliath/beast/ancient/leader = null
no inicialices variables como null

2020-12-07 04:10 UTC, Evankhell561 requested changes

2020-12-07 04:10 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +		if(istype(G, /mob/living/simple_animal/hostile/asteroid/goliath) && G.growth_stage == ADULT)
```suggestion
		if((istype(G, /mob/living/simple_animal/hostile/asteroid/goliath) && G.growth_stage == ADULT) || !istype(G, /mob/living/simple_animal/hostile/asteroid/goliath))
```
si el spawner no es un goliath entonces deberia mantener el efecto anterior.

2020-12-07 04:10 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	var/mob/living/simple_animal/hostile/asteroid/goliath/G = spawner
no entinedo la necesidad de declarar G cuando en la linea de abajo pudiste hacer. esto:
if(istype(spawner, /mob/living/simple_animal/hostile/asteroid/goliath) 
la variable G me parece inutil.

2020-12-07 04:19 UTC, Evankhell561 requested changes

2020-12-07 04:19 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +/mob/living/simple_animal/hostile/asteroid/goliath/revive()
hay dos procs llamados revive, elimina este que es una copia del otor.

2020-12-10 03:29 UTC, PotatoTheDeveloper commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +/mob/living/simple_animal/hostile/asteroid/goliath/revive()
ya elimine 1 listardo

2020-12-10 03:35 UTC, Evankhell561 requested changes

2020-12-10 03:35 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	var/growth = 1200 // Out of 1200.
```suggestion
	var/growth = GROWTH_MAX //1200.
```

2020-12-10 03:35 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	. = ..()
lo primero que deberias hacer acá luego del . = ..() es comprobar si el goliath esá vivo o no y si no lo está, salir de este proc con un return FALSE puesto que segun veo nada en tu code tiene sentido en caso de que esté vivo. si me equivoco me avisas.

2020-12-10 03:35 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	..(gibbed)
el ..() va de ultimo

2020-12-10 03:35 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	loot = list()
según veo el beast no tiene loot por lo que esto seria solo una variable repetida. en general elimina todos los loot = list() de tu code.

2020-12-10 03:44 UTC, Evankhell561 requested changes

2020-12-10 03:44 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +		if((aux_tentacles != 0) || (growth_stage == JUVENILE && draconian != NOT_DRACONIAN))
lo primero que deberias hacer en este proc es ver si vas a generar los tentaculos extra y fijar cuantos serán, luego poner algo como esto
`visible_message("<span class='warning'>[src] digs [aux_tentacles + extra_tentacles  > 0 ? "its tentacles " : "a tentacle"] under [target]!</span>")`
otra cosa es que tampoco entiendo por qué si cada status del goliath tiene una cantidad de tencaculos extra distintos para cada uno, necesitas añadir otro en caso de que el goliath sea un anciano. bastaria con cambair la var aux_tentacles  para cada nivel de crecimiento.

2020-12-10 03:46 UTC, Evankhell561 requested changes

2020-12-10 03:46 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	var/extra_tentacles = 0
deberias declarar esta variable luego del primer return debido a que antes de pasar el primer return de este proc es inutil esta var, asi como que tampoco entineod para que la nitas si cada nivel de crecimiento tiene una cantidad de tentaculs extra distintos.

2020-12-10 03:56 UTC, Evankhell561 requested changes

2020-12-10 03:56 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	if(growth >= 1200 && growth_stage == SUBADULT && !stat) // Grow to adult
GROWTH_MAX

2020-12-10 03:56 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +			tame_progress += rand(950, 1200)
GROWTH_MAX

2020-12-10 04:00 UTC, Evankhell561 requested changes

2020-12-10 04:00 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	if(tame_progress >= 600 && tame_stage == WILD) // Become neutral
veo que 600 es una var importante en tu codigo, haz un define con  él.

2020-12-10 04:00 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	if(tame_progress <= 599 && tame_stage != WILD) // Become feral if left alone for too long
esto esta bien pero es mejor colocar tame_progress < 600

2020-12-10 04:00 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	return
este return sobra si no retornarás nada mejor no ponerlo.

2020-12-10 04:02 UTC, Evankhell561 requested changes

2020-12-10 04:02 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	gender = NEUTER
por qué le añades esto?

2020-12-10 04:02 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	sentience_type = SENTIENCE_OTHER
why?

2020-12-10 16:21 UTC, PotatoTheDeveloper commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +			tame_progress += rand(950, 1200)
tame_progress no tiene nada que ver con el crecimiento

2020-12-10 16:50 UTC, Evankhell561 requested changes

2020-12-10 16:50 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	if(growth >= 1200 && growth_stage == SUBADULT && !stat) // Grow to adult
le diste a resolver esto pero no parece estar resuelto.

2020-12-10 21:39 UTC, Evankhell561 requested changes

2020-12-10 21:39 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	growth = 599
```suggestion
	growth = GROWTH_HALF-1
```

2020-12-10 21:48 UTC, Evankhell561 requested changes

2020-12-10 21:48 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	gender = NEUTER
por qué haces a los goliaths de genero neutro?

2020-12-10 21:48 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	else if(istype(O, DRAGONSBLOOD) && draconian <= 1)
```suggestion
	else if(istype(O, DRAGONSBLOOD) && draconian <= DRACONIAN)
```

2020-12-10 21:48 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +		if((stat == DEAD) && (tame_stage != TAMED)) // So that 1) an ancient goliath can't immediately spawn another juvenile goliath if it dies, and 2) can't easily cheese the juvenile goliath taming proc
que quiere decir este comentario?

2020-12-10 21:52 UTC, Evankhell561 requested changes

2020-12-10 21:52 UTC, Evankhell561 commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	var/tame_progress = 0
este tammet progresss... al final lo has codeado tu, deberias especificar en algun lado cual es el valor maximo de esta variable, en algun define. y hacer el mismo tabajo que has hecho con la var growth.

2020-12-11 23:31 UTC, PotatoTheDeveloper commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	var/tame_progress = 0
tame_progress no tiene maximo pero el codigo hace una cosa rara y cuando fallas el tameo final te lo reduce a 2100 pero tecnicamente puedes subirlo hasta 3000, a los 2600 basicamente el bicho se tamea, si esto falla te devuelve a 2100, si no puedes seguir aumentandolo aunque deberia poder hacer el tope 3000

2020-12-11 23:34 UTC, PotatoTheDeveloper commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +		if((stat == DEAD) && (tame_stage != TAMED)) // So that 1) an ancient goliath can't immediately spawn another juvenile goliath if it dies, and 2) can't easily cheese the juvenile goliath taming proc
el ancient goliath puede spawnear 3 goliaths juveniles, o hacer sus subditos los goliaths en su vision con un maximo de 3, es y el numero de subditos se reduce cuando el goliath desaparece no cuando muere, y ese codigo es para que el ancient no spamee el spawn basicamente, detiene que spawnee constantemente juveniles

2020-12-15 22:20 UTC, PotatoTheDeveloper commented on code/hispania/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	var/tame_progress = 0
Resumen: no tiene maximo

2020-12-16 02:05 UTC, Evankhell561 requested changes

2020-12-16 02:05 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +		new /obj/effect/temp_visual/goliath_tentacle/original(tturf, src, (aux_tentacles))
```suggestion
		new /obj/effect/temp_visual/goliath_tentacle/original(tturf, src, aux_tentacles)
```

2020-12-16 02:05 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +				goliaths_owned++
eso esta bien pero me encantaria que metas todo esto dentro de un proc y lo pongas en hispania.
```suggestion
	handle_goliaths_owner()
```

2020-12-16 02:05 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +		if(istype(G, /mob/living/simple_animal/hostile/asteroid/goliath) && G.growth_stage == ADULT || !istype(G, /mob/living/simple_animal/hostile/asteroid/goliath))
```suggestion
		if((istype(G, /mob/living/simple_animal/hostile/asteroid/goliath) && G.growth_stage == ADULT) || !istype(G, /mob/living/simple_animal/hostile/asteroid/goliath))
```

2020-12-17 01:06 UTC, Evankhell561 requested changes

2020-12-17 01:06 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +		if(istype(G, /mob/living/simple_animal/hostile/asteroid/goliath) && G.growth_stage == ADULT || !istype(G, /mob/living/simple_animal/hostile/asteroid/goliath))
```suggestion
		if((istype(G, /mob/living/simple_animal/hostile/asteroid/goliath) && G.growth_stage == ADULT) || !istype(G, /mob/living/simple_animal/hostile/asteroid/goliath))
```

2020-12-17 01:50 UTC, PotatoTheDeveloper commented on code/modules/mob/living/simple_animal/hostile/mining/goliath.dm
> +	if(amount > 0)
para que las heal no lo activen

2020-12-17 01:53 UTC, merged