Añade Plataformas Yay (Resubido porque evan me jodio el repo)
Helixis/Paradise pull request #787
Opened 2020-12-03 19:37 UTC by Danaleja2005

Añade Plataformas al juego con el fin de tener mejores estructuras para fines esteticos, existen dos tipos, metalicos y reforzados ( hechos de plasteel) con su variante de corner, y se hacen con 10 la plataforma normal y 5 el corner

![Screenshot_1](https://user-images.githubusercontent.com/43283605/100301981-b933ff00-2f6f-11eb-9120-4585a0f494f4.png)

![Screenshot_2](https://user-images.githubusercontent.com/43283605/100301986-ba652c00-2f6f-11eb-9c01-5db91df6e6e2.png)

![Screenshot_3](https://user-images.githubusercontent.com/43283605/100301989-bb965900-2f6f-11eb-8540-be97ea96bcde.png)

:cl: Danaleja2005
add: Plataforma ( Metal y Plasteel)
imageadd: añade sprites de plataforma metalica y de plasteel
/:cl:

2020-12-07 03:52 UTC, Evankhell561 requested changes

2020-12-07 03:52 UTC, Evankhell561 commented on code/hispania/game/objects/structures/platform.dm
> +	desc =  "A metal platform"
espacios raros

2020-12-07 03:52 UTC, Evankhell561 commented on code/hispania/game/objects/structures/platform.dm
> +	else
espacios demas

2020-12-07 03:52 UTC, Evankhell561 commented on code/hispania/game/objects/structures/platform.dm
> +	desc =  "A robust platform made of plasteel, more resistance for hazard sites"
espacios raros

2020-12-07 03:52 UTC, Evankhell561 requested changes
en general corrige los dobles espacios y los espacios al iniciar la desc.

2020-12-07 03:54 UTC, Danaleja2005 commented
Bien

2020-12-07 03:55 UTC, Evankhell561 requested changes

2020-12-07 03:55 UTC, Evankhell561 commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new /datum/stack_recipe("Metal Platform Corner", /obj/structure/platform/corner, 5, time = 30, one_per_turf = TRUE, on_floor = TRUE),
añade comentarios apra identificar que estas dos linas son nuestras.

2020-12-07 03:55 UTC, Evankhell561 commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new /datum/stack_recipe("Reinforced Plasteel Platform Corner", /obj/structure/platform/reinforced/corner, 5, time = 30,one_per_turf = TRUE, on_floor = TRUE),
añade comentarios apra identificar que estas dos linas son nuestras.

2020-12-07 04:20 UTC, Evankhell561 requested changes

2020-12-07 04:20 UTC, Evankhell561 commented on code/hispania/game/objects/structures/platform.dm
> +		..()
wtf, ahora pusiste tabs demás

2020-12-07 04:51 UTC, Evankhell561 requested changes, later dismissed

2020-12-07 04:51 UTC, Evankhell561 commented on code/hispania/game/objects/structures/platform.dm
> +/obj/structure/platform/metal2/map
creo que te olvidaste de cambiar esta ruta.

2020-12-09 21:53 UTC, Silverexperience submitted a review, later dismissed
- Solo puedo girar las plataformas en un sentido.
![imagen](https://user-images.githubusercontent.com/58746682/101690676-e4d5df80-3a6d-11eb-98a7-3644e98976d6.png)

- No puedo poner varias plataformas en un mismo tile. Aunque si puedes poner plataformas en un mismo tile si los pulleas esto lleva al problema de que puedas superponer dos plataformas en el mismo sentido
![imagen](https://user-images.githubusercontent.com/58746682/101691615-3cc11600-3a6f-11eb-96b5-4ef1d49ea6f3.png)


- Solo puedes escalar las plataformas en un sentido, basicamente al hacer climb te mueve al tile plataforma pero luego no puedes bajarte o al contrario.

- ¿Las escaleras solo se pueden hacer pintando el suelo? No seria mejor poder hacer escaleras de otra forma.

- Queda un poco rara la escalera de arriba.
![imagen](https://user-images.githubusercontent.com/58746682/101692818-0ab0b380-3a71-11eb-8f3c-cdcec53d0583.png)



- Le puede bloquear el camino al robot de sec, Beepsky, y parece que su IA no lo cuenta para esquivar.
![imagen](https://user-images.githubusercontent.com/58746682/101692286-48610c80-3a70-11eb-94de-a32fbe106c65.png)
Seguramente también pase con los demas.

- Las esquinas no giran en el sentido contrario de las agujas del reloj, giran como les da la gana.

- Una imagen dice más que mil palabras
![imagen](https://user-images.githubusercontent.com/58746682/101692642-ccb38f80-3a70-11eb-93b4-8efbbb230667.png)
![imagen](https://user-images.githubusercontent.com/58746682/101693013-54010300-3a71-11eb-90b7-bf54ad0a9173.png)

2021-04-30 01:19 UTC, Danaleja2005 commented
Platforms lista, insta-merge gracias

2021-04-30 15:12 UTC, SagaStars approved these changes
Funcionando, funcionando.

2021-05-04 11:32 UTC, Spircen commented on code/game/objects/structures.dm
> +
Espacios agregados y eliminados de mas.

2021-05-04 19:00 UTC, DanaDririon reviewed
Borra las platform/map, arregla unos espacios y arregla material_amount

2021-05-04 19:00 UTC, DanaDririon commented on code/hispania/game/objects/structures/platform.dm
> +	anchored = TRUE
```suggestion
	material_amount = 2
```

2021-05-04 19:00 UTC, DanaDririon commented on code/hispania/game/objects/structures/platform.dm
> +	material_amount = 5
```suggestion
	material_amount = 2
```

2021-05-04 19:00 UTC, DanaDririon commented on code/game/objects/structures.dm
> +
```suggestion
```

2021-05-04 19:00 UTC, DanaDririon commented on code/game/objects/structures.dm
>  /obj/structure/proc/structure_shaken()
```suggestion
/obj/structure/proc/structure_shaken()

```

2021-05-06 02:14 UTC, Danaleja2005 commented
**Ultimos Cambios**

> Reduce el tiempo de construcción de las platforms, debido a que tardaba bastante.

> Codigo para evitar que al climbear un platform puedas traspasar objetos con densidad.

![Screenshot_4](https://user-images.githubusercontent.com/43283605/117232452-28e7c900-adef-11eb-8f5d-bf49f0f4bb54.png)
![Screenshot_6](https://user-images.githubusercontent.com/43283605/117232455-2be2b980-adef-11eb-9e4e-55844be5e25d.png)
![Screenshot_5](https://user-images.githubusercontent.com/43283605/117232457-2dac7d00-adef-11eb-8f9f-639d48227eee.png)

2021-05-07 03:36 UTC, Spircen commented
Luego de años, lograste terminar el PR prometido. Buen trabajo, dedicación, esfuerzo y paciencia.

2021-05-07 03:44 UTC, merged