Nuevas WinterCoats █ Edición Seguridad || 358/2 days EDITION ||
Helixis/Paradise pull request #790
Opened 2020-12-10 04:29 UTC by SagaStars

## What Does This PR Do

- Se agregan 4 wintercoats nuevas para los siguientes puestos:
`◘ Warden`
`◘ HoS`
`◘ Brig Physician`
`◘ Detective`
Vienen con sus defensas acordes a los suits del job, en otras palabras el wintercoat del warden tiene la misma armadura que la armored jacket del warden, eso si, bajándole la defensa a todas las wintercoats cosas como la resistencia de fuego y ácido, a excepción del HoS que se queda con la mismas estadísticas. Pueden ser obtenidas por el loadout, no hay otro metodo.

- Se le da defensa a la hoods de los wintercoats de sec para que no sea un sacrificio de armadura por estética, quiero reiterar que la diferencia entre las wintercoats y las armaduras de sec es que estas tienen mucha menor resistencia contra el fuego y ácido.

_Intentare sacar mas para los demás departamentos._

## Why It's Good For The Game
Mas ropa siempre pinta bien ademas de que poder darle un tremendo uso para el mapa de nieve cuando este terminado.

---------
#### `Como siempre la imagen en paint.`
---------
![PR](https://user-images.githubusercontent.com/55407528/99436920-1aacfb80-28e8-11eb-80b5-47d83e7b6448.png)

## Changelog
:cl:
add: Cuatro nuevos newcoats para el departamento de sec, obtenibles por el loadout.
tweak: Las hoods de wintercoats de sec tienen defensas similares a las de sus hats ordinarios.
/:cl:

2020-12-10 15:17 UTC, Evankhell561 submitted a review, later dismissed

2020-12-10 15:17 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	hispania_icon = TRUE
el hispania icon no es suficinete para que se vea bien en todos los casos, añade la variable icon.

2020-12-31 19:27 UTC, Evankhell561 commented
A ver, me asignaste este pr pero yo ya te habia dicho lo que queria y a ti no te parecen buenas ideas y no quieres llevarla a cabo. So, pinea a @Silverexperience para que se encarge de juzgarlo 💤

2021-04-02 17:47 UTC, Evankhell561 requested changes

2021-04-02 17:47 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	allowed = list(/obj/item/gun/energy,/obj/item/reagent_containers/spray/pepper,/obj/item/gun/projectile,/obj/item/ammo_box,/obj/item/ammo_casing,/obj/item/melee/baton,/obj/item/restraints/handcuffs,/
```suggestion
		allowed = list(/obj/item/stack/medical, /obj/item/reagent_containers/dropper, /obj/item/reagent_containers/hypospray, /obj/item/reagent_containers/applicator, /obj/item/reagent_containers/syringe,
	/obj/item/healthanalyzer, /obj/item/flashlight, \
	/obj/item/radio, /obj/item/tank/internals/emergency_oxygen,/obj/item/rad_laser)
```

2021-04-02 18:02 UTC, Evankhell561 requested changes

2021-04-02 18:02 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	allowed = list(/obj/item/tank/emergency_oxygen, /obj/item/reagent_containers/spray/pepper, /obj/item/flashlight, /obj/item/gun, /obj/item/ammo_box, /obj/item/ammo_casing, /obj/item/melee/baton, /obj
```suggestion
	allowed = list(/obj/item/tank/internals/emergency_oxygen, /obj/item/reagent_containers/spray/pepper, /obj/item/flashlight, /obj/item/gun, /obj/item/ammo_box, /obj/item/ammo_casing, /obj/item/melee/baton, /obj/item/restraints/handcuffs, /obj/item/storage/fancy/cigarettes, /obj/item/lighter, /obj/item/detective_scanner, /obj/item/taperecorder)
```

2021-04-02 18:02 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	resistance_flags = NONE
```suggestion
	resistance_flags = FLAMMABLE
```

2021-04-02 18:09 UTC, Evankhell561 requested changes

2021-04-02 18:09 UTC, Evankhell561 commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list("melee" = 35, "bullet" = 30, "laser" = 30,"energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 15) // HISPANIA ARMOR
```suggestion
	armor = list("melee" = 20, "bullet" = 15, "laser" = 20,"energy" = 5, "bomb" = 20, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 15)) // HISPANIA ARMOR
```

2021-04-04 01:34 UTC, Evankhell561 requested changes

2021-04-04 01:34 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 30, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 25)
```suggestion
	armor = list("melee" = 20, "bullet" = 20, "laser" = 20, "energy" = 10, "bomb" = 15, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 25)
```

2021-04-04 01:34 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 30, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 70, "acid" = 90)
```suggestion
	armor = list("melee" = 20, "bullet" = 20, "laser" = 20, "energy" = 5, "bomb" = 15, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 50)
```

2021-04-04 01:34 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 25, "bullet" = 10, "laser" = 25, "energy" = 10, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 45)
```suggestion
	armor = list("melee" = 15, "bullet" = 5, "laser" = 15, "energy" = 5, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 40)
```

2021-04-04 01:34 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	armor = list(melee = 10, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 10, rad = 0, fire = 25, acid = 25)
```suggestion
	armor = list(melee = 5, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 10, rad = 0, fire = 25, acid = 25)
```

2021-04-04 01:34 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	armor = list(melee = 10, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 10, rad = 0, fire = 25, acid = 25)
```suggestion
	armor = list(melee = 5, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 10, rad = 0, fire = 25, acid = 25)
```

2021-04-04 01:34 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 40, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 15)
```suggestion
	armor = list("melee" = 30, "bullet" = 20, "laser" = 20, "energy" = 5, "bomb" = 15, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 15)
```

2021-04-04 01:34 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 25, "bullet" = 5, "laser" = 25, "energy" = 10, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 15)
```suggestion
	armor = list("melee" = 15, "bullet" = 5, "laser" = 15, "energy" = 5, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 0, "acid" = 15)
```

2021-04-04 01:34 UTC, Evankhell561 commented on code/hispania/modules/clothing/suits/winter.dm
> +	armor = list("melee" = 40, "bullet" = 30, "laser" = 30, "energy" = 10, "bomb" = 25, "bio" = 10, "rad" = 0, "fire" = 0, "acid" = 15)
```suggestion
	armor = list("melee" = 30, "bullet" = 20, "laser" = 20, "energy" = 5, "bomb" = 15, "bio" = 10, "rad" = 0, "fire" = 0, "acid" = 15)
```

2021-04-04 02:34 UTC, DanaDririon approved these changes
Testeado. Funciona con Humano, Vox y Grey.

2021-04-04 03:03 UTC, Evankhell561 approved these changes
apruébese el balance de este pr

2021-04-04 03:44 UTC, Danaleja2005 commented
finalmente después de 1 año :tada:

2021-04-04 05:00 UTC, merged

2021-04-04 05:01 UTC, SagaStars commented
> finalmente después de 1 año 🎉

Cuidado que te pasa lo mismo