Speedos
Helixis/Paradise pull request #798
Opened 2020-12-31 02:23 UTC by Frex-Creator

## ¿Qué hace este PR
añade mas trajes de baño. pero para hombres
## Por qué es bueno para el juego
trae mas variedad
## Imágenes de cambios
<! - Si no hiciste una edición de mapa o sprite, puedes borrar esta sección. Puede incluir un gif de su función si lo desea ->

añadir: swimsuits

2020-12-31 10:27 UTC, Evankhell561 requested changes
El code debería ir en hispania/modules/chlothing cómo toda la ropa

2020-12-31 10:29 UTC, Evankhell561 requested changes

2020-12-31 10:29 UTC, Evankhell561 commented on code/hispania/speedo/speedo.dm
> +/obj/item/clothing/under/swimsuit
Why?

2020-12-31 13:08 UTC, Frex-Creator reviewed
creo que ahi ya esta todo lo que pedias

2020-12-31 17:29 UTC, Evankhell561 commented
> creo que ahi ya esta todo lo que pedias

y por qué es un draft aun?

2020-12-31 17:30 UTC, Evankhell561 requested changes
ok, perfecto, pero donde se supone que los jugadores consigan estas cosas nuevas? de buenas a primeras solo se me ocurre que sean admin spawn.

2020-12-31 17:31 UTC, Evankhell561 requested changes
tambien, arregla el changelog.

2020-12-31 17:42 UTC, Evankhell561 commented
me parece que este pr no está haciendo absolutamente nada. bueno, es un draft y está bien que esté incompleto pero tampoco entinedo por qué dices solucionar todo lo que pedi si esto aun no es la version final.

2021-02-15 22:30 UTC, Evankhell561 commented
arreglar[as esto algun dia?

2021-02-15 22:32 UTC, Frex-Creator commented
Si. Talvez el día que me guíe. Y no esté baneado de la comunidad 😊

El lun., 15 de feb. de 2021 19:30, Evankhell561 <notifications@github.com>
escribió:

> arreglar[as esto algun dia?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Helixis/Paradise/pull/798#issuecomment-779475653>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQS7OKXUNWRZCRWES3VCZ5DS7GN7ZANCNFSM4VO6GMQA>
> .
>

2021-03-22 04:17 UTC, Evankhell561 commented
me han dicho que no piensan desbanearte y tampoco parece que tengas interés en arreglar esto así que voy a cerrarlo. Aunque personalmente te agradezco que lo hayas puesto en draft. Si quieres terminar esto te animo a reabrirlo.

2021-03-22 04:17 UTC, closed without merging