Balanceo Coloso
Helixis/Paradise pull request #805
Opened 2021-02-11 17:57 UTC by NervalARS

Quita la penetración de los proyectiles del coloso y reduce la velocidad de los proyectiles de 2 a 1.

## What Does This PR Do
Elimina la penetración de armadura de los proyectiles del coloso y reduce la velocidad de estos de 2 a 1.

## Why It's Good For The Game
Actualmente los proyectiles de los colosos pueden matarte extremadamente fácil al recibir unos pocos golpes seguidos debido a que ignora en su totalidad cualquier armadura, esto causa que el personaje sufra fracturas y por ende reduzca su velocidad, impidiendo que escape a la siguiente andanada de proyectiles, además la velocidad de estos no fue adaptada a Paradise, por lo que es bastante difícil y frustrante evadir los proyectiles, incluso sin tener ningún tipo de daño. Eliminar la penetración, y reducir la velocidad brindara una experiencia mas agradable para los mineros, los cuales tendrán mas margen de maniobra.

## Images of changes

## Changelog
:cl:
balance:
/:cl:

2021-02-11 18:01 UTC, Cocacolagua requested changes
no te des host lol

2021-02-11 18:02 UTC, Evankhell561 commented
> no te des host lol

es solo la carpeta example, no tiene un cambio real... pero aun asi no deberia hacer ese cambio

2021-02-11 18:11 UTC, Evankhell561 requested changes
Este cambio es demasiado excesivo, mitad de velocidad de proyectiles es un nerf bastante grande ya que da más posibilidades de esquivar pero si además de esas posibilidades de esquivar, las veces en las que no puedes hacerlo tienes una gran probabilidad de bloquear el ataque me parece excesivo. So, o lo uno o lo otro o le reduces la velocidad o le reduces la penetracion de armadura a la mitad.

2021-02-11 18:12 UTC, Evankhell561 requested changes
también. añade un changelog apropiado

2021-02-11 18:21 UTC, Evankhell561 submitted a review, later dismissed
No deberias eliminar el archivo admins.txt

2021-02-11 18:57 UTC, Evankhell561 approved these changes
Los cambios a la penetración de armadura me parecen bien como un cambio aislado, no estoy seguro acerca del cambio en la velocidad junto a este pero en cualquier caso aunque en primera instancia ambas cosas combinadas puede que sea excesivo no son descabelladas. Aun asi, lo dejo a consideracion de quien vaya margear esto. Por mi parte tiene mi aprobado.

2021-02-11 18:58 UTC, Evankhell561 requested changes

2021-02-11 18:58 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
>  	damage = 25
```suggestion
	damage = 25
	armour_penetration = 50
```

2021-02-11 18:59 UTC, Evankhell561 approved these changes

2021-02-12 16:57 UTC, Evankhell561 requested changes
haz un changelog apropiado.

2021-02-12 17:05 UTC, Evankhell561 commented
recibiendo un poco de feedback de la comunidad:
![image](https://user-images.githubusercontent.com/49106866/107798406-5bd47080-6d5c-11eb-81d1-2a2e79ec653c.png)
![image](https://user-images.githubusercontent.com/49106866/107798427-65f66f00-6d5c-11eb-9507-10a7e7e7e1a3.png)
![image](https://user-images.githubusercontent.com/49106866/107798437-6abb2300-6d5c-11eb-82df-bd0ce35d2b3a.png)
![image](https://user-images.githubusercontent.com/49106866/107798773-e1f0b700-6d5c-11eb-82d5-db39995e701c.png)

2021-02-12 23:43 UTC, Evankhell561 requested changes

2021-02-12 23:43 UTC, Evankhell561 commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +	speed = 1
Solo se aceptará el nerf a la penetracion de armadura, este no. Si lo retiras y haces bien el changelog, maximo para el 16 de este mes se margea esto.

2021-02-15 23:20 UTC, Evankhell561 requested changes
cuando arregles el changelog avisame para margear esto

2021-02-16 14:06 UTC, merged