HispaniaBox is fucking back, en forma radial.
Helixis/Paradise pull request #821
Opened 2021-03-15 03:22 UTC by SagaStars

La rocola ha REGRESADO en forma de chap- menus radiales de seleccion multiple :)
**Mismas canciones con adición de 2 mas**
```
• Daft Punk - Veridis Quo
• Porco Rosso Main Theme
```
Tambien le añade un comportamiento para ser emmageada que le otorgara también 2 mas, dando en total a 4 canciones nuevas (No dire cuales son para que sea mas divertido :)))
**Y NUEVA SPRITES WOOOOO**

## Why It's Good For The Game
Musica buena, musica incuestionable. y es una de las cosas que tenemos mas especial de toda la repo. Todo el mundo lo pedía a gritos.

## Images of changes
                                                  Rocola NUEVA
![1](https://user-images.githubusercontent.com/55407528/111099055-15b92b00-851b-11eb-92f4-e8c4c5ab9ba5.png)

                                      Primera PAGINA
                                      
![2](https://user-images.githubusercontent.com/55407528/111099058-16ea5800-851b-11eb-8a0d-b605def458e0.png)

                                                 Segunda PAGINA
                                                 
![3](https://user-images.githubusercontent.com/55407528/111099060-1782ee80-851b-11eb-8ab2-000099211b41.png)

                                                     Tercera PAGINA
                                                     
![4](https://user-images.githubusercontent.com/55407528/111099061-181b8500-851b-11eb-8c44-56d554ededf1.png)

                                                  Cuarta PAGINA
                                                  
![5](https://user-images.githubusercontent.com/55407528/111099065-18b41b80-851b-11eb-814f-dfc81bbbf717.png)

                                                     Cuarta PAGINA + EMAG
                                                     
![6](https://user-images.githubusercontent.com/55407528/111099067-19e54880-851b-11eb-9975-a199970a3ae1.png)

## Changelog
:cl:
tweak: La rocola es emmageable, brindando 2 canciones mas.
fix: La rocula vuelve a funcionar, de manera diferente.
soundadd: 4 Canciones nuevas para la rocola.
/:cl:

2021-03-17 21:47 UTC, Silverexperience requested changes
-Si la música esta sonando y le lanzas una EMP se desactiva la máquina, pero la música no para de sonar. También sucede si se va la energía.

-Si hay dos hispaniabox, solo a uno le funciona la música. Entiendo que esto esta hecho de esta forma, pero la otra hispaniabox sigue mostrando que tiene música aunque se desactiven los dos. Podria la otra hispaniabox desactivarse si se activa uno dentro del rango.

-Podría tener un mensaje para cuando lo intentas anclar al espacio.

2021-03-18 02:36 UTC, SagaStars commented
Arreglado todas las peticiones que me pediste silver, a excepción de 
> También sucede si se va la energía.

La maquina no funciona por la energía de la estación, nunca lo ha hecho, y no debería hacerlo. Es una de las cosas simples de la jukebox que lo hace tan especial, quizás después en posteriores PRs se le podría implementar una batería pero entre que funcione por electricidad o no, es mejor que no. Apoya ideas como ir al bar a escuchar música por que se fue la electricidad y nadie puede seguir trabajando hasta que este arreglada. No ganamos nada haciendo que no sirva sin electricidad.

2021-03-20 14:42 UTC, Silverexperience submitted a review, later dismissed
Me parece bien que tu deseo sea que no funcione con energía de la sala, mas si funciona con ella. Lo que yo me refería es que cuando suena la música y la energía de la sala se va, la máquina deja de funcionar, pero la música sigue sonando.

2021-03-21 00:40 UTC, SagaStars commented
> Me parece bien que tu deseo sea que no funcione con energía de la sala, mas si funciona con ella. Lo que yo me refería es que cuando suena la música y la energía de la sala se va, la máquina deja de funcionar, pero la música sigue sonando.

O h . Arreglado.

2021-03-21 00:44 UTC, Evankhell561 requested changes

2021-03-21 00:44 UTC, Evankhell561 commented on code/hispania/game/machinery/jukebox.dm
> +	if(stat == BROKEN)
```suggestion
	if(stat & BROKEN)
```

2021-03-21 00:44 UTC, Evankhell561 commented on code/hispania/game/machinery/jukebox.dm
> +	if(stat != BROKEN)
why?

2021-03-21 00:54 UTC, SagaStars commented on code/hispania/game/machinery/jukebox.dm
> +	if(stat == BROKEN)
Oh, asi funcionan, podrias decirme de todos modos la diferencia entre una & y una &&?

2021-03-21 00:55 UTC, SagaStars commented on code/hispania/game/machinery/jukebox.dm
> +	if(stat != BROKEN)
Para que siga iluminando aun sin luz.

2021-03-21 03:02 UTC, Evankhell561 commented on code/hispania/game/machinery/jukebox.dm
> +	if(stat == BROKEN)
si haces (stat && broken) lo que retonará será true si stat es true (o existe) y si broken es true (o tiene un valor)
en cambio & lo que hace es preguntar si broken se encuentra en stat (algo asi como si un elemento se encuentra o no dentro de una lista) y si broken se encuentra en stat entonces retorna true si no retorna false.

2021-03-21 03:08 UTC, Evankhell561 submitted a review, later dismissed

2021-03-21 03:08 UTC, Evankhell561 commented on code/hispania/game/machinery/jukebox.dm
> +	if(stat != BROKEN)
```suggestion
	if(!(stat & BROKEN))
```

2021-03-21 03:16 UTC, SagaStars commented on code/hispania/game/machinery/jukebox.dm
> +	if(stat == BROKEN)
Ya veo, sera algo único de los tidbyte.

2021-03-25 21:42 UTC, Evankhell561 submitted a review, later dismissed

2021-03-25 21:42 UTC, Evankhell561 commented on code/hispania/game/machinery/jukebox.dm
> +	var/song_icon = null
```suggestion
	var/song_icon
```

2021-03-25 21:58 UTC, DanaDririon approved these changes
Los reviews de Silver y Evan fueron incorporados y testeados

2021-03-25 21:58 UTC, merged