Funcionamiento original de la duct tape
Helixis/Paradise pull request #823
Opened 2021-03-15 13:10 UTC by SagaStars

Los duct tapes vuelven a pegarse en las paredes como antes, por offset de la posición del mouse en vez de una posición al azar en la pared.

## Why It's Good For The Game
Es lo que hacia especial a la duct tape, esto debe ser considerado un buff muy necesario.

## Images of changes
`Antes`

![Screenshot_1](https://user-images.githubusercontent.com/55407528/111157656-8426d900-856d-11eb-9e38-d424c9bd02cd.png)

`AHORA`
                                    
![image](https://user-images.githubusercontent.com/55407528/111157630-7c673480-856d-11eb-80c5-5b218fea1be5.png)

## Changelog
:cl:
tweak: duct tape buff
/:cl:

2021-03-17 22:08 UTC, Evankhell561 approved these changes
aun no testeo esto pero el code se ve bien.

2021-03-20 15:16 UTC, Silverexperience requested changes
Tiene comportamientos extraños si lo pegas a la pared en el menú de alt.

2021-03-21 02:57 UTC, DanaDririon commented
> Tiene comportamientos extraños si lo pegas a la pared en el menú de alt.

A mi me funciona bien, con el menú turf (alt + click) incluído. Lo que pasa esque no se pueden poder en diagonales por code.

Por ahora lo apruebo.

2021-03-21 02:58 UTC, DanaDririon approved these changes

2021-03-21 03:05 UTC, Evankhell561 commented
@Silverexperience estaria bien que vuelvas a darle un ojo a esto o mostrar a que te refieres cuando dices que tiene comportamientos extraños.

2021-03-25 21:56 UTC, merged