Resaltar items por los que pases por encima en la UI
Helixis/Paradise pull request #825
Opened 2021-03-16 13:49 UTC by SagaStars

Port de TG || Al pasar el mouse por encima de objetos en tu inventario estos se resaltaran con el color de tu `ui_style_color`, que es seleccionable por el jugador en el menu de preferencias.

## Why It's Good For The Game
Mas feedback en el menu, todo cambio que quiera mejorar la interectividad de jugador con UI es inmediatamente
 positiva.

## Images of changes
![Screenshot_1](https://user-images.githubusercontent.com/55407528/111319585-8b68e800-863c-11eb-933d-40fdbc624a73.png)
![Screenshot_2](https://user-images.githubusercontent.com/55407528/111319599-8e63d880-863c-11eb-87bb-3d1fec587e7b.png)

                      Al estar incapacitado el color del hover se vuelve grisaseo

![Screenshot_3](https://user-images.githubusercontent.com/55407528/111319655-9face500-863c-11eb-9ca7-4f5c3d05682e.png)

## Changelog
:cl:
add: Resaltar objetos por los que pases por encima en el inventario.
/:cl:

2021-03-16 14:52 UTC, Evankhell561 requested changes

2021-03-16 14:52 UTC, Evankhell561 commented on code/game/objects/items.dm
> +		outline_filter = null
a hispania

2021-03-17 04:51 UTC, Evankhell561 commented on code/hispania/game/objects/items.dm
> +/obj/item/proc/apply_outline(outline_color = null)
este dm no está en incluido en el dme

2021-03-17 12:16 UTC, SagaStars commented on code/hispania/game/objects/items.dm
> +/obj/item/proc/apply_outline(outline_color = null)
Si lo esta.

2021-03-17 22:06 UTC, Evankhell561 requested changes

2021-03-17 22:06 UTC, Evankhell561 commented on code/game/objects/items.dm
> +	remove_outline()
a hispania.

2021-03-18 17:41 UTC, merged