Full-automatic firemode // WIP
Helixis/Paradise pull request #827
Opened 2021-03-18 16:30 UTC by SagaStars

## DRAFT - FULLAUTO HISPANIA
1. Funcionamiento del fullauto firemode ✔️ 
1. Dual Wielding ❌ 
1. Bugfix ❌
1. Cambios de Armas ❌ 
   1. Lg6saw teniendo sus 100 balas ✔️ 
   1. Cambiar precio de la municion de Lg6saw para que sea mas cara ❌ 
   1. Pasar armas que deberían ser full-auto a full-auto❌
   1. Cambios de Sprites ❌
   1. Cargador de tambor de 100 balas para la tommy gun ❌
   1. El arma del heavy de tf2 ❌
   1. Darle modo automatico al rifle de sec??? ❌
1. Acomodar rutas donde deberian ir ❌
1. Pasar todo lo posible a hispania ❌ 
  
 BUGS // Han de haber mas, se necesita mas testeo
- No se puede tirar el arma con el click_handler.
- Si salen muchas balas a la vez hay veces que no contara el daño y solo se aplicara 1. Probablemente por que como hay 4 balas en un mismo tile y impactan a la vez solo una aplica. Esto no supone mucho problema ya que a ese nivel de firerate se comienza convertir en un lag machine, igual es bueno tenerse a consideracion.

## Changelog
:cl:

/:cl:

2021-03-18 16:32 UTC, Evankhell561 requested changes

2021-03-18 16:32 UTC, Evankhell561 commented on code/hispania/modules/projectiles/guns/fullauto.dm
> +	return
no pongas return al final de un proc si no vas a devolver nada.

2021-03-20 21:07 UTC, Evankhell561 requested changes

2021-03-20 21:07 UTC, Evankhell561 commented on code/game/objects/items.dm
> +
a hispania

2021-03-20 21:28 UTC, Evankhell561 submitted a review, later dismissed

2021-03-20 21:28 UTC, Evankhell561 commented on code/hispania/datums/autofiresystem.dm
> +	.=..()
```suggestion
	return ..()
```

2021-03-20 21:28 UTC, Evankhell561 commented on code/hispania/datums/autofiresystem.dm
> +	.=..()
```suggestion
	return ..()
```

2021-03-20 21:28 UTC, Evankhell561 commented on code/hispania/datums/autofiresystem.dm
> +	return null
```suggestion
	return
```

2021-03-20 21:28 UTC, Evankhell561 commented on code/hispania/datums/autofiresystem.dm
> +	var/atom/target = null
```suggestion
	var/atom/target
```

2021-03-20 21:28 UTC, Evankhell561 commented on code/hispania/datums/autofiresystem.dm
> +	.=..()
```suggestion
	return ..()
```

2021-03-20 21:28 UTC, Evankhell561 commented on code/hispania/modules/projectiles/guns/fullauto.dm
> +	var/datum/click_handler/fullauto/CH = null
```suggestion
	var/datum/click_handler/fullauto/CH
```

2021-03-20 21:28 UTC, Evankhell561 commented on code/hispania/modules/projectiles/guns/fullauto.dm
> +	var/datum/click_handler/fullauto/CH = null
```suggestion
	var/datum/click_handler/fullauto/CH
```

2021-03-23 00:25 UTC, DanaDririon requested changes, later dismissed
Encontré un par de interacciones interesantes:

-Si se aprieta el botón de throw, se mantiene apretado el click izq, y luego se aprieta de nuevo el botón throw, **el arma pierde la capacidad de full auto.** El full auto se gana nuevamente al sacar y poner el cartucho o lanzar el arma con throw.

-No te puedes poner un arma full auto en la boca (apuntando a la boca en help y luego click en ti) para hacer la interacción de suicidio, pero haciendo lo de arriba gana de vuelta esta interacción.

-Al hacer click en una casilla que no se ve (un tile que está detras de una pared), el arma dispara siempre hacia la diagonal abajo izq, mientras que con otras armas no se dispara del todo.

-La interacción double wield (tener una arma en cada mano y en harm) no sirve con armas fullauto. (Por ejemplo la Uzi)

Por lo demás, no tiene Runtimes y funciona como se esperaba.

2021-03-25 20:21 UTC, DanaDririon approved these changes
Bueno, arreglado los errores que encontré, opino que el PR está listo.

Testeado y corregido.

2021-03-25 21:56 UTC, merged