balanceo
Helixis/Paradise pull request #830
Opened 2021-03-22 16:29 UTC by PotatoTheDeveloper

## What Does This PR Do
Baja el requirimiento para tamear una criatura en un 20%

## Why It's Good For The Game
He notado que encima de que son increiblemente dificiles de encontrar, de que tienes que pacificarlos y que algunos alimentos son un poco problematicos de encontrar, el requerimiento para domesticarlos es un poco alto, con esto intento hacerlo un poco mas facil para los jugadores.

## Changelog
:cl:
tweak: el requerimiento para domesticar goliaths pasa de 2400 a 2000
/:cl:

2021-03-22 16:35 UTC, SagaStars approved these changes
:)

2021-03-22 16:55 UTC, DanaDririon approved these changes
Alguien ha tameado en el server? xd

2021-03-22 16:58 UTC, PotatoTheDeveloper commented
> Alguien ha tameado en el server? xd

ye pero pocos por que suele ser bastante costoso o dura mucho y siempre terminan pidiendome ayuda por que no esta 100% claro si no que te tienes que guiar por examine y tus sentimientos

2021-03-22 18:54 UTC, Evankhell561 requested changes
si un maintainer quiere margearlo estaria bien pero si el problema es que la gente no sabe que hacer deberias incrementar el feedback que dá el goliath añadiendo cosas como TAMEABLE, DESEA X COSA, o algo asi al darle en examine o quizá añadir unas notas de que haces ic o algo asi. porque por mucho que bajes el valor el problema seguirá ahi.

2021-03-22 19:19 UTC, PotatoTheDeveloper commented
> si un maintainer quiere margearlo estaria bien pero si el problema es que la gente no sabe que hacer deberias incrementar el feedback que dá el goliath añadiendo cosas como TAMEABLE, DESEA X COSA, o algo asi al darle en examine o quizá añadir unas notas de que haces ic o algo asi. porque por mucho que bajes el valor el problema seguirá ahi.

ya planeaba hacer eso despues el tema es que no se como implementarlo, si se los digo directamente con examine no hay ningun tipo de inmersion ni nada solo es un listado de items que buscar

2021-03-22 19:39 UTC, Evo-S commented
> > si un maintainer quiere margearlo estaria bien pero si el problema es que la gente no sabe que hacer deberias incrementar el feedback que dá el goliath añadiendo cosas como TAMEABLE, DESEA X COSA, o algo asi al darle en examine o quizá añadir unas notas de que haces ic o algo asi. porque por mucho que bajes el valor el problema seguirá ahi.
> 
> ya planeaba hacer eso despues el tema es que no se como implementarlo, si se los digo directamente con examine no hay ningun tipo de inmersion ni nada solo es un listado de items que buscar
> 
> igual esto es necesario por que aunque sepas de memoria todos los items de toma muchisimo tamearlo

Serie buena idea si implementas un libro o algún cartel dentro de lavaland que explique como hacerlo.

2021-03-22 23:50 UTC, DanaDririon commented
> Serie buena idea si implementas un libro o algún cartel dentro de lavaland que explique como hacerlo.

Un libro me gusta. Que esté en la sala de descanso en la base minera. Podrías agregarlo en este PR ya que es una pena que una interacción interesante como esta se pierda por poca información IC.

2021-04-03 20:06 UTC, Evankhell561 approved these changes
arpobaré esto porque patata tiene su repo roto y no está muy interesado pero lo mejor seria seguir las reviews dadas anteriormente (quizá en un furuto pr :iseeyou:.
so, si alguien quiere hacer los honores adelante.

2021-04-04 02:40 UTC, DanaDririon commented
![image](https://user-images.githubusercontent.com/52227547/113497024-f4be7700-94d5-11eb-8cca-c14546f536b2.png)

2021-04-04 02:40 UTC, merged