La SM Update NOW REAL
Helixis/Paradise pull request #835
Opened 2021-03-27 14:22 UTC by AsrielFBI

## What Does This PR Do
+Añade Duchas en ingeniería para que los ingenieros dejen de ir en plan chernobyl por la estación:
![imagen](https://user-images.githubusercontent.com/56162938/112723399-92320d80-8f0e-11eb-938b-188923584e22.png)

-Cambio el cableado de la SM para que ahora 1 de los SMEs esté dedicado a ingeniería y sea más fácil la administración energética además de que es útil para casos de emergencia NO tener que recablear nada para poder energizar la SM la cual antes de este PR dependía de la energía de la PowerGrid DE LA ESTACIÓN:
![imagen](https://user-images.githubusercontent.com/56162938/112723444-cc031400-8f0e-11eb-9afb-d68355e3b2ca.png)

+Se le devuelve a la secure storage de ingeniería las floodlights de emergencia además de más espacio para poder almacenar objetos:
![imagen](https://user-images.githubusercontent.com/56162938/112723468-eb9a3c80-8f0e-11eb-80f4-931d0853a445.png)

## Why It's Good For The Game
-Primero de todos, los ingenieros ya no salen irradiados de ingeniería.
-La SM ya no depende de la energía de la estación para funcionar.
-Ingeniería DEPENDE de la energía generada al momento por los plasma collectors para energizarse a sí misma, ahora con su propia SME tiene respaldo energético.
-La secure storage era muy útil por su capacidad en guardar objetos de forma segura y a la vez las floodlights eran muy usadas en emergencias, solo se podían obtener a través de la secure storage y el satélite de ing, ahora se devuelven para que puedan seguir siendo usados.

## Images of changes
![imagen](https://user-images.githubusercontent.com/56162938/112723650-f86b6000-8f0f-11eb-94a6-3d5d536da7bb.png)

## Changelog
:cl:
add: Una ducha en ing
add: Más espacio en la secure storage
add: Las floodlight de nuevo en la secure storage
tweak: Cambiado el cableado de la SM
/:cl:

2021-03-27 19:03 UTC, Evankhell561 commented
una imagen de como se veia antes ayudaria

2021-04-03 20:07 UTC, Evankhell561 approved these changes
Yo no estoy capacitado para testear esto, si algun otro maintainer lo está que lo haga y si no que coordinen con el prefecto del servidor para coordinar un testmarge y un posible rapido revert.

2021-04-04 01:20 UTC, DanaDririon requested changes
Ok, en general me gusta el PR. La ducha, el storage y separar el cableado de inge.

Lo único que quisiera cambiar sería el siguiente cableado:

![image](https://user-images.githubusercontent.com/52227547/113495822-6a244a80-94ca-11eb-9ed4-475023f99c3f.png)

-No me gusta que hayan cables importantes debajo de ventanas o paredes, mejor que pase por la puerta.
-Ya que los cables de los emitters son el mismo sistema que el de la SM, mejor cámbialos todos de un color.
-Por último, para que te sea más fácil, dejar el SMES de abajo a la izquierda como SMES de la SM.

2021-04-04 01:29 UTC, AsrielFBI commented
1: Los cables que pasan debajo de la ventana ya estaban ahí, no es algo que yo haya elegido hacer.

2: El color más que nada sirve para diferenciar cual cable es el que va a emitters y cuál va a recolección de energía, si que se pueden poner del mismo color pero eso ya es para otro PR. Lo que necesito ahora es que ya se acepte la funcionalidad del actual PR.

3: El hecho de que sea el SM de abajo a la izquierda o derecha ya son gustos personales...

2021-04-04 02:12 UTC, DanaDririon approved these changes
Bueno, está bien. Y lo siento, fue una descoordinación entre maintainers.

Como funciona bien y fue testeado sin runtimes, aprobado.

2021-04-04 02:13 UTC, merged

2021-04-04 02:19 UTC, AsrielFBI commented
De acuerdo, me pondré lo más pronto posible para hacer la segunda parte. Espero que te guste.
Gracias por aprobar el PR btw.