[RESPRITE] Sec Officer Blue y Red (WIP)
Helixis/Paradise pull request #839
Opened 2021-04-03 23:43 UTC by Danaleja2005

## What Does This PR Do

Resprite de mis sprites (Sec Officer Blue y Red) de hace un año que en ese momento me quedaron geniales pero ahora con mayor nivel me parecen feos. (Tenia que hacerlo XD)

WIP: Corbata Azul y Roja y Sprites para Raza Grey y Vox ( Que flojera hacer ropa a estas razas, quien juega Vox y Grey lol)

## Why It's Good For The Game

Mejorar la calidad visual de este código

## Images of changes

![image](https://user-images.githubusercontent.com/43283605/113494225-6be31380-94b4-11eb-9f57-235c9cd69515.png)

![image](https://user-images.githubusercontent.com/43283605/113494230-76051200-94b4-11eb-95e2-91693492b977.png)

## Changelog
:cl:
tweak: Resprite de Sec Officer Blue y Red
imageadd: Añade nuevos y mejorados sprites Sec Officer Blue y Red
imagedel: Elimina los anteriores Sprites de Sec Officer Blue y Red
/:cl:

2021-04-03 23:53 UTC, SagaStars commented
Al CI le había dado un infarto pero ya esta bien. Que no se te olviden las gorras :eyes:

2021-04-03 23:54 UTC, Evankhell561 requested changes, later dismissed
me niego a revisar tus prs, no me has llamado desde aquella noche juntos.

2021-04-03 23:55 UTC, Danaleja2005 commented
las gorras están bien, bueno el sprite del obj no, bueno cambie el color un poco tambien debo recolorearlo aaaaaaa

2021-04-03 23:56 UTC, Danaleja2005 commented
> me niego a revisar tus prs, no me has llamado desde aquella noche juntos.

Si dije que me iría, pero estoy haciendo mierdas otra vez, ni yo me entiendo, no me juzgues :flushed:

2021-04-04 16:15 UTC, Danaleja2005 commented
Señores Maintainers, les gusta este resprite del sprite del hat de sec?

![image](https://user-images.githubusercontent.com/43283605/113514927-4fd88400-953f-11eb-9ad1-4f6e3bbc1417.png)

2021-04-04 16:19 UTC, Danaleja2005 commented
@SagaStars @DanaDririon @Evankhell561

2021-04-04 18:33 UTC, SagaStars commented
> Señores Maintainers, les gusta este resprite del sprite del hat de sec?
> 
> ![image](https://user-images.githubusercontent.com/43283605/113514927-4fd88400-953f-11eb-9ad1-4f6e3bbc1417.png)

ponle los bordes mas notorio con lineas casi negras, asi es mas fácil de notar en los tiles y va mas consistente con los demás sprites.

2021-04-04 19:14 UTC, Danaleja2005 commented
Yo no me ajusto a los demas sprites, yo ajusto los demas sprites a mi

2021-04-04 19:17 UTC, Danaleja2005 commented
@SagaStars  
![image](https://user-images.githubusercontent.com/43283605/113519228-e6fe0580-9558-11eb-9c52-022bf87b80e1.png)  asi?

2021-04-05 00:37 UTC, Danaleja2005 commented
vale, si es mejor debatir el sprite en un canal de discord

2021-04-07 18:20 UTC, SagaStars requested changes
- Las ties no tienen sprite.
- No aparecen las ties junto a los trajes.
- El preview en el TGUI se ve horrible.

![Screenshot_2](https://user-images.githubusercontent.com/55407528/113914507-a0541980-97ab-11eb-91a6-236f3a2c4868.png)
Ahora a cambios que pido que son mas subjetivos son un cambio de paleta, los colores son muy blandos que no es necesariamente malo, pero es malo para Paradise. Simplemente no se sienten bien, parece ropa de otro code, no de Paradise.
![Screenshot_1](https://user-images.githubusercontent.com/55407528/113914409-84e90e80-97ab-11eb-80c3-615109aaf33c.png)
Personalmente opino que los colores que tenia antes le daban mas vida y hacia que tuviera mas valor al verlo junto a otra ropa. (Por que los pasates los pantalones de azul marino a gris, estan mejor en pantalon azul marino por favor)
![Screenshot_3](https://user-images.githubusercontent.com/55407528/113914500-9cc09280-97ab-11eb-92bd-54f7461a931c.png)
![Screenshot_4](https://user-images.githubusercontent.com/55407528/113914840-fe80fc80-97ab-11eb-9167-fb2113f2f36c.png)

                A comparativa
Darle mas contrastes a la ropa a como estaba antes estaría mejor para el estilo de Paradise, el cambio de paleta en este PR lo veo innecesario y lo empeora, eso es todo.

2021-04-13 01:29 UTC, Danaleja2005 commented
![image](https://user-images.githubusercontent.com/43283605/114482406-8748cf80-9bd4-11eb-999b-e7823a0da549.png)

![image](https://user-images.githubusercontent.com/43283605/114482567-c5de8a00-9bd4-11eb-96ff-40056e0c9bb8.png)

**Cambios Realizados:**

- Re-recolor a los sprites de los uniformes ( Por petición de Saga )

- Se añade un codigo para poder poner accesorios de todo tipo a las ropas under cuando son credas ( **starting_accessories = list()** )

- Cambios Menores a otros Sprites ( Ajustes en pantalones que cubrian los pies)

2021-04-21 00:25 UTC, SagaStars requested changes, later dismissed
Acomoda las imágenes del PR con las actuales, pronto lo probare.

2021-04-23 14:38 UTC, Danaleja2005 commented
> Acomoda las imágenes del PR con las actuales, pronto lo probare.

Hecho

2021-04-28 01:18 UTC, Evankhell561 submitted a review, later dismissed
No le pungas numeros a los paths por favor,

2021-04-28 01:18 UTC, Evankhell561 commented on code/hispania/modules/clothing/under/accessories/accessory.dm
> +/obj/item/clothing/accessory/blue1
```suggestion
/obj/item/clothing/accessory/blue_alt
```

2021-04-28 01:18 UTC, Evankhell561 commented on code/hispania/modules/clothing/under/accessories/accessory.dm
> +/obj/item/clothing/accessory/red1
```suggestion
/obj/item/clothing/accessory/red_alt
```

2021-04-28 01:18 UTC, Evankhell561 commented on code/hispania/modules/clothing/under/jobs/security.dm
> +	starting_accessories = list(/obj/item/clothing/accessory/blue1)
```suggestion
	starting_accessories = list(/obj/item/clothing/accessory/blue_alt)
```

2021-04-28 01:18 UTC, Evankhell561 commented on code/hispania/modules/clothing/under/jobs/security.dm
> +	starting_accessories = list(/obj/item/clothing/accessory/red1)
```suggestion
	starting_accessories = list(/obj/item/clothing/accessory/red_alt)
```

2021-04-28 01:31 UTC, Danaleja2005 commented
> No le pungas numeros a los paths por favor,
Ok

2021-04-28 20:47 UTC, SagaStars requested changes
Ta bien.

2021-04-28 20:49 UTC, SagaStars approved these changes

2021-04-28 20:50 UTC, merged