Ordena Alfabéticamente las semillas de Hispania
Helixis/Paradise pull request #842
Opened 2021-04-05 21:36 UTC by DanaDririon

## What Does This PR Do
Ordena Alfabéticamente las semillas de Hispania en el vendedor de semillas.

## Why It's Good For The Game
Para que sea más fácil encontrar las semillas

## Changelog
:cl: DanaDririon
tweak: Orden de semillas en Vendedora
/:cl:

2021-04-06 16:50 UTC, SagaStars approved these changes
Ta bien.

2021-04-06 16:53 UTC, SagaStars requested changes
Mentira, no esta, pusistes una imagen de antes en el PR pero no una de despues y me dejo mal sabor de boca.

2021-04-06 18:43 UTC, DanaDririon commented
Jajaja se me olvidó porque tenía que compilar pero el code está bien :pogfish:

2021-04-07 18:26 UTC, SagaStars commented
> Jajaja se me olvidó porque tenía que compilar pero el code está bien :pogfish:

Nada de peros :gun:

2021-04-07 20:09 UTC, merged