Eliminacion del multiplicador de daño
Helixis/Paradise pull request #844
Opened 2021-04-09 18:09 UTC by NervalARS

## What Does This PR Do
Se elimina el multiplicador de daño bruto y daño por quemaduras de los IPC.

## Why It's Good For The Game
Los IPC ahora recibiran el mismo daño que los seres humanos, y por ende no serán tan fáciles de desmabrar y matar.

## Changelog
:cl:
del: Se eliminan los multiplicadores de daño.
/:cl:

2021-04-09 20:26 UTC, DanaDririon requested changes
En efecto, testeando, el 0.66 de modificación por tener partes robóticas no es un **bonus**, si no que es una resistencia, haciendo que los IPC resistan más golpes que humanos, lo que no es bueno teniendo en cuenta los pros que tiene la raza.

Propongo que por lo menos tengan un bonus de daño del 20%, en vez del 50% actual.

2021-04-09 20:34 UTC, NervalARS commented
> En efecto, testeando, el 0.66 de modificación por tener partes robóticas no es un **bonus**, si no que es una resistencia, haciendo que los IPC resistan más golpes que humanos, lo que no es bueno teniendo en cuenta los pros que tiene la raza.
> 
> Propongo que por lo menos tengan un bonus de daño del 20%, en vez del 50% actual. Para esto el número de modificador de daño bruto y quemaduras debe ser **1.82**

El multiplicador de daño no tiene cabida aqui, no hay nada a nivel de lore que justifique que unos seres de metal sean menos resistentes que un ser humano promedio. Lo unico que tendria "sentido" seria el daño por quemaduras e igualmente el argumento estaría agarrado con pinzas, si, pienso que deberían recibir mas daño que los seres humanos al ser electrocutados, pero no de un proyectil laser o de una bola de fuego. Pienso que el multiplicador de 0.66 que hay por defecto en las extremidades robóticas ya es suficiente y es una desventaja equivalente al daño multiplicado que puede recibir un slime por congelación, aunque no sea una fuente común de daño.

2021-04-09 21:00 UTC, SagaStars commented on code/modules/mob/living/carbon/human/species/machine.dm
> +	brute_mod = 1.5 // 100% * 1.5 * 0.66 (robolimbs) ~= 100%
```suggestion
	brute_mod = 1.51 // 100% * 1.51 * 0.66 (robolimbs) ~= 100%
	burn_mod = 1.51 // 100% * 1.51 * 0.66 (robolimbs) ~= 100%
```

2021-04-11 00:28 UTC, DanaDririon approved these changes

2021-04-11 00:28 UTC, DanaDririon commented on code/modules/mob/living/carbon/human/species/machine.dm
> +	burn_mod = 2.28
```suggestion
	burn_mod = 2.28 // 100% * 2.28 * 0.66 (robolimbs) ~= 150%
```

2021-04-11 00:48 UTC, merged