Crea chem dispenser para botanica
Helixis/Paradise pull request #850
Opened 2021-04-16 03:05 UTC by Ume-D

## What Does This PR Do
Crea un chem dispenser exclusivo para botanica. Disponible en RnD.
No mas gritar "MED MUTAGENO" una y otra vez como si tuvieras retraso mental. Ahora podrás regar tus flores tranquilamente.

## Why It's Good For The Game
Los botanicos podrán tener sus químicos sin necesidad de ir una y otra vez a medbay. Sin embargo, no quitará la necesidad de trabajo en equipo con ciencias para lograr los niveles de RnD para construir dicho dispenser.

## Images of changes
![image](https://user-images.githubusercontent.com/47925856/114965474-06453e80-9e47-11eb-8500-e698593db421.png) 
![image](https://user-images.githubusercontent.com/47925856/114965499-12c99700-9e47-11eb-9804-aa1e5132e812.png)

## Changelog
:cl:
add: Añade nuevo chem dispenser con químicos para botánica
imageadd: Añade sprites para diferenciar el chem dispenser de botanica de los demás
experiment: Si se abusa de los chems que trae por defecto (Se dejaron todos los que trae el dispenser de lavaland) se reducirá la cantidad de estos
/:cl:

2021-04-21 00:23 UTC, SagaStars requested changes
Ya hecho mi única sugerencia, quiero preguntar no es un poco inútil como tal? Digo, ya podrían pedirle a ciencias que le dieran un chem dispenser, supongo que el nombre hará que los científicos tengan mas tendencia a hacerlo, un pensamiento nada mas. 

Acomoda el cambio, testeo y vemos si lo mergeamos.

2021-04-21 00:23 UTC, SagaStars commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		"cryoxadone",
Eh eso definitivamente no 
```suggestion

```

2021-04-22 23:45 UTC, Ume-D commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		"cryoxadone",
Si lavaland lo tiene por algo será, pero como quieras,

2021-04-23 00:19 UTC, Sikroth commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		"cryoxadone",
El cryoxadone cura a las plantas:
![image](https://user-images.githubusercontent.com/7857084/115800046-14acd080-a3da-11eb-838c-a2bfb8aa560e.png)
Tampoco creo que sea mucho problema igual tenerlo en botánica, no se me ocurre mucho modo de abusarlo.

2021-04-23 00:25 UTC, PotatoTheDeveloper commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		"cryoxadone",
es una fuente infinita de un químico avanzado de medbay que helea mas que omnizine y solo esta limitado por la temperatura no veo como pueden dejárselo

2021-04-23 00:28 UTC, Sikroth commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		"cryoxadone",
Cryox solo cura si la temperatura externa es fría. aka en un cryotubo o en el espacio.

2021-04-23 00:30 UTC, PotatoTheDeveloper commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		"cryoxadone",
y que detiene a botánica de darle a med 200 de cryoxadone round start

2021-04-23 00:43 UTC, Sikroth commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		"cryoxadone",
> y que detiene a botánica de darle a med 200 de cryoxadone round start

Entonces este chem dispenser va a estar en botánica en roundstart? Tenía entendido que no. Honestamente no creo que sea relevante. Mmedbay empieza con cryox de sobra para los tubos y la única utilidad adicional es hacer biomasa, que honestamente con nuestra pop con 5-10u de cryox tienes de sobra lol.

En cualquier caso si les parece tan problemático quítenla 🤷

2021-04-23 00:50 UTC, DanaDririon reviewed
Y si lo dejan como upgrade? :pogfish:

2021-04-23 00:50 UTC, DanaDririon commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +	upgrade_reagents = null
```suggestion
	upgrade_reagents = "cryoxadone"
```

2021-04-23 00:56 UTC, Ume-D commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +		"cryoxadone",
Tbh estoy del lado de sikroth

2021-04-23 00:56 UTC, Ume-D commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +	upgrade_reagents = null
Me voy a puto suicidar.

Mañana lo hago, ya estoy en la cama.

2021-04-23 00:57 UTC, DanaDririon commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +	upgrade_reagents = null
Puedes hacer el commit aquí mismo desde la página xd

2021-04-23 01:56 UTC, Ume-D commented on code/hispania/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +	upgrade_reagents = null
Es mala práctica hacer cosas sin testearlas 🔪

2021-04-25 19:34 UTC, DanaDririon approved these changes
Si porfa

2021-04-26 14:09 UTC, SagaStars approved these changes

2021-04-26 14:15 UTC, merged