La Gran Ingeniería Update (WIP)
Helixis/Paradise pull request #851
Opened 2021-04-19 15:59 UTC by AsrielFBI

AVISO: No está terminado, falta que se deba revisar de forma más extensiva todo el mapa y a la vez escuchar sugerencias para implementar en el mapa, he añadido esto ya aquí para que la gente pueda ir viendo mi trabajo y contribuir tanto ideas como soporte. :)

## What Does This PR Do

Cambia en general toda ingeniería para añadir otro motor y un rework del maint de inge/cargo al igual de pequeños detalles en la estación.

## Why It's Good For The Game

Da un nuevo aire a la estación, da más posibilidad a los ingenieros para experimentar y poder tener un motor funcionando dando igual los niveles de conocimiento. Agrega más posibilidades para antags de estabilizarse en un más denso maint con más funcionalidades que afectan a la estación como por ejemplo una pequeña sala atmosférica con acceso directo al supply y scrubbers del soporte vital de la estación.

## Images of changes

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: Tweaked a few things
fix: Fixed a few things
wip: Added a few works in progress
soundadd: Added a new sound thingy
sounddel: Removed an old sound thingy
imageadd: Added some icons and images
imagedel: Deleted some icons and images
spellcheck: Fixed a few typos
experiment: Added an experimental thingy
/:cl:

2021-04-28 05:52 UTC, DanaDririon requested changes
-El área del SMES del solar está mala. Debería ser "/area/maintenance/portsolar", en congruencia con el resto de los solares.
![image](https://user-images.githubusercontent.com/52227547/116352861-cfb2e080-a7c3-11eb-9248-439668328a78.png)

-Opino que estas paredes molestan.
![image](https://user-images.githubusercontent.com/52227547/116352975-02f56f80-a7c4-11eb-9695-e153f9938816.png)
![image](https://user-images.githubusercontent.com/52227547/116353251-6c757e00-a7c4-11eb-93f2-04b6fc1688a1.png)


-Un poquito más de luz en maint sur de ciencias tal vez xd
![image](https://user-images.githubusercontent.com/52227547/116353128-40f29380-a7c4-11eb-902f-4179b7916ced.png)

2021-05-02 15:41 UTC, Evankhell561 requested changes
Estoy decuerdo con que ingeneria pueda colocar más motores a la vez pero no estoy seguro de estar deacuerdo con los cambios a maint, y el que hayas movido algunas salas de ingeneria a un lugar más profundo de ésta. 

Como por ejemplo no me gusta el que hayas movido el secure estorage y no me gusta que la oficina del CE esté tan profundo en el departamento de ingeneria.

2021-05-02 15:46 UTC, Evankhell561 submitted a review, later dismissed
Por cierto, te recomiendo hacer el cambio de lo de las camaras de ingeneria en otro pr y asi se margearia muy rapidamente.

2021-05-02 16:53 UTC, AsrielFBI commented
> 
> 
> Estoy decuerdo con que ingeneria pueda colocar más motores a la vez pero no estoy seguro de estar deacuerdo con los cambios a maint, y el que hayas movido algunas salas de ingeneria a un lugar más profundo de ésta.
> 
> Como por ejemplo no me gusta el que hayas movido el secure estorage y no me gusta que la oficina del CE esté tan profundo en el departamento de ingeneria.

Estar de acuerdo o no en las cosas es muy poco objetivo,... Si tienes un cambio en mente lo puedes solicitar y en un futuro PR se puede poner, por lo resto simplemente limitate a que no tengo pensado hacer el PR más grande viendo como os gusta joderme el PR a base de mergear cambios de mapas de otra gente que ha llegado tarde antes que el mío.

2021-05-02 16:56 UTC, Evankhell561 commented
> > Estoy decuerdo con que ingeneria pueda colocar más motores a la vez pero no estoy seguro de estar deacuerdo con los cambios a maint, y el que hayas movido algunas salas de ingeneria a un lugar más profundo de ésta.
> > Como por ejemplo no me gusta el que hayas movido el secure estorage y no me gusta que la oficina del CE esté tan profundo en el departamento de ingeneria.
> 
> Estar de acuerdo o no en las cosas es muy poco objetivo,... Si tienes un cambio en mente lo puedes solicitar y en un futuro PR se puede poner, por lo resto simplemente limitate a que no tengo pensado hacer el PR más grande viendo como os gusta joderme el PR a base de mergear cambios de mapas de otra gente que ha llegado tarde antes que el mío.

estar decuerdo o no es lo que determina si lo apruebo o no. ya te lo dije, no quiero que sea más dificil entrar en la oficina del CE y no quiero que muevas el secure storage de circuitos.

2021-05-04 11:29 UTC, Spircen requested changes
La Shuttle de Mineria no funciona debido a los cambios que se hicieron en los limites que esta posee en un PR pasado, te recomiendo solo copiar y pegar el docking_port en la estación de un .dmm con la version actual del mapa. 
![image](https://user-images.githubusercontent.com/46639834/116996445-06e03080-aca1-11eb-9d73-2e9fb9116132.png)

Hay una consola de cámaras que me deja ver incluso las cámaras de CC estando desnudo.
![image](https://user-images.githubusercontent.com/46639834/116996605-47d84500-aca1-11eb-9d42-ec7ed0cc67ab.png)

Original siendo el live / Base siendo tu mapa
Original entra en base sin ningún problema.
![image](https://user-images.githubusercontent.com/46639834/116996743-8110b500-aca1-11eb-9217-460c9b597e63.png)

Tienes una windoor frente a un generador de Obstruction aleatorio en este lugar, esto causa que suceda una door welded detras de ella, quita el obstruction.
![image](https://user-images.githubusercontent.com/46639834/116996850-a8678200-aca1-11eb-9d1a-56d92e9860dc.png)

No tengo problema con darle un dormitorio al janitor pero tiene permisos de maint. Asi cualquiera puede entrar a su lugar. 
![image](https://user-images.githubusercontent.com/46639834/116996982-d2b93f80-aca1-11eb-91a3-420664c8c262.png)

Hay una camara en maint la cual no puede ir, es el lugar seguro de IAs
![image](https://user-images.githubusercontent.com/46639834/116997065-ebc1f080-aca1-11eb-9fb5-2f01a99ec472.png)

Aparte de esos cambios no me termina de agradar la idea pero ya metiste mucho esfuerzo en hacer esto. Doy mi voto de aprobado en cuanto resuelvas estos cambios.

2021-05-05 07:00 UTC, Spircen requested changes
Esa puerta aun tiene solo acceso a maint, cualquiera puede entrar a su dormitorio. 
![image](https://user-images.githubusercontent.com/46639834/117106303-3fd1e100-ad45-11eb-85d4-de22de8551b1.png)

La camara del maint de ingeniería sigue aqui.
![image](https://user-images.githubusercontent.com/46639834/117106349-524c1a80-ad45-11eb-983c-729083f9faf8.png)

Sigue bloqueada la shuttle. 
![image](https://user-images.githubusercontent.com/46639834/117106407-68f27180-ad45-11eb-88dd-788325774968.png)

Elimina estas y que siga siendo carpet con una cama ahí ya luego yo reagrego las duchas en el otro PR.
![image](https://user-images.githubusercontent.com/46639834/117106503-963f1f80-ad45-11eb-882b-f189014da95c.png)

2021-05-05 10:14 UTC, AsrielFBI commented
> Esa puerta aun tiene solo acceso a maint, cualquiera puede entrar a su dormitorio.
> ![image](https://user-images.githubusercontent.com/46639834/117106303-3fd1e100-ad45-11eb-85d4-de22de8551b1.png)
> 
> La camara del maint de ingeniería sigue aqui.
> ![image](https://user-images.githubusercontent.com/46639834/117106349-524c1a80-ad45-11eb-983c-729083f9faf8.png)
> 
> Sigue bloqueada la shuttle.
> ![image](https://user-images.githubusercontent.com/46639834/117106407-68f27180-ad45-11eb-88dd-788325774968.png)
> 
> Elimina estas y que siga siendo carpet con una cama ahí ya luego yo reagrego las duchas en el otro PR.
> ![image](https://user-images.githubusercontent.com/46639834/117106503-963f1f80-ad45-11eb-882b-f189014da95c.png)



Una imagen dice más que mil palabras:
![Captura de pantalla de 2021-05-05 12-13-16](https://user-images.githubusercontent.com/56162938/117126683-67539880-ad9b-11eb-8c71-3486fdc87552.png)

2021-05-05 11:06 UTC, Spircen commented
No hagas esta clase de cosas: 

"AVISO: ESTÁ TERMINADA, cualquier petición a cambios deben de ser para arreglar FALLOS en el PR, cualquier otra cosa irá en OTRO PR para reducir riesgo de equivocaciones."

Si alguien solicita que modifiques algo de tu PR en base a feedback para evitar que genere vulnerabilidades o buffs innecesarios a X zona del departamento tienes que estar dispuesto a hacerlo. Nadie aquí esta en tu contra o tiene algo personal a por alguien. 

Cosas como "como os gusta joderme el PR" tienen cero lugar aquí cuando tu mismo hablas de objetividad. 

Espero un cambio de actitud cuando estés haciendo cosas de este estilo por que solo atrasas las cosas si cuando alguien te pide hacer un cambio y te pones a debatir de si hacerlo o no.

2021-05-05 11:08 UTC, merged

2021-05-05 11:10 UTC, AsrielFBI commented
> 
> 
> No hagas esta clase de cosas:
> 
> "AVISO: ESTÁ TERMINADA, cualquier petición a cambios deben de ser para arreglar FALLOS en el PR, cualquier otra cosa irá en OTRO PR para reducir riesgo de equivocaciones."
> 
> Si alguien solicita que modifiques algo de tu PR en base a feedback para evitar que genere vulnerabilidades o buffs innecesarios a X zona del departamento tienes que estar dispuesto a hacerlo. Nadie aquí esta en tu contra o tiene algo personal a por alguien.
> 
> Cosas como "como os gusta joderme el PR" tienen cero lugar aquí cuando tu mismo hablas de objetividad.
> 
> Espero un cambio de actitud cuando estés haciendo cosas de este estilo por que solo atrasas las cosas si cuando alguien te pide hacer un cambio y te pones a debatir de si hacerlo o no.

A eso me refiero en base a que no venga usuarios y digan "Yo quiero que tenga x cosa más"... Bruh.

2021-05-05 11:12 UTC, AsrielFBI commented
btw, no dejaste a dana hacer su commit xd