Fix Pancakes y Aguacates Asesinos
Helixis/Paradise pull request #861
Opened 2021-04-28 14:44 UTC by Spircen

## What Does This PR Do
Repara una definicion en los pancakes que causaba el sprite no funcionara debido a que el objeto existia declarado dos veces bajo el mismo nombre, cambia el nombre de los pancakes creados por N0thing para denotar la diferencia entre ellos y repara una probabilidad del aguacate que estaba en 50% de cortarte la mano al cortarlo.

## Why It's Good For The Game
Repara una receta agradable para la crew y evita la gente muera intentando cortar un aguacate.

## Images of changes
![image](https://user-images.githubusercontent.com/46639834/116423266-25a87800-a806-11eb-862a-51db61be4918.png)
![image](https://user-images.githubusercontent.com/46639834/116423276-280ad200-a806-11eb-8c3c-bf2c3cbc4368.png)

## Changelog
:cl:
fix: Aguacates
fix: Pancakes
/:cl:

2021-04-28 14:46 UTC, Danaleja2005 commented
wait,¿porque hay probabilidad cortarte la mano con un aguacate?

2021-04-28 14:50 UTC, Spircen commented on code/hispania/modules/hydroponics/grown/avocado.dm
> +		if(prob(20))
Esto en una versión anterior de BYOND lo reconocía como 50 en lugar de 5, probándolo veo que funciona como debería de forma correcta así que quitare este cambio, el resto si es necesario por que no se ven los sprites de pancakes.

2021-04-28 14:52 UTC, Spircen commented
> wait,¿porque hay probabilidad cortarte la mano con un aguacate?

Fue parte de las ideas que surgieron cuando programe las plantas que Hessica solicito. Es un 5% tienes que tener la peor suerte del mundo para que suceda y un 1% de cortarte todo el brazo.

2021-04-28 14:55 UTC, Danaleja2005 commented
> > wait,¿porque hay probabilidad cortarte la mano con un aguacate?
> 
> Fue parte de las ideas que surgieron cuando programe las plantas que Hessica solicito. Es un 5% tienes que tener la peor suerte del mundo para que suceda y un 1% de cortarte todo el brazo.

Ah, genial, me parece bastante curioso XD

2021-04-28 20:11 UTC, SagaStars requested changes
Acomoda la desc del PR y estamos.

2021-04-28 22:11 UTC, Spircen commented
Listo.

2021-04-29 11:51 UTC, SagaStars approved these changes

2021-04-29 11:51 UTC, merged