Add Hand-Made Splint
Helixis/Paradise pull request #862
Opened 2021-04-28 15:52 UTC by Spircen

## What Does This PR Do
Añade la posibilidad de crear splints hechas a mano a partir de (15)Tapes, (10)Coil y (20)Metal Rods , estas sirven para entablillar miembros fracturados pero cuestan mucho tiempo para aplicar. Recordemos que las Splints NO entablillan pecho, cabeza y NO curan daños internos. 

## Why It's Good For The Game
Actualmente el personal tiene pocas formas de tratar con huesos rotos cuando no hay equipo medico y me parece posible que sea viable tengan esta receta de forma básica. 

## Images of changes
![image](https://user-images.githubusercontent.com/46639834/116433772-6fe22700-a80f-11eb-988a-bbce57de5660.png)
![image](https://user-images.githubusercontent.com/46639834/116433844-7f617000-a80f-11eb-87b4-2ead200a387c.png)

## Changelog
:cl:
add: Hand Made Splints
/:cl:

2021-04-28 17:11 UTC, DanaDririon commented
Hhmm opino que 20 metal rods para 1 splint es mucho
Tal vez 10 mejor? :thinking:

2021-04-28 20:06 UTC, SagaStars requested changes
Baja el metal a 10 y los tape a 5, tomalo o dejalo.

2021-04-28 22:10 UTC, Spircen commented
Lo que crea es un stack que te da 6 Splints, tendría que corregir la descripción.

2021-04-29 11:51 UTC, SagaStars commented
Eso tiene mucho mas sentido, ahi va

2021-04-29 11:52 UTC, SagaStars approved these changes

2021-04-29 11:52 UTC, merged