Add Pistas de Audio (Ambiente)
Helixis/Paradise pull request #870
Opened 2021-05-01 15:19 UTC by Spircen

## What Does This PR Do
Añade cinco pistas de audio nuevas para los biomas de ruinas, general, espacio y peligro. Adjunto un enlace donde puedes escuchar cada una: 

ambigen16: https://drive.google.com/file/d/1YVG1RvRZR9B5orCJll2_gzg17TGb1XnB/view
ambiruin8: https://drive.google.com/file/d/1rE5fDOe_n6epU1jU00sM5i_2-j3BXfMa/view
ambispace4: https://drive.google.com/file/d/1BwA63xfwPiQNk5_O6qT3_FKXlYIE1QLp/view
ambidanger3: https://drive.google.com/file/d/1M5K7Ctg0qqAM6e51TBotKQNFVXJ5AmMx/view
ambispace3: https://drive.google.com/file/d/19rzmg6KGT5DzmPivmEK-yraiZGeRgDLA/view

## Why It's Good For The Game
El audio representa una parte muy importante del juego, cada efecto de sonido te hace sentirte inmerso. Poder contar con efectos propios nos ayuda a comenzar a formar mas identidad e inmersión para la comunidad.

## Images of changes

![image0-10-1](https://user-images.githubusercontent.com/46639834/116786842-8e8e2b00-aa66-11eb-9209-d2bd798a5da4.gif)

## Changelog
:cl:
add: Sound Effects Hispania
/:cl:

2021-05-01 15:37 UTC, SagaStars requested changes
El `ambispace3.ogg` pesa 1.3MB y el `ambispace4.ogg` 716KB , recomendaría que de alguna forma comprimas los archivo de audio ya que el sistema de sonido de paradise es shit y hasta que no se cargue un audio el juego se congela (por eso la rocola puede dar unos framedrops tremendos, ya debería de haberlo acomododado yo 👀) no esta guay que vayas caminando y de la nada se te detiene el juego por que se tiene que cargar la música...

2021-05-01 15:39 UTC, Spircen commented
Estoy al tanto de ese, esta comprimido hasta donde mas pude. Los archivos de espacio son de los mas pesados, aquí te dejo un ejemplo del cual tome para comprimirlo a un rango aceptable: 

https://github.com/Helixis/Paradise/blob/Lambda/sound/ambience/ambispace.ogg

2021-05-04 13:43 UTC, SagaStars commented
> Estoy al tanto de ese, esta comprimido hasta donde mas pude. Los archivos de espacio son de los mas pesados, aquí te dejo un ejemplo del cual tome para comprimirlo a un rango aceptable:
> 
> https://github.com/Helixis/Paradise/blob/Lambda/sound/ambience/ambispace.ogg
> 
> Hasta donde recuerdo en mi experiencia ese tamaño no me da Lag o almenos considerando que la pool es pequeña a cada rato están sonando las mismas en space.

Hmmmm veremos como sale.

2021-05-04 13:43 UTC, SagaStars approved these changes

2021-05-04 13:43 UTC, merged