Tweak Syringe Dump
Helixis/Paradise pull request #874
Opened 2021-05-02 23:28 UTC by Spircen

## What Does This PR Do
Permite tirar el contenido de las jeringas en el suelo al estar en HARM y apuntar al suelo. Al estar en HELP tirara un mensaje indicando que casi tiras el contenido de la jeringa. 

## Why It's Good For The Game
Múltiples veces me han comentado que es molesto siempre tener que llegar a usar un beaker para tirar el contenido de una jeringa y no simplemente poder tirarla al suelo como sucede con los beakers. Esto debería ayudar a mejorar los tiempos de acción para múltiples tratamientos. 

## Images of changes
![image](https://user-images.githubusercontent.com/46639834/116831268-d6e73f00-ab73-11eb-8c34-c040cf85308e.png)

## Changelog
:cl:
tweak: Syringe Dump
/:cl:

2021-05-03 12:38 UTC, SagaStars approved these changes

2021-05-04 04:56 UTC, DanaDririon requested changes
Opino que no debería ir ni el mensaje en INTENT_HELP ni el mensaje de que está vacío, ya que los beakers no tienen estos mensajes.

También podrías agregar esta interacción a los dropper 🐟

2021-05-04 06:28 UTC, Spircen commented
> Opino que no debería ir ni el mensaje en INTENT_HELP ni el mensaje de que está vacío, ya que los beakers no tienen estos mensajes.
> 
> También podrías agregar esta interacción a los dropper 🐟

Vale, agregare el método para que funcione con el dropper y eliminare los mensajes extra.

2021-05-04 06:38 UTC, DanaDririon commented
Y el mensaje de que el contenedor está vacío? ![824884265790996482](https://user-images.githubusercontent.com/52227547/116968105-d4730b00-ac81-11eb-9503-1283483ba03b.png)

2021-05-04 18:37 UTC, DanaDririon approved these changes
Osi osi

2021-05-04 18:37 UTC, merged