VUELVE EL OLD MAN EN SU GLORIA
Helixis/Paradise pull request #882
Opened 2021-05-05 07:04 UTC by DanaDririon

## What Does This PR Do
Arregla unos fallos que tenía el evento del oldman, el oldman en sí y mejora la interacción con el femur breaker.

## Why It's Good For The Game
Porque es el mejor evento automático creado en Hispania.

## Changelog
:cl: DanaDririon
tweak: Detalles Old Man
fix: Evento Old Man
/:cl:

2021-05-05 12:47 UTC, Spircen approved these changes
Todo funciona de maravilla, pero no tengo ni idea acerca de SCP me costo mucho comprender como funcionaba el femur breaker sin leer el código. No se si quisieras hacerlo mas accesible por que es algo complicado de ocupar. Igual todo funciona si alguien mas lo aprueba el merge sin problemas.

2021-05-05 13:24 UTC, SagaStars requested changes

2021-05-05 13:24 UTC, SagaStars commented on code/hispania/game/gamemodes/miniantags/oldman/oldman.dm
> +					P.germ_level += INFECTION_LEVEL_ONE //cada golpe tiene una prob de infectar
Hay un trait que te hace inmune a los germenes, podrías cambiar el condicional de ishuman(L) por ese.

2021-05-05 14:49 UTC, Evankhell561 requested changes

2021-05-05 14:49 UTC, Evankhell561 commented on code/hispania/game/gamemodes/miniantags/oldman/oldman.dm
> +	..()
```suggestion
	. = ..()
```

2021-05-05 14:49 UTC, Evankhell561 commented on code/hispania/game/gamemodes/miniantags/oldman/oldman.dm
> +	..()
```suggestion
	return ..()
```

2021-05-05 14:57 UTC, Evankhell561 requested changes

2021-05-05 14:57 UTC, Evankhell561 commented on code/hispania/modules/events/oldman.dm
> +		var/mob/living/simple_animal/hostile/oldman/SCP = new /mob/living/simple_animal/hostile/oldman/(pick(spawn_locs))
```suggestion
		var/mob/living/simple_animal/hostile/oldman/SCP = new /mob/living/simple_animal/hostile/oldman(pick(spawn_locs))
```

2021-05-09 06:02 UTC, DanaDririon commented
Ahí agregué los cambios de Evan y el check de trait de germs de Saga
El check de (ishuman(L)) lo dejo porque sino me tira runtimes al atacar simple_mob
El fémur breaker es parecido a la guillotina, de hecho tiene harto código de esa. Quería que la interacción fuera intuitiva para los que sepan sobre el Old Man, pero no tan evidente.

2021-05-09 10:35 UTC, merged