Tweak Curas Avanzadas Virus
Helixis/Paradise pull request #905
Opened 2021-05-11 00:16 UTC by Spircen

## What Does This PR Do
Sustituye toda la lista actual de curas para virus por las siguientes: "salglu_solution", "mannitol", "perfluorodecalin","mitocholide", "spaceacillin", "pen_acid","haloperidol", "carpotoxin", "prions","nanomachines", "bath_salts". 

## Why It's Good For The Game
Sustituye las curas de los virus sencillas por componentes químicos mas complicados de encontrar pero que se encuentran bien documentados en las Wikis existentes. Esto hace que los virus requieran mas inversión de tiempo en ser curados y no un simple viaje a cargo o ciencias por una barra de oro o silver. 

## Changelog
:cl:
tweak: Curas diferentes a virus
/:cl:

2021-05-11 15:45 UTC, SagaStars approved these changes
Bendito seas y todo pero paracetamol chem when?

2021-05-13 07:26 UTC, DanaDririon requested changes
No me convencen los prions ni los nanomachines, ya que el primero es un veneno mortal y el segundo te convierte en cyborg, todo lo contrario a una "cura" xd

Tampoco estoy seguro sobre el carpotoxin por la dificultad de obtención. No en todas las rondas sale una escuela de carpas.

2021-05-13 07:29 UTC, Evo-S commented
> No me convencen los prions ni los nanomachines, ya que el primero es un veneno mortal y el segundo te convierte en cyborg, todo lo contrario a una "cura" xd
> 
> Tampoco estoy seguro sobre el carpotoxin por la dificultad de obtención. No en todas las rondas sale una escuela de carpas.

No se necesita un evento de escuela de capras para conseguir el carpotoxin, de hecho puede ser creada es dosis bajas si sabes lo que haces

2021-05-13 09:02 UTC, NervalARS commented
Me aparece bien complicar las curas, pero substituira la capratoxina, los priones y las nanomachines por otras cosas. Como por ejemplo Omnizine, Strange Reagent o algun químico que se obtenga de plantas de botánica, esto último tendría mucho sentido ya que mucho de los remedios antiguos para enfermedades venían de plantas.

2021-05-13 11:27 UTC, Spircen commented
> No me convencen los prions ni los nanomachines, ya que el primero es un veneno mortal y el segundo te convierte en cyborg, todo lo contrario a una "cura" xd
> 
> Tampoco estoy seguro sobre el carpotoxin por la dificultad de obtención. No en todas las rondas sale una escuela de carpas.

Ambas son posibles toxinas pero si inyectas 1u de estas no haces nada al pobre individuo es mas una forma de poder demostrar a los doctores que no todo es letal y por las carptoxins puedes conseguirlas de la maquina de mascotas como baby carps estas te dan un filite de carpa.

2021-05-16 15:42 UTC, Spircen commented
Mirando que quedamos en dos votos aprobados y uno denegado lo voy a mergear.

2021-05-16 15:43 UTC, merged