Add Quickclot Kit Surgical/Survival (IB Stopper)
Helixis/Paradise pull request #908
Opened 2021-05-11 22:10 UTC by Spircen

## What Does This PR Do
Agrega Quickclot una herramienta medica que sirve para detener sangrado interno SOLO de extremidades, NO detiene sangrado interno en cabeza, torso o pelvis. Este kit existe en dos versiones, surgical es la mejor versión y survival una versión mas sencilla para mineria (Diferencia tiempo de aplicación).

 Se proporciona 1 Kit de Surgical a: Blueshield / CMO / Paramedic en lockers y 1 Kit de Survival a: Shaft Miner en equipamento base.
 
 Surgical QC puede comprar en cargo por un costo alto de 120 Puntos. Survival QC puede ser comprado por 1600 Puntos.

Al ser equipamiento de emergencia y bastante util es caro. 

## Why It's Good For The Game
Proporciona una nueva herramienta a medbay para poder laborar de forma mas ordenada durante las emergencias y ayuda a el personal de minería a poder tener una chance de supervivencia ligeramente mayor.

## Images of changes
![image](https://user-images.githubusercontent.com/46639834/117890960-b3ab4680-b27b-11eb-8299-1ccbbcc80f0e.png)
![image](https://user-images.githubusercontent.com/46639834/117890357-a477c900-b27a-11eb-97c2-2b8d1319369f.png)
![image](https://user-images.githubusercontent.com/46639834/117890570-0801f680-b27b-11eb-997b-b67b2914afab.png)
![image](https://user-images.githubusercontent.com/46639834/117890612-1ea84d80-b27b-11eb-920c-22085d73b5d5.png)
![image](https://user-images.githubusercontent.com/46639834/117890732-57e0bd80-b27b-11eb-8129-9b2a671fb037.png)
![image](https://user-images.githubusercontent.com/46639834/117890770-64651600-b27b-11eb-8d11-680b9f33eb3b.png)

## Changelog
:cl:
add: Quickclot
/:cl:

2021-05-11 22:11 UTC, Dapple27 commented
Inreible, es como un patch cierto?

2021-05-11 22:12 UTC, Spircen commented
Es mas como una splint pero sin flags por que una splint detiene no cura.

2021-05-11 22:31 UTC, Dapple27 commented
Oh vale

2021-05-12 00:06 UTC, SagaStars approved these changes
Fucking yes, cambia el precio de la desc del PR tho

2021-05-12 03:49 UTC, Spircen commented
Ahí quedo.

2021-05-18 17:17 UTC, DanaDririon requested changes
Perdón por la demora
Lo testié y funciona correctamente
Sólo que tiene un Runtime al aplicar el QuickClot en un limb cortado
Por ejemplo aquí me corté una pierna y luego intenté aplicar el QuickClot
![image](https://user-images.githubusercontent.com/52227547/118695644-6b3fdb80-b7db-11eb-9c46-f0eb53ae689c.png)

2021-05-18 17:17 UTC, DanaDririon commented on code/hispania/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +/obj/structure/closet/secure_closet/paramedic/New()
```suggestion
/obj/structure/closet/secure_closet/paramedic/populate_contents()
```

2021-05-18 17:37 UTC, DanaDririon requested changes
Esto arregla el Runtime de arriba 🐟

2021-05-18 17:37 UTC, DanaDririon commented on code/hispania/game/objects/items/divices/stacks/medical.dm
> +		var/obj/item/organ/external/affecting = H.get_organ(user.zone_selected)
```suggestion
		var/obj/item/organ/external/affecting = H.get_organ(user.zone_selected)
		if(!affecting)
			to_chat(user, "<span class='warning'>[M] doesn't have a limb there!</span>")
			return TRUE
```

2021-05-18 17:37 UTC, Spircen commented on code/hispania/game/objects/items/divices/stacks/medical.dm
> +		var/obj/item/organ/external/affecting = H.get_organ(user.zone_selected)
Ya, pero tiene sentido que puedas curar sangrados con ello. Lo arreglare de otra forma.

2021-05-18 19:11 UTC, DanaDririon approved these changes
Testeado, sin runtimes y funcionando como lo esperado

2021-05-18 19:12 UTC, merged