Llega el ERP a la estacion Hispania
Helixis/Paradise pull request #909
Opened 2021-05-12 01:20 UTC by TurboRata

![Screenshot_1](https://user-images.githubusercontent.com/84026734/117902401-558e5b80-b29b-11eb-8aa8-0bb6290adbc9.png)
Llego el ERP (Emergency Ration Pack )
## What Does This PR Do
Traigo un Port de Cev-Eris
![Screenshot_3](https://user-images.githubusercontent.com/84026734/117903647-f41bbc00-b29d-11eb-9680-5a255a872cc7.png)
Añade el ERP una racion de emergencia diseñada para tropas de combate. Incluye 5 objetos
- Racion MRE
- Lata de Arepas de emergencia
- Galletas Enriquesidas
- Chocolate Moralizador
- Un tenedor

Te preguntaras que Hacen?
**Racion MRE**: Te da un objeto de comida aleatoria, perfecto para comer en situaciones donde no hay cocina
![Screenshot_7](https://user-images.githubusercontent.com/84026734/117902716-17de0280-b29c-11eb-85b6-8562e51519ad.png)

**Lata de Arepas de emergencia**: Para esos momentos donde necesitas una arepa (todos los momentos)
![Screenshot_4](https://user-images.githubusercontent.com/84026734/117902886-73a88b80-b29c-11eb-8902-97f3407464d8.png)
**Galletas Enriquesidas**: Unas buenas galletas para empezar el dia incluye medicinas currativas sueaves para casos de emergencia dentro de la emergencia 
![Screenshot_8](https://user-images.githubusercontent.com/84026734/117903147-06492a80-b29d-11eb-9665-f2e4345e4747.png)
**Chocolate Moralizador**:
Un chocolate usado antiguamente en guerras, llamado moralizador por la cantidad de drogas que tiene, contiene nicotina epinefrina y cafeina, aunque no apto para el consumo normal por la cantidad de drogas que contiene debe servir para encuentros de combate **_ADVERTENCIA: NT NO SE RESPONSABILIZA POR LAS CONSECUENCIAS DE CONSUMIR EL CHOCOLATE_** 
![Screenshot_10](https://user-images.githubusercontent.com/84026734/117903404-7952a100-b29d-11eb-8361-e3ef2a58f7bb.png)

Estas Raciones seran utilizadas por el cuerpo de seguridad y los mineros para mantener alta la moral y lleno el estomago en las circunstancias mas peligrosas, ademas de eso el Blue Shield tambien cuanta con varias de estas en caso de que no haya comida y haya que alimentar a miembros de commando. 
Si los civiles quieren utilizarlas? Se las vendemos Extremadamente caras pero las vendemos, disponibles en cargo por 200 puntos 
![Screenshot_2](https://user-images.githubusercontent.com/84026734/117903622-e7976380-b29d-11eb-9da3-f8c0ca07f54f.png)

## Why It's Good For The Game
Hace que sea mas divertido comer y no mucho mas en general, El chocolate trae estimulantes pero nada que no puedan conseguir los jugadores por su cuenta
## Images of changes
![Screenshot_5](https://user-images.githubusercontent.com/84026734/117903834-3fce6580-b29e-11eb-93c9-7e8c521691c8.png)
     Arepa en todo momento

![Screenshot_6](https://user-images.githubusercontent.com/84026734/117903835-4066fc00-b29e-11eb-9fe3-4929ed169435.png)
     Oh hay problemas en el bar pero tengo hambre

![Screenshot_9](https://user-images.githubusercontent.com/84026734/117903837-40ff9280-b29e-11eb-82c7-70c50ff3b073.png)
     Las galletas no curan tanto como pense

![Screenshot_11](https://user-images.githubusercontent.com/84026734/117903840-42c95600-b29e-11eb-8c80-d0df2de3e798.png)
     Se comio 2 chocolates

## Changelog
🆑
Añade el el ERP y permite conseguirlo en el vender de sec, bluespace pods, oficina del BS y cargo
/🆑

2021-05-12 01:45 UTC, SagaStars requested changes
Un par de detalles, apoyo el PR en especial por la parte del chocolate, arreglalos y apruebo. Chef mains may cry.

2021-05-12 01:45 UTC, SagaStars commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	Thermal insulation will keep them warm for over four hours. Nutrient paste and morale bar contains medicinal additives for field performace, DO NOT OVERCONSUME.\""
```suggestion
	\"Instructions: Remove contents from packaging, open both mre container and ration can. \
	Enriched crackers and morale bar contains medicinal additives for field performace, DO NOT OVERCONSUME.\""
```

2021-05-12 01:45 UTC, SagaStars commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	desc = "A silver can that contains a random arepa, made for special emergencies"
```suggestion
	desc = "A silver can that contains a random arepa, made for special emergencies."
```

2021-05-12 01:45 UTC, SagaStars commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	desc = "A pouch that contains a random meal, made for emergencies"
```suggestion
	desc = "A pouch that contains a random meal, made for emergencies."
```

2021-05-12 01:45 UTC, SagaStars commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +/obj/item/storage/fancy/mre_cracker
El paquete de crackers deberia de tener una descripcion en especial por sus propiedades curativas.

2021-05-12 01:45 UTC, SagaStars commented on code/hispania/modules/food_and_drinks/food/foods/candy.dm
> +	desc = "Some brand of non-melting military chocolate with a lot of stimulants. It has a label that says \"WARNING DO NOT EAT MORE THAN ONE\""
```suggestion
	desc = "Some brand of non-melting military chocolate with a lot of stimulants. It has a label that says \"WARNING DO NOT EAT MORE THAN ONE\"."
```

2021-05-12 01:46 UTC, SagaStars commented
Tambien deberias poner en la desc del PR que se puede comprar por cargo al precio de 200 puntos.

2021-05-12 02:01 UTC, Danaleja2005 commented
Esto es increible, un grande Turborata

2021-05-12 02:38 UTC, SagaStars approved these changes

2021-05-12 03:48 UTC, Spircen requested changes
El código se ve bien y me agradan los valores nutricionales pero prefiero que pongas la ración como objeto premium y limitada a una o dos por vending machine, por que es demasiada comida para seguridad.

2021-05-12 04:02 UTC, TurboRata commented
> El código se ve bien y me agradan los valores nutricionales pero prefiero que pongas la ración como objeto premium y limitada a una o dos por vending machine, por que es demasiada comida para seguridad.

Puedes bajarlo a 3?

2021-05-12 15:06 UTC, Spircen commented
Sigo necesitando que la pongas como item premium que se puede comprar con monedas. Hay referencias como hacerlo en ese mismo file de vending machine. Entiendo que los mineros puedan disponer de uno pero seguridad no es un equipo de militares que afrontan un ecosistema que los quiere matar constantemente a diferencia de los mineros.

2021-05-12 15:28 UTC, TRBRT2 commented
> Sigo necesitando que la pongas como item premium que se puede comprar con monedas. Hay referencias como hacerlo en ese mismo file de vending machine. Entiendo que los mineros puedan disponer de uno pero seguridad no es un equipo de militares que afrontan un ecosistema que los quiere matar constantemente a diferencia de los mineros.

Entiendo tu punto y lo puedo poner por creditos pero si se compra por monedas literalmente nadie lo va a comprar, hay como 3 monedas en maint y si no corres en el principio de la ronda a maint no vas a tener ni oportunidad, y si es asi vas a tenerle que llorar a mineria por 4 horas por que te den una moneda y eso va contra el espiritu de una racion de emergencia, si es asi mejor ponerlo en la armeria o algo

2021-05-12 15:37 UTC, Spircen commented
En ese caso ponlo como un item que cueste créditos y bájalo a dos.

2021-05-12 17:25 UTC, Spircen requested changes
Fuera de los detalles que marco en la review la idea me agrada y considero veré mucha gente distribuirlas o venderlas. Buen Port.

2021-05-12 17:25 UTC, Spircen commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +/obj/item/storage/toolbox/mre //godoforeos: Jason Conrad
Aquí hay un problema al ser un objeto heredado de tipo toolbox este item hace considerable daño al atacar, puede estar vacía y le puedo romper la cabeza a alguien con una bolsa vacía de ERP.  Recomiendo que mejor lo hagas un tipo de bolsa similar a las de plástico.

2021-05-12 17:25 UTC, Spircen commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +/obj/item/storage/toolbox/lata_arepa
Sucede lo mismo con el resto de objetos que se heredan desde toolbox.

2021-05-12 17:25 UTC, Spircen commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +/obj/item/storage/toolbox/lata_arepa/remove_from_storage(obj/item/I, atom/new_location)
Una vez la abres entiendo y tomas el contenido entiendo que no puedas volver a insertarlo dentro, pero cuando intentas insertarla dentro te marca que se encuentra lleno el storage. 

![image](https://user-images.githubusercontent.com/46639834/118017527-59ae8d80-b31c-11eb-862f-e92b5ee2d3c9.png)

"The emergency ration is full, make some space" 

Ya sea que quieras cambiarlo para que puedas volver a meter la comida o que el objeto cambie a tipo trash pero no puede mostrar que se encuentra lleno cuando no hay nada, actualmente lo mas similar es el sistema en snacks.dm para Trash.

2021-05-12 17:25 UTC, Spircen commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +/obj/item/storage/toolbox/lata_arepa/remove_from_storage(obj/item/I, atom/new_location)
Esto aplica tanto para las bolsas dentro del ERP como para el ERP mismo.

2021-05-12 17:25 UTC, Spircen commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +/obj/item/storage/toolbox/lata_arepa/remove_from_storage(obj/item/I, atom/new_location)
Si hay alguna duda de como poder resolverlo me pingeas por Discord o me mandas DM. Cualquier cosa en cuanto quede resuelto el detalle de que es un objeto heredado de toolbox y el hecho de que marcan las bolsas estar llenas cuando no tienen nada esta listo para mergear.

2021-05-13 06:45 UTC, DanaDririon requested changes
Refactoriza procs.
Cambia el mensaje de abrir de warning a notice.
Otros detalles.

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +		to_chat(usr, "<span class='warning'>You open \the [src] .")
```suggestion
		to_chat(usr, "<span class='notice'>You open \the [src].</span>")
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +		to_chat(usr, "<span class='warning'>You open \the [src] .")
```suggestion
		to_chat(usr, "<span class='notice'>You open \the [src].</span>")
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +		to_chat(user, "<span class='warning'>You tear \the [src] open.")
```suggestion
		to_chat(usr, "<span class='notice'>You tear \the [src] open.</span>")
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +		to_chat(user, "<span class='warning'>You tear \the [src] open.")
```suggestion
		to_chat(usr, "<span class='notice'>You tear \the [src] open.</span>")
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/structures/crates_lockers/closets/secure/security.dm
> +/obj/structure/closet/secure_closet/blueshield/New()
```suggestion
/obj/structure/closet/secure_closet/blueshield/populate_contents()
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/structures/crates_lockers/closets/secure/security.dm
> +/obj/structure/closet/secure_closet/blueshield/New()
Hay que hacer esto con todos los closets de Hispania, pero en otro PR

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/storage/bag/plasticbag/mre(src)
```suggestion
	for(var/i in 1 to 5)
		new /obj/item/storage/bag/plasticbag/mre(src)
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	..()
```suggestion
/obj/item/storage/bag/plasticbag/mre/populate_contents()
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	..()
```suggestion
/obj/item/storage/lata_arepa/populate_contents()
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +	..()
```suggestion
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +/obj/item/storage/fancy/mre_cracker/show_to(mob/user)
```suggestion
/obj/item/storage/fancy/mre_cracker/attackself()
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +	..()
```suggestion
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +	icon_state = "crackersbox"
```suggestion
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +	icon_state = "crackersbox"
Why

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +	icon_state = "crackersbox5"
```suggestion
	icon_state = "crackersbox"
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +/obj/item/storage/bag/plasticbag/mre/show_to(mob/user)
```suggestion
/obj/item/storage/bag/plasticbag/mre/attack_self()
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/modules/food_and_drinks/food/foods/candy.dm
> +/obj/item/reagent_containers/food/snacks/choco_mre/attack_self(mob/user)
```suggestion
/obj/item/reagent_containers/food/snacks/choco_mre/attack_self()
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/modules/food_and_drinks/food/foods/candy.dm
> +		to_chat(user,("You tear \the [src] open."))
```suggestion
		to_chat(usr,(<span class='notice'>"You tear \the [src] open.</span>"))
		
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/fancy.dm
> +	return
```suggestion
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	to_chat(usr, "<span class='warning'>You dont find a way to put the item in \the [src].")
```suggestion
	to_chat(usr, "<span class='warning'>You dont find a way to put the item in \the [src].</span>")
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	to_chat(usr, "<span class='warning'>You dont find a way to put the item in \the [src].")
```suggestion
	to_chat(usr, "<span class='warning'>You dont find a way to put the item in \the [src].</span>")
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	to_chat(usr, "<span class='warning'>You dont find a way to put the item in \the [src].")
```suggestion
	to_chat(usr, "<span class='warning'>You dont find a way to put the item in \the [src].</span>")
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	..()
```suggestion
/obj/item/storage/bag/plasticbag/comida_mre/populate_contents()
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/modules/food_and_drinks/food/foods/candy.dm
> +	if(!open)
```suggestion
	if(!open && (M == user))
```

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/modules/food_and_drinks/food/foods/candy.dm
> +	if(!open)
Este check es necesario, ya que sin esto se puede abrir la barra dándosela a otro mob, lo que no tiene sentido según el mensaje.

2021-05-13 06:45 UTC, DanaDririon commented on code/hispania/modules/food_and_drinks/food/foods/candy.dm
> +	. = ..()
```suggestion
	if(!open)
		to_chat(usr, "<span class='warning'>Open \the [src] first!</span>")
		return
	else
		..()
```

2021-05-13 06:48 UTC, DanaDririon commented on code/hispania/modules/food_and_drinks/food/foods/candy.dm
> +	. = ..()
> Este check es necesario, ya que sin esto se puede abrir la barra dándosela a otro mob, lo que no tiene sentido según el mensaje.

Continuación.

2021-05-14 00:28 UTC, DanaDririon approved these changes
No tires la comida al suelo que se ensucia

2021-05-14 00:28 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	pickup_sound =  'sound/items/handling/paper_pickup.ogg'
```suggestion
	pickup_sound =  'sound/items/handling/paper_pickup.ogg'
	allow_quick_empty = FALSE
	allow_quick_gather = FALSE
```

2021-05-14 00:28 UTC, DanaDririon commented on code/hispania/game/objects/items/weapons/storage/erp.dm
> +	pickup_sound =  'sound/items/handling/paper_pickup.ogg'
```suggestion
	pickup_sound =  'sound/items/handling/paper_pickup.ogg'
	allow_quick_empty = FALSE
	allow_quick_gather = FALSE
```

2021-05-14 00:33 UTC, DanaDririon commented
![image](https://user-images.githubusercontent.com/52227547/118203608-6b7e5680-b42a-11eb-973a-0e302c449bc5.png)

2021-05-14 00:33 UTC, merged