añade el legendario pid boy al juego
Helixis/Paradise pull request #927
Opened 2021-05-18 04:34 UTC by Evankhell561

## What Does This PR Do

es un pda que puede ponerse en el slot de los guantes y operarse desde ahi, simulando el pid boy de fall out.

## Why It's Good For The Game

## Images of changes

![image](https://user-images.githubusercontent.com/49106866/118590632-c8527780-b770-11eb-9383-08794aa2a950.png)

## Changelog
:cl:
add: pid boy
/:cl:

2021-05-18 16:09 UTC, SagaStars commented on code/hispania/modules/pda/pdas.dm
> +	slot_flags = SLOT_ID | SLOT_BELT | SLOT_PDA | SLOT_GLOVES
Solo GUANTES

2021-05-18 16:11 UTC, SagaStars commented
Le estaría faltando un `item_state`, un pda que vaya en tu brazo pero no lo puedas ver es muy FOME.

2021-05-18 16:12 UTC, Spircen commented
¿Este es el item custom que evos quería?

2021-05-18 16:19 UTC, Danaleja2005 commented
el sprite del guantelete se me sigue haciendo muy grande, y le hace falta un sprite para el brazo :eye:, pero ahora me pregunto que pasaría si pierde uno o ambos brazos

2021-05-18 18:18 UTC, Evankhell561 commented on code/hispania/modules/pda/pdas.dm
> +	slot_flags = SLOT_ID | SLOT_BELT | SLOT_PDA | SLOT_GLOVES
a ver, puedes meterlo en esos bolsillos pero el boto nde accion solo aparece en los guantes. Si es del tamaño adecuado no veo por qué no pueda colocarse en otro slot.

2021-06-29 22:02 UTC, SagaStars requested changes
`item_sprite` para terminar tu mierda por favor

2021-07-16 15:53 UTC, Evankhell561 commented
> `item_sprite` para terminar tu mierda por favor

los maintainers estan en mi conatra y no aprueban mis prs.

2022-07-23 01:02 UTC, closed without merging