Medbay Oxigen Assistant: 358/2 days (funky mode edition) DX EDITION 2021 FINAL TAKE: LAST RESORT
Helixis/Paradise pull request #955
Opened 2021-05-26 17:38 UTC by SagaStars

El PR de M.O.A obligatorio por año, veamos si es el ultimo.

Trae a Hispania un nuevo objeto único, el M.O.A = Medbay Oxigen Assistant, una poderosa maquina para estabilizar pacientes con problemas pulmonares, tiene las siguientes caracteristicas.
- Al estar conectado a un paciente, el daño de oxyloss no puede subir. Si estas en 180 de daño y no tienes un pulmón, no importa, no va a subir a 200. Aun así se puede bajar el daño.
- Cura el mismo Oxyloss que el salbutamol.
- Reduce el shortbreath.
- Reduce el ritmo cardiaco.
- Es un objeto bulky que no puede ser guardado.
- Te da un slowdown al estar bajo sus efectos.
- Funciona a base de energia, cuidado con las EMPs.
- Sonido de respiradero, no tienen ni idea de lo genial que queda en medbay.
- A los pacientes con enfermedades al estar conectados, tienen un 50% de chance por ciclo de enfermedad de que no les pase nada, un modo de controlar a pacientes y ralentizar su muerte.

El objeto sera conseguible por ciencias con los siguientes niveles: `("materials" = 5, "biotech" = 4, "engineering" = 5)`

## Why It's Good For The Game
Facilita el control de pacientes con problemas respiratorios, dandoles mas chances a medbay de salvar vidas sin que estas se mueran antes, mejores oportunidades de roleo basically, sumado con el 50% de enfermedades, ahora tiene mucho mas sentido mantener a pacientes en el isolation de virología, ya que no morirán tan rapido si estan en medbay.

## Images of changes

                          Lastima que no escuchen el sonido.
                          
![moa2](https://user-images.githubusercontent.com/55407528/119705923-5391d400-be27-11eb-8fba-1345ae6b0a51.gif)

                          EL M.O.A

![MOA](https://user-images.githubusercontent.com/55407528/119705950-5d1b3c00-be27-11eb-8c89-6fc1c3e9e0ec.png)

## Changelog
:cl:
add: MOA, MEDBAY OXYGEN ASSISTANT
/:cl:

2021-05-27 02:40 UTC, Spircen commented
Da un sync a la branch y ya deberia pasar CI luego de eso ya lo reviso.

2021-05-31 18:57 UTC, Spircen requested changes, later dismissed

2021-05-31 18:57 UTC, Spircen commented on code/hispania/modules/reagents/reagent_containers/moa.dm
> +			if(L.wear_mask)
Aquí hay que hacer una validación que pregunte por las especies que no pueden remover su mascara y que aun así puedan ocupar el MoA ya sea si quieres preguntar por el tipo de mascara unica de los vox y plasmaman o por las razas directo.

2021-05-31 18:57 UTC, Spircen commented on code/hispania/modules/reagents/reagent_containers/moa.dm
> +			if(L.wear_mask)
A no ser que quieras dejarlo fuera, yo no tengo ningún problema si solo es útil en X tipo de especie.

2021-05-31 18:57 UTC, Spircen commented on code/hispania/modules/reagents/chemistry/reagents/medicine.dm
> +	M.SetSlowed(1)
Inyecta un total de 1u y en ningún momento llego a tener mas de esto por que mi cuerpo lo procesa en consecuencia el slow no se siente para nada, hay que subirlo.

2021-05-31 18:57 UTC, Spircen commented on code/__DEFINES/combat.dm
> +#define MOAED			64 // Hispania, evita daño de oxy
Esta flag va en su equivalente en hispania aunque no tenemos pero hay que crear uno.

2021-05-31 21:23 UTC, SagaStars commented
- Ahora los Vox Y Plasmamen reciben daños extras al insertarselos, es un M.O.A, la O es de Oxigeno, no de plasma o nitrogeno. Si quieres hacer que se mueran mas rápido asfixiados, todo suyo.

- No puedo enviar el define de la flag a una semejante de hispania por que no pasa por el `_disease.dm`,
![UHOH](https://user-images.githubusercontent.com/55407528/120243072-9fcc8200-c234-11eb-8ae9-32cb2dfb5238.png)
cuando se trata de defines parece importar el orden de archivos?

- Slowdown duplicado, alguien en silla de ruedas te gana en una carrera jaja

- Se añade un ciclo mas al sonido para que no sea tan repetitivo, sin dejar de serlo.

2021-06-01 00:07 UTC, merged