Actualiza el precio del build your own KA
Helixis/Paradise pull request #976
Opened 2021-06-03 00:59 UTC by PotatoTheDeveloper

## What Does This PR Do
Cambia el precio de 30000 a 9500

## Why It's Good For The Game
El KA no vale 30000, es inutil por si mismo y encima tienes que gastar de 5k a 15k puntos para customizarlo.

## Changelog
:cl:
tweak: Precio del Build-Your-Own KA bajado de 30000 puntos a 9500 puntos
/:cl:

2021-06-03 14:48 UTC, SagaStars commented
Patata, cuanto es 330 de mod capacity? Cuanto costaría compra un KA asi con todas las mejoras de fuerza.

2021-06-04 20:06 UTC, Spircen commented
A mi parecer sigue estando muy caro, bájalo aun mas por que los modkits de ciencias si consumen muchos minerales y no me imagino que científico te dara 20 modkits de algo luego de que vea se gasto 20 sheets de uranio.

2021-06-06 15:23 UTC, SagaStars requested changes
PATATAAAAAA, ALINEALO. 🔪 
![image](https://user-images.githubusercontent.com/55407528/120930039-93737980-c6b9-11eb-8cfe-7de1dde09b1d.png)

2021-06-06 18:04 UTC, PotatoTheDeveloper commented
> PATATAAAAAA, ALINEALO. 
> ![image](https://user-images.githubusercontent.com/55407528/120930039-93737980-c6b9-11eb-8cfe-7de1dde09b1d.png)

PERO NO FUI YOOOOOOO

2021-06-06 18:14 UTC, PotatoTheDeveloper commented
> Patata, cuanto es 330 de mod capacity? Cuanto costaría compra un KA asi con todas las mejoras de fuerza.

llenar todo eso de mejora de damage te costaria  aproximadamente 12k o 13k puntos de mineria y al final del dia haria damage cada 3 años asi que seria bastante malo

2021-06-07 20:34 UTC, Spircen approved these changes

2021-06-07 20:51 UTC, SagaStars approved these changes

2021-06-07 20:51 UTC, SagaStars commented
Vamos a ver como termina jugando esto.

2021-06-07 20:51 UTC, merged